/**
 * Per-cell editorial narratives.
 *
 * The cache at data/content/cell_narratives_v1.json is generated by
 * scripts/content/generate_narratives.py. Entries are keyed by
 * `${country}|${geo_id}|${industry_id}|${sizeBand || 'total'}` and the
 * value is the rendered 2-paragraph narrative as a single string.
 *
 * The file is read once at module load (server-side only). Cells with no
 * cached narrative return null — the page's narrative section silently
 * omits itself per the Wave 4a (D2) degrade-quietly rule.
 */
import fs from "node:fs";
import path from "node:path";

const NARRATIVES: Record<string, string> = (() => {
  try {
    const p = path.resolve(
      process.cwd(),
      "data",
      "content",
      "cell_narratives_v1.json"
    );
    const raw = fs.readFileSync(p, "utf-8");
    return JSON.parse(raw) as Record<string, string>;
  } catch {
    return {};
  }
})();

/**
 * Look up the editorial narrative for a given cell.
 *
 * Keying convention matches the bulk generator:
 *   - country: ISO2 uppercase
 *   - geo_id:  raw geo_id as stored in the source table
 *   - industry_id: friendly taxonomy id
 *   - sizeBand: "total" when null/empty
 *
 * Returns null when no narrative is cached for this cell. Callers should
 * conditionally render the narrative section based on a non-null return.
 */
export function getCellNarrative(
  country: string,
  geoId: string,
  industryId: string,
  sizeBand: string | null | undefined
): string | null {
  const c = country.toUpperCase();
  const sb = sizeBand || "total";
  // Try the specific size-band entry first, then fall back to the cell's
  // "total" band (the narrative generator only covered "total" cells; the
  // commentary applies to the industry × geo regardless of which size band
  // the user happens to be filtering by).
  const direct = `${c}|${geoId}|${industryId}|${sb}`;
  if (NARRATIVES[direct]) return NARRATIVES[direct];
  if (sb !== "total") {
    const total = `${c}|${geoId}|${industryId}|total`;
    if (NARRATIVES[total]) return NARRATIVES[total];
  }
  return null;
}

/**
 * Total cached narratives. Useful for the admin dashboard to confirm the
 * generator finished and the file is reachable from the running server.
 */
export function getNarrativeCount(): number {
  return Object.keys(NARRATIVES).length;
}
