/**
 * Load pre-baked homepage snapshots.
 *
 * These JSONs are generated by scripts/snapshots/build_homepage_snapshots.ts.
 * Reading them at request time is ~10000× faster than the equivalent
 * Supabase fallback walk. The homepage now ships with zero DB queries.
 *
 * Each loader returns the cell list AND tolerates a missing file: if the
 * snapshot hasn't been built yet, callers fall back to their own data
 * fetch path. That keeps dev environments working even without baked data.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export type SnapshotCell = {
  iso2: string;
  geo: string;
  industry_id: string;
  revenue_per_firm: number | null;
  n_enterprises: number | null;
  n_employees: number | null;
  payroll_per_employee: number | null;
  quality_score: number | null;
  coverage_tier: string | null;
  year: number;
  geo_name: string | null;
  industry_name: string | null;
};

type Snapshot = {
  generated_at: string;
  cells: SnapshotCell[];
};

const DIR = resolve(process.cwd(), "data", "snapshots");

function loadSnapshot(filename: string): Snapshot | null {
  try {
    const raw = readFileSync(resolve(DIR, filename), "utf-8");
    return JSON.parse(raw) as Snapshot;
  } catch {
    return null;
  }
}

let featuredCache: Snapshot | null | undefined = undefined;
let cellOfTheWeekCache: Snapshot | null | undefined = undefined;
let popularRotationCache: Snapshot | null | undefined = undefined;

export function getFeaturedSnapshot(): Snapshot | null {
  if (featuredCache === undefined) featuredCache = loadSnapshot("featured-tiles.json");
  return featuredCache;
}

export function getCellOfTheWeekSnapshot(): Snapshot | null {
  if (cellOfTheWeekCache === undefined) cellOfTheWeekCache = loadSnapshot("cell-of-the-week.json");
  return cellOfTheWeekCache;
}

export function getPopularRotationSnapshot(): Snapshot | null {
  if (popularRotationCache === undefined) popularRotationCache = loadSnapshot("popular-cell-rotation.json");
  return popularRotationCache;
}

/** Find a cell in a snapshot by (iso2, geo, industry_id). */
export function findSnapshotCell(
  snap: Snapshot | null,
  iso2: string,
  geo: string,
  industry: string,
): SnapshotCell | null {
  if (!snap) return null;
  const normIndustry = industry.replace(/-/g, "_");
  return (
    snap.cells.find(
      (c) =>
        c.iso2.toUpperCase() === iso2.toUpperCase() &&
        c.geo.toLowerCase() === geo.toLowerCase() &&
        c.industry_id === normIndustry,
    ) || null
  );
}
