/**
 * AUTO-GENERATED by scripts/cities/build_city_aliases.ts
 * Plan v22 Block E + v23 Part 1 — friendly city slug -> geo_id + display label.
 * Re-run when adding new curated cities:
 *   npx tsx scripts/cities/build_city_aliases.ts
 */

/** country (ISO-2 upper) -> friendly city slug -> underlying geo_id (lowercase) */
export const CITY_FRIENDLY_TO_GEO_ID: Record<string, Record<string, string>> = {
  AD: {
    "andorra-la-vella": "ad-city-andorra-la-vella",
  },
  AE: {
    "abu-dhabi": "ae-city-abu-dhabi",
    "dubai": "ae-city-dubai",
    "sharjah": "ae-city-sharjah",
  },
  AL: {
    "durr-s": "al-city-durres",
    "elbasan": "al-city-elbasan",
    "fier": "al-city-fier",
    "shkod-r": "al-city-shkoder",
    "tirana": "al-city-tirana",
    "vlor": "al-city-vlore",
  },
  AM: {
    "yerevan": "am-city-yerevan",
  },
  AO: {
    "luanda": "ao-city-luanda",
  },
  AR: {
    "buenos-aires": "ar-city-buenos-aires",
    "c-rdoba": "ar-city-cordoba",
    "mendoza": "ar-city-mendoza",
    "rosario": "ar-city-rosario",
  },
  AT: {
    "graz": "at-city-graz",
    "innsbruck": "at-city-innsbruck",
    "linz": "at-city-linz",
    "salzburg": "at-city-salzburg",
    "vienna": "at-city-vienna",
  },
  AU: {
    "melbourne": "au-city-melbourne",
    "sydney": "au-city-sydney",
  },
  AZ: {
    "baku": "az-city-baku",
    "ganja": "az-city-ganja",
    "sumqayit": "az-city-sumqayit",
  },
  BB: {
    "bridgetown": "bb-city-bridgetown",
  },
  BD: {
    "chittagong": "bd-city-chittagong",
    "dhaka": "bd-city-dhaka",
  },
  BE: {
    "antwerp": "be-city-antwerp",
    "brussels": "be-city-brussels",
  },
  BF: {
    "ouagadougou": "bf-city-ouagadougou",
  },
  BH: {
    "manama": "bh-city-manama",
  },
  BJ: {
    "cotonou": "bj-city-cotonou",
  },
  BO: {
    "la-paz": "bo-city-la-paz",
    "santa-cruz": "bo-city-santa-cruz",
  },
  BR: {
    "bel-m": "br-city-belem",
    "belo-horizonte": "br-city-belo-horizonte",
    "bras-lia": "br-city-brasilia",
    "campinas": "br-city-campinas",
    "curitiba": "br-city-curitiba",
    "florian-polis": "br-city-florianopolis",
    "fortaleza": "br-city-fortaleza",
    "goi-nia": "br-city-goiania",
    "manaus": "br-city-manaus",
    "porto-alegre": "br-city-porto-alegre",
    "recife": "br-city-recife",
    "rio-de-janeiro": "br-city-rio-de-janeiro",
    "s-o-paulo": "br-city-sao-paulo",
    "salvador": "br-city-salvador",
    "vit-ria": "br-city-vitoria",
  },
  BS: {
    "nassau": "bs-city-nassau",
  },
  BY: {
    "minsk": "by-city-minsk",
  },
  CA: {
    "calgary": "ca-city-calgary",
    "edmonton": "ca-city-edmonton",
    "halifax": "ca-city-halifax",
    "hamilton": "ca-city-hamilton",
    "montreal": "ca-qc",
    "ottawa": "ca-city-ottawa",
    "quebec-city": "ca-city-quebec-city",
    "toronto": "ca-on",
    "vancouver": "ca-bc",
    "winnipeg": "ca-city-winnipeg",
  },
  CH: {
    "basel": "ch-city-basel",
    "bern": "ch-city-bern",
    "geneva": "ch-city-geneva",
    "lausanne": "ch-city-lausanne",
    "lugano": "ch-city-lugano",
    "zurich": "ch-city-zurich",
  },
  CI: {
    "abidjan": "ci-city-abidjan",
    "yamoussoukro": "ci-city-yamoussoukro",
  },
  CL: {
    "antofagasta": "cl-city-antofagasta",
    "concepci-n": "cl-city-concepcion",
    "santiago": "cl-city-santiago",
    "valpara-so": "cl-city-valparaiso",
  },
  CM: {
    "douala": "cm-city-douala",
    "yaound": "cm-city-yaounde",
  },
  CN: {
    "beijing": "cn-city-beijing",
    "chengdu": "cn-city-chengdu",
    "chongqing": "cn-city-chongqing",
    "guangzhou": "cn-city-guangzhou",
    "hangzhou": "cn-city-hangzhou",
    "shanghai": "cn-city-shanghai",
    "shenzhen": "cn-city-shenzhen",
    "tianjin": "cn-city-tianjin",
    "wuhan": "cn-city-wuhan",
    "xian": "cn-city-xi-an",
  },
  CO: {
    "barranquilla": "co-city-barranquilla",
    "bogot": "co-city-bogota",
    "cali": "co-city-cali",
    "medell-n": "co-city-medellin",
  },
  CR: {
    "san-jos": "cr-city-san-jose",
  },
  CU: {
    "havana": "cu-city-havana",
  },
  CZ: {
    "prague": "cz01",
  },
  DE: {
    "berlin": "de3",
    "frankfurt": "de7",
    "hamburg": "de6",
    "munich": "de21",
  },
  DK: {
    "copenhagen": "dk01",
  },
  DO: {
    "santiago": "do-city-santiago",
    "santo-domingo": "do-city-santo-domingo",
  },
  DZ: {
    "algiers": "dz-city-algiers",
    "oran": "dz-city-oran",
  },
  EC: {
    "guayaquil": "ec-city-guayaquil",
    "quito": "ec-city-quito",
  },
  EG: {
    "alexandria": "eg-city-alexandria",
    "cairo": "eg-city-cairo",
    "giza": "eg-city-giza",
  },
  ES: {
    "barcelona": "es-08",
    "madrid": "es-28",
    "seville": "es-41",
    "valencia": "es-46",
  },
  ET: {
    "addis-ababa": "et-city-addis-ababa",
  },
  FI: {
    "helsinki": "fi1b",
  },
  FJ: {
    "suva": "fj-city-suva",
  },
  FR: {
    "lyon": "frk2",
    "marseille": "frl0",
    "paris": "fr10",
  },
  GB: {
    "birmingham-uk": "gb-e08000025",
    "edinburgh": "gb-s12000036",
    "london": "gb-e09000001",
    "manchester": "gb-e08000003",
  },
  GE: {
    "batumi": "ge-city-batumi",
    "kutaisi": "ge-city-kutaisi",
    "rustavi": "ge-city-rustavi",
    "tbilisi": "ge-city-tbilisi",
  },
  GH: {
    "accra": "gh-city-accra",
    "kumasi": "gh-city-kumasi",
  },
  GR: {
    "athens": "el3",
  },
  GT: {
    "guatemala-city": "gt-city-guatemala-city",
  },
  HK: {
    "hong-kong": "hk-city-hong-kong",
  },
  HN: {
    "san-pedro-sula": "hn-city-san-pedro-sula",
    "tegucigalpa": "hn-city-tegucigalpa",
  },
  HU: {
    "budapest": "hu1",
  },
  ID: {
    "bandung": "id-city-bandung",
    "jakarta": "id-city-jakarta",
    "makassar": "id-city-makassar",
    "medan": "id-city-medan",
    "semarang": "id-city-semarang",
    "surabaya": "id-city-surabaya",
  },
  IE: {
    "dublin": "ie06",
  },
  IL: {
    "ashdod": "il-city-ashdod",
    "beer-sheva": "il-city-be-er-sheva",
    "beersheba": "il-city-beersheba",
    "haifa": "il-city-haifa",
    "jerusalem": "il-city-jerusalem",
    "netanya": "il-city-netanya",
    "tel-aviv": "il-city-tel-aviv",
  },
  IN: {
    "ahmedabad": "in-city-ahmedabad",
    "bangalore": "in-city-bangalore",
    "chennai": "in-city-chennai",
    "delhi": "in-city-delhi",
    "hyderabad": "in-city-hyderabad",
    "kolkata": "in-city-kolkata",
    "mumbai": "in-city-mumbai",
    "pune": "in-city-pune",
  },
  IR: {
    "isfahan": "ir-city-isfahan",
    "mashhad": "ir-city-mashhad",
    "shiraz": "ir-city-shiraz",
    "tehran": "ir-city-tehran",
  },
  IT: {
    "milan": "it-city-milan",
    "rome": "it-city-rome",
  },
  JM: {
    "kingston": "jm-city-kingston",
  },
  JO: {
    "amman": "jo-city-amman",
  },
  JP: {
    "kyoto": "jp-26100",
    "osaka": "jp-27100",
    "tokyo": "jp-13000",
    "yokohama": "jp-14100",
  },
  KE: {
    "kisumu": "ke-city-kisumu",
    "mombasa": "ke-city-mombasa",
    "nairobi": "ke-city-nairobi",
  },
  KG: {
    "bishkek": "kg-city-bishkek",
  },
  KR: {
    "busan": "kr-city-busan",
    "daegu": "kr-city-daegu",
    "daejeon": "kr-city-daejeon",
    "gwangju": "kr-city-gwangju",
    "incheon": "kr-city-incheon",
    "seoul": "kr-city-seoul",
  },
  KW: {
    "kuwait-city": "kw-city-kuwait-city",
  },
  KZ: {
    "aktobe": "kz-city-aktobe",
    "almaty": "kz-city-almaty",
    "astana": "kz-city-astana",
    "karaganda": "kz-city-karaganda",
    "shymkent": "kz-city-shymkent",
  },
  LB: {
    "beirut": "lb-city-beirut",
  },
  LI: {
    "schaan": "li-city-schaan",
    "vaduz": "li-city-vaduz",
  },
  LK: {
    "colombo": "lk-city-colombo",
  },
  MA: {
    "casablanca": "ma-city-casablanca",
    "fez": "ma-city-fez",
    "marrakech": "ma-city-marrakech",
    "marrakesh": "ma-city-marrakesh",
    "rabat": "ma-city-rabat",
    "tangier": "ma-city-tangier",
  },
  MC: {
    "monaco": "mc-city-monaco",
  },
  MD: {
    "chi-in-u": "md-city-chisinau",
  },
  MG: {
    "antananarivo": "mg-city-antananarivo",
  },
  ML: {
    "bamako": "ml-city-bamako",
  },
  MX: {
    "mexico-city": "mx-city-mexico-city",
  },
  MY: {
    "george-town": "my-city-george-town",
    "johor-bahru": "my-city-johor-bahru",
    "kota-kinabalu": "my-city-kota-kinabalu",
    "kuala-lumpur": "my-city-kuala-lumpur",
    "penang": "my-city-penang",
  },
  MZ: {
    "maputo": "mz-city-maputo",
  },
  NE: {
    "niamey": "ne-city-niamey",
  },
  NG: {
    "abuja": "ng-city-abuja",
    "ibadan": "ng-city-ibadan",
    "kano": "ng-city-kano",
    "lagos": "ng-city-lagos",
    "port-harcourt": "ng-city-port-harcourt",
  },
  NI: {
    "managua": "ni-city-managua",
  },
  NL: {
    "amsterdam": "nl-gm0363",
    "rotterdam": "nl-gm0599",
  },
  NO: {
    "oslo": "no0",
  },
  NZ: {
    "auckland": "nz-city-auckland",
    "christchurch": "nz-city-christchurch",
    "hamilton": "nz-city-hamilton",
    "wellington": "nz-city-wellington",
  },
  OM: {
    "muscat": "om-city-muscat",
  },
  PA: {
    "panama-city": "pa-city-panama-city",
  },
  PE: {
    "arequipa": "pe-city-arequipa",
    "chiclayo": "pe-city-chiclayo",
    "lima": "pe-city-lima",
    "trujillo": "pe-city-trujillo",
  },
  PG: {
    "port-moresby": "pg-city-port-moresby",
  },
  PH: {
    "cebu": "ph-city-cebu",
    "davao": "ph-city-davao",
    "manila": "ph-city-manila",
    "quezon-city": "ph-city-quezon-city",
  },
  PK: {
    "faisalabad": "pk-city-faisalabad",
    "islamabad": "pk-city-islamabad",
    "karachi": "pk-city-karachi",
    "lahore": "pk-city-lahore",
  },
  PL: {
    "warsaw": "pl12",
  },
  PT: {
    "lisbon": "pt17",
  },
  PY: {
    "asunci-n": "py-city-asuncion",
  },
  QA: {
    "doha": "qa-city-doha",
  },
  RU: {
    "kazan": "ru-city-kazan",
    "krasnodar": "ru-city-krasnodar",
    "moscow": "ru-city-moscow",
    "nizhny-novgorod": "ru-city-nizhny-novgorod",
    "novosibirsk": "ru-city-novosibirsk",
    "rostov-on-don": "ru-city-rostov-on-don",
    "saint-petersburg": "ru-city-saint-petersburg",
    "samara": "ru-city-samara",
    "ufa": "ru-city-ufa",
    "yekaterinburg": "ru-city-yekaterinburg",
  },
  RW: {
    "kigali": "rw-city-kigali",
  },
  SA: {
    "dammam": "sa-city-dammam",
    "jeddah": "sa-city-jeddah",
    "mecca": "sa-city-mecca",
    "medina": "sa-city-medina",
    "riyadh": "sa-city-riyadh",
  },
  SE: {
    "stockholm": "se11",
  },
  SG: {
    "singapore": "sg-city-singapore",
  },
  SM: {
    "city-of-san-marino": "sm-city-city-of-san-marino",
    "serravalle": "sm-city-serravalle",
  },
  SN: {
    "dakar": "sn-city-dakar",
  },
  SV: {
    "san-salvador": "sv-city-san-salvador",
  },
  TH: {
    "bangkok": "th-city-bangkok",
    "chiang-mai": "th-city-chiang-mai",
    "pattaya": "th-city-pattaya",
    "phuket": "th-city-phuket",
  },
  TJ: {
    "dushanbe": "tj-city-dushanbe",
  },
  TM: {
    "ashgabat": "tm-city-ashgabat",
  },
  TN: {
    "sfax": "tn-city-sfax",
    "tunis": "tn-city-tunis",
  },
  TR: {
    "ankara": "tr-city-ankara",
    "antalya": "tr-city-antalya",
    "bursa": "tr-city-bursa",
    "istanbul": "tr-city-istanbul",
    "izmir": "tr-city-izmir",
  },
  TT: {
    "port-of-spain": "tt-city-port-of-spain",
  },
  TW: {
    "taipei": "tw-city-taipei",
  },
  TZ: {
    "dar-es-salaam": "tz-city-dar-es-salaam",
    "dodoma": "tz-city-dodoma",
  },
  UA: {
    "kharkiv": "ua-city-kharkiv",
    "kyiv": "ua-city-kyiv",
    "lviv": "ua-city-lviv",
    "odesa": "ua-city-odesa",
  },
  UG: {
    "kampala": "ug-city-kampala",
  },
  US: {
    "atlanta": "us-13-121",
    "austin": "us-48-453",
    "boston": "us-25-025",
    "chicago": "us-17-031",
    "dallas": "us-48-113",
    "denver": "us-08-031",
    "houston": "us-48-201",
    "los-angeles": "us-06-037",
    "miami": "us-12-086",
    "nashville": "us-47-037",
    "new-york": "us-city-new-york",
    "philadelphia": "us-42-101",
    "phoenix": "us-04-013",
    "portland": "us-41-051",
    "san-francisco": "us-06-075",
    "seattle": "us-53-033",
    "washington-dc": "us-11-001",
  },
  UY: {
    "montevideo": "uy-city-montevideo",
  },
  UZ: {
    "samarkand": "uz-city-samarkand",
    "tashkent": "uz-city-tashkent",
  },
  VE: {
    "caracas": "ve-city-caracas",
    "maracaibo": "ve-city-maracaibo",
  },
  VN: {
    "can-tho": "vn-city-can-tho",
    "da-nang": "vn-city-da-nang",
    "haiphong": "vn-city-haiphong",
    "hanoi": "vn-city-hanoi",
    "ho-chi-minh-city": "vn-city-ho-chi-minh",
  },
  WS: {
    "apia": "ws-city-apia",
  },
  ZA: {
    "cape-town": "za-city-cape-town",
    "durban": "za-city-durban",
    "johannesburg": "za-city-johannesburg",
    "port-elizabeth": "za-city-port-elizabeth",
    "pretoria": "za-city-pretoria",
  },
  ZM: {
    "kitwe": "zm-city-kitwe",
    "lusaka": "zm-city-lusaka",
  },
  ZW: {
    "bulawayo": "zw-city-bulawayo",
    "harare": "zw-city-harare",
  },
};

/** country (ISO-2 upper) → region/state slug → list of city friendly slugs */
export const CITIES_BY_STATE: Record<string, Record<string, string[]>> = {
  AE: {
    "dubai": ["dubai"],
  },
  AR: {
    "buenos-aires-province": ["buenos-aires"],
  },
  AT: {
    "vienna": ["vienna"],
  },
  AU: {
    "new-south-wales": ["sydney"],
    "victoria": ["melbourne"],
  },
  BE: {
    "brussels-capital": ["brussels"],
    "flanders": ["antwerp"],
  },
  BR: {
    "rio-de-janeiro": ["rio-de-janeiro"],
    "s-o-paulo": ["s-o-paulo"],
  },
  CA: {
    "british-columbia": ["vancouver"],
    "ontario": ["toronto"],
    "quebec": ["montreal"],
  },
  CH: {
    "z-rich": ["zurich"],
  },
  CL: {
    "santiago-metropolitan": ["santiago"],
  },
  CN: {
    "beijing-municipality": ["beijing"],
    "guangdong": ["guangzhou","shenzhen"],
    "shanghai-municipality": ["shanghai"],
  },
  CO: {
    "bogot-d-c": ["bogot"],
  },
  CZ: {
    "prague": ["prague"],
  },
  DE: {
    "bavaria": ["munich"],
    "berlin": ["berlin"],
    "hamburg": ["hamburg"],
    "hessen": ["frankfurt"],
  },
  DK: {
    "capital-region": ["copenhagen"],
  },
  EG: {
    "cairo-governorate": ["cairo"],
  },
  ES: {
    "andaluc-a": ["seville"],
    "catalu-a": ["barcelona"],
    "comunidad-de-madrid": ["madrid"],
    "comunidad-valenciana": ["valencia"],
  },
  FI: {
    "uusimaa": ["helsinki"],
  },
  FR: {
    "auvergne-rh-ne-alpes": ["lyon"],
    "le-de-france": ["paris"],
    "provence-alpes-c-te-dazur": ["marseille"],
  },
  GB: {
    "england": ["london","manchester","birmingham-uk"],
    "scotland": ["edinburgh"],
  },
  GR: {
    "attica": ["athens"],
  },
  HK: {
    "hong-kong": ["hong-kong"],
  },
  HU: {
    "budapest": ["budapest"],
  },
  ID: {
    "dki-jakarta": ["jakarta"],
  },
  IE: {
    "eastern-and-midland": ["dublin"],
  },
  IL: {
    "tel-aviv-district": ["tel-aviv"],
  },
  IN: {
    "delhi": ["delhi"],
    "karnataka": ["bangalore"],
    "maharashtra": ["mumbai","pune"],
    "tamil-nadu": ["chennai"],
    "telangana": ["hyderabad"],
    "west-bengal": ["kolkata"],
  },
  IR: {
    "tehran-province": ["tehran"],
  },
  IT: {
    "lazio": ["rome"],
    "lombardia": ["milan"],
  },
  JP: {
    "kanagawa": ["yokohama"],
    "kyoto-prefecture": ["kyoto"],
    "osaka": ["osaka"],
    "tokyo-metropolis": ["tokyo"],
  },
  KE: {
    "nairobi-county": ["nairobi"],
  },
  KR: {
    "busan-metropolitan": ["busan"],
    "seoul-special-city": ["seoul"],
  },
  MA: {
    "casablanca-settat": ["casablanca"],
  },
  MX: {
    "ciudad-de-m-xico": ["mexico-city"],
  },
  MY: {
    "kuala-lumpur": ["kuala-lumpur"],
  },
  NG: {
    "lagos-state": ["lagos"],
  },
  NL: {
    "noord-holland": ["amsterdam"],
    "zuid-holland": ["rotterdam"],
  },
  NO: {
    "oslo": ["oslo"],
  },
  NZ: {
    "auckland-region": ["auckland"],
    "wellington-region": ["wellington"],
  },
  PE: {
    "lima-province": ["lima"],
  },
  PH: {
    "national-capital-region": ["manila"],
  },
  PK: {
    "sindh": ["karachi"],
  },
  PL: {
    "mazowieckie": ["warsaw"],
  },
  PT: {
    "lisbon-region": ["lisbon"],
  },
  RU: {
    "moscow-federal-city": ["moscow"],
  },
  SA: {
    "riyadh-province": ["riyadh"],
  },
  SE: {
    "stockholm-county": ["stockholm"],
  },
  SG: {
    "singapore": ["singapore"],
  },
  TH: {
    "bangkok-metropolitan": ["bangkok"],
  },
  TR: {
    "istanbul-province": ["istanbul"],
  },
  TW: {
    "taipei": ["taipei"],
  },
  US: {
    "arizona": ["phoenix"],
    "california": ["los-angeles","san-francisco"],
    "colorado": ["denver"],
    "district-of-columbia": ["washington-dc"],
    "florida": ["miami"],
    "georgia": ["atlanta"],
    "illinois": ["chicago"],
    "massachusetts": ["boston"],
    "new-york": ["new-york"],
    "oregon": ["portland"],
    "pennsylvania": ["philadelphia"],
    "tennessee": ["nashville"],
    "texas": ["dallas","houston","austin"],
    "washington": ["seattle"],
  },
  VN: {
    "ho-chi-minh": ["ho-chi-minh-city"],
  },
  ZA: {
    "gauteng": ["johannesburg"],
    "western-cape": ["cape-town"],
  },
};

/** country (ISO-2 upper) -> friendly city slug -> canonical display label. */
/** Used to override cell.geo_name when the URL used a friendly alias, so   */
/** /es/barcelona/restaurants always renders 'Barcelona', never 'ES' or a   */
/** malformed DB value like 'Tokoto'. Plan v23 Part 1 grammar fix.          */
export const CITY_FRIENDLY_DISPLAY_LABEL: Record<string, Record<string, string>> = {
  AD: {
    "andorra-la-vella": "Andorra la Vella",
  },
  AE: {
    "abu-dhabi": "Abu Dhabi",
    "dubai": "Dubai",
    "sharjah": "Sharjah",
  },
  AL: {
    "durr-s": "Durrës",
    "elbasan": "Elbasan",
    "fier": "Fier",
    "shkod-r": "Shkodër",
    "tirana": "Tirana",
    "vlor": "Vlorë",
  },
  AM: {
    "yerevan": "Yerevan",
  },
  AO: {
    "luanda": "Luanda",
  },
  AR: {
    "buenos-aires": "Buenos Aires",
    "c-rdoba": "Córdoba",
    "mendoza": "Mendoza",
    "rosario": "Rosario",
  },
  AT: {
    "graz": "Graz",
    "innsbruck": "Innsbruck",
    "linz": "Linz",
    "salzburg": "Salzburg",
    "vienna": "Vienna",
  },
  AU: {
    "melbourne": "Melbourne",
    "sydney": "Sydney",
  },
  AZ: {
    "baku": "Baku",
    "ganja": "Ganja",
    "sumqayit": "Sumqayit",
  },
  BB: {
    "bridgetown": "Bridgetown",
  },
  BD: {
    "chittagong": "Chittagong",
    "dhaka": "Dhaka",
  },
  BE: {
    "antwerp": "Antwerp",
    "brussels": "Brussels",
  },
  BF: {
    "ouagadougou": "Ouagadougou",
  },
  BH: {
    "manama": "Manama",
  },
  BJ: {
    "cotonou": "Cotonou",
  },
  BO: {
    "la-paz": "La Paz",
    "santa-cruz": "Santa Cruz",
  },
  BR: {
    "bel-m": "Belém",
    "belo-horizonte": "Belo Horizonte",
    "bras-lia": "Brasília",
    "campinas": "Campinas",
    "curitiba": "Curitiba",
    "florian-polis": "Florianópolis",
    "fortaleza": "Fortaleza",
    "goi-nia": "Goiânia",
    "manaus": "Manaus",
    "porto-alegre": "Porto Alegre",
    "recife": "Recife",
    "rio-de-janeiro": "Rio de Janeiro",
    "s-o-paulo": "São Paulo",
    "salvador": "Salvador",
    "vit-ria": "Vitória",
  },
  BS: {
    "nassau": "Nassau",
  },
  BY: {
    "minsk": "Minsk",
  },
  CA: {
    "calgary": "Calgary",
    "edmonton": "Edmonton",
    "halifax": "Halifax",
    "hamilton": "Hamilton",
    "montreal": "Montreal",
    "ottawa": "Ottawa",
    "quebec-city": "Quebec City",
    "toronto": "Toronto",
    "vancouver": "Vancouver",
    "winnipeg": "Winnipeg",
  },
  CH: {
    "basel": "Basel",
    "bern": "Bern",
    "geneva": "Geneva",
    "lausanne": "Lausanne",
    "lugano": "Lugano",
    "zurich": "Zurich",
  },
  CI: {
    "abidjan": "Abidjan",
    "yamoussoukro": "Yamoussoukro",
  },
  CL: {
    "antofagasta": "Antofagasta",
    "concepci-n": "Concepción",
    "santiago": "Santiago",
    "valpara-so": "Valparaíso",
  },
  CM: {
    "douala": "Douala",
    "yaound": "Yaoundé",
  },
  CN: {
    "beijing": "Beijing",
    "chengdu": "Chengdu",
    "chongqing": "Chongqing",
    "guangzhou": "Guangzhou",
    "hangzhou": "Hangzhou",
    "shanghai": "Shanghai",
    "shenzhen": "Shenzhen",
    "tianjin": "Tianjin",
    "wuhan": "Wuhan",
    "xian": "Xi'an",
  },
  CO: {
    "barranquilla": "Barranquilla",
    "bogot": "Bogotá",
    "cali": "Cali",
    "medell-n": "Medellín",
  },
  CR: {
    "san-jos": "San José",
  },
  CU: {
    "havana": "Havana",
  },
  CZ: {
    "prague": "Prague",
  },
  DE: {
    "berlin": "Berlin",
    "frankfurt": "Frankfurt",
    "hamburg": "Hamburg",
    "munich": "Munich",
  },
  DK: {
    "copenhagen": "Copenhagen",
  },
  DO: {
    "santiago": "Santiago",
    "santo-domingo": "Santo Domingo",
  },
  DZ: {
    "algiers": "Algiers",
    "oran": "Oran",
  },
  EC: {
    "guayaquil": "Guayaquil",
    "quito": "Quito",
  },
  EG: {
    "alexandria": "Alexandria",
    "cairo": "Cairo",
    "giza": "Giza",
  },
  ES: {
    "barcelona": "Barcelona",
    "madrid": "Madrid",
    "seville": "Seville",
    "valencia": "Valencia",
  },
  ET: {
    "addis-ababa": "Addis Ababa",
  },
  FI: {
    "helsinki": "Helsinki",
  },
  FJ: {
    "suva": "Suva",
  },
  FR: {
    "lyon": "Lyon",
    "marseille": "Marseille",
    "paris": "Paris",
  },
  GB: {
    "birmingham-uk": "Birmingham (UK)",
    "edinburgh": "Edinburgh",
    "london": "London",
    "manchester": "Manchester",
  },
  GE: {
    "batumi": "Batumi",
    "kutaisi": "Kutaisi",
    "rustavi": "Rustavi",
    "tbilisi": "Tbilisi",
  },
  GH: {
    "accra": "Accra",
    "kumasi": "Kumasi",
  },
  GR: {
    "athens": "Athens",
  },
  GT: {
    "guatemala-city": "Guatemala City",
  },
  HK: {
    "hong-kong": "Hong Kong",
  },
  HN: {
    "san-pedro-sula": "San Pedro Sula",
    "tegucigalpa": "Tegucigalpa",
  },
  HU: {
    "budapest": "Budapest",
  },
  ID: {
    "bandung": "Bandung",
    "jakarta": "Jakarta",
    "makassar": "Makassar",
    "medan": "Medan",
    "semarang": "Semarang",
    "surabaya": "Surabaya",
  },
  IE: {
    "dublin": "Dublin",
  },
  IL: {
    "ashdod": "Ashdod",
    "beer-sheva": "Be'er Sheva",
    "beersheba": "Beersheba",
    "haifa": "Haifa",
    "jerusalem": "Jerusalem",
    "netanya": "Netanya",
    "tel-aviv": "Tel Aviv",
  },
  IN: {
    "ahmedabad": "Ahmedabad",
    "bangalore": "Bangalore",
    "chennai": "Chennai",
    "delhi": "Delhi",
    "hyderabad": "Hyderabad",
    "kolkata": "Kolkata",
    "mumbai": "Mumbai",
    "pune": "Pune",
  },
  IR: {
    "isfahan": "Isfahan",
    "mashhad": "Mashhad",
    "shiraz": "Shiraz",
    "tehran": "Tehran",
  },
  IT: {
    "milan": "Milan",
    "rome": "Rome",
  },
  JM: {
    "kingston": "Kingston",
  },
  JO: {
    "amman": "Amman",
  },
  JP: {
    "kyoto": "Kyoto",
    "osaka": "Osaka",
    "tokyo": "Tokyo",
    "yokohama": "Yokohama",
  },
  KE: {
    "kisumu": "Kisumu",
    "mombasa": "Mombasa",
    "nairobi": "Nairobi",
  },
  KG: {
    "bishkek": "Bishkek",
  },
  KR: {
    "busan": "Busan",
    "daegu": "Daegu",
    "daejeon": "Daejeon",
    "gwangju": "Gwangju",
    "incheon": "Incheon",
    "seoul": "Seoul",
  },
  KW: {
    "kuwait-city": "Kuwait City",
  },
  KZ: {
    "aktobe": "Aktobe",
    "almaty": "Almaty",
    "astana": "Astana",
    "karaganda": "Karaganda",
    "shymkent": "Shymkent",
  },
  LB: {
    "beirut": "Beirut",
  },
  LI: {
    "schaan": "Schaan",
    "vaduz": "Vaduz",
  },
  LK: {
    "colombo": "Colombo",
  },
  MA: {
    "casablanca": "Casablanca",
    "fez": "Fez",
    "marrakech": "Marrakech",
    "marrakesh": "Marrakesh",
    "rabat": "Rabat",
    "tangier": "Tangier",
  },
  MC: {
    "monaco": "Monaco",
  },
  MD: {
    "chi-in-u": "Chișinău",
  },
  MG: {
    "antananarivo": "Antananarivo",
  },
  ML: {
    "bamako": "Bamako",
  },
  MX: {
    "mexico-city": "Mexico City",
  },
  MY: {
    "george-town": "George Town",
    "johor-bahru": "Johor Bahru",
    "kota-kinabalu": "Kota Kinabalu",
    "kuala-lumpur": "Kuala Lumpur",
    "penang": "Penang",
  },
  MZ: {
    "maputo": "Maputo",
  },
  NE: {
    "niamey": "Niamey",
  },
  NG: {
    "abuja": "Abuja",
    "ibadan": "Ibadan",
    "kano": "Kano",
    "lagos": "Lagos",
    "port-harcourt": "Port Harcourt",
  },
  NI: {
    "managua": "Managua",
  },
  NL: {
    "amsterdam": "Amsterdam",
    "rotterdam": "Rotterdam",
  },
  NO: {
    "oslo": "Oslo",
  },
  NZ: {
    "auckland": "Auckland",
    "christchurch": "Christchurch",
    "hamilton": "Hamilton",
    "wellington": "Wellington",
  },
  OM: {
    "muscat": "Muscat",
  },
  PA: {
    "panama-city": "Panama City",
  },
  PE: {
    "arequipa": "Arequipa",
    "chiclayo": "Chiclayo",
    "lima": "Lima",
    "trujillo": "Trujillo",
  },
  PG: {
    "port-moresby": "Port Moresby",
  },
  PH: {
    "cebu": "Cebu",
    "davao": "Davao",
    "manila": "Manila",
    "quezon-city": "Quezon City",
  },
  PK: {
    "faisalabad": "Faisalabad",
    "islamabad": "Islamabad",
    "karachi": "Karachi",
    "lahore": "Lahore",
  },
  PL: {
    "warsaw": "Warsaw",
  },
  PT: {
    "lisbon": "Lisbon",
  },
  PY: {
    "asunci-n": "Asunción",
  },
  QA: {
    "doha": "Doha",
  },
  RU: {
    "kazan": "Kazan",
    "krasnodar": "Krasnodar",
    "moscow": "Moscow",
    "nizhny-novgorod": "Nizhny Novgorod",
    "novosibirsk": "Novosibirsk",
    "rostov-on-don": "Rostov-on-Don",
    "saint-petersburg": "Saint Petersburg",
    "samara": "Samara",
    "ufa": "Ufa",
    "yekaterinburg": "Yekaterinburg",
  },
  RW: {
    "kigali": "Kigali",
  },
  SA: {
    "dammam": "Dammam",
    "jeddah": "Jeddah",
    "mecca": "Mecca",
    "medina": "Medina",
    "riyadh": "Riyadh",
  },
  SE: {
    "stockholm": "Stockholm",
  },
  SG: {
    "singapore": "Singapore",
  },
  SM: {
    "city-of-san-marino": "City of San Marino",
    "serravalle": "Serravalle",
  },
  SN: {
    "dakar": "Dakar",
  },
  SV: {
    "san-salvador": "San Salvador",
  },
  TH: {
    "bangkok": "Bangkok",
    "chiang-mai": "Chiang Mai",
    "pattaya": "Pattaya",
    "phuket": "Phuket",
  },
  TJ: {
    "dushanbe": "Dushanbe",
  },
  TM: {
    "ashgabat": "Ashgabat",
  },
  TN: {
    "sfax": "Sfax",
    "tunis": "Tunis",
  },
  TR: {
    "ankara": "Ankara",
    "antalya": "Antalya",
    "bursa": "Bursa",
    "istanbul": "Istanbul",
    "izmir": "Izmir",
  },
  TT: {
    "port-of-spain": "Port of Spain",
  },
  TW: {
    "taipei": "Taipei",
  },
  TZ: {
    "dar-es-salaam": "Dar es Salaam",
    "dodoma": "Dodoma",
  },
  UA: {
    "kharkiv": "Kharkiv",
    "kyiv": "Kyiv",
    "lviv": "Lviv",
    "odesa": "Odesa",
  },
  UG: {
    "kampala": "Kampala",
  },
  US: {
    "atlanta": "Atlanta",
    "austin": "Austin",
    "boston": "Boston",
    "chicago": "Chicago",
    "dallas": "Dallas",
    "denver": "Denver",
    "houston": "Houston",
    "los-angeles": "Los Angeles",
    "miami": "Miami",
    "nashville": "Nashville",
    "new-york": "New York",
    "philadelphia": "Philadelphia",
    "phoenix": "Phoenix",
    "portland": "Portland",
    "san-francisco": "San Francisco",
    "seattle": "Seattle",
    "washington-dc": "Washington DC",
  },
  UY: {
    "montevideo": "Montevideo",
  },
  UZ: {
    "samarkand": "Samarkand",
    "tashkent": "Tashkent",
  },
  VE: {
    "caracas": "Caracas",
    "maracaibo": "Maracaibo",
  },
  VN: {
    "can-tho": "Can Tho",
    "da-nang": "Da Nang",
    "haiphong": "Haiphong",
    "hanoi": "Hanoi",
    "ho-chi-minh-city": "Ho Chi Minh City",
  },
  WS: {
    "apia": "Apia",
  },
  ZA: {
    "cape-town": "Cape Town",
    "durban": "Durban",
    "johannesburg": "Johannesburg",
    "port-elizabeth": "Port Elizabeth",
    "pretoria": "Pretoria",
  },
  ZM: {
    "kitwe": "Kitwe",
    "lusaka": "Lusaka",
  },
  ZW: {
    "bulawayo": "Bulawayo",
    "harare": "Harare",
  },
};