/**
 * scripts/cities/build_uk_cities.ts
 *
 * THE UK'S CITIES WITH A PAGE, FOR THE HOME SEARCH (milestone 3, masterplan step 33): read from data/cities/city_list_v1.json and
 * written to src/lib/home/uk_cities_generated.ts, a few lines the search form can carry to the browser where the 216 KB list
 * cannot. Never typed: the destination test (tests/home/destination.test.ts) holds the generated file to the list, so a city
 * added to the list and not regenerated reds there.
 *
 * Run: npx tsx scripts/cities/build_uk_cities.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

type Entry = { slug: string; name: string; iso2: string };
const list = (JSON.parse(readFileSync("data/cities/city_list_v1.json", "utf8")) as { cities: Entry[] }).cities;
const uk = list
  .filter((c) => c.iso2.toUpperCase() === "GB")
  .map((c) => ({ slug: c.slug, label: c.name }))
  .sort((a, b) => a.label.localeCompare(b.label));
const body = [
  "/**",
  " * AUTO-GENERATED by scripts/cities/build_uk_cities.ts from data/cities/city_list_v1.json: the UK's cities with a page of their",
  " * own, by name. Do not edit; run the script. tests/home/destination.test.ts holds this file to the list.",
  " */",
  `export const UK_CITY_PAGES: ReadonlyArray<{ slug: string; label: string }> = ${JSON.stringify(uk, null, 2).replace(/"(slug|label)":/g, "$1:")};`,
  "",
].join("\n");
writeFileSync("src/lib/home/uk_cities_generated.ts", body, "utf8");
console.log(`wrote src/lib/home/uk_cities_generated.ts: ${uk.length} cities (${uk.map((c) => c.slug).join(", ")})`);
