/**
 * atlas-icons-data.ts - the 40-glyph ma- UI icon manifest, ported from the
 * design export (docs/brand/assets/incoming/Margin-Atlas--5/atlas-icons.js)
 * per docs/brand/visual-assets.md 2.3. GENERATED by a one-shot converter;
 * edit glyphs here directly from now on (the export is reference only).
 * One family: 32-unit grid, 1.6 stroke, rounded joins, currentColor ink,
 * one sparing vermillion accent per glyph at most.
 */

export type AtlasIconId =
  | "startup-cost"
  | "owner-keeps"
  | "revenue"
  | "range"
  | "cost-breakdown"
  | "wages"
  | "break-even"
  | "seasonality"
  | "first-year"
  | "competition"
  | "taxes"
  | "register-cost"
  | "red-tape"
  | "hiring"
  | "min-wage"
  | "spending-power"
  | "commercial-rent"
  | "free-zone"
  | "airport"
  | "tourist"
  | "best-areas"
  | "neighborhood"
  | "compare"
  | "vs-world"
  | "corruption"
  | "locals-know"
  | "honest-take"
  | "contrarian"
  | "myth-reality"
  | "who-for"
  | "gut-check"
  | "worked-example"
  | "operator-voices"
  | "freshness"
  | "flag"
  | "bookmark"
  | "watch"
  | "calculator"
  | "methodology"
  | "search";

export type AtlasIconGroup =
  | "money-performance"
  | "cost-rules-workforce"
  | "place-comparison"
  | "judgement-voice"
  | "interface-actions";

export interface AtlasIconDef {
  id: AtlasIconId;
  group: AtlasIconGroup;
  label: string;
  blurb: string;
  /** Raw SVG inner markup (viewBox 0 0 32 32, stroke-based). The
   *  accent classes "a" (stroke) / "af" (fill) bind to the vermillion
   *  token through the component layer, never a hardcoded hex. */
  body: string;
}

export const ATLAS_ICONS: AtlasIconDef[] = [
  {
    id: "startup-cost",
    group: "money-performance",
    label: "Startup cost",
    blurb: "What it takes to open the doors.",
    body: "<ellipse class=\"a\" cx=\"16\" cy=\"9\" rx=\"8\" ry=\"3\"/><path d=\"M8 9v4c0 1.7 3.6 3 8 3s8-1.3 8-3V9\"/><path d=\"M8 13v4c0 1.7 3.6 3 8 3s8-1.3 8-3v-4\"/><path d=\"M8 17v4c0 1.7 3.6 3 8 3s8-1.3 8-3v-4\"/>",
  },
  {
    id: "owner-keeps",
    group: "money-performance",
    label: "What the owner keeps",
    blurb: "The take-home after everything is paid.",
    body: "<rect x=\"5\" y=\"8\" width=\"22\" height=\"16\" rx=\"3\"/><path d=\"M19 14h8v5h-8a2.5 2.5 0 0 1 0-5Z\"/><circle class=\"af\" cx=\"21.5\" cy=\"16.5\" r=\"1.3\"/>",
  },
  {
    id: "revenue",
    group: "money-performance",
    label: "Revenue",
    blurb: "Top-line turnover before costs.",
    body: "<path d=\"M5 22 13 14l4 4L27 8\"/><path class=\"a\" d=\"M21 8h6v6\"/>",
  },
  {
    id: "range",
    group: "money-performance",
    label: "Range / spread",
    blurb: "Low to high, with the median marked.",
    body: "<path d=\"M7 16h18\"/><path d=\"M7 11v10M25 11v10\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"2.2\"/>",
  },
  {
    id: "cost-breakdown",
    group: "money-performance",
    label: "Where the money goes",
    blurb: "Cost breakdown, slice by slice.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><path d=\"M16 16V5\"/><path d=\"M16 16 25.5 21.5\"/><path class=\"a\" d=\"M16 5a11 11 0 0 1 9.5 16.5\"/>",
  },
  {
    id: "wages",
    group: "money-performance",
    label: "Wages by role",
    blurb: "What each seat on the floor costs.",
    body: "<circle cx=\"9\" cy=\"10\" r=\"3.4\"/><path d=\"M3.4 24c0-3.4 2.5-5.6 5.6-5.6s5.6 2.2 5.6 5.6\"/><path d=\"M20 24v-5\"/><path d=\"M24 24v-8.5\"/><path class=\"a\" d=\"M28 24v-12\"/>",
  },
  {
    id: "break-even",
    group: "money-performance",
    label: "Break-even",
    blurb: "Where cost and revenue finally cross.",
    body: "<path d=\"M5 24 27 8\"/><path d=\"M5 8 27 24\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"2.2\"/>",
  },
  {
    id: "seasonality",
    group: "money-performance",
    label: "Seasonality",
    blurb: "The annual rhythm of busy and quiet.",
    body: "<path d=\"M4 16c2.4-6 4.8-6 7.2 0s4.8 6 7.2 0 4.8-6 7.2 0\"/><circle class=\"af\" cx=\"7.6\" cy=\"11.2\" r=\"1.5\"/>",
  },
  {
    id: "first-year",
    group: "money-performance",
    label: "First year",
    blurb: "The make-or-break opening twelve months.",
    body: "<rect x=\"5\" y=\"7\" width=\"22\" height=\"20\" rx=\"2.5\"/><path d=\"M5 13h22\"/><path d=\"M11 4v5M21 4v5\"/><rect class=\"af\" x=\"9.5\" y=\"16.5\" width=\"4.5\" height=\"4.5\" rx=\"1\"/>",
  },
  {
    id: "competition",
    group: "cost-rules-workforce",
    label: "Competition",
    blurb: "How crowded the field already is.",
    body: "<path d=\"M8 5v22\"/><path d=\"M8 7h8l-2.6 3 2.6 3H8\"/><path d=\"M24 5v22\"/><path class=\"a\" d=\"M24 7h-8l2.6 3-2.6 3h8\"/>",
  },
  {
    id: "taxes",
    group: "cost-rules-workforce",
    label: "Taxes",
    blurb: "The state's cut, line by line.",
    body: "<path d=\"M4 13 16 6l12 7\"/><path d=\"M5 13h22\"/><path d=\"M8 13v11M14 13v11M18 13v11M24 13v11\"/><path d=\"M5 27h22\"/>",
  },
  {
    id: "register-cost",
    group: "cost-rules-workforce",
    label: "Cost to register",
    blurb: "Fees and filings to become legal.",
    body: "<path d=\"M9 5h9l5 5v13a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z\"/><path d=\"M18 5v5h5\"/><circle class=\"a\" cx=\"15\" cy=\"18\" r=\"3.4\"/><path class=\"a\" d=\"M13 20.5 12 25l3-1.8L18 25l-1-4.5\"/>",
  },
  {
    id: "red-tape",
    group: "cost-rules-workforce",
    label: "Red tape / time-to-open",
    blurb: "How long the bureaucracy takes.",
    body: "<path d=\"M8 5h16M8 27h16\"/><path d=\"M10 5c0 5 6 7 6 11s-6 6-6 11\"/><path d=\"M22 5c0 5-6 7-6 11s6 6 6 11\"/><path class=\"af\" d=\"M12 25h8l-4-5Z\"/>",
  },
  {
    id: "hiring",
    group: "cost-rules-workforce",
    label: "Hiring / workforce",
    blurb: "The people you need on payroll.",
    body: "<circle cx=\"11\" cy=\"12\" r=\"3.2\"/><circle cx=\"21\" cy=\"12\" r=\"3.2\"/><path d=\"M5 24c0-3.3 2.7-5.4 6-5.4s6 2.1 6 5.4\"/><path d=\"M15 24c0-3.3 2.7-5.4 6-5.4s6 2.1 6 5.4\"/><path class=\"a\" d=\"M26 6v5M23.5 8.5h5\"/>",
  },
  {
    id: "min-wage",
    group: "cost-rules-workforce",
    label: "Minimum wage",
    blurb: "The legal floor under every wage.",
    body: "<circle cx=\"16\" cy=\"12\" r=\"6.5\"/><path d=\"M16 8v8M13.8 9.5h3a2 2 0 0 1 0 4h-2a2 2 0 0 0 0 4h3\"/><path class=\"a\" d=\"M5 25h22\"/>",
  },
  {
    id: "spending-power",
    group: "cost-rules-workforce",
    label: "Local spending power",
    blurb: "What customers here can actually pay.",
    body: "<path d=\"M8 11h16l-1.4 14.5a1.8 1.8 0 0 1-1.8 1.6H11.2a1.8 1.8 0 0 1-1.8-1.6Z\"/><path d=\"M12 11V8.5a4 4 0 0 1 8 0V11\"/><circle class=\"af\" cx=\"16\" cy=\"18\" r=\"1.8\"/>",
  },
  {
    id: "commercial-rent",
    group: "cost-rules-workforce",
    label: "Commercial rent",
    blurb: "The price of a storefront, monthly.",
    body: "<path d=\"M5 13 7 7h18l2 6\"/><path d=\"M5 13h22\"/><path d=\"M7 13v14h18V13\"/><path class=\"a\" d=\"M13 27v-7h6v7\"/>",
  },
  {
    id: "free-zone",
    group: "cost-rules-workforce",
    label: "Free economic zone",
    blurb: "A ring-fenced, tax-light enclave.",
    body: "<rect x=\"5\" y=\"5\" width=\"22\" height=\"22\" rx=\"3\" stroke-dasharray=\"4 3.4\"/><circle class=\"a\" cx=\"11.5\" cy=\"11.5\" r=\"1.5\"/><circle class=\"a\" cx=\"20.5\" cy=\"20.5\" r=\"1.5\"/><path class=\"a\" d=\"M21 11 11 21\"/>",
  },
  {
    id: "airport",
    group: "cost-rules-workforce",
    label: "Airport / captive venue",
    blurb: "A site with a built-in, trapped crowd.",
    body: "<path d=\"M16 4c1.1 0 1.9 2 1.9 4.8v3.4l8.1 4.9v2.4l-8.1-2.4v4l2.5 1.9v1.9L16 24l-4.4 1.3v-1.9l2.5-1.9v-4l-8.1 2.4v-2.4l8.1-4.9V8.8C14.1 6 14.9 4 16 4Z\"/>",
  },
  {
    id: "tourist",
    group: "place-comparison",
    label: "Tourist vs local",
    blurb: "Visitor money against resident money.",
    body: "<rect x=\"4\" y=\"10\" width=\"24\" height=\"16\" rx=\"2.5\"/><path d=\"M11 10l2-3h6l2 3\"/><circle cx=\"16\" cy=\"18\" r=\"4.5\"/><circle class=\"af\" cx=\"16\" cy=\"18\" r=\"1.6\"/><circle cx=\"23.5\" cy=\"13.5\" r=\"1\"/>",
  },
  {
    id: "best-areas",
    group: "place-comparison",
    label: "Best areas",
    blurb: "Where this trade actually wins.",
    body: "<path d=\"M16 28c5.5-6.5 9-10 9-14.5A9 9 0 0 0 7 13.5C7 18 10.5 21.5 16 28Z\"/><path class=\"af\" d=\"M16 9.4 16.88 11.79 19.42 11.89 17.43 13.46 18.12 15.91 16 14.5 13.88 15.91 14.57 13.46 12.58 11.89 15.12 11.79Z\"/>",
  },
  {
    id: "neighborhood",
    group: "place-comparison",
    label: "Neighborhood",
    blurb: "The few blocks that set the tone.",
    body: "<path d=\"M4 27h24\"/><path d=\"M6 27V15h7v12\"/><path d=\"M13 27V9h7v18\"/><path d=\"M20 27V19h6v8\"/><path d=\"M8.5 20h2.5M22 23h2\"/><rect class=\"af\" x=\"15.4\" y=\"12.5\" width=\"3\" height=\"3\" rx=\".6\"/>",
  },
  {
    id: "compare",
    group: "place-comparison",
    label: "Compare",
    blurb: "Two places, weighed side by side.",
    body: "<path d=\"M6 13h14\"/><path class=\"a\" d=\"M17 9 21 13l-4 4\"/><path d=\"M26 19H12\"/><path d=\"M15 15l-4 4 4 4\"/>",
  },
  {
    id: "vs-world",
    group: "place-comparison",
    label: "Vs the world",
    blurb: "How this market reads globally.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><path d=\"M5 16h22\"/><ellipse cx=\"16\" cy=\"16\" rx=\"5\" ry=\"11\"/><circle class=\"af\" cx=\"20\" cy=\"11\" r=\"1.6\"/>",
  },
  {
    id: "corruption",
    group: "judgement-voice",
    label: "Corruption / informal economy",
    blurb: "What changes hands off the books.",
    body: "<rect class=\"a\" x=\"11\" y=\"5\" width=\"10\" height=\"6\" rx=\"1\"/><rect x=\"5\" y=\"9\" width=\"22\" height=\"14\" rx=\"2\"/><path d=\"M5 10 16 18 27 10\"/>",
  },
  {
    id: "locals-know",
    group: "judgement-voice",
    label: "What locals know",
    blurb: "The insider read you can't Google.",
    body: "<circle class=\"a\" cx=\"10\" cy=\"10\" r=\"4.5\"/><path d=\"M13.2 13.2 25 25\"/><path d=\"M21 21l2.5-2.5M24 24l2.5-2.5\"/>",
  },
  {
    id: "honest-take",
    group: "judgement-voice",
    label: "The honest take",
    blurb: "Our straight read, no spin.",
    body: "<path d=\"M4 16s4.5-8 12-8 12 8 12 8-4.5 8-12 8S4 16 4 16Z\"/><circle cx=\"16\" cy=\"16\" r=\"3.4\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"1.4\"/>",
  },
  {
    id: "contrarian",
    group: "judgement-voice",
    label: "Contrarian insight",
    blurb: "The view that cuts against the room.",
    body: "<path d=\"M11 21a8 8 0 1 1 10 0c-.9.7-1.4 1.7-1.4 2.8v.7h-7.2v-.7c0-1.1-.5-2.1-1.4-2.8Z\"/><path d=\"M12.5 27h7M13.5 30h5\"/><path class=\"a\" d=\"M13.5 16.5 16 12l2.5 4.5\"/>",
  },
  {
    id: "myth-reality",
    group: "judgement-voice",
    label: "Myth vs reality",
    blurb: "What's believed against what's true.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><path class=\"af\" d=\"M16 5a11 11 0 0 1 0 22Z\"/><path d=\"M16 5v22\"/>",
  },
  {
    id: "who-for",
    group: "judgement-voice",
    label: "Who it's for",
    blurb: "The operator this actually suits.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><circle cx=\"16\" cy=\"16\" r=\"6\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"2.3\"/>",
  },
  {
    id: "gut-check",
    group: "judgement-voice",
    label: "Gut-check",
    blurb: "A quick orient before you commit.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><path class=\"a\" d=\"M16 8 18.5 16 16 24 13.5 16Z\"/><circle cx=\"16\" cy=\"16\" r=\"1.2\"/>",
  },
  {
    id: "worked-example",
    group: "judgement-voice",
    label: "Worked example",
    blurb: "The numbers run end to end.",
    body: "<path d=\"M6 26l1.2-4.6L20.5 8a2.2 2.2 0 0 1 3.1 0l.4.4a2.2 2.2 0 0 1 0 3.1L10.6 24.8 6 26Z\"/><path d=\"M18.5 10 22 13.5\"/><path class=\"a\" d=\"M6 29h9\"/>",
  },
  {
    id: "operator-voices",
    group: "interface-actions",
    label: "Operator voices",
    blurb: "Quotes from people who run it.",
    body: "<path d=\"M6 6h20a2.2 2.2 0 0 1 2.2 2.2v10a2.2 2.2 0 0 1-2.2 2.2H14l-5.5 4.6V20.6H6A2.2 2.2 0 0 1 3.8 18.4V8.2A2.2 2.2 0 0 1 6 6Z\"/><path class=\"a\" d=\"M11 12.5c-1.7.4-2.6 1.7-2.6 3.7h2.8v-3.7Zm6.5 0c-1.7.4-2.6 1.7-2.6 3.7h2.8v-3.7Z\"/>",
  },
  {
    id: "freshness",
    group: "interface-actions",
    label: "Freshness / last-checked",
    blurb: "When we last verified the data.",
    body: "<circle cx=\"16\" cy=\"16\" r=\"11\"/><path d=\"M16 9.5V16l4.5 2.8\"/><circle class=\"af\" cx=\"16\" cy=\"5.2\" r=\"1.4\"/>",
  },
  {
    id: "flag",
    group: "interface-actions",
    label: "Flag this",
    blurb: "Tell us something looks off.",
    body: "<path d=\"M9 4v25\"/><path class=\"a\" d=\"M9 6h14l-3.5 4.5L23 15H9Z\"/>",
  },
  {
    id: "bookmark",
    group: "interface-actions",
    label: "Save / bookmark",
    blurb: "Keep this cell for later.",
    body: "<path d=\"M9 5h14a1.5 1.5 0 0 1 1.5 1.5V28L16 22.5 7.5 28V6.5A1.5 1.5 0 0 1 9 5Z\"/>",
  },
  {
    id: "watch",
    group: "interface-actions",
    label: "Watch / alert",
    blurb: "Ping me when this changes.",
    body: "<path d=\"M9 23c1.6-1.4 2.4-3.2 2.4-6V15a4.6 4.6 0 0 1 9.2 0v2c0 2.8.8 4.6 2.4 6Z\"/><path d=\"M13.5 23v.6a2.5 2.5 0 0 0 5 0V23\"/><path d=\"M16 10.4V8\"/><circle class=\"af\" cx=\"23.5\" cy=\"9.5\" r=\"2.4\"/>",
  },
  {
    id: "calculator",
    group: "interface-actions",
    label: "Calculator",
    blurb: "Run your own scenario.",
    body: "<rect x=\"7\" y=\"4\" width=\"18\" height=\"24\" rx=\"3\"/><rect x=\"10.5\" y=\"8\" width=\"11\" height=\"4\" rx=\"1\"/><circle cx=\"11.5\" cy=\"17\" r=\"1\"/><circle cx=\"16\" cy=\"17\" r=\"1\"/><circle cx=\"20.5\" cy=\"17\" r=\"1\"/><circle cx=\"11.5\" cy=\"22\" r=\"1\"/><circle cx=\"16\" cy=\"22\" r=\"1\"/><circle class=\"af\" cx=\"20.5\" cy=\"22\" r=\"1.4\"/>",
  },
  {
    id: "methodology",
    group: "interface-actions",
    label: "Methodology",
    blurb: "How the figures were built.",
    body: "<path d=\"M13 5v8L7 24a2 2 0 0 0 1.8 3h14.4A2 2 0 0 0 25 24l-6-11V5\"/><path d=\"M11 5h10\"/><path class=\"a\" d=\"M9.5 19h13\"/><circle class=\"af\" cx=\"14\" cy=\"22.5\" r=\"1\"/>",
  },
  {
    id: "search",
    group: "interface-actions",
    label: "Search",
    blurb: "Find any place or trade.",
    body: "<circle cx=\"14\" cy=\"14\" r=\"8\"/><path d=\"M20 20 27 27\"/>",
  },
];

export const ATLAS_ICONS_BY_ID: Record<AtlasIconId, AtlasIconDef> = Object.fromEntries(
  ATLAS_ICONS.map((d) => [d.id, d]),
) as Record<AtlasIconId, AtlasIconDef>;
