/**
 * AUTO-GENERATED by scripts/regions/build_regions_table.ts
 * Do not hand-edit. Re-run when ingest lands new regions:
 *   npx tsx scripts/regions/build_regions_table.ts
 */
export type RegionEntry = {
  value: string;
  label: string;
  level: string | null;
};

export const REGIONS_BY_COUNTRY_AUTO: Record<string, RegionEntry[]> = {
  AD: [
    { value: "ad-city-andorra-la-vella", label: "Andorra la Vella", level: "city" }
  ],
  AE: [
    { value: "ae-city-dubai", label: "Dubai", level: "city" },
    { value: "ae-city-sharjah", label: "Sharjah", level: "city" },
    { value: "ae-city-abu-dhabi", label: "Abu Dhabi", level: "city" }
  ],
  AF: [
    { value: "af", label: "All of AF", level: "country" }
  ],
  AG: [
    { value: "ag", label: "All of AG", level: "country" }
  ],
  AL: [
    { value: "al-city-fier", label: "Fier", level: "city" },
    { value: "al-city-vlore", label: "Vlorë", level: "city" },
    { value: "al-city-durres", label: "Durrës", level: "city" },
    { value: "al-city-tirana", label: "Tirana", level: "city" },
    { value: "al-city-elbasan", label: "Elbasan", level: "city" },
    { value: "al-city-shkoder", label: "Shkodër", level: "city" }
  ],
  AM: [
    { value: "am-city-yerevan", label: "Yerevan", level: "city" }
  ],
  AO: [
    { value: "ao-city-luanda", label: "Luanda", level: "city" }
  ],
  AR: [
    { value: "ar-city-cordoba", label: "Córdoba", level: "city" },
    { value: "ar-city-mendoza", label: "Mendoza", level: "city" },
    { value: "ar-city-rosario", label: "Rosario", level: "city" },
    { value: "ar-city-buenos-aires", label: "Buenos Aires", level: "city" }
  ],
  AT: [
    { value: "at1", label: "Ostösterreich", level: "nuts1" },
    { value: "at2", label: "Südösterreich", level: "nuts1" },
    { value: "at3", label: "Westösterreich", level: "nuts1" },
    { value: "at11", label: "Burgenland", level: "nuts2" },
    { value: "at21", label: "Kärnten", level: "nuts2" },
    { value: "at12", label: "Niederösterreich", level: "nuts2" },
    { value: "at31", label: "Oberösterreich", level: "nuts2" },
    { value: "at32", label: "Salzburg", level: "nuts2" },
    { value: "at22", label: "Steiermark", level: "nuts2" },
    { value: "at33", label: "Tirol", level: "nuts2" },
    { value: "at34", label: "Vorarlberg", level: "nuts2" },
    { value: "at13", label: "Wien", level: "nuts2" },
    { value: "at-city-graz", label: "Graz", level: "city" },
    { value: "at-city-linz", label: "Linz", level: "city" },
    { value: "at-city-vienna", label: "Vienna", level: "city" },
    { value: "at-city-salzburg", label: "Salzburg", level: "city" },
    { value: "at-city-innsbruck", label: "Innsbruck", level: "city" }
  ],
  AU: [
    { value: "au-206071139", label: "Abbotsford", level: "sa2" },
    { value: "au-403041071", label: "Aberfoyle Park", level: "sa2" },
    { value: "au-116021562", label: "Acacia Gardens", level: "sa2" },
    { value: "au-801111140", label: "ACT - South West", level: "sa2" },
    { value: "au-604011075", label: "Acton - Upper Burnie", level: "sa2" },
    { value: "au-111031222", label: "Adamstown - Kotara", level: "sa2" },
    { value: "au-401011001", label: "Adelaide", level: "sa2" },
    { value: "au-404031104", label: "Adelaide Airport", level: "sa2" },
    { value: "au-401021003", label: "Adelaide Hills", level: "sa2" },
    { value: "au-308051530", label: "Agnes Water - Miriam Vale", level: "sa2" },
    { value: "au-801051050", label: "Ainslie", level: "sa2" },
    { value: "au-312031359", label: "Airlie - Whitsundays", level: "sa2" },
    { value: "au-210011226", label: "Airport West", level: "sa2" },
    { value: "au-318021467", label: "Aitkenvale", level: "sa2" },
    { value: "au-701021010", label: "Alawa", level: "sa2" },
    { value: "au-509011225", label: "Albany", level: "sa2" },
    { value: "au-314011382", label: "Albany Creek", level: "sa2" },
    { value: "au-509011226", label: "Albany Surrounds", level: "sa2" },
    { value: "au-206051128", label: "Albert Park", level: "sa2" },
    { value: "au-305031119", label: "Albion", level: "sa2" },
    { value: "au-107031136", label: "Albion Park - Macquarie Pass", level: "sa2" },
    { value: "au-107031137", label: "Albion Park Rail", level: "sa2" },
    { value: "au-109011172", label: "Albury - East", level: "sa2" },
    { value: "au-109011173", label: "Albury - North", level: "sa2" },
    { value: "au-109011174", label: "Albury - South", level: "sa2" },
    { value: "au-109011175", label: "Albury Surrounds", level: "sa2" },
    { value: "au-305031120", label: "Alderley", level: "sa2" },
    { value: "au-401021004", label: "Aldgate - Stirling", level: "sa2" },
    { value: "au-403041072", label: "Aldinga", level: "sa2" },
    { value: "au-505031098", label: "Alexander Heights - Koondoola", level: "sa2" },
    { value: "au-204011054", label: "Alexandra", level: "sa2" },
    { value: "au-301011001", label: "Alexandra Hills", level: "sa2" },
    { value: "au-201011001", label: "Alfredton", level: "sa2" },
    { value: "au-303051072", label: "Algester", level: "sa2" },
    { value: "au-505031255", label: "Alkimos - Eglinton", level: "sa2" },
    { value: "au-702031057", label: "Alligator", level: "sa2" },
    { value: "au-206021110", label: "Alphington - Fairfield", level: "sa2" },
    { value: "au-205051099", label: "Alps - West", level: "sa2" },
    { value: "au-213021341", label: "Altona", level: "sa2" },
    { value: "au-213021342", label: "Altona Meadows", level: "sa2" },
    { value: "au-213021343", label: "Altona North", level: "sa2" },
    { value: "au-801041034", label: "Amaroo", level: "sa2" },
    { value: "au-312021342", label: "Andergrove - Beaconsfield", level: "sa2" },
    { value: "au-106031119", label: "Anna Bay", level: "sa2" },
    { value: "au-120021674", label: "Annandale (NSW)", level: "sa2" },
    { value: "au-318021468", label: "Annandale (Qld)", level: "sa2" },
    { value: "au-303021052", label: "Annerley", level: "sa2" },
    { value: "au-701021011", label: "Anula", level: "sa2" },
    { value: "au-507041175", label: "Applecross - Ardross", level: "sa2" },
    { value: "au-801011001", label: "Aranda", level: "sa2" },
    { value: "au-215011386", label: "Ararat", level: "sa2" },
    { value: "au-215011387", label: "Ararat Surrounds", level: "sa2" },
    { value: "au-213011328", label: "Ardeer - Albion", level: "sa2" },
    { value: "au-206061135", label: "Armadale", level: "sa2" },
    { value: "au-506011110", label: "Armadale - Wungong - Brookdale", level: "sa2" },
    { value: "au-110011186", label: "Armidale", level: "sa2" },
    { value: "au-110011187", label: "Armidale Surrounds - North", level: "sa2" },
    { value: "au-110011188", label: "Armidale Surrounds - South", level: "sa2" },
    { value: "au-119041668", label: "Arncliffe - Bardwell Valley", level: "sa2" },
    { value: "au-316021417", label: "Aroona - Currimundi", level: "sa2" }
  ],
  AZ: [
    { value: "az-city-baku", label: "Baku", level: "city" },
    { value: "az-city-ganja", label: "Ganja", level: "city" },
    { value: "az-city-sumqayit", label: "Sumqayit", level: "city" }
  ],
  BA: [
    { value: "ba", label: "All of BA", level: "country" }
  ],
  BB: [
    { value: "bb-city-bridgetown", label: "Bridgetown", level: "city" }
  ],
  BD: [
    { value: "bd-city-dhaka", label: "Dhaka", level: "city" },
    { value: "bd-city-chittagong", label: "Chittagong", level: "city" }
  ],
  BE: [
    { value: "be1", label: "Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest", level: "nuts1" },
    { value: "be3", label: "Région wallonne", level: "nuts1" },
    { value: "be2", label: "Vlaams Gewest", level: "nuts1" },
    { value: "be21", label: "Prov. Antwerpen", level: "nuts2" },
    { value: "be31", label: "Prov. Brabant wallon", level: "nuts2" },
    { value: "be32", label: "Prov. Hainaut", level: "nuts2" },
    { value: "be33", label: "Prov. Liège", level: "nuts2" },
    { value: "be22", label: "Prov. Limburg (BE)", level: "nuts2" },
    { value: "be34", label: "Prov. Luxembourg (BE)", level: "nuts2" },
    { value: "be35", label: "Prov. Namur", level: "nuts2" },
    { value: "be23", label: "Prov. Oost-Vlaanderen", level: "nuts2" },
    { value: "be24", label: "Prov. Vlaams-Brabant", level: "nuts2" },
    { value: "be25", label: "Prov. West-Vlaanderen", level: "nuts2" },
    { value: "be10", label: "Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest", level: "nuts2" }
  ],
  BF: [
    { value: "bf-city-ouagadougou", label: "Ouagadougou", level: "city" }
  ],
  BG: [
    { value: "bg3", label: "Severna i Yugoiztochna Bulgaria", level: "nuts1" },
    { value: "bg4", label: "Yugozapadna i Yuzhna tsentralna Bulgaria", level: "nuts1" },
    { value: "bg32", label: "Severen tsentralen", level: "nuts2" },
    { value: "bg33", label: "Severoiztochen", level: "nuts2" },
    { value: "bg31", label: "Severozapaden", level: "nuts2" },
    { value: "bg34", label: "Yugoiztochen", level: "nuts2" },
    { value: "bg41", label: "Yugozapaden", level: "nuts2" },
    { value: "bg42", label: "Yuzhen tsentralen", level: "nuts2" }
  ],
  BH: [
    { value: "bh-city-manama", label: "Manama", level: "city" }
  ],
  BI: [
    { value: "bi", label: "All of BI", level: "country" }
  ],
  BJ: [
    { value: "bj-city-cotonou", label: "Cotonou", level: "city" }
  ],
  BN: [
    { value: "bn", label: "All of BN", level: "country" }
  ],
  BO: [
    { value: "bo-city-la-paz", label: "La Paz", level: "city" },
    { value: "bo-city-santa-cruz", label: "Santa Cruz", level: "city" }
  ],
  BR: [
    { value: "br-ac", label: "Acre", level: "state" },
    { value: "br-al", label: "Alagoas", level: "state" },
    { value: "br-ap", label: "Amapá", level: "state" },
    { value: "br-am", label: "Amazonas", level: "state" },
    { value: "br-ba", label: "Bahia", level: "state" },
    { value: "br-ce", label: "Ceará", level: "state" },
    { value: "br-df", label: "Distrito Federal", level: "state" },
    { value: "br-es", label: "Espírito Santo", level: "state" },
    { value: "br-go", label: "Goiás", level: "state" },
    { value: "br-ma", label: "Maranhão", level: "state" },
    { value: "br-mt", label: "Mato Grosso", level: "state" },
    { value: "br-ms", label: "Mato Grosso do Sul", level: "state" },
    { value: "br-mg", label: "Minas Gerais", level: "state" },
    { value: "br-pa", label: "Pará", level: "state" },
    { value: "br-pb", label: "Paraíba", level: "state" },
    { value: "br-pr", label: "Paraná", level: "state" },
    { value: "br-pe", label: "Pernambuco", level: "state" },
    { value: "br-pi", label: "Piauí", level: "state" },
    { value: "br-rj", label: "Rio de Janeiro", level: "state" },
    { value: "br-rn", label: "Rio Grande do Norte", level: "state" },
    { value: "br-rs", label: "Rio Grande do Sul", level: "state" },
    { value: "br-ro", label: "Rondônia", level: "state" },
    { value: "br-rr", label: "Roraima", level: "state" },
    { value: "br-sc", label: "Santa Catarina", level: "state" },
    { value: "br-sp", label: "São Paulo", level: "state" },
    { value: "br-se", label: "Sergipe", level: "state" },
    { value: "br-to", label: "Tocantins", level: "state" },
    { value: "br-city-belem", label: "Belém", level: "city" },
    { value: "br-city-manaus", label: "Manaus", level: "city" },
    { value: "br-city-recife", label: "Recife", level: "city" },
    { value: "br-city-goiania", label: "Goiânia", level: "city" },
    { value: "br-city-vitoria", label: "Vitória", level: "city" },
    { value: "br-city-brasilia", label: "Brasília", level: "city" },
    { value: "br-city-campinas", label: "Campinas", level: "city" },
    { value: "br-city-curitiba", label: "Curitiba", level: "city" },
    { value: "br-city-salvador", label: "Salvador", level: "city" },
    { value: "br-city-fortaleza", label: "Fortaleza", level: "city" },
    { value: "br-city-sao-paulo", label: "São Paulo", level: "city" },
    { value: "br-city-porto-alegre", label: "Porto Alegre", level: "city" },
    { value: "br-city-florianopolis", label: "Florianópolis", level: "city" },
    { value: "br-city-belo-horizonte", label: "Belo Horizonte", level: "city" },
    { value: "br-city-rio-de-janeiro", label: "Rio de Janeiro", level: "city" }
  ],
  BS: [
    { value: "bs-city-nassau", label: "Nassau", level: "city" }
  ],
  BT: [
    { value: "bt", label: "All of BT", level: "country" }
  ],
  BW: [
    { value: "bw", label: "All of BW", level: "country" }
  ],
  BY: [
    { value: "by-city-minsk", label: "Minsk", level: "city" }
  ],
  BZ: [
    { value: "bz", label: "All of BZ", level: "country" }
  ],
  CA: [
    { value: "ca-ab", label: "Alberta", level: "province" },
    { value: "ca-bc", label: "British Columbia", level: "province" },
    { value: "ca-mb", label: "Manitoba", level: "province" },
    { value: "ca-nb", label: "New Brunswick", level: "province" },
    { value: "ca-nl", label: "Newfoundland and Labrador", level: "province" },
    { value: "ca-nt", label: "Northwest Territories", level: "province" },
    { value: "ca-ns", label: "Nova Scotia", level: "province" },
    { value: "ca-nu", label: "Nunavut", level: "province" },
    { value: "ca-on", label: "Ontario", level: "province" },
    { value: "ca-pe", label: "Prince Edward Island", level: "province" },
    { value: "ca-qc", label: "Quebec", level: "province" },
    { value: "ca-sk", label: "Saskatchewan", level: "province" },
    { value: "ca-yt", label: "Yukon", level: "province" },
    { value: "ca-city-ottawa", label: "Ottawa", level: "city" },
    { value: "ca-city-calgary", label: "Calgary", level: "city" },
    { value: "ca-city-halifax", label: "Halifax", level: "city" },
    { value: "ca-city-toronto", label: "Toronto", level: "city" },
    { value: "ca-city-edmonton", label: "Edmonton", level: "city" },
    { value: "ca-city-hamilton", label: "Hamilton", level: "city" },
    { value: "ca-city-montreal", label: "Montreal", level: "city" },
    { value: "ca-city-winnipeg", label: "Winnipeg", level: "city" },
    { value: "ca-city-vancouver", label: "Vancouver", level: "city" },
    { value: "ca-city-quebec-city", label: "Quebec City", level: "city" }
  ],
  CD: [
    { value: "cd", label: "All of CD", level: "country" }
  ],
  CF: [
    { value: "cf", label: "All of CF", level: "country" }
  ],
  CG: [
    { value: "cg", label: "All of CG", level: "country" }
  ],
  CH: [
    { value: "ch-city-bern", label: "Bern", level: "city" },
    { value: "ch-city-basel", label: "Basel", level: "city" },
    { value: "ch-city-geneva", label: "Geneva", level: "city" },
    { value: "ch-city-lugano", label: "Lugano", level: "city" },
    { value: "ch-city-zurich", label: "Zurich", level: "city" },
    { value: "ch-city-lausanne", label: "Lausanne", level: "city" }
  ],
  CI: [
    { value: "ci-city-abidjan", label: "Abidjan", level: "city" },
    { value: "ci-city-yamoussoukro", label: "Yamoussoukro", level: "city" }
  ],
  CL: [
    { value: "cl-city-santiago", label: "Santiago", level: "city" },
    { value: "cl-city-concepcion", label: "Concepción", level: "city" },
    { value: "cl-city-valparaiso", label: "Valparaíso", level: "city" },
    { value: "cl-city-antofagasta", label: "Antofagasta", level: "city" }
  ],
  CM: [
    { value: "cm-city-douala", label: "Douala", level: "city" },
    { value: "cm-city-yaounde", label: "Yaoundé", level: "city" }
  ],
  CN: [
    { value: "cn-city-wuhan", label: "Wuhan", level: "city" },
    { value: "cn-city-xi-an", label: "Xi'an", level: "city" },
    { value: "cn-city-beijing", label: "Beijing", level: "city" },
    { value: "cn-city-chengdu", label: "Chengdu", level: "city" },
    { value: "cn-city-tianjin", label: "Tianjin", level: "city" },
    { value: "cn-city-hangzhou", label: "Hangzhou", level: "city" },
    { value: "cn-city-shanghai", label: "Shanghai", level: "city" },
    { value: "cn-city-shenzhen", label: "Shenzhen", level: "city" },
    { value: "cn-city-chongqing", label: "Chongqing", level: "city" },
    { value: "cn-city-guangzhou", label: "Guangzhou", level: "city" }
  ],
  CO: [
    { value: "co-city-cali", label: "Cali", level: "city" },
    { value: "co-city-bogota", label: "Bogotá", level: "city" },
    { value: "co-city-medellin", label: "Medellín", level: "city" },
    { value: "co-city-barranquilla", label: "Barranquilla", level: "city" }
  ],
  CR: [
    { value: "cr-city-san-jose", label: "San José", level: "city" }
  ],
  CU: [
    { value: "cu-city-havana", label: "Havana", level: "city" }
  ],
  CV: [
    { value: "cv", label: "All of CV", level: "country" }
  ],
  CY: [
    { value: "cy0", label: "Kýpros", level: "nuts1" },
    { value: "cy00", label: "Kýpros", level: "nuts2" }
  ],
  CZ: [
    { value: "cz0", label: "Česko", level: "nuts1" },
    { value: "czz", label: "Extra-Regio NUTS 1", level: "nuts1" },
    { value: "czzz", label: "Extra-Regio NUTS 2", level: "nuts2" },
    { value: "cz06", label: "Jihovýchod", level: "nuts2" },
    { value: "cz03", label: "Jihozápad", level: "nuts2" },
    { value: "cz08", label: "Moravskoslezsko", level: "nuts2" },
    { value: "cz01", label: "Praha", level: "nuts2" },
    { value: "cz05", label: "Severovýchod", level: "nuts2" },
    { value: "cz04", label: "Severozápad", level: "nuts2" },
    { value: "cz02", label: "Střední Čechy", level: "nuts2" },
    { value: "cz07", label: "Střední Morava", level: "nuts2" }
  ],
  DE: [
    { value: "de1", label: "Baden-Württemberg", level: "nuts1" },
    { value: "de2", label: "Bayern", level: "nuts1" },
    { value: "de3", label: "Berlin", level: "nuts1" },
    { value: "de4", label: "Brandenburg", level: "nuts1" },
    { value: "de5", label: "Bremen", level: "nuts1" },
    { value: "de6", label: "Hamburg", level: "nuts1" },
    { value: "de7", label: "Hessen", level: "nuts1" },
    { value: "de8", label: "Mecklenburg-Vorpommern", level: "nuts1" },
    { value: "de9", label: "Niedersachsen", level: "nuts1" },
    { value: "dea", label: "Nordrhein-Westfalen", level: "nuts1" },
    { value: "deb", label: "Rheinland-Pfalz", level: "nuts1" },
    { value: "dec", label: "Saarland", level: "nuts1" },
    { value: "ded", label: "Sachsen", level: "nuts1" },
    { value: "dee", label: "Sachsen-Anhalt", level: "nuts1" },
    { value: "def", label: "Schleswig-Holstein", level: "nuts1" },
    { value: "deg", label: "Thüringen", level: "nuts1" },
    { value: "dea5", label: "Arnsberg", level: "nuts2" },
    { value: "de30", label: "Berlin", level: "nuts2" },
    { value: "de40", label: "Brandenburg", level: "nuts2" },
    { value: "de91", label: "Braunschweig", level: "nuts2" },
    { value: "de50", label: "Bremen", level: "nuts2" },
    { value: "ded4", label: "Chemnitz", level: "nuts2" },
    { value: "de71", label: "Darmstadt", level: "nuts2" },
    { value: "dea4", label: "Detmold", level: "nuts2" },
    { value: "ded2", label: "Dresden", level: "nuts2" },
    { value: "dea1", label: "Düsseldorf", level: "nuts2" },
    { value: "de13", label: "Freiburg", level: "nuts2" },
    { value: "de72", label: "Gießen", level: "nuts2" },
    { value: "de60", label: "Hamburg", level: "nuts2" },
    { value: "de92", label: "Hannover", level: "nuts2" },
    { value: "de12", label: "Karlsruhe", level: "nuts2" },
    { value: "de73", label: "Kassel", level: "nuts2" },
    { value: "deb1", label: "Koblenz", level: "nuts2" },
    { value: "dea2", label: "Köln", level: "nuts2" },
    { value: "ded5", label: "Leipzig", level: "nuts2" },
    { value: "de93", label: "Lüneburg", level: "nuts2" },
    { value: "de80", label: "Mecklenburg-Vorpommern", level: "nuts2" },
    { value: "de25", label: "Mittelfranken", level: "nuts2" },
    { value: "dea3", label: "Münster", level: "nuts2" },
    { value: "de22", label: "Niederbayern", level: "nuts2" },
    { value: "de21", label: "Oberbayern", level: "nuts2" },
    { value: "de24", label: "Oberfranken", level: "nuts2" },
    { value: "de23", label: "Oberpfalz", level: "nuts2" },
    { value: "deb3", label: "Rheinhessen-Pfalz", level: "nuts2" },
    { value: "dec0", label: "Saarland", level: "nuts2" },
    { value: "dee0", label: "Sachsen-Anhalt", level: "nuts2" },
    { value: "def0", label: "Schleswig-Holstein", level: "nuts2" },
    { value: "de27", label: "Schwaben", level: "nuts2" },
    { value: "de11", label: "Stuttgart", level: "nuts2" },
    { value: "deg0", label: "Thüringen", level: "nuts2" },
    { value: "deb2", label: "Trier", level: "nuts2" },
    { value: "de14", label: "Tübingen", level: "nuts2" },
    { value: "de26", label: "Unterfranken", level: "nuts2" },
    { value: "de94", label: "Weser-Ems", level: "nuts2" }
  ],
  DJ: [
    { value: "dj", label: "All of DJ", level: "country" }
  ],
  DK: [
    { value: "dk0", label: "Danmark", level: "nuts1" },
    { value: "dk01", label: "Hovedstaden", level: "nuts2" },
    { value: "dk04", label: "Midtjylland", level: "nuts2" },
    { value: "dk05", label: "Nordjylland", level: "nuts2" },
    { value: "dk02", label: "Sjælland", level: "nuts2" },
    { value: "dk03", label: "Syddanmark", level: "nuts2" }
  ],
  DM: [
    { value: "dm", label: "All of DM", level: "country" }
  ],
  DO: [
    { value: "do-city-santiago", label: "Santiago", level: "city" },
    { value: "do-city-santo-domingo", label: "Santo Domingo", level: "city" }
  ],
  DZ: [
    { value: "dz-city-oran", label: "Oran", level: "city" },
    { value: "dz-city-algiers", label: "Algiers", level: "city" }
  ],
  EC: [
    { value: "ec-city-quito", label: "Quito", level: "city" },
    { value: "ec-city-guayaquil", label: "Guayaquil", level: "city" }
  ],
  EE: [
    { value: "ee0", label: "Eesti", level: "nuts1" },
    { value: "ee00", label: "Eesti", level: "nuts2" }
  ],
  EG: [
    { value: "eg-city-giza", label: "Giza", level: "city" },
    { value: "eg-city-cairo", label: "Cairo", level: "city" },
    { value: "eg-city-alexandria", label: "Alexandria", level: "city" }
  ],
  EL: [
    { value: "el3", label: "Attiki", level: "nuts1" },
    { value: "el30", label: "Attiki", level: "nuts2" },
    { value: "el4", label: "Nisia Aigaiou, Kriti", level: "nuts1" },
    { value: "el41", label: "Voreio Aigaio", level: "nuts2" },
    { value: "el42", label: "Notio Aigaio", level: "nuts2" },
    { value: "el43", label: "Kriti", level: "nuts2" },
    { value: "el5", label: "Voreia Elláda", level: "nuts1" },
    { value: "el51", label: "Anatoliki Makedonia, Thraki", level: "nuts2" },
    { value: "el52", label: "Kentriki Makedonia", level: "nuts2" },
    { value: "el53", label: "Dytiki Makedonia", level: "nuts2" },
    { value: "el54", label: "Ipeiros", level: "nuts2" },
    { value: "el6", label: "Kentriki Elláda", level: "nuts1" },
    { value: "el61", label: "Thessalia", level: "nuts2" },
    { value: "el62", label: "Ionia Nisia", level: "nuts2" },
    { value: "el63", label: "Dytiki Elláda", level: "nuts2" },
    { value: "el64", label: "Sterea Elláda", level: "nuts2" },
    { value: "el65", label: "Peloponnisos", level: "nuts2" },
    { value: "elz", label: "Extra-Regio NUTS 1", level: "nuts1" },
    { value: "elzz", label: "Extra-Regio NUTS 2", level: "nuts2" }
  ],
  ER: [
    { value: "er", label: "All of ER", level: "country" }
  ],
  ES: [
    { value: "es7", label: "Canarias", level: "nuts1" },
    { value: "es4", label: "Centro (ES)", level: "nuts1" },
    { value: "es3", label: "Comunidad de Madrid", level: "nuts1" },
    { value: "es5", label: "Este", level: "nuts1" },
    { value: "es2", label: "Noreste", level: "nuts1" },
    { value: "es1", label: "Noroeste", level: "nuts1" },
    { value: "es6", label: "Sur", level: "nuts1" },
    { value: "es61", label: "Andalucía", level: "nuts2" },
    { value: "es24", label: "Aragón", level: "nuts2" },
    { value: "es70", label: "Canarias", level: "nuts2" },
    { value: "es13", label: "Cantabria", level: "nuts2" },
    { value: "es41", label: "Castilla y León", level: "nuts2" },
    { value: "es42", label: "Castilla-La Mancha", level: "nuts2" },
    { value: "es51", label: "Cataluña", level: "nuts2" },
    { value: "es63", label: "Ciudad de Ceuta", level: "nuts2" },
    { value: "es64", label: "Ciudad de Melilla", level: "nuts2" },
    { value: "es30", label: "Comunidad de Madrid", level: "nuts2" },
    { value: "es22", label: "Comunidad Foral de Navarra", level: "nuts2" },
    { value: "es52", label: "Comunitat Valenciana", level: "nuts2" },
    { value: "es43", label: "Extremadura", level: "nuts2" },
    { value: "es11", label: "Galicia", level: "nuts2" },
    { value: "es53", label: "Illes Balears", level: "nuts2" },
    { value: "es23", label: "La Rioja", level: "nuts2" },
    { value: "es21", label: "País Vasco", level: "nuts2" },
    { value: "es12", label: "Principado de Asturias", level: "nuts2" },
    { value: "es62", label: "Región de Murcia", level: "nuts2" },
    { value: "es-15", label: "A Coruña", level: "province" },
    { value: "es-01", label: "Álava", level: "province" },
    { value: "es-02", label: "Albacete", level: "province" },
    { value: "es-03", label: "Alicante", level: "province" },
    { value: "es-04", label: "Almería", level: "province" },
    { value: "es-33", label: "Asturias", level: "province" },
    { value: "es-05", label: "Ávila", level: "province" },
    { value: "es-06", label: "Badajoz", level: "province" },
    { value: "es-07", label: "Baleares", level: "province" },
    { value: "es-08", label: "Barcelona", level: "province" },
    { value: "es-48", label: "Bizkaia", level: "province" },
    { value: "es-09", label: "Burgos", level: "province" },
    { value: "es-10", label: "Cáceres", level: "province" },
    { value: "es-11", label: "Cádiz", level: "province" },
    { value: "es-39", label: "Cantabria", level: "province" },
    { value: "es-12", label: "Castellón", level: "province" },
    { value: "es-51", label: "Ceuta", level: "province" },
    { value: "es-13", label: "Ciudad Real", level: "province" },
    { value: "es-14", label: "Córdoba", level: "province" },
    { value: "es-16", label: "Cuenca", level: "province" },
    { value: "es-17", label: "Girona", level: "province" },
    { value: "es-18", label: "Granada", level: "province" },
    { value: "es-19", label: "Guadalajara", level: "province" },
    { value: "es-20", label: "Guipúzcoa", level: "province" },
    { value: "es-21", label: "Huelva", level: "province" },
    { value: "es-22", label: "Huesca", level: "province" },
    { value: "es-23", label: "Jaén", level: "province" },
    { value: "es-26", label: "La Rioja", level: "province" },
    { value: "es-35", label: "Las Palmas", level: "province" },
    { value: "es-24", label: "León", level: "province" },
    { value: "es-25", label: "Lleida", level: "province" },
    { value: "es-27", label: "Lugo", level: "province" },
    { value: "es-28", label: "Madrid", level: "province" },
    { value: "es-29", label: "Málaga", level: "province" }
  ],
  ET: [
    { value: "et-city-addis-ababa", label: "Addis Ababa", level: "city" }
  ],
  FI: [
    { value: "fi2", label: "Åland", level: "nuts1" },
    { value: "fi1", label: "Manner-Suomi", level: "nuts1" },
    { value: "fi20", label: "Åland", level: "nuts2" },
    { value: "fi1c", label: "Etelä-Suomi", level: "nuts2" },
    { value: "fi1b", label: "Helsinki-Uusimaa", level: "nuts2" },
    { value: "fi19", label: "Länsi-Suomi", level: "nuts2" },
    { value: "fi1d", label: "Pohjois- ja Itä-Suomi", level: "nuts2" }
  ],
  FJ: [
    { value: "fj-city-suva", label: "Suva", level: "city" }
  ],
  FM: [
    { value: "fm", label: "All of FM", level: "country" }
  ],
  FR: [
    { value: "frk", label: "Auvergne-Rhône-Alpes", level: "nuts1" },
    { value: "frc", label: "Bourgogne-Franche-Comté", level: "nuts1" },
    { value: "frh", label: "Bretagne", level: "nuts1" },
    { value: "frb", label: "Centre - Val de Loire", level: "nuts1" },
    { value: "frm", label: "Corse", level: "nuts1" },
    { value: "frz", label: "Extra-Regio NUTS 1", level: "nuts1" },
    { value: "frf", label: "Grand Est", level: "nuts1" },
    { value: "fre", label: "Hauts-de-France", level: "nuts1" },
    { value: "fr1", label: "Ile de France", level: "nuts1" },
    { value: "frd", label: "Normandie", level: "nuts1" },
    { value: "fri", label: "Nouvelle-Aquitaine", level: "nuts1" },
    { value: "frj", label: "Occitanie", level: "nuts1" },
    { value: "frg", label: "Pays de la Loire", level: "nuts1" },
    { value: "frl", label: "Provence-Alpes-Côte d’Azur", level: "nuts1" },
    { value: "fry", label: "RUP FR - Régions Ultrapériphériques Françaises", level: "nuts1" },
    { value: "frf1", label: "Alsace", level: "nuts2" },
    { value: "fri1", label: "Aquitaine", level: "nuts2" },
    { value: "frk1", label: "Auvergne", level: "nuts2" },
    { value: "frd1", label: "Basse-Normandie", level: "nuts2" },
    { value: "frc1", label: "Bourgogne", level: "nuts2" },
    { value: "frh0", label: "Bretagne", level: "nuts2" },
    { value: "frb0", label: "Centre - Val de Loire", level: "nuts2" },
    { value: "frf2", label: "Champagne-Ardenne", level: "nuts2" },
    { value: "frm0", label: "Corse", level: "nuts2" },
    { value: "frzz", label: "Extra-Regio NUTS 2", level: "nuts2" },
    { value: "frc2", label: "Franche-Comté", level: "nuts2" },
    { value: "fry1", label: "Guadeloupe", level: "nuts2" },
    { value: "fry3", label: "Guyane", level: "nuts2" },
    { value: "frd2", label: "Haute-Normandie", level: "nuts2" },
    { value: "fr10", label: "Ile de France", level: "nuts2" },
    { value: "fry4", label: "La Réunion", level: "nuts2" },
    { value: "frj1", label: "Languedoc-Roussillon", level: "nuts2" },
    { value: "fri2", label: "Limousin", level: "nuts2" },
    { value: "frf3", label: "Lorraine", level: "nuts2" },
    { value: "fry2", label: "Martinique", level: "nuts2" },
    { value: "fry5", label: "Mayotte", level: "nuts2" },
    { value: "frj2", label: "Midi-Pyrénées", level: "nuts2" },
    { value: "fre1", label: "Nord-Pas de Calais", level: "nuts2" },
    { value: "frg0", label: "Pays de la Loire", level: "nuts2" },
    { value: "fre2", label: "Picardie", level: "nuts2" },
    { value: "fri3", label: "Poitou-Charentes", level: "nuts2" },
    { value: "frl0", label: "Provence-Alpes-Côte d’Azur", level: "nuts2" },
    { value: "frk2", label: "Rhône-Alpes", level: "nuts2" }
  ],
  GA: [
    { value: "ga", label: "All of GA", level: "country" }
  ],
  GB: [
    { value: "gb-e07000223", label: "Adur", level: "lad" },
    { value: "gb-e07000026", label: "Allerdale", level: "lad" },
    { value: "gb-e07000032", label: "Amber Valley", level: "lad" },
    { value: "gb-e07000224", label: "Arun", level: "lad" },
    { value: "gb-e07000170", label: "Ashfield", level: "lad" },
    { value: "gb-e07000105", label: "Ashford", level: "lad" },
    { value: "gb-e07000004", label: "Aylesbury Vale", level: "lad" },
    { value: "gb-e07000200", label: "Babergh", level: "lad" },
    { value: "gb-e09000002", label: "Barking and Dagenham", level: "lad" },
    { value: "gb-e09000003", label: "Barnet", level: "lad" },
    { value: "gb-e08000016", label: "Barnsley", level: "lad" },
    { value: "gb-e07000027", label: "Barrow-in-Furness", level: "lad" },
    { value: "gb-e07000066", label: "Basildon", level: "lad" },
    { value: "gb-e07000084", label: "Basingstoke and Deane", level: "lad" },
    { value: "gb-e07000171", label: "Bassetlaw", level: "lad" },
    { value: "gb-e06000055", label: "Bedford", level: "lad" },
    { value: "gb-e09000004", label: "Bexley", level: "lad" },
    { value: "gb-e08000025", label: "Birmingham", level: "lad" },
    { value: "gb-e07000129", label: "Blaby", level: "lad" },
    { value: "gb-e06000008", label: "Blackburn with Darwen", level: "lad" },
    { value: "gb-e06000009", label: "Blackpool", level: "lad" },
    { value: "gb-e07000033", label: "Bolsover", level: "lad" },
    { value: "gb-e08000001", label: "Bolton", level: "lad" },
    { value: "gb-e07000136", label: "Boston", level: "lad" },
    { value: "gb-e06000036", label: "Bracknell Forest", level: "lad" },
    { value: "gb-e08000032", label: "Bradford", level: "lad" },
    { value: "gb-e07000067", label: "Braintree", level: "lad" },
    { value: "gb-e07000143", label: "Breckland", level: "lad" },
    { value: "gb-e09000005", label: "Brent", level: "lad" },
    { value: "gb-e07000068", label: "Brentwood", level: "lad" },
    { value: "gb-e06000043", label: "Brighton and Hove", level: "lad" },
    { value: "gb-e07000144", label: "Broadland", level: "lad" },
    { value: "gb-e09000006", label: "Bromley", level: "lad" },
    { value: "gb-e07000234", label: "Bromsgrove", level: "lad" },
    { value: "gb-e07000095", label: "Broxbourne", level: "lad" },
    { value: "gb-e07000172", label: "Broxtowe", level: "lad" },
    { value: "gb-e07000117", label: "Burnley", level: "lad" },
    { value: "gb-e08000002", label: "Bury", level: "lad" },
    { value: "gb-e08000033", label: "Calderdale", level: "lad" },
    { value: "gb-e07000008", label: "Cambridge", level: "lad" },
    { value: "gb-e09000007", label: "Camden", level: "lad" },
    { value: "gb-e07000192", label: "Cannock Chase", level: "lad" },
    { value: "gb-e07000106", label: "Canterbury", level: "lad" },
    { value: "gb-e07000028", label: "Carlisle", level: "lad" },
    { value: "gb-e07000069", label: "Castle Point", level: "lad" },
    { value: "gb-e06000056", label: "Central Bedfordshire", level: "lad" },
    { value: "gb-e07000130", label: "Charnwood", level: "lad" },
    { value: "gb-e07000070", label: "Chelmsford", level: "lad" },
    { value: "gb-e07000177", label: "Cherwell", level: "lad" },
    { value: "gb-e06000049", label: "Cheshire East", level: "lad" },
    { value: "gb-e06000050", label: "Cheshire West and Chester", level: "lad" },
    { value: "gb-e07000034", label: "Chesterfield", level: "lad" },
    { value: "gb-e07000225", label: "Chichester", level: "lad" },
    { value: "gb-e07000005", label: "Chiltern", level: "lad" },
    { value: "gb-e07000118", label: "Chorley", level: "lad" },
    { value: "gb-e09000001", label: "City of London", level: "lad" },
    { value: "gb-e07000071", label: "Colchester", level: "lad" },
    { value: "gb-e07000029", label: "Copeland", level: "lad" },
    { value: "gb-e07000150", label: "Corby", level: "lad" },
    { value: "gb-e06000047", label: "County Durham", level: "lad" }
  ],
  GD: [
    { value: "gd", label: "All of GD", level: "country" }
  ],
  GE: [
    { value: "ge-city-batumi", label: "Batumi", level: "city" },
    { value: "ge-city-kutaisi", label: "Kutaisi", level: "city" },
    { value: "ge-city-rustavi", label: "Rustavi", level: "city" },
    { value: "ge-city-tbilisi", label: "Tbilisi", level: "city" }
  ],
  GH: [
    { value: "gh-city-accra", label: "Accra", level: "city" },
    { value: "gh-city-kumasi", label: "Kumasi", level: "city" }
  ],
  GN: [
    { value: "gn", label: "All of GN", level: "country" }
  ],
  GQ: [
    { value: "gq", label: "All of GQ", level: "country" }
  ],
  GR: [
    { value: "gr", label: "All of GR", level: "country" }
  ],
  GT: [
    { value: "gt-city-guatemala-city", label: "Guatemala City", level: "city" }
  ],
  GW: [
    { value: "gw", label: "All of GW", level: "country" }
  ],
  GY: [
    { value: "gy", label: "All of GY", level: "country" }
  ],
  HK: [
    { value: "hk-city-hong-kong", label: "Hong Kong", level: "city" }
  ],
  HN: [
    { value: "hn-city-tegucigalpa", label: "Tegucigalpa", level: "city" },
    { value: "hn-city-san-pedro-sula", label: "San Pedro Sula", level: "city" }
  ],
  HR: [
    { value: "hr0", label: "Hrvatska", level: "nuts1" },
    { value: "hr05", label: "Grad Zagreb", level: "nuts2" },
    { value: "hr03", label: "Jadranska Hrvatska", level: "nuts2" },
    { value: "hr04", label: "Kontinentalna Hrvatska (NUTS 2016)", level: "nuts2" },
    { value: "hr02", label: "Panonska Hrvatska", level: "nuts2" },
    { value: "hr06", label: "Sjeverna Hrvatska", level: "nuts2" }
  ],
  HT: [
    { value: "ht", label: "All of HT", level: "country" }
  ],
  HU: [
    { value: "hu3", label: "Alföld és Észak", level: "nuts1" },
    { value: "hu2", label: "Dunántúl", level: "nuts1" },
    { value: "hu1", label: "Közép-Magyarország", level: "nuts1" },
    { value: "hu11", label: "Budapest", level: "nuts2" },
    { value: "hu33", label: "Dél-Alföld", level: "nuts2" },
    { value: "hu23", label: "Dél-Dunántúl", level: "nuts2" },
    { value: "hu32", label: "Észak-Alföld", level: "nuts2" },
    { value: "hu31", label: "Észak-Magyarország", level: "nuts2" },
    { value: "hu21", label: "Közép-Dunántúl", level: "nuts2" },
    { value: "hu22", label: "Nyugat-Dunántúl", level: "nuts2" },
    { value: "hu12", label: "Pest", level: "nuts2" }
  ],
  ID: [
    { value: "id-city-medan", label: "Medan", level: "city" },
    { value: "id-city-bandung", label: "Bandung", level: "city" },
    { value: "id-city-jakarta", label: "Jakarta", level: "city" },
    { value: "id-city-makassar", label: "Makassar", level: "city" },
    { value: "id-city-semarang", label: "Semarang", level: "city" },
    { value: "id-city-surabaya", label: "Surabaya", level: "city" }
  ],
  IE: [
    { value: "ie0", label: "Ireland", level: "nuts1" },
    { value: "ie06", label: "Eastern and Midland", level: "nuts2" },
    { value: "ie04", label: "Northern and Western", level: "nuts2" },
    { value: "ie05", label: "Southern", level: "nuts2" }
  ],
  IL: [
    { value: "il-city-haifa", label: "Haifa", level: "city" },
    { value: "il-city-ashdod", label: "Ashdod", level: "city" },
    { value: "il-city-netanya", label: "Netanya", level: "city" },
    { value: "il-city-tel-aviv", label: "Tel Aviv", level: "city" },
    { value: "il-city-beersheba", label: "Beersheba", level: "city" },
    { value: "il-city-jerusalem", label: "Jerusalem", level: "city" },
    { value: "il-city-be-er-sheva", label: "Be'er Sheva", level: "city" },
    { value: "il-city-tel-aviv-yafo", label: "Tel Aviv-Yafo", level: "city" }
  ],
  IN: [
    { value: "in-city-pune", label: "Pune", level: "city" },
    { value: "in-city-delhi", label: "Delhi", level: "city" },
    { value: "in-city-mumbai", label: "Mumbai", level: "city" },
    { value: "in-city-chennai", label: "Chennai", level: "city" },
    { value: "in-city-kolkata", label: "Kolkata", level: "city" },
    { value: "in-city-ahmedabad", label: "Ahmedabad", level: "city" },
    { value: "in-city-bangalore", label: "Bangalore", level: "city" },
    { value: "in-city-hyderabad", label: "Hyderabad", level: "city" }
  ],
  IQ: [
    { value: "iq", label: "All of IQ", level: "country" }
  ],
  IR: [
    { value: "ir-city-shiraz", label: "Shiraz", level: "city" },
    { value: "ir-city-tehran", label: "Tehran", level: "city" },
    { value: "ir-city-isfahan", label: "Isfahan", level: "city" },
    { value: "ir-city-mashhad", label: "Mashhad", level: "city" }
  ],
  IS: [
    { value: "is0", label: "Ísland", level: "nuts1" },
    { value: "is00", label: "Ísland", level: "nuts2" }
  ],
  IT: [
    { value: "iti", label: "Centro (IT)", level: "nuts1" },
    { value: "itg", label: "Isole", level: "nuts1" },
    { value: "ith", label: "Nord-Est", level: "nuts1" },
    { value: "itc", label: "Nord-Ovest", level: "nuts1" },
    { value: "itf", label: "Sud", level: "nuts1" },
    { value: "itf1", label: "Abruzzo", level: "nuts2" },
    { value: "itf5", label: "Basilicata", level: "nuts2" },
    { value: "itf6", label: "Calabria", level: "nuts2" },
    { value: "itf3", label: "Campania", level: "nuts2" },
    { value: "ith5", label: "Emilia-Romagna", level: "nuts2" },
    { value: "ith4", label: "Friuli-Venezia Giulia", level: "nuts2" },
    { value: "iti4", label: "Lazio", level: "nuts2" },
    { value: "itc3", label: "Liguria", level: "nuts2" },
    { value: "itc4", label: "Lombardia", level: "nuts2" },
    { value: "iti3", label: "Marche", level: "nuts2" },
    { value: "itf2", label: "Molise", level: "nuts2" },
    { value: "itc1", label: "Piemonte", level: "nuts2" },
    { value: "ith1", label: "Provincia Autonoma di Bolzano/Bozen", level: "nuts2" },
    { value: "ith2", label: "Provincia Autonoma di Trento", level: "nuts2" },
    { value: "itf4", label: "Puglia", level: "nuts2" },
    { value: "itg2", label: "Sardegna", level: "nuts2" },
    { value: "itg1", label: "Sicilia", level: "nuts2" },
    { value: "iti1", label: "Toscana", level: "nuts2" },
    { value: "iti2", label: "Umbria", level: "nuts2" },
    { value: "itc2", label: "Valle d’Aosta/Vallée d’Aoste", level: "nuts2" },
    { value: "ith3", label: "Veneto", level: "nuts2" }
  ],
  JM: [
    { value: "jm-city-kingston", label: "Kingston", level: "city" }
  ],
  JO: [
    { value: "jo-city-amman", label: "Amman", level: "city" }
  ],
  JP: [
    { value: "jp-23000", label: "Aichi-ken", level: "prefecture" },
    { value: "jp-28203", label: "Akashi-shi", level: "municipality" },
    { value: "jp-05000", label: "Akita-ken", level: "prefecture" },
    { value: "jp-05201", label: "Akita-shi", level: "municipality" },
    { value: "jp-28202", label: "Amagasaki-shi", level: "municipality" },
    { value: "jp-02000", label: "Aomori-ken", level: "prefecture" },
    { value: "jp-02201", label: "Aomori-shi", level: "municipality" },
    { value: "jp-01204", label: "Asahikawa-shi", level: "municipality" },
    { value: "jp-12000", label: "Chiba-ken", level: "prefecture" },
    { value: "jp-12100", label: "Chiba-shi", level: "municipality" },
    { value: "jp-38000", label: "Ehime-ken", level: "prefecture" },
    { value: "jp-14205", label: "Fujisawa-shi", level: "municipality" },
    { value: "jp-18000", label: "Fukui-ken", level: "prefecture" },
    { value: "jp-18201", label: "Fukui-shi", level: "municipality" },
    { value: "jp-40000", label: "Fukuoka-ken", level: "prefecture" },
    { value: "jp-40130", label: "Fukuoka-shi", level: "municipality" },
    { value: "jp-07000", label: "Fukushima-ken", level: "prefecture" },
    { value: "jp-07201", label: "Fukushima-shi", level: "municipality" },
    { value: "jp-34207", label: "Fukuyama-shi", level: "municipality" },
    { value: "jp-12204", label: "Funabashi-shi", level: "municipality" },
    { value: "jp-21000", label: "Gifu-ken", level: "prefecture" },
    { value: "jp-21201", label: "Gifu-shi", level: "municipality" },
    { value: "jp-10000", label: "Gumma-ken", level: "prefecture" },
    { value: "jp-13201", label: "Hachioji-shi", level: "municipality" },
    { value: "jp-22130", label: "Hamamatsu-shi", level: "municipality" },
    { value: "jp-27227", label: "Higashiosaka-shi", level: "municipality" },
    { value: "jp-28201", label: "Himeji-shi", level: "municipality" },
    { value: "jp-27210", label: "Hirakata-shi", level: "municipality" },
    { value: "jp-34000", label: "Hiroshima-ken", level: "prefecture" },
    { value: "jp-34100", label: "Hiroshima-shi", level: "municipality" },
    { value: "jp-01000", label: "Hokkaido", level: "prefecture" },
    { value: "jp-28000", label: "Hyogo-ken", level: "prefecture" },
    { value: "jp-08000", label: "Ibaraki-ken", level: "prefecture" },
    { value: "jp-12203", label: "Ichikawa-shi", level: "municipality" },
    { value: "jp-23203", label: "Ichinomiya-shi", level: "municipality" },
    { value: "jp-17000", label: "Ishikawa-ken", level: "prefecture" },
    { value: "jp-07204", label: "Iwaki-shi", level: "municipality" },
    { value: "jp-03000", label: "Iwate-ken", level: "prefecture" },
    { value: "jp-37000", label: "Kagawa-ken", level: "prefecture" },
    { value: "jp-46000", label: "Kagoshima-ken", level: "prefecture" },
    { value: "jp-46201", label: "Kagoshima-shi", level: "municipality" },
    { value: "jp-14000", label: "Kanagawa-ken", level: "prefecture" },
    { value: "jp-17201", label: "Kanazawa-shi", level: "municipality" },
    { value: "jp-12217", label: "Kashiwa-shi", level: "municipality" },
    { value: "jp-23206", label: "Kasugai-shi", level: "municipality" },
    { value: "jp-11201", label: "Kawagoe-shi", level: "municipality" },
    { value: "jp-11203", label: "Kawaguchi-shi", level: "municipality" },
    { value: "jp-14130", label: "Kawasaki-shi", level: "municipality" },
    { value: "jp-40100", label: "Kitakyushu-shi", level: "municipality" },
    { value: "jp-28100", label: "Kobe-shi", level: "municipality" },
    { value: "jp-39000", label: "Kochi-ken", level: "prefecture" },
    { value: "jp-39201", label: "Kochi-shi", level: "municipality" },
    { value: "jp-19201", label: "Kofu-shi", level: "municipality" },
    { value: "jp-07203", label: "Koriyama-shi", level: "municipality" },
    { value: "jp-11222", label: "Koshigaya-shi", level: "municipality" },
    { value: "jp-13100", label: "Ku-area", level: "municipality" },
    { value: "jp-43000", label: "Kumamoto-ken", level: "prefecture" },
    { value: "jp-43100", label: "Kumamoto-shi", level: "municipality" },
    { value: "jp-33202", label: "Kurashiki-shi", level: "municipality" },
    { value: "jp-40203", label: "Kurume-shi", level: "municipality" }
  ],
  KE: [
    { value: "ke-city-kisumu", label: "Kisumu", level: "city" },
    { value: "ke-city-mombasa", label: "Mombasa", level: "city" },
    { value: "ke-city-nairobi", label: "Nairobi", level: "city" }
  ],
  KG: [
    { value: "kg-city-bishkek", label: "Bishkek", level: "city" }
  ],
  KH: [
    { value: "kh", label: "All of KH", level: "country" }
  ],
  KI: [
    { value: "ki", label: "All of KI", level: "country" }
  ],
  KM: [
    { value: "km", label: "All of KM", level: "country" }
  ],
  KN: [
    { value: "kn", label: "All of KN", level: "country" }
  ],
  KP: [
    { value: "kp", label: "All of KP", level: "country" }
  ],
  KR: [
    { value: "kr-city-busan", label: "Busan", level: "city" },
    { value: "kr-city-daegu", label: "Daegu", level: "city" },
    { value: "kr-city-seoul", label: "Seoul", level: "city" },
    { value: "kr-city-daejeon", label: "Daejeon", level: "city" },
    { value: "kr-city-gwangju", label: "Gwangju", level: "city" },
    { value: "kr-city-incheon", label: "Incheon", level: "city" }
  ],
  KW: [
    { value: "kw-city-kuwait-city", label: "Kuwait City", level: "city" }
  ],
  KZ: [
    { value: "kz-city-aktobe", label: "Aktobe", level: "city" },
    { value: "kz-city-almaty", label: "Almaty", level: "city" },
    { value: "kz-city-astana", label: "Astana", level: "city" },
    { value: "kz-city-shymkent", label: "Shymkent", level: "city" },
    { value: "kz-city-karaganda", label: "Karaganda", level: "city" }
  ],
  LA: [
    { value: "la", label: "All of LA", level: "country" }
  ],
  LB: [
    { value: "lb-city-beirut", label: "Beirut", level: "city" }
  ],
  LC: [
    { value: "lc", label: "All of LC", level: "country" }
  ],
  LI: [
    { value: "li-city-vaduz", label: "Vaduz", level: "city" },
    { value: "li-city-schaan", label: "Schaan", level: "city" }
  ],
  LK: [
    { value: "lk-city-colombo", label: "Colombo", level: "city" }
  ],
  LR: [
    { value: "lr", label: "All of LR", level: "country" }
  ],
  LS: [
    { value: "ls", label: "All of LS", level: "country" }
  ],
  LT: [
    { value: "lt0", label: "Lietuva", level: "nuts1" },
    { value: "lt01", label: "Sostinės regionas", level: "nuts2" },
    { value: "lt02", label: "Vidurio ir vakarų Lietuvos regionas", level: "nuts2" }
  ],
  LU: [
    { value: "lu0", label: "Luxembourg", level: "nuts1" },
    { value: "lu00", label: "Luxembourg", level: "nuts2" }
  ],
  LV: [
    { value: "lv0", label: "Latvija", level: "nuts1" },
    { value: "lv00", label: "Latvija", level: "nuts2" }
  ],
  LY: [
    { value: "ly", label: "All of LY", level: "country" }
  ],
  MA: [
    { value: "ma-city-fez", label: "Fez", level: "city" },
    { value: "ma-city-rabat", label: "Rabat", level: "city" },
    { value: "ma-city-tangier", label: "Tangier", level: "city" },
    { value: "ma-city-marrakech", label: "Marrakech", level: "city" },
    { value: "ma-city-marrakesh", label: "Marrakesh", level: "city" },
    { value: "ma-city-casablanca", label: "Casablanca", level: "city" }
  ],
  MC: [
    { value: "mc-city-monaco", label: "Monaco", level: "city" }
  ],
  MD: [
    { value: "md-city-chisinau", label: "Chișinău", level: "city" }
  ],
  ME: [
    { value: "me", label: "All of ME", level: "country" }
  ],
  MG: [
    { value: "mg-city-antananarivo", label: "Antananarivo", level: "city" }
  ],
  MH: [
    { value: "mh", label: "All of MH", level: "country" }
  ],
  MK: [
    { value: "mk", label: "All of MK", level: "country" }
  ],
  ML: [
    { value: "ml-city-bamako", label: "Bamako", level: "city" }
  ],
  MM: [
    { value: "mm", label: "All of MM", level: "country" }
  ],
  MN: [
    { value: "mn", label: "All of MN", level: "country" }
  ],
  MR: [
    { value: "mr", label: "All of MR", level: "country" }
  ],
  MT: [
    { value: "mt0", label: "Malta", level: "nuts1" },
    { value: "mt00", label: "Malta", level: "nuts2" }
  ],
  MU: [
    { value: "mu", label: "All of MU", level: "country" }
  ],
  MV: [
    { value: "mv", label: "All of MV", level: "country" }
  ],
  MW: [
    { value: "mw", label: "All of MW", level: "country" }
  ],
  MX: [
    { value: "mx-agu", label: "Aguascalientes", level: "state" },
    { value: "mx-bcn", label: "Baja California", level: "state" },
    { value: "mx-bcs", label: "Baja California Sur", level: "state" },
    { value: "mx-cam", label: "Campeche", level: "state" },
    { value: "mx-chp", label: "Chiapas", level: "state" },
    { value: "mx-chh", label: "Chihuahua", level: "state" },
    { value: "mx-cmx", label: "Ciudad de México", level: "state" },
    { value: "mx-coa", label: "Coahuila", level: "state" },
    { value: "mx-col", label: "Colima", level: "state" },
    { value: "mx-dur", label: "Durango", level: "state" },
    { value: "mx-gua", label: "Guanajuato", level: "state" },
    { value: "mx-gro", label: "Guerrero", level: "state" },
    { value: "mx-hid", label: "Hidalgo", level: "state" },
    { value: "mx-jal", label: "Jalisco", level: "state" },
    { value: "mx-mex", label: "México (Estado)", level: "state" },
    { value: "mx-mic", label: "Michoacán", level: "state" },
    { value: "mx-mor", label: "Morelos", level: "state" },
    { value: "mx-nay", label: "Nayarit", level: "state" },
    { value: "mx-nle", label: "Nuevo León", level: "state" },
    { value: "mx-oax", label: "Oaxaca", level: "state" },
    { value: "mx-pue", label: "Puebla", level: "state" },
    { value: "mx-que", label: "Querétaro", level: "state" },
    { value: "mx-roo", label: "Quintana Roo", level: "state" },
    { value: "mx-slp", label: "San Luis Potosí", level: "state" },
    { value: "mx-sin", label: "Sinaloa", level: "state" },
    { value: "mx-son", label: "Sonora", level: "state" },
    { value: "mx-tab", label: "Tabasco", level: "state" },
    { value: "mx-tam", label: "Tamaulipas", level: "state" },
    { value: "mx-tla", label: "Tlaxcala", level: "state" },
    { value: "mx-ver", label: "Veracruz", level: "state" },
    { value: "mx-yuc", label: "Yucatán", level: "state" },
    { value: "mx-zac", label: "Zacatecas", level: "state" },
    { value: "mx-20-549", label: "\"Heroica Villa Tezoatlán de Segura y Luna, Oaxaca", level: "municipality" },
    { value: "mx-31-001", label: "Abalá, Yucatán", level: "municipality" },
    { value: "mx-11-001", label: "Abasolo, Guanajuato", level: "municipality" },
    { value: "mx-19-001", label: "Abasolo, Nuevo León", level: "municipality" },
    { value: "mx-28-001", label: "Abasolo, Tamaulipas", level: "municipality" },
    { value: "mx-20-001", label: "Abejones, Oaxaca", level: "municipality" },
    { value: "mx-07-001", label: "Acacoyagua, Chiapas", level: "municipality" },
    { value: "mx-21-001", label: "Acajete, Puebla", level: "municipality" },
    { value: "mx-30-001", label: "Acajete, Veracruz de Ignacio de la Llave", level: "municipality" },
    { value: "mx-07-002", label: "Acala, Chiapas", level: "municipality" },
    { value: "mx-11-002", label: "Acámbaro, Guanajuato", level: "municipality" },
    { value: "mx-15-001", label: "Acambay de Ruíz Castañeda, México", level: "municipality" },
    { value: "mx-31-002", label: "Acanceh, Yucatán", level: "municipality" },
    { value: "mx-07-003", label: "Acapetahua, Chiapas", level: "municipality" },
    { value: "mx-18-001", label: "Acaponeta, Nayarit", level: "municipality" },
    { value: "mx-12-001", label: "Acapulco de Juárez, Guerrero", level: "municipality" },
    { value: "mx-21-002", label: "Acateno, Puebla", level: "municipality" },
    { value: "mx-12-076", label: "Acatepec, Guerrero", level: "municipality" },
    { value: "mx-14-001", label: "Acatic, Jalisco", level: "municipality" },
    { value: "mx-14-002", label: "Acatlán de Juárez, Jalisco", level: "municipality" },
    { value: "mx-20-002", label: "Acatlán de Pérez Figueroa, Oaxaca", level: "municipality" },
    { value: "mx-13-001", label: "Acatlán, Hidalgo", level: "municipality" },
    { value: "mx-21-003", label: "Acatlán, Puebla", level: "municipality" },
    { value: "mx-30-002", label: "Acatlán, Veracruz de Ignacio de la Llave", level: "municipality" },
    { value: "mx-21-004", label: "Acatzingo, Puebla", level: "municipality" },
    { value: "mx-13-002", label: "Acaxochitlán, Hidalgo", level: "municipality" },
    { value: "mx-30-003", label: "Acayucan, Veracruz de Ignacio de la Llave", level: "municipality" },
    { value: "mx-15-002", label: "Acolman, México", level: "municipality" }
  ],
  MY: [
    { value: "my-city-penang", label: "Penang", level: "city" },
    { value: "my-city-george-town", label: "George Town", level: "city" },
    { value: "my-city-johor-bahru", label: "Johor Bahru", level: "city" },
    { value: "my-city-kuala-lumpur", label: "Kuala Lumpur", level: "city" },
    { value: "my-city-kota-kinabalu", label: "Kota Kinabalu", level: "city" }
  ],
  MZ: [
    { value: "mz-city-maputo", label: "Maputo", level: "city" }
  ],
  NA: [
    { value: "na", label: "All of NA", level: "country" }
  ],
  NE: [
    { value: "ne-city-niamey", label: "Niamey", level: "city" }
  ],
  NG: [
    { value: "ng-city-kano", label: "Kano", level: "city" },
    { value: "ng-city-abuja", label: "Abuja", level: "city" },
    { value: "ng-city-lagos", label: "Lagos", level: "city" },
    { value: "ng-city-ibadan", label: "Ibadan", level: "city" },
    { value: "ng-city-port-harcourt", label: "Port Harcourt", level: "city" }
  ],
  NI: [
    { value: "ni-city-managua", label: "Managua", level: "city" }
  ],
  NL: [
    { value: "nl1", label: "Noord-Nederland", level: "nuts1" },
    { value: "nl2", label: "Oost-Nederland", level: "nuts1" },
    { value: "nl3", label: "West-Nederland", level: "nuts1" },
    { value: "nl4", label: "Zuid-Nederland", level: "nuts1" },
    { value: "nl13", label: "Drenthe", level: "nuts2" },
    { value: "nl23", label: "Flevoland", level: "nuts2" },
    { value: "nl12", label: "Friesland (NL)", level: "nuts2" },
    { value: "nl22", label: "Gelderland", level: "nuts2" },
    { value: "nl11", label: "Groningen", level: "nuts2" },
    { value: "nl42", label: "Limburg (NL)", level: "nuts2" },
    { value: "nl41", label: "Noord-Brabant", level: "nuts2" },
    { value: "nl32", label: "Noord-Holland", level: "nuts2" },
    { value: "nl21", label: "Overijssel", level: "nuts2" },
    { value: "nl31", label: "Utrecht (NUTS 2021)", level: "nuts2" },
    { value: "nl34", label: "Zeeland", level: "nuts2" },
    { value: "nl33", label: "Zuid-Holland (NUTS 2021)", level: "nuts2" },
    { value: "nl-gm0518", label: "'s-Gravenhage (gemeente)", level: "municipality" },
    { value: "nl-gm0796", label: "'s-Hertogenbosch", level: "municipality" },
    { value: "nl-gm1680", label: "Aa en Hunze", level: "municipality" },
    { value: "nl-gm0358", label: "Aalsmeer", level: "municipality" },
    { value: "nl-gm0197", label: "Aalten", level: "municipality" },
    { value: "nl-gm0059", label: "Achtkarspelen", level: "municipality" },
    { value: "nl-gm0482", label: "Alblasserdam", level: "municipality" },
    { value: "nl-gm0613", label: "Albrandswaard", level: "municipality" },
    { value: "nl-gm0361", label: "Alkmaar", level: "municipality" },
    { value: "nl-gm0141", label: "Almelo", level: "municipality" },
    { value: "nl-gm0034", label: "Almere", level: "municipality" },
    { value: "nl-gm0484", label: "Alphen aan den Rijn", level: "municipality" },
    { value: "nl-gm1723", label: "Alphen-Chaam", level: "municipality" },
    { value: "nl-gm1959", label: "Altena", level: "municipality" },
    { value: "nl-gm0060", label: "Ameland", level: "municipality" },
    { value: "nl-gm0307", label: "Amersfoort", level: "municipality" },
    { value: "nl-gm0362", label: "Amstelveen", level: "municipality" },
    { value: "nl-gm0363", label: "Amsterdam", level: "municipality" },
    { value: "nl-gm0200", label: "Apeldoorn", level: "municipality" },
    { value: "nl-gm0202", label: "Arnhem", level: "municipality" },
    { value: "nl-gm0106", label: "Assen", level: "municipality" },
    { value: "nl-gm0743", label: "Asten", level: "municipality" },
    { value: "nl-gm0744", label: "Baarle-Nassau", level: "municipality" },
    { value: "nl-gm0308", label: "Baarn", level: "municipality" },
    { value: "nl-gm0489", label: "Barendrecht", level: "municipality" },
    { value: "nl-gm0203", label: "Barneveld", level: "municipality" },
    { value: "nl-gm0888", label: "Beek (L.)", level: "municipality" },
    { value: "nl-gm1954", label: "Beekdaelen", level: "municipality" },
    { value: "nl-gm0889", label: "Beesel", level: "municipality" },
    { value: "nl-gm1945", label: "Berg en Dal", level: "municipality" },
    { value: "nl-gm1724", label: "Bergeijk", level: "municipality" },
    { value: "nl-gm0893", label: "Bergen (L.)", level: "municipality" },
    { value: "nl-gm0373", label: "Bergen (NH.)", level: "municipality" },
    { value: "nl-gm0748", label: "Bergen op Zoom", level: "municipality" },
    { value: "nl-gm1859", label: "Berkelland", level: "municipality" },
    { value: "nl-gm1721", label: "Bernheze", level: "municipality" },
    { value: "nl-gm0753", label: "Best", level: "municipality" },
    { value: "nl-gm0209", label: "Beuningen", level: "municipality" },
    { value: "nl-gm0375", label: "Beverwijk", level: "municipality" },
    { value: "nl-gm1728", label: "Bladel", level: "municipality" },
    { value: "nl-gm0376", label: "Blaricum", level: "municipality" },
    { value: "nl-gm0377", label: "Bloemendaal", level: "municipality" },
    { value: "nl-gm1901", label: "Bodegraven-Reeuwijk", level: "municipality" },
    { value: "nl-gm0755", label: "Boekel", level: "municipality" }
  ],
  NO: [
    { value: "no0", label: "Norge", level: "nuts1" },
    { value: "no04", label: "Agder og Rogaland (statistical region 2016)", level: "nuts2" },
    { value: "no09", label: "Agder og Sør-Østlandet", level: "nuts2" },
    { value: "no02", label: "Innlandet", level: "nuts2" },
    { value: "no07", label: "Nord-Norge", level: "nuts2" },
    { value: "no01", label: "Oslo og Akershus (statistical region 2016)", level: "nuts2" },
    { value: "no08", label: "Oslo og Viken", level: "nuts2" },
    { value: "no03", label: "Sør-Østlandet (statistical region 2016)", level: "nuts2" },
    { value: "no0b", label: "Svalbard og Jan Mayen", level: "nuts2" },
    { value: "no06", label: "Trøndelag", level: "nuts2" },
    { value: "no0a", label: "Vestlandet", level: "nuts2" },
    { value: "no05", label: "Vestlandet (statistical region 2016)", level: "nuts2" }
  ],
  NP: [
    { value: "np", label: "All of NP", level: "country" }
  ],
  NR: [
    { value: "nr", label: "All of NR", level: "country" }
  ],
  NZ: [
    { value: "nz-city-auckland", label: "Auckland", level: "city" },
    { value: "nz-city-hamilton", label: "Hamilton", level: "city" },
    { value: "nz-city-wellington", label: "Wellington", level: "city" },
    { value: "nz-city-christchurch", label: "Christchurch", level: "city" }
  ],
  OM: [
    { value: "om-city-muscat", label: "Muscat", level: "city" }
  ],
  PA: [
    { value: "pa-city-panama-city", label: "Panama City", level: "city" }
  ],
  PE: [
    { value: "pe-city-lima", label: "Lima", level: "city" },
    { value: "pe-city-arequipa", label: "Arequipa", level: "city" },
    { value: "pe-city-chiclayo", label: "Chiclayo", level: "city" },
    { value: "pe-city-trujillo", label: "Trujillo", level: "city" }
  ],
  PG: [
    { value: "pg-city-port-moresby", label: "Port Moresby", level: "city" }
  ],
  PH: [
    { value: "ph-city-cebu", label: "Cebu", level: "city" },
    { value: "ph-city-davao", label: "Davao", level: "city" },
    { value: "ph-city-manila", label: "Manila", level: "city" },
    { value: "ph-city-cebu-city", label: "Cebu City", level: "city" },
    { value: "ph-city-davao-city", label: "Davao City", level: "city" },
    { value: "ph-city-quezon-city", label: "Quezon City", level: "city" }
  ],
  PK: [
    { value: "pk-city-lahore", label: "Lahore", level: "city" },
    { value: "pk-city-karachi", label: "Karachi", level: "city" },
    { value: "pk-city-islamabad", label: "Islamabad", level: "city" },
    { value: "pk-city-faisalabad", label: "Faisalabad", level: "city" }
  ],
  PL: [
    { value: "pl7", label: "Makroregion centralny", level: "nuts1" },
    { value: "pl4", label: "Makroregion północno-zachodni", level: "nuts1" },
    { value: "pl6", label: "Makroregion północny", level: "nuts1" },
    { value: "pl5", label: "Makroregion południowo-zachodni", level: "nuts1" },
    { value: "pl2", label: "Makroregion południowy", level: "nuts1" },
    { value: "pl9", label: "Makroregion województwo mazowieckie", level: "nuts1" },
    { value: "pl8", label: "Makroregion wschodni", level: "nuts1" },
    { value: "pl51", label: "Dolnośląskie", level: "nuts2" },
    { value: "pl61", label: "Kujawsko-pomorskie", level: "nuts2" },
    { value: "pl71", label: "Łódzkie", level: "nuts2" },
    { value: "pl81", label: "Lubelskie", level: "nuts2" },
    { value: "pl43", label: "Lubuskie", level: "nuts2" },
    { value: "pl21", label: "Małopolskie", level: "nuts2" },
    { value: "pl92", label: "Mazowiecki regionalny", level: "nuts2" },
    { value: "pl52", label: "Opolskie", level: "nuts2" },
    { value: "pl82", label: "Podkarpackie", level: "nuts2" },
    { value: "pl84", label: "Podlaskie", level: "nuts2" },
    { value: "pl63", label: "Pomorskie", level: "nuts2" },
    { value: "pl22", label: "Śląskie", level: "nuts2" },
    { value: "pl72", label: "Świętokrzyskie", level: "nuts2" },
    { value: "pl62", label: "Warmińsko-mazurskie", level: "nuts2" },
    { value: "pl91", label: "Warszawski stołeczny", level: "nuts2" },
    { value: "pl41", label: "Wielkopolskie", level: "nuts2" },
    { value: "pl42", label: "Zachodniopomorskie", level: "nuts2" }
  ],
  PS: [
    { value: "ps", label: "All of PS", level: "country" }
  ],
  PT: [
    { value: "pt1", label: "Continente", level: "nuts1" },
    { value: "pt3", label: "Região Autónoma da Madeira", level: "nuts1" },
    { value: "pt2", label: "Região Autónoma dos Açores", level: "nuts1" },
    { value: "pt18", label: "Alentejo (NUTS 2021)", level: "nuts2" },
    { value: "pt15", label: "Algarve", level: "nuts2" },
    { value: "pt17", label: "Área Metropolitana de Lisboa (NUTS 2021)", level: "nuts2" },
    { value: "pt16", label: "Centro (PT) (NUTS 2021)", level: "nuts2" },
    { value: "pt11", label: "Norte", level: "nuts2" },
    { value: "pt30", label: "Região Autónoma da Madeira", level: "nuts2" },
    { value: "pt20", label: "Região Autónoma dos Açores", level: "nuts2" }
  ],
  PW: [
    { value: "pw", label: "All of PW", level: "country" }
  ],
  PY: [
    { value: "py-city-asuncion", label: "Asunción", level: "city" }
  ],
  QA: [
    { value: "qa-city-doha", label: "Doha", level: "city" }
  ],
  RO: [
    { value: "ro2", label: "Macroregiunea Doi", level: "nuts1" },
    { value: "ro4", label: "Macroregiunea Patru", level: "nuts1" },
    { value: "ro3", label: "Macroregiunea Trei", level: "nuts1" },
    { value: "ro1", label: "Macroregiunea Unu", level: "nuts1" },
    { value: "ro32", label: "Bucureşti-Ilfov", level: "nuts2" },
    { value: "ro12", label: "Centru", level: "nuts2" },
    { value: "ro21", label: "Nord-Est", level: "nuts2" },
    { value: "ro11", label: "Nord-Vest", level: "nuts2" },
    { value: "ro22", label: "Sud-Est", level: "nuts2" },
    { value: "ro31", label: "Sud-Muntenia", level: "nuts2" },
    { value: "ro41", label: "Sud-Vest Oltenia", level: "nuts2" },
    { value: "ro42", label: "Vest", level: "nuts2" }
  ],
  RS: [
    { value: "rs", label: "All of RS", level: "country" }
  ],
  RU: [
    { value: "ru-city-ufa", label: "Ufa", level: "city" },
    { value: "ru-city-kazan", label: "Kazan", level: "city" },
    { value: "ru-city-moscow", label: "Moscow", level: "city" },
    { value: "ru-city-samara", label: "Samara", level: "city" },
    { value: "ru-city-krasnodar", label: "Krasnodar", level: "city" },
    { value: "ru-city-novosibirsk", label: "Novosibirsk", level: "city" },
    { value: "ru-city-rostov-on-don", label: "Rostov-on-Don", level: "city" },
    { value: "ru-city-yekaterinburg", label: "Yekaterinburg", level: "city" },
    { value: "ru-city-nizhny-novgorod", label: "Nizhny Novgorod", level: "city" },
    { value: "ru-city-saint-petersburg", label: "Saint Petersburg", level: "city" }
  ],
  RW: [
    { value: "rw-city-kigali", label: "Kigali", level: "city" }
  ],
  SA: [
    { value: "sa-city-mecca", label: "Mecca", level: "city" },
    { value: "sa-city-dammam", label: "Dammam", level: "city" },
    { value: "sa-city-jeddah", label: "Jeddah", level: "city" },
    { value: "sa-city-medina", label: "Medina", level: "city" },
    { value: "sa-city-riyadh", label: "Riyadh", level: "city" }
  ],
  SB: [
    { value: "sb", label: "All of SB", level: "country" }
  ],
  SC: [
    { value: "sc", label: "All of SC", level: "country" }
  ],
  SD: [
    { value: "sd", label: "All of SD", level: "country" }
  ],
  SE: [
    { value: "se3", label: "Norra Sverige", level: "nuts1" },
    { value: "se1", label: "Östra Sverige", level: "nuts1" },
    { value: "se2", label: "Södra Sverige", level: "nuts1" },
    { value: "se32", label: "Mellersta Norrland", level: "nuts2" },
    { value: "se31", label: "Norra Mellansverige", level: "nuts2" },
    { value: "se12", label: "Östra Mellansverige", level: "nuts2" },
    { value: "se33", label: "Övre Norrland", level: "nuts2" },
    { value: "se21", label: "Småland med öarna", level: "nuts2" },
    { value: "se11", label: "Stockholm", level: "nuts2" },
    { value: "se22", label: "Sydsverige", level: "nuts2" },
    { value: "se23", label: "Västsverige", level: "nuts2" }
  ],
  SG: [
    { value: "sg", label: "All of SG", level: "country" }
  ],
  SI: [
    { value: "si0", label: "Slovenija", level: "nuts1" },
    { value: "si03", label: "Vzhodna Slovenija", level: "nuts2" },
    { value: "si04", label: "Zahodna Slovenija", level: "nuts2" }
  ],
  SK: [
    { value: "sk0", label: "Slovensko", level: "nuts1" },
    { value: "sk01", label: "Bratislavský kraj", level: "nuts2" },
    { value: "sk03", label: "Stredné Slovensko", level: "nuts2" },
    { value: "sk04", label: "Východné Slovensko", level: "nuts2" },
    { value: "sk02", label: "Západné Slovensko", level: "nuts2" }
  ],
  SL: [
    { value: "sl", label: "All of SL", level: "country" }
  ],
  SM: [
    { value: "sm-city-serravalle", label: "Serravalle", level: "city" },
    { value: "sm-city-city-of-san-marino", label: "City of San Marino", level: "city" }
  ],
  SN: [
    { value: "sn-city-dakar", label: "Dakar", level: "city" }
  ],
  SO: [
    { value: "so", label: "All of SO", level: "country" }
  ],
  SR: [
    { value: "sr", label: "All of SR", level: "country" }
  ],
  SS: [
    { value: "ss", label: "All of SS", level: "country" }
  ],
  ST: [
    { value: "st", label: "All of ST", level: "country" }
  ],
  SV: [
    { value: "sv-city-san-salvador", label: "San Salvador", level: "city" }
  ],
  SY: [
    { value: "sy", label: "All of SY", level: "country" }
  ],
  SZ: [
    { value: "sz", label: "All of SZ", level: "country" }
  ],
  TD: [
    { value: "td", label: "All of TD", level: "country" }
  ],
  TG: [
    { value: "tg", label: "All of TG", level: "country" }
  ],
  TH: [
    { value: "th-city-phuket", label: "Phuket", level: "city" },
    { value: "th-city-bangkok", label: "Bangkok", level: "city" },
    { value: "th-city-pattaya", label: "Pattaya", level: "city" },
    { value: "th-city-chiang-mai", label: "Chiang Mai", level: "city" }
  ],
  TJ: [
    { value: "tj-city-dushanbe", label: "Dushanbe", level: "city" }
  ],
  TL: [
    { value: "tl", label: "All of TL", level: "country" }
  ],
  TM: [
    { value: "tm-city-ashgabat", label: "Ashgabat", level: "city" }
  ],
  TN: [
    { value: "tn-city-sfax", label: "Sfax", level: "city" },
    { value: "tn-city-tunis", label: "Tunis", level: "city" }
  ],
  TO: [
    { value: "to", label: "All of TO", level: "country" }
  ],
  TR: [
    { value: "tr-city-bursa", label: "Bursa", level: "city" },
    { value: "tr-city-izmir", label: "Izmir", level: "city" },
    { value: "tr-city-ankara", label: "Ankara", level: "city" },
    { value: "tr-city-antalya", label: "Antalya", level: "city" },
    { value: "tr-city-istanbul", label: "Istanbul", level: "city" }
  ],
  TT: [
    { value: "tt-city-port-of-spain", label: "Port of Spain", level: "city" }
  ],
  TV: [
    { value: "tv", label: "All of TV", level: "country" }
  ],
  TW: [
    { value: "tw", label: "All of TW", level: "country" }
  ],
  TZ: [
    { value: "tz-city-dodoma", label: "Dodoma", level: "city" },
    { value: "tz-city-dar-es-salaam", label: "Dar es Salaam", level: "city" }
  ],
  UA: [
    { value: "ua-city-kyiv", label: "Kyiv", level: "city" },
    { value: "ua-city-lviv", label: "Lviv", level: "city" },
    { value: "ua-city-odesa", label: "Odesa", level: "city" },
    { value: "ua-city-kharkiv", label: "Kharkiv", level: "city" }
  ],
  UG: [
    { value: "ug-city-kampala", label: "Kampala", level: "city" }
  ],
  UK: [
    { value: "ukc", label: "North East (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukc1", label: "Tees Valley and Durham (NUTS 2021)", level: "nuts2" },
    { value: "ukc2", label: "Northumberland and Tyne and Wear (NUTS 2021)", level: "nuts2" },
    { value: "ukd", label: "North West (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukd1", label: "Cumbria (NUTS 2021)", level: "nuts2" },
    { value: "ukd3", label: "Greater Manchester (NUTS 2021)", level: "nuts2" },
    { value: "ukd4", label: "Lancashire (NUTS 2021)", level: "nuts2" },
    { value: "ukd6", label: "Cheshire (NUTS 2021)", level: "nuts2" },
    { value: "ukd7", label: "Merseyside (NUTS 2021)", level: "nuts2" },
    { value: "uke", label: "Yorkshire and The Humber (NUTS 2021)", level: "nuts1" },
    { value: "uke1", label: "East Yorkshire and Northern Lincolnshire (NUTS 2021)", level: "nuts2" },
    { value: "uke2", label: "North Yorkshire (NUTS 2021)", level: "nuts2" },
    { value: "uke3", label: "South Yorkshire (NUTS 2021)", level: "nuts2" },
    { value: "uke4", label: "West Yorkshire (NUTS 2021)", level: "nuts2" },
    { value: "ukf", label: "East Midlands (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukf1", label: "Derbyshire and Nottinghamshire (NUTS 2021)", level: "nuts2" },
    { value: "ukf2", label: "Leicestershire, Rutland and Northamptonshire (NUTS 2021)", level: "nuts2" },
    { value: "ukf3", label: "Lincolnshire (NUTS 2021)", level: "nuts2" },
    { value: "ukg", label: "West Midlands (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukg1", label: "Herefordshire, Worcestershire and Warwickshire (NUTS 2021)", level: "nuts2" },
    { value: "ukg2", label: "Shropshire and Staffordshire (NUTS 2021)", level: "nuts2" },
    { value: "ukg3", label: "West Midlands (NUTS 2021)", level: "nuts2" },
    { value: "ukh", label: "East of England (NUTS 2021)", level: "nuts1" },
    { value: "ukh1", label: "East Anglia (NUTS 2021)", level: "nuts2" },
    { value: "ukh2", label: "Bedfordshire and Hertfordshire (NUTS 2021)", level: "nuts2" },
    { value: "ukh3", label: "Essex (NUTS 2021)", level: "nuts2" },
    { value: "uki", label: "London (NUTS 2021)", level: "nuts1" },
    { value: "uki3", label: "Inner London - West (NUTS 2021)", level: "nuts2" },
    { value: "uki4", label: "Inner London - East (NUTS 2021)", level: "nuts2" },
    { value: "uki5", label: "Outer London - East and North East (NUTS 2021)", level: "nuts2" },
    { value: "uki6", label: "Outer London - South (NUTS 2021)", level: "nuts2" },
    { value: "uki7", label: "Outer London - West and North West (NUTS 2021)", level: "nuts2" },
    { value: "ukj", label: "South East (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukj1", label: "Berkshire, Buckinghamshire and Oxfordshire (NUTS 2021)", level: "nuts2" },
    { value: "ukj2", label: "Surrey, East and West Sussex (NUTS 2021)", level: "nuts2" },
    { value: "ukj3", label: "Hampshire and Isle of Wight (NUTS 2021)", level: "nuts2" },
    { value: "ukj4", label: "Kent (NUTS 2021)", level: "nuts2" },
    { value: "ukk", label: "South West (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukk1", label: "Gloucestershire, Wiltshire and Bristol/Bath area (NUTS 2021)", level: "nuts2" },
    { value: "ukk2", label: "Dorset and Somerset (NUTS 2021)", level: "nuts2" },
    { value: "ukk3", label: "Cornwall and Isles of Scilly (NUTS 2021)", level: "nuts2" },
    { value: "ukk4", label: "Devon (NUTS 2021)", level: "nuts2" },
    { value: "ukl", label: "Wales (NUTS 2021)", level: "nuts1" },
    { value: "ukl1", label: "West Wales and The Valleys (NUTS 2021)", level: "nuts2" },
    { value: "ukl2", label: "East Wales (NUTS 2021)", level: "nuts2" },
    { value: "ukm", label: "Scotland (NUTS 2021)", level: "nuts1" },
    { value: "ukm5", label: "North Eastern Scotland (NUTS 2021)", level: "nuts2" },
    { value: "ukm6", label: "Highlands and Islands (NUTS 2021)", level: "nuts2" },
    { value: "ukm7", label: "Eastern Scotland (NUTS 2021)", level: "nuts2" },
    { value: "ukm8", label: "West Central Scotland (NUTS 2021)", level: "nuts2" },
    { value: "ukm9", label: "Southern Scotland (NUTS 2021)", level: "nuts2" },
    { value: "ukn", label: "Northern Ireland (UK) (NUTS 2021)", level: "nuts1" },
    { value: "ukn0", label: "Northern Ireland (UK) (NUTS 2021)", level: "nuts2" }
  ],
  US: [
    { value: "us-45-001", label: "Abbeville County, South Carolina", level: "county" },
    { value: "us-22-001", label: "Acadia Parish, Louisiana", level: "county" },
    { value: "us-51-001", label: "Accomack County, Virginia", level: "county" },
    { value: "us-16-001", label: "Ada County, Idaho", level: "county" },
    { value: "us-19-001", label: "Adair County, Iowa", level: "county" },
    { value: "us-21-001", label: "Adair County, Kentucky", level: "county" },
    { value: "us-29-001", label: "Adair County, Missouri", level: "county" },
    { value: "us-40-001", label: "Adair County, Oklahoma", level: "county" },
    { value: "us-08-001", label: "Adams County, Colorado", level: "county" },
    { value: "us-16-003", label: "Adams County, Idaho", level: "county" },
    { value: "us-17-001", label: "Adams County, Illinois", level: "county" },
    { value: "us-18-001", label: "Adams County, Indiana", level: "county" },
    { value: "us-19-003", label: "Adams County, Iowa", level: "county" },
    { value: "us-28-001", label: "Adams County, Mississippi", level: "county" },
    { value: "us-31-001", label: "Adams County, Nebraska", level: "county" },
    { value: "us-38-001", label: "Adams County, North Dakota", level: "county" },
    { value: "us-39-001", label: "Adams County, Ohio", level: "county" },
    { value: "us-42-001", label: "Adams County, Pennsylvania", level: "county" },
    { value: "us-53-001", label: "Adams County, Washington", level: "county" },
    { value: "us-55-001", label: "Adams County, Wisconsin", level: "county" },
    { value: "us-50-001", label: "Addison County, Vermont", level: "county" },
    { value: "us-45-003", label: "Aiken County, South Carolina", level: "county" },
    { value: "us-27-001", label: "Aitkin County, Minnesota", level: "county" },
    { value: "us-12-001", label: "Alachua County, Florida", level: "county" },
    { value: "us-37-001", label: "Alamance County, North Carolina", level: "county" },
    { value: "us-06-001", label: "Alameda County, California", level: "county" },
    { value: "us-08-003", label: "Alamosa County, Colorado", level: "county" },
    { value: "us-36-001", label: "Albany County, New York", level: "county" },
    { value: "us-56-001", label: "Albany County, Wyoming", level: "county" },
    { value: "us-51-003", label: "Albemarle County, Virginia", level: "county" },
    { value: "us-26-001", label: "Alcona County, Michigan", level: "county" },
    { value: "us-28-003", label: "Alcorn County, Mississippi", level: "county" },
    { value: "us-02-013", label: "Aleutians East Borough, Alaska", level: "county" },
    { value: "us-02-016", label: "Aleutians West Census Area, Alaska", level: "county" },
    { value: "us-17-003", label: "Alexander County, Illinois", level: "county" },
    { value: "us-37-003", label: "Alexander County, North Carolina", level: "county" },
    { value: "us-51-510", label: "Alexandria city, Virginia", level: "county" },
    { value: "us-40-003", label: "Alfalfa County, Oklahoma", level: "county" },
    { value: "us-26-003", label: "Alger County, Michigan", level: "county" },
    { value: "us-19-005", label: "Allamakee County, Iowa", level: "county" },
    { value: "us-26-005", label: "Allegan County, Michigan", level: "county" },
    { value: "us-24-001", label: "Allegany County, Maryland", level: "county" },
    { value: "us-36-003", label: "Allegany County, New York", level: "county" },
    { value: "us-37-005", label: "Alleghany County, North Carolina", level: "county" },
    { value: "us-51-005", label: "Alleghany County, Virginia", level: "county" },
    { value: "us-42-003", label: "Allegheny County, Pennsylvania", level: "county" },
    { value: "us-18-003", label: "Allen County, Indiana", level: "county" },
    { value: "us-20-001", label: "Allen County, Kansas", level: "county" },
    { value: "us-21-003", label: "Allen County, Kentucky", level: "county" },
    { value: "us-39-003", label: "Allen County, Ohio", level: "county" },
    { value: "us-22-003", label: "Allen Parish, Louisiana", level: "county" },
    { value: "us-45-005", label: "Allendale County, South Carolina", level: "county" },
    { value: "us-26-007", label: "Alpena County, Michigan", level: "county" },
    { value: "us-06-003", label: "Alpine County, California", level: "county" },
    { value: "us-06-005", label: "Amador County, California", level: "county" },
    { value: "us-51-007", label: "Amelia County, Virginia", level: "county" },
    { value: "us-51-009", label: "Amherst County, Virginia", level: "county" },
    { value: "us-28-005", label: "Amite County, Mississippi", level: "county" },
    { value: "us-02-020", label: "Anchorage Municipality, Alaska", level: "county" },
    { value: "us-20-003", label: "Anderson County, Kansas", level: "county" }
  ],
  UY: [
    { value: "uy-city-montevideo", label: "Montevideo", level: "city" }
  ],
  UZ: [
    { value: "uz-city-tashkent", label: "Tashkent", level: "city" },
    { value: "uz-city-samarkand", label: "Samarkand", level: "city" }
  ],
  VA: [
    { value: "va", label: "All of VA", level: "country" }
  ],
  VC: [
    { value: "vc", label: "All of VC", level: "country" }
  ],
  VE: [
    { value: "ve-city-caracas", label: "Caracas", level: "city" },
    { value: "ve-city-maracaibo", label: "Maracaibo", level: "city" }
  ],
  VN: [
    { value: "vn-city-hanoi", label: "Hanoi", level: "city" },
    { value: "vn-city-can-tho", label: "Can Tho", level: "city" },
    { value: "vn-city-da-nang", label: "Da Nang", level: "city" },
    { value: "vn-city-haiphong", label: "Haiphong", level: "city" },
    { value: "vn-city-ho-chi-minh-city", label: "Ho Chi Minh City", level: "city" }
  ],
  VU: [
    { value: "vu", label: "All of VU", level: "country" }
  ],
  WS: [
    { value: "ws-city-apia", label: "Apia", level: "city" }
  ],
  XK: [
    { value: "xk", label: "All of XK", level: "country" }
  ],
  YE: [
    { value: "ye", label: "All of YE", level: "country" }
  ],
  ZA: [
    { value: "za-city-durban", label: "Durban", level: "city" },
    { value: "za-city-pretoria", label: "Pretoria", level: "city" },
    { value: "za-city-cape-town", label: "Cape Town", level: "city" },
    { value: "za-city-johannesburg", label: "Johannesburg", level: "city" },
    { value: "za-city-port-elizabeth", label: "Port Elizabeth", level: "city" }
  ],
  ZM: [
    { value: "zm-city-kitwe", label: "Kitwe", level: "city" },
    { value: "zm-city-lusaka", label: "Lusaka", level: "city" }
  ],
  ZW: [
    { value: "zw-city-harare", label: "Harare", level: "city" },
    { value: "zw-city-bulawayo", label: "Bulawayo", level: "city" }
  ],
};

export const REGIONS_GENERATED_AT = "2026-05-21T19:51:11.705Z";
export const REGIONS_TOTAL_COUNTRIES = 199;