/**
 * Region cascade table for the NavigatorForm.
 *
 * For each country, exposes the major first-level regions that resolve to
 * a measured cell in `regional_cells`. Slug form matches what
 * `regionalSlugToGeoId()` expects in `src/lib/cells.ts`.
 *
 * Seed coverage: top 30 countries with regional data. Countries not in
 * this table fall back to a single "All of {country}" option that resolves
 * via `getExtrapolatedCell` at the data layer.
 */
export type RegionOption = {
  /** Slug used in URL + passed to `regionalSlugToGeoId`. */
  value: string;
  /** Human label for the dropdown. */
  label: string;
};

export const REGIONS_BY_COUNTRY: Record<string, RegionOption[]> = {
  US: [
    { value: "alabama", label: "Alabama" },
    { value: "alaska", label: "Alaska" },
    { value: "arizona", label: "Arizona" },
    { value: "arkansas", label: "Arkansas" },
    { value: "california", label: "California" },
    { value: "colorado", label: "Colorado" },
    { value: "connecticut", label: "Connecticut" },
    { value: "delaware", label: "Delaware" },
    { value: "district-of-columbia", label: "District of Columbia" },
    { value: "florida", label: "Florida" },
    { value: "georgia", label: "Georgia" },
    { value: "hawaii", label: "Hawaii" },
    { value: "idaho", label: "Idaho" },
    { value: "illinois", label: "Illinois" },
    { value: "indiana", label: "Indiana" },
    { value: "iowa", label: "Iowa" },
    { value: "kansas", label: "Kansas" },
    { value: "kentucky", label: "Kentucky" },
    { value: "louisiana", label: "Louisiana" },
    { value: "maine", label: "Maine" },
    { value: "maryland", label: "Maryland" },
    { value: "massachusetts", label: "Massachusetts" },
    { value: "michigan", label: "Michigan" },
    { value: "minnesota", label: "Minnesota" },
    { value: "mississippi", label: "Mississippi" },
    { value: "missouri", label: "Missouri" },
    { value: "montana", label: "Montana" },
    { value: "nebraska", label: "Nebraska" },
    { value: "nevada", label: "Nevada" },
    { value: "new-hampshire", label: "New Hampshire" },
    { value: "new-jersey", label: "New Jersey" },
    { value: "new-mexico", label: "New Mexico" },
    { value: "new-york", label: "New York" },
    { value: "north-carolina", label: "North Carolina" },
    { value: "north-dakota", label: "North Dakota" },
    { value: "ohio", label: "Ohio" },
    { value: "oklahoma", label: "Oklahoma" },
    { value: "oregon", label: "Oregon" },
    { value: "pennsylvania", label: "Pennsylvania" },
    { value: "rhode-island", label: "Rhode Island" },
    { value: "south-carolina", label: "South Carolina" },
    { value: "south-dakota", label: "South Dakota" },
    { value: "tennessee", label: "Tennessee" },
    { value: "texas", label: "Texas" },
    { value: "utah", label: "Utah" },
    { value: "vermont", label: "Vermont" },
    { value: "virginia", label: "Virginia" },
    { value: "washington", label: "Washington" },
    { value: "west-virginia", label: "West Virginia" },
    { value: "wisconsin", label: "Wisconsin" },
    { value: "wyoming", label: "Wyoming" },
  ],
  DE: [
    { value: "de1", label: "Baden-Württemberg" },
    { value: "de2", label: "Bavaria (Bayern)" },
    { value: "de21", label: "Upper Bavaria" },
    { value: "de212", label: "Munich" },
    { value: "de3", label: "Berlin" },
    { value: "de5", label: "Bremen" },
    { value: "de6", label: "Hamburg" },
    { value: "de7", label: "Hesse" },
    { value: "de71", label: "Darmstadt" },
    { value: "de712", label: "Frankfurt am Main" },
    { value: "de9", label: "Lower Saxony" },
    { value: "dea", label: "North Rhine-Westphalia" },
    { value: "dea1", label: "Düsseldorf" },
    { value: "dea2", label: "Cologne (Köln)" },
    { value: "deb", label: "Rhineland-Palatinate" },
    { value: "ded", label: "Saxony" },
    { value: "ded2", label: "Dresden" },
    { value: "ded5", label: "Leipzig" },
    { value: "def", label: "Schleswig-Holstein" },
    { value: "deg", label: "Thuringia" },
  ],
  FR: [
    { value: "fr10", label: "Île-de-France (Paris region)" },
    { value: "fr101", label: "Paris" },
    { value: "fr102", label: "Hauts-de-Seine" },
    { value: "frb", label: "Centre-Val de Loire" },
    { value: "frc", label: "Bourgogne-Franche-Comté" },
    { value: "frd", label: "Normandy" },
    { value: "fre", label: "Hauts-de-France" },
    { value: "frf", label: "Grand Est" },
    { value: "frg", label: "Pays de la Loire" },
    { value: "frh", label: "Brittany" },
    { value: "fri", label: "Nouvelle-Aquitaine" },
    { value: "frj", label: "Occitanie" },
    { value: "frk", label: "Auvergne-Rhône-Alpes" },
    { value: "frk2", label: "Rhône-Alpes" },
    { value: "frl", label: "Provence-Alpes-Côte d'Azur" },
    { value: "frm", label: "Corsica" },
  ],
  IT: [
    { value: "itc1", label: "Piedmont" },
    { value: "itc11", label: "Turin" },
    { value: "itc3", label: "Liguria" },
    { value: "itc4", label: "Lombardy" },
    { value: "itc4c", label: "Milan" },
    { value: "ith1", label: "Bolzano-Bozen" },
    { value: "ith3", label: "Veneto" },
    { value: "ith4", label: "Friuli-Venezia Giulia" },
    { value: "ith5", label: "Emilia-Romagna" },
    { value: "iti1", label: "Tuscany" },
    { value: "iti4", label: "Lazio (Rome region)" },
    { value: "iti43", label: "Rome" },
    { value: "itf1", label: "Abruzzo" },
    { value: "itf3", label: "Campania" },
    { value: "itf33", label: "Naples" },
    { value: "itf4", label: "Puglia" },
    { value: "itg1", label: "Sicily" },
    { value: "itg2", label: "Sardinia" },
  ],
  ES: [
    { value: "es11", label: "Galicia" },
    { value: "es21", label: "Basque Country" },
    { value: "es3", label: "Community of Madrid" },
    { value: "es30", label: "Madrid" },
    { value: "es41", label: "Castile and León" },
    { value: "es42", label: "Castilla-La Mancha" },
    { value: "es43", label: "Extremadura" },
    { value: "es51", label: "Catalonia" },
    { value: "es511", label: "Barcelona" },
    { value: "es52", label: "Valencian Community" },
    { value: "es521", label: "Valencia" },
    { value: "es61", label: "Andalusia" },
    { value: "es617", label: "Málaga" },
    { value: "es618", label: "Seville" },
    { value: "es62", label: "Region of Murcia" },
    { value: "es70", label: "Canary Islands" },
  ],
  GB: [
    { value: "ukc", label: "North East England" },
    { value: "ukd", label: "North West England" },
    { value: "uke", label: "Yorkshire and the Humber" },
    { value: "ukf", label: "East Midlands" },
    { value: "ukg", label: "West Midlands" },
    { value: "ukh", label: "East of England" },
    { value: "uki", label: "Greater London" },
    { value: "ukj", label: "South East England" },
    { value: "ukk", label: "South West England" },
    { value: "ukl", label: "Wales" },
    { value: "ukm", label: "Scotland" },
    { value: "ukn", label: "Northern Ireland" },
  ],
  JP: [
    { value: "jp-13000", label: "Tokyo" },
    { value: "jp-14000", label: "Kanagawa (Yokohama)" },
    { value: "jp-11000", label: "Saitama" },
    { value: "jp-12000", label: "Chiba" },
    { value: "jp-27000", label: "Osaka" },
    { value: "jp-28000", label: "Hyogo (Kobe)" },
    { value: "jp-26000", label: "Kyoto" },
    { value: "jp-23000", label: "Aichi (Nagoya)" },
    { value: "jp-01000", label: "Hokkaido (Sapporo)" },
    { value: "jp-40000", label: "Fukuoka" },
    { value: "jp-04000", label: "Miyagi (Sendai)" },
    { value: "jp-22000", label: "Shizuoka" },
    { value: "jp-34000", label: "Hiroshima" },
  ],
  BR: [
    { value: "br-sp", label: "São Paulo state" },
    { value: "br-rj", label: "Rio de Janeiro state" },
    { value: "br-mg", label: "Minas Gerais" },
    { value: "br-rs", label: "Rio Grande do Sul" },
    { value: "br-pr", label: "Paraná" },
    { value: "br-ba", label: "Bahia" },
    { value: "br-sc", label: "Santa Catarina" },
    { value: "br-pe", label: "Pernambuco" },
    { value: "br-ce", label: "Ceará" },
    { value: "br-df", label: "Federal District (Brasília)" },
    { value: "br-go", label: "Goiás" },
    { value: "br-pa", label: "Pará" },
    { value: "br-am", label: "Amazonas" },
    { value: "br-city-sao-paulo", label: "São Paulo city" },
    { value: "br-city-rio-de-janeiro", label: "Rio de Janeiro city" },
    { value: "br-city-belo-horizonte", label: "Belo Horizonte" },
    { value: "br-city-brasilia", label: "Brasília" },
    { value: "br-city-salvador", label: "Salvador" },
    { value: "br-city-curitiba", label: "Curitiba" },
    { value: "br-city-fortaleza", label: "Fortaleza" },
  ],
  MX: [
    { value: "mx-cmx", label: "Mexico City" },
    { value: "mx-mex", label: "State of Mexico" },
    { value: "mx-jal", label: "Jalisco (Guadalajara)" },
    { value: "mx-nle", label: "Nuevo León (Monterrey)" },
    { value: "mx-pue", label: "Puebla" },
    { value: "mx-gua", label: "Guanajuato" },
    { value: "mx-chh", label: "Chihuahua" },
    { value: "mx-bcn", label: "Baja California (Tijuana)" },
    { value: "mx-roo", label: "Quintana Roo (Cancún)" },
    { value: "mx-ver", label: "Veracruz" },
    { value: "mx-yuc", label: "Yucatán (Mérida)" },
  ],
  CA: [
    { value: "ca-on", label: "Ontario" },
    { value: "ca-qc", label: "Quebec" },
    { value: "ca-bc", label: "British Columbia" },
    { value: "ca-ab", label: "Alberta" },
    { value: "ca-mb", label: "Manitoba" },
    { value: "ca-sk", label: "Saskatchewan" },
    { value: "ca-ns", label: "Nova Scotia" },
    { value: "ca-nb", label: "New Brunswick" },
    { value: "ca-nl", label: "Newfoundland and Labrador" },
  ],
  AU: [
    { value: "au-nsw", label: "New South Wales (Sydney)" },
    { value: "au-vic", label: "Victoria (Melbourne)" },
    { value: "au-qld", label: "Queensland (Brisbane)" },
    { value: "au-wa", label: "Western Australia (Perth)" },
    { value: "au-sa", label: "South Australia (Adelaide)" },
    { value: "au-tas", label: "Tasmania (Hobart)" },
    { value: "au-act", label: "Australian Capital Territory" },
  ],
  NL: [
    { value: "nl11", label: "Groningen" },
    { value: "nl21", label: "Overijssel" },
    { value: "nl23", label: "Flevoland" },
    { value: "nl31", label: "Utrecht" },
    { value: "nl32", label: "North Holland (Amsterdam)" },
    { value: "nl33", label: "South Holland (Rotterdam, The Hague)" },
    { value: "nl41", label: "North Brabant" },
    { value: "nl42", label: "Limburg" },
  ],
  PL: [
    { value: "pl12", label: "Mazowieckie (Warsaw)" },
    { value: "pl21", label: "Małopolskie (Kraków)" },
    { value: "pl22", label: "Śląskie" },
    { value: "pl41", label: "Wielkopolskie (Poznań)" },
    { value: "pl42", label: "Zachodniopomorskie" },
    { value: "pl51", label: "Dolnośląskie (Wrocław)" },
    { value: "pl63", label: "Pomorskie (Gdańsk)" },
  ],
  PT: [
    { value: "pt11", label: "Northern Portugal (Porto)" },
    { value: "pt15", label: "Algarve" },
    { value: "pt17", label: "Lisbon Metropolitan Area" },
    { value: "pt18", label: "Alentejo" },
    { value: "pt30", label: "Madeira" },
  ],
  BE: [
    { value: "be1", label: "Brussels" },
    { value: "be2", label: "Flanders" },
    { value: "be21", label: "Antwerp province" },
    { value: "be3", label: "Wallonia" },
  ],
  AT: [
    { value: "at1", label: "Eastern Austria (Vienna)" },
    { value: "at13", label: "Vienna" },
    { value: "at2", label: "Southern Austria" },
    { value: "at3", label: "Western Austria" },
  ],
  CH: [
    { value: "ch01", label: "Lake Geneva region" },
    { value: "ch02", label: "Espace Mittelland (Bern)" },
    { value: "ch03", label: "Northwestern Switzerland" },
    { value: "ch04", label: "Zürich" },
    { value: "ch05", label: "Eastern Switzerland" },
    { value: "ch06", label: "Central Switzerland" },
    { value: "ch07", label: "Ticino" },
  ],
  SE: [
    { value: "se11", label: "Stockholm region" },
    { value: "se12", label: "East Middle Sweden" },
    { value: "se21", label: "Småland and the islands" },
    { value: "se22", label: "South Sweden (Malmö)" },
    { value: "se23", label: "West Sweden (Gothenburg)" },
    { value: "se31", label: "North Middle Sweden" },
    { value: "se32", label: "Middle Norrland" },
    { value: "se33", label: "Upper Norrland" },
  ],
  NO: [
    { value: "no01", label: "Oslo and Akershus" },
    { value: "no03", label: "Sør-Østlandet" },
    { value: "no04", label: "Agder and Rogaland" },
    { value: "no05", label: "Western Norway (Bergen)" },
    { value: "no06", label: "Trøndelag (Trondheim)" },
    { value: "no07", label: "Northern Norway" },
  ],
  DK: [
    { value: "dk01", label: "Capital region (Copenhagen)" },
    { value: "dk02", label: "Zealand" },
    { value: "dk03", label: "Southern Denmark (Odense)" },
    { value: "dk04", label: "Central Denmark (Aarhus)" },
    { value: "dk05", label: "Northern Denmark" },
  ],
  FI: [
    { value: "fi19", label: "Western Finland" },
    { value: "fi1b", label: "Helsinki-Uusimaa" },
    { value: "fi1c", label: "Southern Finland" },
    { value: "fi1d", label: "Northern and Eastern Finland" },
  ],
  IE: [
    { value: "ie04", label: "Northern and Western Ireland" },
    { value: "ie05", label: "Southern Ireland" },
    { value: "ie06", label: "Eastern and Midland (Dublin)" },
  ],
  GR: [
    { value: "el3", label: "Attica (Athens)" },
    { value: "el5", label: "Northern Greece (Thessaloniki)" },
    { value: "el6", label: "Central Greece" },
    { value: "el4", label: "Aegean and Crete" },
  ],
  CZ: [
    { value: "cz01", label: "Prague" },
    { value: "cz02", label: "Central Bohemia" },
    { value: "cz06", label: "Southeast (Brno)" },
    { value: "cz07", label: "Central Moravia" },
    { value: "cz08", label: "Moravia-Silesia (Ostrava)" },
  ],
  HU: [
    { value: "hu11", label: "Budapest" },
    { value: "hu12", label: "Pest county" },
    { value: "hu23", label: "Southern Transdanubia" },
    { value: "hu33", label: "Southern Great Plain" },
  ],
  RO: [
    { value: "ro32", label: "Bucharest-Ilfov" },
    { value: "ro12", label: "Center" },
    { value: "ro21", label: "Northeast" },
    { value: "ro42", label: "West" },
  ],
  IN: [
    { value: "india", label: "All of India" },
  ],
  CN: [
    { value: "china", label: "All of China" },
  ],
  RU: [
    { value: "ru-city-moscow", label: "Moscow" },
    { value: "ru-city-saint-petersburg", label: "Saint Petersburg" },
    { value: "ru-city-novosibirsk", label: "Novosibirsk" },
    { value: "ru-city-yekaterinburg", label: "Yekaterinburg" },
  ],
};

/**
 * Returns the regions for a given country, or a single country-level
 * fallback option if the country isn't in the table.
 */
export function getRegionsForCountry(iso2: string, countryName: string): RegionOption[] {
  const entry = REGIONS_BY_COUNTRY[iso2.toUpperCase()];
  if (entry && entry.length > 0) return entry;
  // Slug derived from country name, lowercase, hyphen-separated.
  const slug = countryName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return [{ value: slug, label: `All of ${countryName}` }];
}
