-- ============================================================================
-- BULK IMPORT: barbershops cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: Barbershop industry benchmarks 2024 (Booksy, Bookedin).
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.14),
  'payroll_total',          ROUND(rev_p50 * 0.42),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.06),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.03),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Barbershop industry benchmarks 2024 (Booksy, Bookedin). Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'barbershops'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 2000
      WHEN 'CH' THEN 2800
      WHEN 'NO' THEN 2600
      WHEN 'JP' THEN 2600
      WHEN 'SG' THEN 2400
      WHEN 'AU' THEN 2500
      WHEN 'GB' THEN 2400
      WHEN 'DE' THEN 2300
      WHEN 'FR' THEN 2200
      WHEN 'NL' THEN 2300
      WHEN 'SE' THEN 2400
      WHEN 'CA' THEN 2100
      WHEN 'AT' THEN 2200
      WHEN 'DK' THEN 2400
      WHEN 'FI' THEN 2300
      WHEN 'BE' THEN 2300
      WHEN 'IE' THEN 2200
      WHEN 'IL' THEN 2000
      WHEN 'AE' THEN 1900
      WHEN 'KR' THEN 1900
      WHEN 'IT' THEN 1800
      WHEN 'ES' THEN 1700
      WHEN 'NZ' THEN 2200
      WHEN 'PT' THEN 1400
      WHEN 'GR' THEN 1300
      WHEN 'CZ' THEN 1200
      WHEN 'PL' THEN 1100
      WHEN 'HU' THEN 1100
      WHEN 'CL' THEN 1100
      WHEN 'CN' THEN 1100
      WHEN 'MY' THEN 1000
      WHEN 'MX' THEN 1000
      WHEN 'AR' THEN 900
      WHEN 'BR' THEN 900
      WHEN 'ZA' THEN 900
      WHEN 'TH' THEN 900
      WHEN 'TR' THEN 800
      WHEN 'CO' THEN 800
      WHEN 'PE' THEN 800
      WHEN 'PH' THEN 800
      WHEN 'MA' THEN 700
      WHEN 'IN' THEN 600
      WHEN 'ID' THEN 600
      WHEN 'VN' THEN 600
      WHEN 'EG' THEN 600
      WHEN 'KE' THEN 600
      WHEN 'NG' THEN 500
      WHEN 'PK' THEN 500
      WHEN 'BD' THEN 500
      ELSE 1000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 45000
      WHEN 'CH' THEN 63000
      WHEN 'NO' THEN 58500
      WHEN 'JP' THEN 58500
      WHEN 'SG' THEN 54000
      WHEN 'AU' THEN 56250
      WHEN 'GB' THEN 54000
      WHEN 'DE' THEN 51750
      WHEN 'FR' THEN 49500
      WHEN 'NL' THEN 51750
      WHEN 'SE' THEN 54000
      WHEN 'CA' THEN 47250
      WHEN 'AT' THEN 49500
      WHEN 'DK' THEN 54000
      WHEN 'FI' THEN 51750
      WHEN 'BE' THEN 51750
      WHEN 'IE' THEN 49500
      WHEN 'IL' THEN 45000
      WHEN 'AE' THEN 42750
      WHEN 'KR' THEN 42750
      WHEN 'IT' THEN 40500
      WHEN 'ES' THEN 38250
      WHEN 'NZ' THEN 49500
      WHEN 'PT' THEN 31500
      WHEN 'GR' THEN 29250
      WHEN 'CZ' THEN 27000
      WHEN 'PL' THEN 24750
      WHEN 'HU' THEN 24750
      WHEN 'CL' THEN 24750
      WHEN 'CN' THEN 24750
      WHEN 'MY' THEN 22500
      WHEN 'MX' THEN 22500
      WHEN 'AR' THEN 20250
      WHEN 'BR' THEN 20250
      WHEN 'ZA' THEN 20250
      WHEN 'TH' THEN 20250
      WHEN 'TR' THEN 18000
      WHEN 'CO' THEN 18000
      WHEN 'PE' THEN 18000
      WHEN 'PH' THEN 18000
      WHEN 'MA' THEN 15750
      WHEN 'IN' THEN 13500
      WHEN 'ID' THEN 13500
      WHEN 'VN' THEN 13500
      WHEN 'EG' THEN 13500
      WHEN 'KE' THEN 13500
      WHEN 'NG' THEN 11250
      WHEN 'PK' THEN 11250
      WHEN 'BD' THEN 11250
      ELSE 22500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 18750
      WHEN 'CH' THEN 26250
      WHEN 'NO' THEN 24375
      WHEN 'JP' THEN 24375
      WHEN 'SG' THEN 22500
      WHEN 'AU' THEN 23438
      WHEN 'GB' THEN 22500
      WHEN 'DE' THEN 21563
      WHEN 'FR' THEN 20625
      WHEN 'NL' THEN 21563
      WHEN 'SE' THEN 22500
      WHEN 'CA' THEN 19688
      WHEN 'AT' THEN 20625
      WHEN 'DK' THEN 22500
      WHEN 'FI' THEN 21563
      WHEN 'BE' THEN 21563
      WHEN 'IE' THEN 20625
      WHEN 'IL' THEN 18750
      WHEN 'AE' THEN 17813
      WHEN 'KR' THEN 17813
      WHEN 'IT' THEN 16875
      WHEN 'ES' THEN 15938
      WHEN 'NZ' THEN 20625
      WHEN 'PT' THEN 13125
      WHEN 'GR' THEN 12188
      WHEN 'CZ' THEN 11250
      WHEN 'PL' THEN 10313
      WHEN 'HU' THEN 10313
      WHEN 'CL' THEN 10313
      WHEN 'CN' THEN 10313
      WHEN 'MY' THEN 9375
      WHEN 'MX' THEN 9375
      WHEN 'AR' THEN 8438
      WHEN 'BR' THEN 8438
      WHEN 'ZA' THEN 8438
      WHEN 'TH' THEN 8438
      WHEN 'TR' THEN 7500
      WHEN 'CO' THEN 7500
      WHEN 'PE' THEN 7500
      WHEN 'PH' THEN 7500
      WHEN 'MA' THEN 6563
      WHEN 'IN' THEN 5625
      WHEN 'ID' THEN 5625
      WHEN 'VN' THEN 5625
      WHEN 'EG' THEN 5625
      WHEN 'KE' THEN 5625
      WHEN 'NG' THEN 4688
      WHEN 'PK' THEN 4688
      WHEN 'BD' THEN 4688
      ELSE 9375
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 4500
      WHEN 'CH' THEN 6300
      WHEN 'NO' THEN 5850
      WHEN 'JP' THEN 5850
      WHEN 'SG' THEN 5400
      WHEN 'AU' THEN 5625
      WHEN 'GB' THEN 5400
      WHEN 'DE' THEN 5175
      WHEN 'FR' THEN 4950
      WHEN 'NL' THEN 5175
      WHEN 'SE' THEN 5400
      WHEN 'CA' THEN 4725
      WHEN 'AT' THEN 4950
      WHEN 'DK' THEN 5400
      WHEN 'FI' THEN 5175
      WHEN 'BE' THEN 5175
      WHEN 'IE' THEN 4950
      WHEN 'IL' THEN 4500
      WHEN 'AE' THEN 4275
      WHEN 'KR' THEN 4275
      WHEN 'IT' THEN 4050
      WHEN 'ES' THEN 3825
      WHEN 'NZ' THEN 4950
      WHEN 'PT' THEN 3150
      WHEN 'GR' THEN 2925
      WHEN 'CZ' THEN 2700
      WHEN 'PL' THEN 2475
      WHEN 'HU' THEN 2475
      WHEN 'CL' THEN 2475
      WHEN 'CN' THEN 2475
      WHEN 'MY' THEN 2250
      WHEN 'MX' THEN 2250
      WHEN 'AR' THEN 2025
      WHEN 'BR' THEN 2025
      WHEN 'ZA' THEN 2025
      WHEN 'TH' THEN 2025
      WHEN 'TR' THEN 1800
      WHEN 'CO' THEN 1800
      WHEN 'PE' THEN 1800
      WHEN 'PH' THEN 1800
      WHEN 'MA' THEN 1575
      WHEN 'IN' THEN 1350
      WHEN 'ID' THEN 1350
      WHEN 'VN' THEN 1350
      WHEN 'EG' THEN 1350
      WHEN 'KE' THEN 1350
      WHEN 'NG' THEN 1125
      WHEN 'PK' THEN 1125
      WHEN 'BD' THEN 1125
      ELSE 2250
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 75000
      WHEN 'CH' THEN 105000
      WHEN 'NO' THEN 97500
      WHEN 'JP' THEN 97500
      WHEN 'SG' THEN 90000
      WHEN 'AU' THEN 93750
      WHEN 'GB' THEN 90000
      WHEN 'DE' THEN 86250
      WHEN 'FR' THEN 82500
      WHEN 'NL' THEN 86250
      WHEN 'SE' THEN 90000
      WHEN 'CA' THEN 78750
      WHEN 'AT' THEN 82500
      WHEN 'DK' THEN 90000
      WHEN 'FI' THEN 86250
      WHEN 'BE' THEN 86250
      WHEN 'IE' THEN 82500
      WHEN 'IL' THEN 75000
      WHEN 'AE' THEN 71250
      WHEN 'KR' THEN 71250
      WHEN 'IT' THEN 67500
      WHEN 'ES' THEN 63750
      WHEN 'NZ' THEN 82500
      WHEN 'PT' THEN 52500
      WHEN 'GR' THEN 48750
      WHEN 'CZ' THEN 45000
      WHEN 'PL' THEN 41250
      WHEN 'HU' THEN 41250
      WHEN 'CL' THEN 41250
      WHEN 'CN' THEN 41250
      WHEN 'MY' THEN 37500
      WHEN 'MX' THEN 37500
      WHEN 'AR' THEN 33750
      WHEN 'BR' THEN 33750
      WHEN 'ZA' THEN 33750
      WHEN 'TH' THEN 33750
      WHEN 'TR' THEN 30000
      WHEN 'CO' THEN 30000
      WHEN 'PE' THEN 30000
      WHEN 'PH' THEN 30000
      WHEN 'MA' THEN 26250
      WHEN 'IN' THEN 22500
      WHEN 'ID' THEN 22500
      WHEN 'VN' THEN 22500
      WHEN 'EG' THEN 22500
      WHEN 'KE' THEN 22500
      WHEN 'NG' THEN 18750
      WHEN 'PK' THEN 18750
      WHEN 'BD' THEN 18750
      ELSE 37500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'barbershops'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 812111)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.14),
  'payroll_total',          ROUND(rev_p50 * 0.42),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.06),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.03),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Barbershop industry benchmarks 2024 (Booksy, Bookedin). US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('812111')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 2000
      WHEN 'CH' THEN 2800
      WHEN 'NO' THEN 2600
      WHEN 'JP' THEN 2600
      WHEN 'SG' THEN 2400
      WHEN 'AU' THEN 2500
      WHEN 'GB' THEN 2400
      WHEN 'DE' THEN 2300
      WHEN 'FR' THEN 2200
      WHEN 'NL' THEN 2300
      WHEN 'SE' THEN 2400
      WHEN 'CA' THEN 2100
      WHEN 'AT' THEN 2200
      WHEN 'DK' THEN 2400
      WHEN 'FI' THEN 2300
      WHEN 'BE' THEN 2300
      WHEN 'IE' THEN 2200
      WHEN 'IL' THEN 2000
      WHEN 'AE' THEN 1900
      WHEN 'KR' THEN 1900
      WHEN 'IT' THEN 1800
      WHEN 'ES' THEN 1700
      WHEN 'NZ' THEN 2200
      WHEN 'PT' THEN 1400
      WHEN 'GR' THEN 1300
      WHEN 'CZ' THEN 1200
      WHEN 'PL' THEN 1100
      WHEN 'HU' THEN 1100
      WHEN 'CL' THEN 1100
      WHEN 'CN' THEN 1100
      WHEN 'MY' THEN 1000
      WHEN 'MX' THEN 1000
      WHEN 'AR' THEN 900
      WHEN 'BR' THEN 900
      WHEN 'ZA' THEN 900
      WHEN 'TH' THEN 900
      WHEN 'TR' THEN 800
      WHEN 'CO' THEN 800
      WHEN 'PE' THEN 800
      WHEN 'PH' THEN 800
      WHEN 'MA' THEN 700
      WHEN 'IN' THEN 600
      WHEN 'ID' THEN 600
      WHEN 'VN' THEN 600
      WHEN 'EG' THEN 600
      WHEN 'KE' THEN 600
      WHEN 'NG' THEN 500
      WHEN 'PK' THEN 500
      WHEN 'BD' THEN 500
      ELSE 1000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 45000
      WHEN 'CH' THEN 63000
      WHEN 'NO' THEN 58500
      WHEN 'JP' THEN 58500
      WHEN 'SG' THEN 54000
      WHEN 'AU' THEN 56250
      WHEN 'GB' THEN 54000
      WHEN 'DE' THEN 51750
      WHEN 'FR' THEN 49500
      WHEN 'NL' THEN 51750
      WHEN 'SE' THEN 54000
      WHEN 'CA' THEN 47250
      WHEN 'AT' THEN 49500
      WHEN 'DK' THEN 54000
      WHEN 'FI' THEN 51750
      WHEN 'BE' THEN 51750
      WHEN 'IE' THEN 49500
      WHEN 'IL' THEN 45000
      WHEN 'AE' THEN 42750
      WHEN 'KR' THEN 42750
      WHEN 'IT' THEN 40500
      WHEN 'ES' THEN 38250
      WHEN 'NZ' THEN 49500
      WHEN 'PT' THEN 31500
      WHEN 'GR' THEN 29250
      WHEN 'CZ' THEN 27000
      WHEN 'PL' THEN 24750
      WHEN 'HU' THEN 24750
      WHEN 'CL' THEN 24750
      WHEN 'CN' THEN 24750
      WHEN 'MY' THEN 22500
      WHEN 'MX' THEN 22500
      WHEN 'AR' THEN 20250
      WHEN 'BR' THEN 20250
      WHEN 'ZA' THEN 20250
      WHEN 'TH' THEN 20250
      WHEN 'TR' THEN 18000
      WHEN 'CO' THEN 18000
      WHEN 'PE' THEN 18000
      WHEN 'PH' THEN 18000
      WHEN 'MA' THEN 15750
      WHEN 'IN' THEN 13500
      WHEN 'ID' THEN 13500
      WHEN 'VN' THEN 13500
      WHEN 'EG' THEN 13500
      WHEN 'KE' THEN 13500
      WHEN 'NG' THEN 11250
      WHEN 'PK' THEN 11250
      WHEN 'BD' THEN 11250
      ELSE 22500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 18750
      WHEN 'CH' THEN 26250
      WHEN 'NO' THEN 24375
      WHEN 'JP' THEN 24375
      WHEN 'SG' THEN 22500
      WHEN 'AU' THEN 23438
      WHEN 'GB' THEN 22500
      WHEN 'DE' THEN 21563
      WHEN 'FR' THEN 20625
      WHEN 'NL' THEN 21563
      WHEN 'SE' THEN 22500
      WHEN 'CA' THEN 19688
      WHEN 'AT' THEN 20625
      WHEN 'DK' THEN 22500
      WHEN 'FI' THEN 21563
      WHEN 'BE' THEN 21563
      WHEN 'IE' THEN 20625
      WHEN 'IL' THEN 18750
      WHEN 'AE' THEN 17813
      WHEN 'KR' THEN 17813
      WHEN 'IT' THEN 16875
      WHEN 'ES' THEN 15938
      WHEN 'NZ' THEN 20625
      WHEN 'PT' THEN 13125
      WHEN 'GR' THEN 12188
      WHEN 'CZ' THEN 11250
      WHEN 'PL' THEN 10313
      WHEN 'HU' THEN 10313
      WHEN 'CL' THEN 10313
      WHEN 'CN' THEN 10313
      WHEN 'MY' THEN 9375
      WHEN 'MX' THEN 9375
      WHEN 'AR' THEN 8438
      WHEN 'BR' THEN 8438
      WHEN 'ZA' THEN 8438
      WHEN 'TH' THEN 8438
      WHEN 'TR' THEN 7500
      WHEN 'CO' THEN 7500
      WHEN 'PE' THEN 7500
      WHEN 'PH' THEN 7500
      WHEN 'MA' THEN 6563
      WHEN 'IN' THEN 5625
      WHEN 'ID' THEN 5625
      WHEN 'VN' THEN 5625
      WHEN 'EG' THEN 5625
      WHEN 'KE' THEN 5625
      WHEN 'NG' THEN 4688
      WHEN 'PK' THEN 4688
      WHEN 'BD' THEN 4688
      ELSE 9375
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 4500
      WHEN 'CH' THEN 6300
      WHEN 'NO' THEN 5850
      WHEN 'JP' THEN 5850
      WHEN 'SG' THEN 5400
      WHEN 'AU' THEN 5625
      WHEN 'GB' THEN 5400
      WHEN 'DE' THEN 5175
      WHEN 'FR' THEN 4950
      WHEN 'NL' THEN 5175
      WHEN 'SE' THEN 5400
      WHEN 'CA' THEN 4725
      WHEN 'AT' THEN 4950
      WHEN 'DK' THEN 5400
      WHEN 'FI' THEN 5175
      WHEN 'BE' THEN 5175
      WHEN 'IE' THEN 4950
      WHEN 'IL' THEN 4500
      WHEN 'AE' THEN 4275
      WHEN 'KR' THEN 4275
      WHEN 'IT' THEN 4050
      WHEN 'ES' THEN 3825
      WHEN 'NZ' THEN 4950
      WHEN 'PT' THEN 3150
      WHEN 'GR' THEN 2925
      WHEN 'CZ' THEN 2700
      WHEN 'PL' THEN 2475
      WHEN 'HU' THEN 2475
      WHEN 'CL' THEN 2475
      WHEN 'CN' THEN 2475
      WHEN 'MY' THEN 2250
      WHEN 'MX' THEN 2250
      WHEN 'AR' THEN 2025
      WHEN 'BR' THEN 2025
      WHEN 'ZA' THEN 2025
      WHEN 'TH' THEN 2025
      WHEN 'TR' THEN 1800
      WHEN 'CO' THEN 1800
      WHEN 'PE' THEN 1800
      WHEN 'PH' THEN 1800
      WHEN 'MA' THEN 1575
      WHEN 'IN' THEN 1350
      WHEN 'ID' THEN 1350
      WHEN 'VN' THEN 1350
      WHEN 'EG' THEN 1350
      WHEN 'KE' THEN 1350
      WHEN 'NG' THEN 1125
      WHEN 'PK' THEN 1125
      WHEN 'BD' THEN 1125
      ELSE 2250
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 75000
      WHEN 'CH' THEN 105000
      WHEN 'NO' THEN 97500
      WHEN 'JP' THEN 97500
      WHEN 'SG' THEN 90000
      WHEN 'AU' THEN 93750
      WHEN 'GB' THEN 90000
      WHEN 'DE' THEN 86250
      WHEN 'FR' THEN 82500
      WHEN 'NL' THEN 86250
      WHEN 'SE' THEN 90000
      WHEN 'CA' THEN 78750
      WHEN 'AT' THEN 82500
      WHEN 'DK' THEN 90000
      WHEN 'FI' THEN 86250
      WHEN 'BE' THEN 86250
      WHEN 'IE' THEN 82500
      WHEN 'IL' THEN 75000
      WHEN 'AE' THEN 71250
      WHEN 'KR' THEN 71250
      WHEN 'IT' THEN 67500
      WHEN 'ES' THEN 63750
      WHEN 'NZ' THEN 82500
      WHEN 'PT' THEN 52500
      WHEN 'GR' THEN 48750
      WHEN 'CZ' THEN 45000
      WHEN 'PL' THEN 41250
      WHEN 'HU' THEN 41250
      WHEN 'CL' THEN 41250
      WHEN 'CN' THEN 41250
      WHEN 'MY' THEN 37500
      WHEN 'MX' THEN 37500
      WHEN 'AR' THEN 33750
      WHEN 'BR' THEN 33750
      WHEN 'ZA' THEN 33750
      WHEN 'TH' THEN 33750
      WHEN 'TR' THEN 30000
      WHEN 'CO' THEN 30000
      WHEN 'PE' THEN 30000
      WHEN 'PH' THEN 30000
      WHEN 'MA' THEN 26250
      WHEN 'IN' THEN 22500
      WHEN 'ID' THEN 22500
      WHEN 'VN' THEN 22500
      WHEN 'EG' THEN 22500
      WHEN 'KE' THEN 22500
      WHEN 'NG' THEN 18750
      WHEN 'PK' THEN 18750
      WHEN 'BD' THEN 18750
      ELSE 37500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('812111')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.14),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.42),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.06),
  'utilities',              ROUND(predicted_rev_per_firm * 0.03),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.02),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.03),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.02),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Barbershop industry benchmarks 2024 (Booksy, Bookedin). Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'barbershops'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
