-- ============================================================================
-- BULK IMPORT: cafes_coffee cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: Toast POS Coffee Report 2024 + Specialty Coffee Association ratios.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.12),
  'payroll_total',          ROUND(rev_p50 * 0.35),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.29),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.05),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Toast POS Coffee Report 2024 + Specialty Coffee Association ratios. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'cafes_coffee'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 3000
      WHEN 'CH' THEN 4200
      WHEN 'NO' THEN 3900
      WHEN 'JP' THEN 3900
      WHEN 'SG' THEN 3600
      WHEN 'AU' THEN 3750
      WHEN 'GB' THEN 3600
      WHEN 'DE' THEN 3450
      WHEN 'FR' THEN 3300
      WHEN 'NL' THEN 3450
      WHEN 'SE' THEN 3600
      WHEN 'CA' THEN 3150
      WHEN 'AT' THEN 3300
      WHEN 'DK' THEN 3600
      WHEN 'FI' THEN 3450
      WHEN 'BE' THEN 3450
      WHEN 'IE' THEN 3300
      WHEN 'IL' THEN 3000
      WHEN 'AE' THEN 2850
      WHEN 'KR' THEN 2850
      WHEN 'IT' THEN 2700
      WHEN 'ES' THEN 2550
      WHEN 'NZ' THEN 3300
      WHEN 'PT' THEN 2100
      WHEN 'GR' THEN 1950
      WHEN 'CZ' THEN 1800
      WHEN 'PL' THEN 1650
      WHEN 'HU' THEN 1650
      WHEN 'CL' THEN 1650
      WHEN 'CN' THEN 1650
      WHEN 'MY' THEN 1500
      WHEN 'MX' THEN 1500
      WHEN 'AR' THEN 1350
      WHEN 'BR' THEN 1350
      WHEN 'ZA' THEN 1350
      WHEN 'TH' THEN 1350
      WHEN 'TR' THEN 1200
      WHEN 'CO' THEN 1200
      WHEN 'PE' THEN 1200
      WHEN 'PH' THEN 1200
      WHEN 'MA' THEN 1050
      WHEN 'IN' THEN 900
      WHEN 'ID' THEN 900
      WHEN 'VN' THEN 900
      WHEN 'EG' THEN 900
      WHEN 'KE' THEN 900
      WHEN 'NG' THEN 750
      WHEN 'PK' THEN 750
      WHEN 'BD' THEN 750
      ELSE 1500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 105000
      WHEN 'CH' THEN 147000
      WHEN 'NO' THEN 136500
      WHEN 'JP' THEN 136500
      WHEN 'SG' THEN 126000
      WHEN 'AU' THEN 131250
      WHEN 'GB' THEN 126000
      WHEN 'DE' THEN 120750
      WHEN 'FR' THEN 115500
      WHEN 'NL' THEN 120750
      WHEN 'SE' THEN 126000
      WHEN 'CA' THEN 110250
      WHEN 'AT' THEN 115500
      WHEN 'DK' THEN 126000
      WHEN 'FI' THEN 120750
      WHEN 'BE' THEN 120750
      WHEN 'IE' THEN 115500
      WHEN 'IL' THEN 105000
      WHEN 'AE' THEN 99750
      WHEN 'KR' THEN 99750
      WHEN 'IT' THEN 94500
      WHEN 'ES' THEN 89250
      WHEN 'NZ' THEN 115500
      WHEN 'PT' THEN 73500
      WHEN 'GR' THEN 68250
      WHEN 'CZ' THEN 63000
      WHEN 'PL' THEN 57750
      WHEN 'HU' THEN 57750
      WHEN 'CL' THEN 57750
      WHEN 'CN' THEN 57750
      WHEN 'MY' THEN 52500
      WHEN 'MX' THEN 52500
      WHEN 'AR' THEN 47250
      WHEN 'BR' THEN 47250
      WHEN 'ZA' THEN 47250
      WHEN 'TH' THEN 47250
      WHEN 'TR' THEN 42000
      WHEN 'CO' THEN 42000
      WHEN 'PE' THEN 42000
      WHEN 'PH' THEN 42000
      WHEN 'MA' THEN 36750
      WHEN 'IN' THEN 31500
      WHEN 'ID' THEN 31500
      WHEN 'VN' THEN 31500
      WHEN 'EG' THEN 31500
      WHEN 'KE' THEN 31500
      WHEN 'NG' THEN 26250
      WHEN 'PK' THEN 26250
      WHEN 'BD' THEN 26250
      ELSE 52500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 43750
      WHEN 'CH' THEN 61250
      WHEN 'NO' THEN 56875
      WHEN 'JP' THEN 56875
      WHEN 'SG' THEN 52500
      WHEN 'AU' THEN 54688
      WHEN 'GB' THEN 52500
      WHEN 'DE' THEN 50312
      WHEN 'FR' THEN 48125
      WHEN 'NL' THEN 50312
      WHEN 'SE' THEN 52500
      WHEN 'CA' THEN 45938
      WHEN 'AT' THEN 48125
      WHEN 'DK' THEN 52500
      WHEN 'FI' THEN 50312
      WHEN 'BE' THEN 50312
      WHEN 'IE' THEN 48125
      WHEN 'IL' THEN 43750
      WHEN 'AE' THEN 41563
      WHEN 'KR' THEN 41563
      WHEN 'IT' THEN 39375
      WHEN 'ES' THEN 37188
      WHEN 'NZ' THEN 48125
      WHEN 'PT' THEN 30625
      WHEN 'GR' THEN 28438
      WHEN 'CZ' THEN 26250
      WHEN 'PL' THEN 24063
      WHEN 'HU' THEN 24063
      WHEN 'CL' THEN 24063
      WHEN 'CN' THEN 24063
      WHEN 'MY' THEN 21875
      WHEN 'MX' THEN 21875
      WHEN 'AR' THEN 19688
      WHEN 'BR' THEN 19688
      WHEN 'ZA' THEN 19688
      WHEN 'TH' THEN 19688
      WHEN 'TR' THEN 17500
      WHEN 'CO' THEN 17500
      WHEN 'PE' THEN 17500
      WHEN 'PH' THEN 17500
      WHEN 'MA' THEN 15312
      WHEN 'IN' THEN 13125
      WHEN 'ID' THEN 13125
      WHEN 'VN' THEN 13125
      WHEN 'EG' THEN 13125
      WHEN 'KE' THEN 13125
      WHEN 'NG' THEN 10938
      WHEN 'PK' THEN 10938
      WHEN 'BD' THEN 10938
      ELSE 21875
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 10500
      WHEN 'CH' THEN 14700
      WHEN 'NO' THEN 13650
      WHEN 'JP' THEN 13650
      WHEN 'SG' THEN 12600
      WHEN 'AU' THEN 13125
      WHEN 'GB' THEN 12600
      WHEN 'DE' THEN 12075
      WHEN 'FR' THEN 11550
      WHEN 'NL' THEN 12075
      WHEN 'SE' THEN 12600
      WHEN 'CA' THEN 11025
      WHEN 'AT' THEN 11550
      WHEN 'DK' THEN 12600
      WHEN 'FI' THEN 12075
      WHEN 'BE' THEN 12075
      WHEN 'IE' THEN 11550
      WHEN 'IL' THEN 10500
      WHEN 'AE' THEN 9975
      WHEN 'KR' THEN 9975
      WHEN 'IT' THEN 9450
      WHEN 'ES' THEN 8925
      WHEN 'NZ' THEN 11550
      WHEN 'PT' THEN 7350
      WHEN 'GR' THEN 6825
      WHEN 'CZ' THEN 6300
      WHEN 'PL' THEN 5775
      WHEN 'HU' THEN 5775
      WHEN 'CL' THEN 5775
      WHEN 'CN' THEN 5775
      WHEN 'MY' THEN 5250
      WHEN 'MX' THEN 5250
      WHEN 'AR' THEN 4725
      WHEN 'BR' THEN 4725
      WHEN 'ZA' THEN 4725
      WHEN 'TH' THEN 4725
      WHEN 'TR' THEN 4200
      WHEN 'CO' THEN 4200
      WHEN 'PE' THEN 4200
      WHEN 'PH' THEN 4200
      WHEN 'MA' THEN 3675
      WHEN 'IN' THEN 3150
      WHEN 'ID' THEN 3150
      WHEN 'VN' THEN 3150
      WHEN 'EG' THEN 3150
      WHEN 'KE' THEN 3150
      WHEN 'NG' THEN 2625
      WHEN 'PK' THEN 2625
      WHEN 'BD' THEN 2625
      ELSE 5250
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 175000
      WHEN 'CH' THEN 245000
      WHEN 'NO' THEN 227500
      WHEN 'JP' THEN 227500
      WHEN 'SG' THEN 210000
      WHEN 'AU' THEN 218750
      WHEN 'GB' THEN 210000
      WHEN 'DE' THEN 201250
      WHEN 'FR' THEN 192500
      WHEN 'NL' THEN 201250
      WHEN 'SE' THEN 210000
      WHEN 'CA' THEN 183750
      WHEN 'AT' THEN 192500
      WHEN 'DK' THEN 210000
      WHEN 'FI' THEN 201250
      WHEN 'BE' THEN 201250
      WHEN 'IE' THEN 192500
      WHEN 'IL' THEN 175000
      WHEN 'AE' THEN 166250
      WHEN 'KR' THEN 166250
      WHEN 'IT' THEN 157500
      WHEN 'ES' THEN 148750
      WHEN 'NZ' THEN 192500
      WHEN 'PT' THEN 122500
      WHEN 'GR' THEN 113750
      WHEN 'CZ' THEN 105000
      WHEN 'PL' THEN 96250
      WHEN 'HU' THEN 96250
      WHEN 'CL' THEN 96250
      WHEN 'CN' THEN 96250
      WHEN 'MY' THEN 87500
      WHEN 'MX' THEN 87500
      WHEN 'AR' THEN 78750
      WHEN 'BR' THEN 78750
      WHEN 'ZA' THEN 78750
      WHEN 'TH' THEN 78750
      WHEN 'TR' THEN 70000
      WHEN 'CO' THEN 70000
      WHEN 'PE' THEN 70000
      WHEN 'PH' THEN 70000
      WHEN 'MA' THEN 61250
      WHEN 'IN' THEN 52500
      WHEN 'ID' THEN 52500
      WHEN 'VN' THEN 52500
      WHEN 'EG' THEN 52500
      WHEN 'KE' THEN 52500
      WHEN 'NG' THEN 43750
      WHEN 'PK' THEN 43750
      WHEN 'BD' THEN 43750
      ELSE 87500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'cafes_coffee'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 722515)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.12),
  'payroll_total',          ROUND(rev_p50 * 0.35),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.29),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.05),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Toast POS Coffee Report 2024 + Specialty Coffee Association ratios. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('722515')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 3000
      WHEN 'CH' THEN 4200
      WHEN 'NO' THEN 3900
      WHEN 'JP' THEN 3900
      WHEN 'SG' THEN 3600
      WHEN 'AU' THEN 3750
      WHEN 'GB' THEN 3600
      WHEN 'DE' THEN 3450
      WHEN 'FR' THEN 3300
      WHEN 'NL' THEN 3450
      WHEN 'SE' THEN 3600
      WHEN 'CA' THEN 3150
      WHEN 'AT' THEN 3300
      WHEN 'DK' THEN 3600
      WHEN 'FI' THEN 3450
      WHEN 'BE' THEN 3450
      WHEN 'IE' THEN 3300
      WHEN 'IL' THEN 3000
      WHEN 'AE' THEN 2850
      WHEN 'KR' THEN 2850
      WHEN 'IT' THEN 2700
      WHEN 'ES' THEN 2550
      WHEN 'NZ' THEN 3300
      WHEN 'PT' THEN 2100
      WHEN 'GR' THEN 1950
      WHEN 'CZ' THEN 1800
      WHEN 'PL' THEN 1650
      WHEN 'HU' THEN 1650
      WHEN 'CL' THEN 1650
      WHEN 'CN' THEN 1650
      WHEN 'MY' THEN 1500
      WHEN 'MX' THEN 1500
      WHEN 'AR' THEN 1350
      WHEN 'BR' THEN 1350
      WHEN 'ZA' THEN 1350
      WHEN 'TH' THEN 1350
      WHEN 'TR' THEN 1200
      WHEN 'CO' THEN 1200
      WHEN 'PE' THEN 1200
      WHEN 'PH' THEN 1200
      WHEN 'MA' THEN 1050
      WHEN 'IN' THEN 900
      WHEN 'ID' THEN 900
      WHEN 'VN' THEN 900
      WHEN 'EG' THEN 900
      WHEN 'KE' THEN 900
      WHEN 'NG' THEN 750
      WHEN 'PK' THEN 750
      WHEN 'BD' THEN 750
      ELSE 1500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 105000
      WHEN 'CH' THEN 147000
      WHEN 'NO' THEN 136500
      WHEN 'JP' THEN 136500
      WHEN 'SG' THEN 126000
      WHEN 'AU' THEN 131250
      WHEN 'GB' THEN 126000
      WHEN 'DE' THEN 120750
      WHEN 'FR' THEN 115500
      WHEN 'NL' THEN 120750
      WHEN 'SE' THEN 126000
      WHEN 'CA' THEN 110250
      WHEN 'AT' THEN 115500
      WHEN 'DK' THEN 126000
      WHEN 'FI' THEN 120750
      WHEN 'BE' THEN 120750
      WHEN 'IE' THEN 115500
      WHEN 'IL' THEN 105000
      WHEN 'AE' THEN 99750
      WHEN 'KR' THEN 99750
      WHEN 'IT' THEN 94500
      WHEN 'ES' THEN 89250
      WHEN 'NZ' THEN 115500
      WHEN 'PT' THEN 73500
      WHEN 'GR' THEN 68250
      WHEN 'CZ' THEN 63000
      WHEN 'PL' THEN 57750
      WHEN 'HU' THEN 57750
      WHEN 'CL' THEN 57750
      WHEN 'CN' THEN 57750
      WHEN 'MY' THEN 52500
      WHEN 'MX' THEN 52500
      WHEN 'AR' THEN 47250
      WHEN 'BR' THEN 47250
      WHEN 'ZA' THEN 47250
      WHEN 'TH' THEN 47250
      WHEN 'TR' THEN 42000
      WHEN 'CO' THEN 42000
      WHEN 'PE' THEN 42000
      WHEN 'PH' THEN 42000
      WHEN 'MA' THEN 36750
      WHEN 'IN' THEN 31500
      WHEN 'ID' THEN 31500
      WHEN 'VN' THEN 31500
      WHEN 'EG' THEN 31500
      WHEN 'KE' THEN 31500
      WHEN 'NG' THEN 26250
      WHEN 'PK' THEN 26250
      WHEN 'BD' THEN 26250
      ELSE 52500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 43750
      WHEN 'CH' THEN 61250
      WHEN 'NO' THEN 56875
      WHEN 'JP' THEN 56875
      WHEN 'SG' THEN 52500
      WHEN 'AU' THEN 54688
      WHEN 'GB' THEN 52500
      WHEN 'DE' THEN 50312
      WHEN 'FR' THEN 48125
      WHEN 'NL' THEN 50312
      WHEN 'SE' THEN 52500
      WHEN 'CA' THEN 45938
      WHEN 'AT' THEN 48125
      WHEN 'DK' THEN 52500
      WHEN 'FI' THEN 50312
      WHEN 'BE' THEN 50312
      WHEN 'IE' THEN 48125
      WHEN 'IL' THEN 43750
      WHEN 'AE' THEN 41563
      WHEN 'KR' THEN 41563
      WHEN 'IT' THEN 39375
      WHEN 'ES' THEN 37188
      WHEN 'NZ' THEN 48125
      WHEN 'PT' THEN 30625
      WHEN 'GR' THEN 28438
      WHEN 'CZ' THEN 26250
      WHEN 'PL' THEN 24063
      WHEN 'HU' THEN 24063
      WHEN 'CL' THEN 24063
      WHEN 'CN' THEN 24063
      WHEN 'MY' THEN 21875
      WHEN 'MX' THEN 21875
      WHEN 'AR' THEN 19688
      WHEN 'BR' THEN 19688
      WHEN 'ZA' THEN 19688
      WHEN 'TH' THEN 19688
      WHEN 'TR' THEN 17500
      WHEN 'CO' THEN 17500
      WHEN 'PE' THEN 17500
      WHEN 'PH' THEN 17500
      WHEN 'MA' THEN 15312
      WHEN 'IN' THEN 13125
      WHEN 'ID' THEN 13125
      WHEN 'VN' THEN 13125
      WHEN 'EG' THEN 13125
      WHEN 'KE' THEN 13125
      WHEN 'NG' THEN 10938
      WHEN 'PK' THEN 10938
      WHEN 'BD' THEN 10938
      ELSE 21875
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 10500
      WHEN 'CH' THEN 14700
      WHEN 'NO' THEN 13650
      WHEN 'JP' THEN 13650
      WHEN 'SG' THEN 12600
      WHEN 'AU' THEN 13125
      WHEN 'GB' THEN 12600
      WHEN 'DE' THEN 12075
      WHEN 'FR' THEN 11550
      WHEN 'NL' THEN 12075
      WHEN 'SE' THEN 12600
      WHEN 'CA' THEN 11025
      WHEN 'AT' THEN 11550
      WHEN 'DK' THEN 12600
      WHEN 'FI' THEN 12075
      WHEN 'BE' THEN 12075
      WHEN 'IE' THEN 11550
      WHEN 'IL' THEN 10500
      WHEN 'AE' THEN 9975
      WHEN 'KR' THEN 9975
      WHEN 'IT' THEN 9450
      WHEN 'ES' THEN 8925
      WHEN 'NZ' THEN 11550
      WHEN 'PT' THEN 7350
      WHEN 'GR' THEN 6825
      WHEN 'CZ' THEN 6300
      WHEN 'PL' THEN 5775
      WHEN 'HU' THEN 5775
      WHEN 'CL' THEN 5775
      WHEN 'CN' THEN 5775
      WHEN 'MY' THEN 5250
      WHEN 'MX' THEN 5250
      WHEN 'AR' THEN 4725
      WHEN 'BR' THEN 4725
      WHEN 'ZA' THEN 4725
      WHEN 'TH' THEN 4725
      WHEN 'TR' THEN 4200
      WHEN 'CO' THEN 4200
      WHEN 'PE' THEN 4200
      WHEN 'PH' THEN 4200
      WHEN 'MA' THEN 3675
      WHEN 'IN' THEN 3150
      WHEN 'ID' THEN 3150
      WHEN 'VN' THEN 3150
      WHEN 'EG' THEN 3150
      WHEN 'KE' THEN 3150
      WHEN 'NG' THEN 2625
      WHEN 'PK' THEN 2625
      WHEN 'BD' THEN 2625
      ELSE 5250
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 175000
      WHEN 'CH' THEN 245000
      WHEN 'NO' THEN 227500
      WHEN 'JP' THEN 227500
      WHEN 'SG' THEN 210000
      WHEN 'AU' THEN 218750
      WHEN 'GB' THEN 210000
      WHEN 'DE' THEN 201250
      WHEN 'FR' THEN 192500
      WHEN 'NL' THEN 201250
      WHEN 'SE' THEN 210000
      WHEN 'CA' THEN 183750
      WHEN 'AT' THEN 192500
      WHEN 'DK' THEN 210000
      WHEN 'FI' THEN 201250
      WHEN 'BE' THEN 201250
      WHEN 'IE' THEN 192500
      WHEN 'IL' THEN 175000
      WHEN 'AE' THEN 166250
      WHEN 'KR' THEN 166250
      WHEN 'IT' THEN 157500
      WHEN 'ES' THEN 148750
      WHEN 'NZ' THEN 192500
      WHEN 'PT' THEN 122500
      WHEN 'GR' THEN 113750
      WHEN 'CZ' THEN 105000
      WHEN 'PL' THEN 96250
      WHEN 'HU' THEN 96250
      WHEN 'CL' THEN 96250
      WHEN 'CN' THEN 96250
      WHEN 'MY' THEN 87500
      WHEN 'MX' THEN 87500
      WHEN 'AR' THEN 78750
      WHEN 'BR' THEN 78750
      WHEN 'ZA' THEN 78750
      WHEN 'TH' THEN 78750
      WHEN 'TR' THEN 70000
      WHEN 'CO' THEN 70000
      WHEN 'PE' THEN 70000
      WHEN 'PH' THEN 70000
      WHEN 'MA' THEN 61250
      WHEN 'IN' THEN 52500
      WHEN 'ID' THEN 52500
      WHEN 'VN' THEN 52500
      WHEN 'EG' THEN 52500
      WHEN 'KE' THEN 52500
      WHEN 'NG' THEN 43750
      WHEN 'PK' THEN 43750
      WHEN 'BD' THEN 43750
      ELSE 87500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('722515')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.12),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.35),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.29),
  'utilities',              ROUND(predicted_rev_per_firm * 0.03),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.02),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.04),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.05),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Toast POS Coffee Report 2024 + Specialty Coffee Association ratios. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'cafes_coffee'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
