-- ============================================================================
-- BULK IMPORT: clothing_stores cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: Retail Owners Institute 2024 + NRF small retailer surveys.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.15),
  'payroll_total',          ROUND(rev_p50 * 0.16),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.5),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.02),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Retail Owners Institute 2024 + NRF small retailer surveys. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'clothing_stores'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 3000
      WHEN 'CH' THEN 4200
      WHEN 'NO' THEN 3900
      WHEN 'JP' THEN 3900
      WHEN 'SG' THEN 3600
      WHEN 'AU' THEN 3750
      WHEN 'GB' THEN 3600
      WHEN 'DE' THEN 3450
      WHEN 'FR' THEN 3300
      WHEN 'NL' THEN 3450
      WHEN 'SE' THEN 3600
      WHEN 'CA' THEN 3150
      WHEN 'AT' THEN 3300
      WHEN 'DK' THEN 3600
      WHEN 'FI' THEN 3450
      WHEN 'BE' THEN 3450
      WHEN 'IE' THEN 3300
      WHEN 'IL' THEN 3000
      WHEN 'AE' THEN 2850
      WHEN 'KR' THEN 2850
      WHEN 'IT' THEN 2700
      WHEN 'ES' THEN 2550
      WHEN 'NZ' THEN 3300
      WHEN 'PT' THEN 2100
      WHEN 'GR' THEN 1950
      WHEN 'CZ' THEN 1800
      WHEN 'PL' THEN 1650
      WHEN 'HU' THEN 1650
      WHEN 'CL' THEN 1650
      WHEN 'CN' THEN 1650
      WHEN 'MY' THEN 1500
      WHEN 'MX' THEN 1500
      WHEN 'AR' THEN 1350
      WHEN 'BR' THEN 1350
      WHEN 'ZA' THEN 1350
      WHEN 'TH' THEN 1350
      WHEN 'TR' THEN 1200
      WHEN 'CO' THEN 1200
      WHEN 'PE' THEN 1200
      WHEN 'PH' THEN 1200
      WHEN 'MA' THEN 1050
      WHEN 'IN' THEN 900
      WHEN 'ID' THEN 900
      WHEN 'VN' THEN 900
      WHEN 'EG' THEN 900
      WHEN 'KE' THEN 900
      WHEN 'NG' THEN 750
      WHEN 'PK' THEN 750
      WHEN 'BD' THEN 750
      ELSE 1500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 120000
      WHEN 'CH' THEN 168000
      WHEN 'NO' THEN 156000
      WHEN 'JP' THEN 156000
      WHEN 'SG' THEN 144000
      WHEN 'AU' THEN 150000
      WHEN 'GB' THEN 144000
      WHEN 'DE' THEN 138000
      WHEN 'FR' THEN 132000
      WHEN 'NL' THEN 138000
      WHEN 'SE' THEN 144000
      WHEN 'CA' THEN 126000
      WHEN 'AT' THEN 132000
      WHEN 'DK' THEN 144000
      WHEN 'FI' THEN 138000
      WHEN 'BE' THEN 138000
      WHEN 'IE' THEN 132000
      WHEN 'IL' THEN 120000
      WHEN 'AE' THEN 114000
      WHEN 'KR' THEN 114000
      WHEN 'IT' THEN 108000
      WHEN 'ES' THEN 102000
      WHEN 'NZ' THEN 132000
      WHEN 'PT' THEN 84000
      WHEN 'GR' THEN 78000
      WHEN 'CZ' THEN 72000
      WHEN 'PL' THEN 66000
      WHEN 'HU' THEN 66000
      WHEN 'CL' THEN 66000
      WHEN 'CN' THEN 66000
      WHEN 'MY' THEN 60000
      WHEN 'MX' THEN 60000
      WHEN 'AR' THEN 54000
      WHEN 'BR' THEN 54000
      WHEN 'ZA' THEN 54000
      WHEN 'TH' THEN 54000
      WHEN 'TR' THEN 48000
      WHEN 'CO' THEN 48000
      WHEN 'PE' THEN 48000
      WHEN 'PH' THEN 48000
      WHEN 'MA' THEN 42000
      WHEN 'IN' THEN 36000
      WHEN 'ID' THEN 36000
      WHEN 'VN' THEN 36000
      WHEN 'EG' THEN 36000
      WHEN 'KE' THEN 36000
      WHEN 'NG' THEN 30000
      WHEN 'PK' THEN 30000
      WHEN 'BD' THEN 30000
      ELSE 60000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 50000
      WHEN 'CH' THEN 70000
      WHEN 'NO' THEN 65000
      WHEN 'JP' THEN 65000
      WHEN 'SG' THEN 60000
      WHEN 'AU' THEN 62500
      WHEN 'GB' THEN 60000
      WHEN 'DE' THEN 57500
      WHEN 'FR' THEN 55000
      WHEN 'NL' THEN 57500
      WHEN 'SE' THEN 60000
      WHEN 'CA' THEN 52500
      WHEN 'AT' THEN 55000
      WHEN 'DK' THEN 60000
      WHEN 'FI' THEN 57500
      WHEN 'BE' THEN 57500
      WHEN 'IE' THEN 55000
      WHEN 'IL' THEN 50000
      WHEN 'AE' THEN 47500
      WHEN 'KR' THEN 47500
      WHEN 'IT' THEN 45000
      WHEN 'ES' THEN 42500
      WHEN 'NZ' THEN 55000
      WHEN 'PT' THEN 35000
      WHEN 'GR' THEN 32500
      WHEN 'CZ' THEN 30000
      WHEN 'PL' THEN 27500
      WHEN 'HU' THEN 27500
      WHEN 'CL' THEN 27500
      WHEN 'CN' THEN 27500
      WHEN 'MY' THEN 25000
      WHEN 'MX' THEN 25000
      WHEN 'AR' THEN 22500
      WHEN 'BR' THEN 22500
      WHEN 'ZA' THEN 22500
      WHEN 'TH' THEN 22500
      WHEN 'TR' THEN 20000
      WHEN 'CO' THEN 20000
      WHEN 'PE' THEN 20000
      WHEN 'PH' THEN 20000
      WHEN 'MA' THEN 17500
      WHEN 'IN' THEN 15000
      WHEN 'ID' THEN 15000
      WHEN 'VN' THEN 15000
      WHEN 'EG' THEN 15000
      WHEN 'KE' THEN 15000
      WHEN 'NG' THEN 12500
      WHEN 'PK' THEN 12500
      WHEN 'BD' THEN 12500
      ELSE 25000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 12000
      WHEN 'CH' THEN 16800
      WHEN 'NO' THEN 15600
      WHEN 'JP' THEN 15600
      WHEN 'SG' THEN 14400
      WHEN 'AU' THEN 15000
      WHEN 'GB' THEN 14400
      WHEN 'DE' THEN 13800
      WHEN 'FR' THEN 13200
      WHEN 'NL' THEN 13800
      WHEN 'SE' THEN 14400
      WHEN 'CA' THEN 12600
      WHEN 'AT' THEN 13200
      WHEN 'DK' THEN 14400
      WHEN 'FI' THEN 13800
      WHEN 'BE' THEN 13800
      WHEN 'IE' THEN 13200
      WHEN 'IL' THEN 12000
      WHEN 'AE' THEN 11400
      WHEN 'KR' THEN 11400
      WHEN 'IT' THEN 10800
      WHEN 'ES' THEN 10200
      WHEN 'NZ' THEN 13200
      WHEN 'PT' THEN 8400
      WHEN 'GR' THEN 7800
      WHEN 'CZ' THEN 7200
      WHEN 'PL' THEN 6600
      WHEN 'HU' THEN 6600
      WHEN 'CL' THEN 6600
      WHEN 'CN' THEN 6600
      WHEN 'MY' THEN 6000
      WHEN 'MX' THEN 6000
      WHEN 'AR' THEN 5400
      WHEN 'BR' THEN 5400
      WHEN 'ZA' THEN 5400
      WHEN 'TH' THEN 5400
      WHEN 'TR' THEN 4800
      WHEN 'CO' THEN 4800
      WHEN 'PE' THEN 4800
      WHEN 'PH' THEN 4800
      WHEN 'MA' THEN 4200
      WHEN 'IN' THEN 3600
      WHEN 'ID' THEN 3600
      WHEN 'VN' THEN 3600
      WHEN 'EG' THEN 3600
      WHEN 'KE' THEN 3600
      WHEN 'NG' THEN 3000
      WHEN 'PK' THEN 3000
      WHEN 'BD' THEN 3000
      ELSE 6000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 200000
      WHEN 'CH' THEN 280000
      WHEN 'NO' THEN 260000
      WHEN 'JP' THEN 260000
      WHEN 'SG' THEN 240000
      WHEN 'AU' THEN 250000
      WHEN 'GB' THEN 240000
      WHEN 'DE' THEN 230000
      WHEN 'FR' THEN 220000
      WHEN 'NL' THEN 230000
      WHEN 'SE' THEN 240000
      WHEN 'CA' THEN 210000
      WHEN 'AT' THEN 220000
      WHEN 'DK' THEN 240000
      WHEN 'FI' THEN 230000
      WHEN 'BE' THEN 230000
      WHEN 'IE' THEN 220000
      WHEN 'IL' THEN 200000
      WHEN 'AE' THEN 190000
      WHEN 'KR' THEN 190000
      WHEN 'IT' THEN 180000
      WHEN 'ES' THEN 170000
      WHEN 'NZ' THEN 220000
      WHEN 'PT' THEN 140000
      WHEN 'GR' THEN 130000
      WHEN 'CZ' THEN 120000
      WHEN 'PL' THEN 110000
      WHEN 'HU' THEN 110000
      WHEN 'CL' THEN 110000
      WHEN 'CN' THEN 110000
      WHEN 'MY' THEN 100000
      WHEN 'MX' THEN 100000
      WHEN 'AR' THEN 90000
      WHEN 'BR' THEN 90000
      WHEN 'ZA' THEN 90000
      WHEN 'TH' THEN 90000
      WHEN 'TR' THEN 80000
      WHEN 'CO' THEN 80000
      WHEN 'PE' THEN 80000
      WHEN 'PH' THEN 80000
      WHEN 'MA' THEN 70000
      WHEN 'IN' THEN 60000
      WHEN 'ID' THEN 60000
      WHEN 'VN' THEN 60000
      WHEN 'EG' THEN 60000
      WHEN 'KE' THEN 60000
      WHEN 'NG' THEN 50000
      WHEN 'PK' THEN 50000
      WHEN 'BD' THEN 50000
      ELSE 100000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'clothing_stores'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 458110)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.15),
  'payroll_total',          ROUND(rev_p50 * 0.16),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.5),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.02),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Retail Owners Institute 2024 + NRF small retailer surveys. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('458110')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 3000
      WHEN 'CH' THEN 4200
      WHEN 'NO' THEN 3900
      WHEN 'JP' THEN 3900
      WHEN 'SG' THEN 3600
      WHEN 'AU' THEN 3750
      WHEN 'GB' THEN 3600
      WHEN 'DE' THEN 3450
      WHEN 'FR' THEN 3300
      WHEN 'NL' THEN 3450
      WHEN 'SE' THEN 3600
      WHEN 'CA' THEN 3150
      WHEN 'AT' THEN 3300
      WHEN 'DK' THEN 3600
      WHEN 'FI' THEN 3450
      WHEN 'BE' THEN 3450
      WHEN 'IE' THEN 3300
      WHEN 'IL' THEN 3000
      WHEN 'AE' THEN 2850
      WHEN 'KR' THEN 2850
      WHEN 'IT' THEN 2700
      WHEN 'ES' THEN 2550
      WHEN 'NZ' THEN 3300
      WHEN 'PT' THEN 2100
      WHEN 'GR' THEN 1950
      WHEN 'CZ' THEN 1800
      WHEN 'PL' THEN 1650
      WHEN 'HU' THEN 1650
      WHEN 'CL' THEN 1650
      WHEN 'CN' THEN 1650
      WHEN 'MY' THEN 1500
      WHEN 'MX' THEN 1500
      WHEN 'AR' THEN 1350
      WHEN 'BR' THEN 1350
      WHEN 'ZA' THEN 1350
      WHEN 'TH' THEN 1350
      WHEN 'TR' THEN 1200
      WHEN 'CO' THEN 1200
      WHEN 'PE' THEN 1200
      WHEN 'PH' THEN 1200
      WHEN 'MA' THEN 1050
      WHEN 'IN' THEN 900
      WHEN 'ID' THEN 900
      WHEN 'VN' THEN 900
      WHEN 'EG' THEN 900
      WHEN 'KE' THEN 900
      WHEN 'NG' THEN 750
      WHEN 'PK' THEN 750
      WHEN 'BD' THEN 750
      ELSE 1500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 120000
      WHEN 'CH' THEN 168000
      WHEN 'NO' THEN 156000
      WHEN 'JP' THEN 156000
      WHEN 'SG' THEN 144000
      WHEN 'AU' THEN 150000
      WHEN 'GB' THEN 144000
      WHEN 'DE' THEN 138000
      WHEN 'FR' THEN 132000
      WHEN 'NL' THEN 138000
      WHEN 'SE' THEN 144000
      WHEN 'CA' THEN 126000
      WHEN 'AT' THEN 132000
      WHEN 'DK' THEN 144000
      WHEN 'FI' THEN 138000
      WHEN 'BE' THEN 138000
      WHEN 'IE' THEN 132000
      WHEN 'IL' THEN 120000
      WHEN 'AE' THEN 114000
      WHEN 'KR' THEN 114000
      WHEN 'IT' THEN 108000
      WHEN 'ES' THEN 102000
      WHEN 'NZ' THEN 132000
      WHEN 'PT' THEN 84000
      WHEN 'GR' THEN 78000
      WHEN 'CZ' THEN 72000
      WHEN 'PL' THEN 66000
      WHEN 'HU' THEN 66000
      WHEN 'CL' THEN 66000
      WHEN 'CN' THEN 66000
      WHEN 'MY' THEN 60000
      WHEN 'MX' THEN 60000
      WHEN 'AR' THEN 54000
      WHEN 'BR' THEN 54000
      WHEN 'ZA' THEN 54000
      WHEN 'TH' THEN 54000
      WHEN 'TR' THEN 48000
      WHEN 'CO' THEN 48000
      WHEN 'PE' THEN 48000
      WHEN 'PH' THEN 48000
      WHEN 'MA' THEN 42000
      WHEN 'IN' THEN 36000
      WHEN 'ID' THEN 36000
      WHEN 'VN' THEN 36000
      WHEN 'EG' THEN 36000
      WHEN 'KE' THEN 36000
      WHEN 'NG' THEN 30000
      WHEN 'PK' THEN 30000
      WHEN 'BD' THEN 30000
      ELSE 60000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 50000
      WHEN 'CH' THEN 70000
      WHEN 'NO' THEN 65000
      WHEN 'JP' THEN 65000
      WHEN 'SG' THEN 60000
      WHEN 'AU' THEN 62500
      WHEN 'GB' THEN 60000
      WHEN 'DE' THEN 57500
      WHEN 'FR' THEN 55000
      WHEN 'NL' THEN 57500
      WHEN 'SE' THEN 60000
      WHEN 'CA' THEN 52500
      WHEN 'AT' THEN 55000
      WHEN 'DK' THEN 60000
      WHEN 'FI' THEN 57500
      WHEN 'BE' THEN 57500
      WHEN 'IE' THEN 55000
      WHEN 'IL' THEN 50000
      WHEN 'AE' THEN 47500
      WHEN 'KR' THEN 47500
      WHEN 'IT' THEN 45000
      WHEN 'ES' THEN 42500
      WHEN 'NZ' THEN 55000
      WHEN 'PT' THEN 35000
      WHEN 'GR' THEN 32500
      WHEN 'CZ' THEN 30000
      WHEN 'PL' THEN 27500
      WHEN 'HU' THEN 27500
      WHEN 'CL' THEN 27500
      WHEN 'CN' THEN 27500
      WHEN 'MY' THEN 25000
      WHEN 'MX' THEN 25000
      WHEN 'AR' THEN 22500
      WHEN 'BR' THEN 22500
      WHEN 'ZA' THEN 22500
      WHEN 'TH' THEN 22500
      WHEN 'TR' THEN 20000
      WHEN 'CO' THEN 20000
      WHEN 'PE' THEN 20000
      WHEN 'PH' THEN 20000
      WHEN 'MA' THEN 17500
      WHEN 'IN' THEN 15000
      WHEN 'ID' THEN 15000
      WHEN 'VN' THEN 15000
      WHEN 'EG' THEN 15000
      WHEN 'KE' THEN 15000
      WHEN 'NG' THEN 12500
      WHEN 'PK' THEN 12500
      WHEN 'BD' THEN 12500
      ELSE 25000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 12000
      WHEN 'CH' THEN 16800
      WHEN 'NO' THEN 15600
      WHEN 'JP' THEN 15600
      WHEN 'SG' THEN 14400
      WHEN 'AU' THEN 15000
      WHEN 'GB' THEN 14400
      WHEN 'DE' THEN 13800
      WHEN 'FR' THEN 13200
      WHEN 'NL' THEN 13800
      WHEN 'SE' THEN 14400
      WHEN 'CA' THEN 12600
      WHEN 'AT' THEN 13200
      WHEN 'DK' THEN 14400
      WHEN 'FI' THEN 13800
      WHEN 'BE' THEN 13800
      WHEN 'IE' THEN 13200
      WHEN 'IL' THEN 12000
      WHEN 'AE' THEN 11400
      WHEN 'KR' THEN 11400
      WHEN 'IT' THEN 10800
      WHEN 'ES' THEN 10200
      WHEN 'NZ' THEN 13200
      WHEN 'PT' THEN 8400
      WHEN 'GR' THEN 7800
      WHEN 'CZ' THEN 7200
      WHEN 'PL' THEN 6600
      WHEN 'HU' THEN 6600
      WHEN 'CL' THEN 6600
      WHEN 'CN' THEN 6600
      WHEN 'MY' THEN 6000
      WHEN 'MX' THEN 6000
      WHEN 'AR' THEN 5400
      WHEN 'BR' THEN 5400
      WHEN 'ZA' THEN 5400
      WHEN 'TH' THEN 5400
      WHEN 'TR' THEN 4800
      WHEN 'CO' THEN 4800
      WHEN 'PE' THEN 4800
      WHEN 'PH' THEN 4800
      WHEN 'MA' THEN 4200
      WHEN 'IN' THEN 3600
      WHEN 'ID' THEN 3600
      WHEN 'VN' THEN 3600
      WHEN 'EG' THEN 3600
      WHEN 'KE' THEN 3600
      WHEN 'NG' THEN 3000
      WHEN 'PK' THEN 3000
      WHEN 'BD' THEN 3000
      ELSE 6000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 200000
      WHEN 'CH' THEN 280000
      WHEN 'NO' THEN 260000
      WHEN 'JP' THEN 260000
      WHEN 'SG' THEN 240000
      WHEN 'AU' THEN 250000
      WHEN 'GB' THEN 240000
      WHEN 'DE' THEN 230000
      WHEN 'FR' THEN 220000
      WHEN 'NL' THEN 230000
      WHEN 'SE' THEN 240000
      WHEN 'CA' THEN 210000
      WHEN 'AT' THEN 220000
      WHEN 'DK' THEN 240000
      WHEN 'FI' THEN 230000
      WHEN 'BE' THEN 230000
      WHEN 'IE' THEN 220000
      WHEN 'IL' THEN 200000
      WHEN 'AE' THEN 190000
      WHEN 'KR' THEN 190000
      WHEN 'IT' THEN 180000
      WHEN 'ES' THEN 170000
      WHEN 'NZ' THEN 220000
      WHEN 'PT' THEN 140000
      WHEN 'GR' THEN 130000
      WHEN 'CZ' THEN 120000
      WHEN 'PL' THEN 110000
      WHEN 'HU' THEN 110000
      WHEN 'CL' THEN 110000
      WHEN 'CN' THEN 110000
      WHEN 'MY' THEN 100000
      WHEN 'MX' THEN 100000
      WHEN 'AR' THEN 90000
      WHEN 'BR' THEN 90000
      WHEN 'ZA' THEN 90000
      WHEN 'TH' THEN 90000
      WHEN 'TR' THEN 80000
      WHEN 'CO' THEN 80000
      WHEN 'PE' THEN 80000
      WHEN 'PH' THEN 80000
      WHEN 'MA' THEN 70000
      WHEN 'IN' THEN 60000
      WHEN 'ID' THEN 60000
      WHEN 'VN' THEN 60000
      WHEN 'EG' THEN 60000
      WHEN 'KE' THEN 60000
      WHEN 'NG' THEN 50000
      WHEN 'PK' THEN 50000
      WHEN 'BD' THEN 50000
      ELSE 100000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('458110')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.15),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.16),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.5),
  'utilities',              ROUND(predicted_rev_per_firm * 0.02),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.04),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.02),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.02),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Retail Owners Institute 2024 + NRF small retailer surveys. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'clothing_stores'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
