-- ============================================================================
-- BULK IMPORT: dental_practices cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: ADA Health Policy Institute economic surveys + dental practice benchmarking 2024.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.28),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.06),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.06),
  'equipment_maintenance',  ROUND(rev_p50 * 0.05),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ADA Health Policy Institute economic surveys + dental practice benchmarking 2024. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'dental_practices'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 300000
      WHEN 'CH' THEN 420000
      WHEN 'NO' THEN 390000
      WHEN 'JP' THEN 390000
      WHEN 'SG' THEN 360000
      WHEN 'AU' THEN 375000
      WHEN 'GB' THEN 360000
      WHEN 'DE' THEN 345000
      WHEN 'FR' THEN 330000
      WHEN 'NL' THEN 345000
      WHEN 'SE' THEN 360000
      WHEN 'CA' THEN 315000
      WHEN 'AT' THEN 330000
      WHEN 'DK' THEN 360000
      WHEN 'FI' THEN 345000
      WHEN 'BE' THEN 345000
      WHEN 'IE' THEN 330000
      WHEN 'IL' THEN 300000
      WHEN 'AE' THEN 285000
      WHEN 'KR' THEN 285000
      WHEN 'IT' THEN 270000
      WHEN 'ES' THEN 255000
      WHEN 'NZ' THEN 330000
      WHEN 'PT' THEN 210000
      WHEN 'GR' THEN 195000
      WHEN 'CZ' THEN 180000
      WHEN 'PL' THEN 165000
      WHEN 'HU' THEN 165000
      WHEN 'CL' THEN 165000
      WHEN 'CN' THEN 165000
      WHEN 'MY' THEN 150000
      WHEN 'MX' THEN 150000
      WHEN 'AR' THEN 135000
      WHEN 'BR' THEN 135000
      WHEN 'ZA' THEN 135000
      WHEN 'TH' THEN 135000
      WHEN 'TR' THEN 120000
      WHEN 'CO' THEN 120000
      WHEN 'PE' THEN 120000
      WHEN 'PH' THEN 120000
      WHEN 'MA' THEN 105000
      WHEN 'IN' THEN 90000
      WHEN 'ID' THEN 90000
      WHEN 'VN' THEN 90000
      WHEN 'EG' THEN 90000
      WHEN 'KE' THEN 90000
      WHEN 'NG' THEN 75000
      WHEN 'PK' THEN 75000
      WHEN 'BD' THEN 75000
      ELSE 150000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 125000
      WHEN 'CH' THEN 175000
      WHEN 'NO' THEN 162500
      WHEN 'JP' THEN 162500
      WHEN 'SG' THEN 150000
      WHEN 'AU' THEN 156250
      WHEN 'GB' THEN 150000
      WHEN 'DE' THEN 143750
      WHEN 'FR' THEN 137500
      WHEN 'NL' THEN 143750
      WHEN 'SE' THEN 150000
      WHEN 'CA' THEN 131250
      WHEN 'AT' THEN 137500
      WHEN 'DK' THEN 150000
      WHEN 'FI' THEN 143750
      WHEN 'BE' THEN 143750
      WHEN 'IE' THEN 137500
      WHEN 'IL' THEN 125000
      WHEN 'AE' THEN 118750
      WHEN 'KR' THEN 118750
      WHEN 'IT' THEN 112500
      WHEN 'ES' THEN 106250
      WHEN 'NZ' THEN 137500
      WHEN 'PT' THEN 87500
      WHEN 'GR' THEN 81250
      WHEN 'CZ' THEN 75000
      WHEN 'PL' THEN 68750
      WHEN 'HU' THEN 68750
      WHEN 'CL' THEN 68750
      WHEN 'CN' THEN 68750
      WHEN 'MY' THEN 62500
      WHEN 'MX' THEN 62500
      WHEN 'AR' THEN 56250
      WHEN 'BR' THEN 56250
      WHEN 'ZA' THEN 56250
      WHEN 'TH' THEN 56250
      WHEN 'TR' THEN 50000
      WHEN 'CO' THEN 50000
      WHEN 'PE' THEN 50000
      WHEN 'PH' THEN 50000
      WHEN 'MA' THEN 43750
      WHEN 'IN' THEN 37500
      WHEN 'ID' THEN 37500
      WHEN 'VN' THEN 37500
      WHEN 'EG' THEN 37500
      WHEN 'KE' THEN 37500
      WHEN 'NG' THEN 31250
      WHEN 'PK' THEN 31250
      WHEN 'BD' THEN 31250
      ELSE 62500
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 30000
      WHEN 'CH' THEN 42000
      WHEN 'NO' THEN 39000
      WHEN 'JP' THEN 39000
      WHEN 'SG' THEN 36000
      WHEN 'AU' THEN 37500
      WHEN 'GB' THEN 36000
      WHEN 'DE' THEN 34500
      WHEN 'FR' THEN 33000
      WHEN 'NL' THEN 34500
      WHEN 'SE' THEN 36000
      WHEN 'CA' THEN 31500
      WHEN 'AT' THEN 33000
      WHEN 'DK' THEN 36000
      WHEN 'FI' THEN 34500
      WHEN 'BE' THEN 34500
      WHEN 'IE' THEN 33000
      WHEN 'IL' THEN 30000
      WHEN 'AE' THEN 28500
      WHEN 'KR' THEN 28500
      WHEN 'IT' THEN 27000
      WHEN 'ES' THEN 25500
      WHEN 'NZ' THEN 33000
      WHEN 'PT' THEN 21000
      WHEN 'GR' THEN 19500
      WHEN 'CZ' THEN 18000
      WHEN 'PL' THEN 16500
      WHEN 'HU' THEN 16500
      WHEN 'CL' THEN 16500
      WHEN 'CN' THEN 16500
      WHEN 'MY' THEN 15000
      WHEN 'MX' THEN 15000
      WHEN 'AR' THEN 13500
      WHEN 'BR' THEN 13500
      WHEN 'ZA' THEN 13500
      WHEN 'TH' THEN 13500
      WHEN 'TR' THEN 12000
      WHEN 'CO' THEN 12000
      WHEN 'PE' THEN 12000
      WHEN 'PH' THEN 12000
      WHEN 'MA' THEN 10500
      WHEN 'IN' THEN 9000
      WHEN 'ID' THEN 9000
      WHEN 'VN' THEN 9000
      WHEN 'EG' THEN 9000
      WHEN 'KE' THEN 9000
      WHEN 'NG' THEN 7500
      WHEN 'PK' THEN 7500
      WHEN 'BD' THEN 7500
      ELSE 15000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 500000
      WHEN 'CH' THEN 700000
      WHEN 'NO' THEN 650000
      WHEN 'JP' THEN 650000
      WHEN 'SG' THEN 600000
      WHEN 'AU' THEN 625000
      WHEN 'GB' THEN 600000
      WHEN 'DE' THEN 575000
      WHEN 'FR' THEN 550000
      WHEN 'NL' THEN 575000
      WHEN 'SE' THEN 600000
      WHEN 'CA' THEN 525000
      WHEN 'AT' THEN 550000
      WHEN 'DK' THEN 600000
      WHEN 'FI' THEN 575000
      WHEN 'BE' THEN 575000
      WHEN 'IE' THEN 550000
      WHEN 'IL' THEN 500000
      WHEN 'AE' THEN 475000
      WHEN 'KR' THEN 475000
      WHEN 'IT' THEN 450000
      WHEN 'ES' THEN 425000
      WHEN 'NZ' THEN 550000
      WHEN 'PT' THEN 350000
      WHEN 'GR' THEN 325000
      WHEN 'CZ' THEN 300000
      WHEN 'PL' THEN 275000
      WHEN 'HU' THEN 275000
      WHEN 'CL' THEN 275000
      WHEN 'CN' THEN 275000
      WHEN 'MY' THEN 250000
      WHEN 'MX' THEN 250000
      WHEN 'AR' THEN 225000
      WHEN 'BR' THEN 225000
      WHEN 'ZA' THEN 225000
      WHEN 'TH' THEN 225000
      WHEN 'TR' THEN 200000
      WHEN 'CO' THEN 200000
      WHEN 'PE' THEN 200000
      WHEN 'PH' THEN 200000
      WHEN 'MA' THEN 175000
      WHEN 'IN' THEN 150000
      WHEN 'ID' THEN 150000
      WHEN 'VN' THEN 150000
      WHEN 'EG' THEN 150000
      WHEN 'KE' THEN 150000
      WHEN 'NG' THEN 125000
      WHEN 'PK' THEN 125000
      WHEN 'BD' THEN 125000
      ELSE 250000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'dental_practices'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 621210)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.28),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.06),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.06),
  'equipment_maintenance',  ROUND(rev_p50 * 0.05),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ADA Health Policy Institute economic surveys + dental practice benchmarking 2024. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('621210')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 300000
      WHEN 'CH' THEN 420000
      WHEN 'NO' THEN 390000
      WHEN 'JP' THEN 390000
      WHEN 'SG' THEN 360000
      WHEN 'AU' THEN 375000
      WHEN 'GB' THEN 360000
      WHEN 'DE' THEN 345000
      WHEN 'FR' THEN 330000
      WHEN 'NL' THEN 345000
      WHEN 'SE' THEN 360000
      WHEN 'CA' THEN 315000
      WHEN 'AT' THEN 330000
      WHEN 'DK' THEN 360000
      WHEN 'FI' THEN 345000
      WHEN 'BE' THEN 345000
      WHEN 'IE' THEN 330000
      WHEN 'IL' THEN 300000
      WHEN 'AE' THEN 285000
      WHEN 'KR' THEN 285000
      WHEN 'IT' THEN 270000
      WHEN 'ES' THEN 255000
      WHEN 'NZ' THEN 330000
      WHEN 'PT' THEN 210000
      WHEN 'GR' THEN 195000
      WHEN 'CZ' THEN 180000
      WHEN 'PL' THEN 165000
      WHEN 'HU' THEN 165000
      WHEN 'CL' THEN 165000
      WHEN 'CN' THEN 165000
      WHEN 'MY' THEN 150000
      WHEN 'MX' THEN 150000
      WHEN 'AR' THEN 135000
      WHEN 'BR' THEN 135000
      WHEN 'ZA' THEN 135000
      WHEN 'TH' THEN 135000
      WHEN 'TR' THEN 120000
      WHEN 'CO' THEN 120000
      WHEN 'PE' THEN 120000
      WHEN 'PH' THEN 120000
      WHEN 'MA' THEN 105000
      WHEN 'IN' THEN 90000
      WHEN 'ID' THEN 90000
      WHEN 'VN' THEN 90000
      WHEN 'EG' THEN 90000
      WHEN 'KE' THEN 90000
      WHEN 'NG' THEN 75000
      WHEN 'PK' THEN 75000
      WHEN 'BD' THEN 75000
      ELSE 150000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 125000
      WHEN 'CH' THEN 175000
      WHEN 'NO' THEN 162500
      WHEN 'JP' THEN 162500
      WHEN 'SG' THEN 150000
      WHEN 'AU' THEN 156250
      WHEN 'GB' THEN 150000
      WHEN 'DE' THEN 143750
      WHEN 'FR' THEN 137500
      WHEN 'NL' THEN 143750
      WHEN 'SE' THEN 150000
      WHEN 'CA' THEN 131250
      WHEN 'AT' THEN 137500
      WHEN 'DK' THEN 150000
      WHEN 'FI' THEN 143750
      WHEN 'BE' THEN 143750
      WHEN 'IE' THEN 137500
      WHEN 'IL' THEN 125000
      WHEN 'AE' THEN 118750
      WHEN 'KR' THEN 118750
      WHEN 'IT' THEN 112500
      WHEN 'ES' THEN 106250
      WHEN 'NZ' THEN 137500
      WHEN 'PT' THEN 87500
      WHEN 'GR' THEN 81250
      WHEN 'CZ' THEN 75000
      WHEN 'PL' THEN 68750
      WHEN 'HU' THEN 68750
      WHEN 'CL' THEN 68750
      WHEN 'CN' THEN 68750
      WHEN 'MY' THEN 62500
      WHEN 'MX' THEN 62500
      WHEN 'AR' THEN 56250
      WHEN 'BR' THEN 56250
      WHEN 'ZA' THEN 56250
      WHEN 'TH' THEN 56250
      WHEN 'TR' THEN 50000
      WHEN 'CO' THEN 50000
      WHEN 'PE' THEN 50000
      WHEN 'PH' THEN 50000
      WHEN 'MA' THEN 43750
      WHEN 'IN' THEN 37500
      WHEN 'ID' THEN 37500
      WHEN 'VN' THEN 37500
      WHEN 'EG' THEN 37500
      WHEN 'KE' THEN 37500
      WHEN 'NG' THEN 31250
      WHEN 'PK' THEN 31250
      WHEN 'BD' THEN 31250
      ELSE 62500
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 30000
      WHEN 'CH' THEN 42000
      WHEN 'NO' THEN 39000
      WHEN 'JP' THEN 39000
      WHEN 'SG' THEN 36000
      WHEN 'AU' THEN 37500
      WHEN 'GB' THEN 36000
      WHEN 'DE' THEN 34500
      WHEN 'FR' THEN 33000
      WHEN 'NL' THEN 34500
      WHEN 'SE' THEN 36000
      WHEN 'CA' THEN 31500
      WHEN 'AT' THEN 33000
      WHEN 'DK' THEN 36000
      WHEN 'FI' THEN 34500
      WHEN 'BE' THEN 34500
      WHEN 'IE' THEN 33000
      WHEN 'IL' THEN 30000
      WHEN 'AE' THEN 28500
      WHEN 'KR' THEN 28500
      WHEN 'IT' THEN 27000
      WHEN 'ES' THEN 25500
      WHEN 'NZ' THEN 33000
      WHEN 'PT' THEN 21000
      WHEN 'GR' THEN 19500
      WHEN 'CZ' THEN 18000
      WHEN 'PL' THEN 16500
      WHEN 'HU' THEN 16500
      WHEN 'CL' THEN 16500
      WHEN 'CN' THEN 16500
      WHEN 'MY' THEN 15000
      WHEN 'MX' THEN 15000
      WHEN 'AR' THEN 13500
      WHEN 'BR' THEN 13500
      WHEN 'ZA' THEN 13500
      WHEN 'TH' THEN 13500
      WHEN 'TR' THEN 12000
      WHEN 'CO' THEN 12000
      WHEN 'PE' THEN 12000
      WHEN 'PH' THEN 12000
      WHEN 'MA' THEN 10500
      WHEN 'IN' THEN 9000
      WHEN 'ID' THEN 9000
      WHEN 'VN' THEN 9000
      WHEN 'EG' THEN 9000
      WHEN 'KE' THEN 9000
      WHEN 'NG' THEN 7500
      WHEN 'PK' THEN 7500
      WHEN 'BD' THEN 7500
      ELSE 15000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 500000
      WHEN 'CH' THEN 700000
      WHEN 'NO' THEN 650000
      WHEN 'JP' THEN 650000
      WHEN 'SG' THEN 600000
      WHEN 'AU' THEN 625000
      WHEN 'GB' THEN 600000
      WHEN 'DE' THEN 575000
      WHEN 'FR' THEN 550000
      WHEN 'NL' THEN 575000
      WHEN 'SE' THEN 600000
      WHEN 'CA' THEN 525000
      WHEN 'AT' THEN 550000
      WHEN 'DK' THEN 600000
      WHEN 'FI' THEN 575000
      WHEN 'BE' THEN 575000
      WHEN 'IE' THEN 550000
      WHEN 'IL' THEN 500000
      WHEN 'AE' THEN 475000
      WHEN 'KR' THEN 475000
      WHEN 'IT' THEN 450000
      WHEN 'ES' THEN 425000
      WHEN 'NZ' THEN 550000
      WHEN 'PT' THEN 350000
      WHEN 'GR' THEN 325000
      WHEN 'CZ' THEN 300000
      WHEN 'PL' THEN 275000
      WHEN 'HU' THEN 275000
      WHEN 'CL' THEN 275000
      WHEN 'CN' THEN 275000
      WHEN 'MY' THEN 250000
      WHEN 'MX' THEN 250000
      WHEN 'AR' THEN 225000
      WHEN 'BR' THEN 225000
      WHEN 'ZA' THEN 225000
      WHEN 'TH' THEN 225000
      WHEN 'TR' THEN 200000
      WHEN 'CO' THEN 200000
      WHEN 'PE' THEN 200000
      WHEN 'PH' THEN 200000
      WHEN 'MA' THEN 175000
      WHEN 'IN' THEN 150000
      WHEN 'ID' THEN 150000
      WHEN 'VN' THEN 150000
      WHEN 'EG' THEN 150000
      WHEN 'KE' THEN 150000
      WHEN 'NG' THEN 125000
      WHEN 'PK' THEN 125000
      WHEN 'BD' THEN 125000
      ELSE 250000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('621210')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.08),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.28),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.06),
  'utilities',              ROUND(predicted_rev_per_firm * 0.02),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.04),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.06),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.05),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ADA Health Policy Institute economic surveys + dental practice benchmarking 2024. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'dental_practices'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
