-- ============================================================================
-- BULK IMPORT: doctors_clinics cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: MGMA Cost and Revenue Survey 2024 + AMA practice benchmarks.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.07),
  'payroll_total',          ROUND(rev_p50 * 0.4),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.07),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.07),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'MGMA Cost and Revenue Survey 2024 + AMA practice benchmarks. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'doctors_clinics'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 210000
      WHEN 'CH' THEN 294000
      WHEN 'NO' THEN 273000
      WHEN 'JP' THEN 273000
      WHEN 'SG' THEN 252000
      WHEN 'AU' THEN 262500
      WHEN 'GB' THEN 252000
      WHEN 'DE' THEN 241500
      WHEN 'FR' THEN 231000
      WHEN 'NL' THEN 241500
      WHEN 'SE' THEN 252000
      WHEN 'CA' THEN 220500
      WHEN 'AT' THEN 231000
      WHEN 'DK' THEN 252000
      WHEN 'FI' THEN 241500
      WHEN 'BE' THEN 241500
      WHEN 'IE' THEN 231000
      WHEN 'IL' THEN 210000
      WHEN 'AE' THEN 199500
      WHEN 'KR' THEN 199500
      WHEN 'IT' THEN 189000
      WHEN 'ES' THEN 178500
      WHEN 'NZ' THEN 231000
      WHEN 'PT' THEN 147000
      WHEN 'GR' THEN 136500
      WHEN 'CZ' THEN 126000
      WHEN 'PL' THEN 115500
      WHEN 'HU' THEN 115500
      WHEN 'CL' THEN 115500
      WHEN 'CN' THEN 115500
      WHEN 'MY' THEN 105000
      WHEN 'MX' THEN 105000
      WHEN 'AR' THEN 94500
      WHEN 'BR' THEN 94500
      WHEN 'ZA' THEN 94500
      WHEN 'TH' THEN 94500
      WHEN 'TR' THEN 84000
      WHEN 'CO' THEN 84000
      WHEN 'PE' THEN 84000
      WHEN 'PH' THEN 84000
      WHEN 'MA' THEN 73500
      WHEN 'IN' THEN 63000
      WHEN 'ID' THEN 63000
      WHEN 'VN' THEN 63000
      WHEN 'EG' THEN 63000
      WHEN 'KE' THEN 63000
      WHEN 'NG' THEN 52500
      WHEN 'PK' THEN 52500
      WHEN 'BD' THEN 52500
      ELSE 105000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 87500
      WHEN 'CH' THEN 122500
      WHEN 'NO' THEN 113750
      WHEN 'JP' THEN 113750
      WHEN 'SG' THEN 105000
      WHEN 'AU' THEN 109375
      WHEN 'GB' THEN 105000
      WHEN 'DE' THEN 100625
      WHEN 'FR' THEN 96250
      WHEN 'NL' THEN 100625
      WHEN 'SE' THEN 105000
      WHEN 'CA' THEN 91875
      WHEN 'AT' THEN 96250
      WHEN 'DK' THEN 105000
      WHEN 'FI' THEN 100625
      WHEN 'BE' THEN 100625
      WHEN 'IE' THEN 96250
      WHEN 'IL' THEN 87500
      WHEN 'AE' THEN 83125
      WHEN 'KR' THEN 83125
      WHEN 'IT' THEN 78750
      WHEN 'ES' THEN 74375
      WHEN 'NZ' THEN 96250
      WHEN 'PT' THEN 61250
      WHEN 'GR' THEN 56875
      WHEN 'CZ' THEN 52500
      WHEN 'PL' THEN 48125
      WHEN 'HU' THEN 48125
      WHEN 'CL' THEN 48125
      WHEN 'CN' THEN 48125
      WHEN 'MY' THEN 43750
      WHEN 'MX' THEN 43750
      WHEN 'AR' THEN 39375
      WHEN 'BR' THEN 39375
      WHEN 'ZA' THEN 39375
      WHEN 'TH' THEN 39375
      WHEN 'TR' THEN 35000
      WHEN 'CO' THEN 35000
      WHEN 'PE' THEN 35000
      WHEN 'PH' THEN 35000
      WHEN 'MA' THEN 30625
      WHEN 'IN' THEN 26250
      WHEN 'ID' THEN 26250
      WHEN 'VN' THEN 26250
      WHEN 'EG' THEN 26250
      WHEN 'KE' THEN 26250
      WHEN 'NG' THEN 21875
      WHEN 'PK' THEN 21875
      WHEN 'BD' THEN 21875
      ELSE 43750
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 21000
      WHEN 'CH' THEN 29400
      WHEN 'NO' THEN 27300
      WHEN 'JP' THEN 27300
      WHEN 'SG' THEN 25200
      WHEN 'AU' THEN 26250
      WHEN 'GB' THEN 25200
      WHEN 'DE' THEN 24150
      WHEN 'FR' THEN 23100
      WHEN 'NL' THEN 24150
      WHEN 'SE' THEN 25200
      WHEN 'CA' THEN 22050
      WHEN 'AT' THEN 23100
      WHEN 'DK' THEN 25200
      WHEN 'FI' THEN 24150
      WHEN 'BE' THEN 24150
      WHEN 'IE' THEN 23100
      WHEN 'IL' THEN 21000
      WHEN 'AE' THEN 19950
      WHEN 'KR' THEN 19950
      WHEN 'IT' THEN 18900
      WHEN 'ES' THEN 17850
      WHEN 'NZ' THEN 23100
      WHEN 'PT' THEN 14700
      WHEN 'GR' THEN 13650
      WHEN 'CZ' THEN 12600
      WHEN 'PL' THEN 11550
      WHEN 'HU' THEN 11550
      WHEN 'CL' THEN 11550
      WHEN 'CN' THEN 11550
      WHEN 'MY' THEN 10500
      WHEN 'MX' THEN 10500
      WHEN 'AR' THEN 9450
      WHEN 'BR' THEN 9450
      WHEN 'ZA' THEN 9450
      WHEN 'TH' THEN 9450
      WHEN 'TR' THEN 8400
      WHEN 'CO' THEN 8400
      WHEN 'PE' THEN 8400
      WHEN 'PH' THEN 8400
      WHEN 'MA' THEN 7350
      WHEN 'IN' THEN 6300
      WHEN 'ID' THEN 6300
      WHEN 'VN' THEN 6300
      WHEN 'EG' THEN 6300
      WHEN 'KE' THEN 6300
      WHEN 'NG' THEN 5250
      WHEN 'PK' THEN 5250
      WHEN 'BD' THEN 5250
      ELSE 10500
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 350000
      WHEN 'CH' THEN 490000
      WHEN 'NO' THEN 455000
      WHEN 'JP' THEN 455000
      WHEN 'SG' THEN 420000
      WHEN 'AU' THEN 437500
      WHEN 'GB' THEN 420000
      WHEN 'DE' THEN 402500
      WHEN 'FR' THEN 385000
      WHEN 'NL' THEN 402500
      WHEN 'SE' THEN 420000
      WHEN 'CA' THEN 367500
      WHEN 'AT' THEN 385000
      WHEN 'DK' THEN 420000
      WHEN 'FI' THEN 402500
      WHEN 'BE' THEN 402500
      WHEN 'IE' THEN 385000
      WHEN 'IL' THEN 350000
      WHEN 'AE' THEN 332500
      WHEN 'KR' THEN 332500
      WHEN 'IT' THEN 315000
      WHEN 'ES' THEN 297500
      WHEN 'NZ' THEN 385000
      WHEN 'PT' THEN 245000
      WHEN 'GR' THEN 227500
      WHEN 'CZ' THEN 210000
      WHEN 'PL' THEN 192500
      WHEN 'HU' THEN 192500
      WHEN 'CL' THEN 192500
      WHEN 'CN' THEN 192500
      WHEN 'MY' THEN 175000
      WHEN 'MX' THEN 175000
      WHEN 'AR' THEN 157500
      WHEN 'BR' THEN 157500
      WHEN 'ZA' THEN 157500
      WHEN 'TH' THEN 157500
      WHEN 'TR' THEN 140000
      WHEN 'CO' THEN 140000
      WHEN 'PE' THEN 140000
      WHEN 'PH' THEN 140000
      WHEN 'MA' THEN 122500
      WHEN 'IN' THEN 105000
      WHEN 'ID' THEN 105000
      WHEN 'VN' THEN 105000
      WHEN 'EG' THEN 105000
      WHEN 'KE' THEN 105000
      WHEN 'NG' THEN 87500
      WHEN 'PK' THEN 87500
      WHEN 'BD' THEN 87500
      ELSE 175000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'doctors_clinics'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 621111 + 621112)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.07),
  'payroll_total',          ROUND(rev_p50 * 0.4),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.07),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.07),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'MGMA Cost and Revenue Survey 2024 + AMA practice benchmarks. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('621111', '621112')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 210000
      WHEN 'CH' THEN 294000
      WHEN 'NO' THEN 273000
      WHEN 'JP' THEN 273000
      WHEN 'SG' THEN 252000
      WHEN 'AU' THEN 262500
      WHEN 'GB' THEN 252000
      WHEN 'DE' THEN 241500
      WHEN 'FR' THEN 231000
      WHEN 'NL' THEN 241500
      WHEN 'SE' THEN 252000
      WHEN 'CA' THEN 220500
      WHEN 'AT' THEN 231000
      WHEN 'DK' THEN 252000
      WHEN 'FI' THEN 241500
      WHEN 'BE' THEN 241500
      WHEN 'IE' THEN 231000
      WHEN 'IL' THEN 210000
      WHEN 'AE' THEN 199500
      WHEN 'KR' THEN 199500
      WHEN 'IT' THEN 189000
      WHEN 'ES' THEN 178500
      WHEN 'NZ' THEN 231000
      WHEN 'PT' THEN 147000
      WHEN 'GR' THEN 136500
      WHEN 'CZ' THEN 126000
      WHEN 'PL' THEN 115500
      WHEN 'HU' THEN 115500
      WHEN 'CL' THEN 115500
      WHEN 'CN' THEN 115500
      WHEN 'MY' THEN 105000
      WHEN 'MX' THEN 105000
      WHEN 'AR' THEN 94500
      WHEN 'BR' THEN 94500
      WHEN 'ZA' THEN 94500
      WHEN 'TH' THEN 94500
      WHEN 'TR' THEN 84000
      WHEN 'CO' THEN 84000
      WHEN 'PE' THEN 84000
      WHEN 'PH' THEN 84000
      WHEN 'MA' THEN 73500
      WHEN 'IN' THEN 63000
      WHEN 'ID' THEN 63000
      WHEN 'VN' THEN 63000
      WHEN 'EG' THEN 63000
      WHEN 'KE' THEN 63000
      WHEN 'NG' THEN 52500
      WHEN 'PK' THEN 52500
      WHEN 'BD' THEN 52500
      ELSE 105000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 87500
      WHEN 'CH' THEN 122500
      WHEN 'NO' THEN 113750
      WHEN 'JP' THEN 113750
      WHEN 'SG' THEN 105000
      WHEN 'AU' THEN 109375
      WHEN 'GB' THEN 105000
      WHEN 'DE' THEN 100625
      WHEN 'FR' THEN 96250
      WHEN 'NL' THEN 100625
      WHEN 'SE' THEN 105000
      WHEN 'CA' THEN 91875
      WHEN 'AT' THEN 96250
      WHEN 'DK' THEN 105000
      WHEN 'FI' THEN 100625
      WHEN 'BE' THEN 100625
      WHEN 'IE' THEN 96250
      WHEN 'IL' THEN 87500
      WHEN 'AE' THEN 83125
      WHEN 'KR' THEN 83125
      WHEN 'IT' THEN 78750
      WHEN 'ES' THEN 74375
      WHEN 'NZ' THEN 96250
      WHEN 'PT' THEN 61250
      WHEN 'GR' THEN 56875
      WHEN 'CZ' THEN 52500
      WHEN 'PL' THEN 48125
      WHEN 'HU' THEN 48125
      WHEN 'CL' THEN 48125
      WHEN 'CN' THEN 48125
      WHEN 'MY' THEN 43750
      WHEN 'MX' THEN 43750
      WHEN 'AR' THEN 39375
      WHEN 'BR' THEN 39375
      WHEN 'ZA' THEN 39375
      WHEN 'TH' THEN 39375
      WHEN 'TR' THEN 35000
      WHEN 'CO' THEN 35000
      WHEN 'PE' THEN 35000
      WHEN 'PH' THEN 35000
      WHEN 'MA' THEN 30625
      WHEN 'IN' THEN 26250
      WHEN 'ID' THEN 26250
      WHEN 'VN' THEN 26250
      WHEN 'EG' THEN 26250
      WHEN 'KE' THEN 26250
      WHEN 'NG' THEN 21875
      WHEN 'PK' THEN 21875
      WHEN 'BD' THEN 21875
      ELSE 43750
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 21000
      WHEN 'CH' THEN 29400
      WHEN 'NO' THEN 27300
      WHEN 'JP' THEN 27300
      WHEN 'SG' THEN 25200
      WHEN 'AU' THEN 26250
      WHEN 'GB' THEN 25200
      WHEN 'DE' THEN 24150
      WHEN 'FR' THEN 23100
      WHEN 'NL' THEN 24150
      WHEN 'SE' THEN 25200
      WHEN 'CA' THEN 22050
      WHEN 'AT' THEN 23100
      WHEN 'DK' THEN 25200
      WHEN 'FI' THEN 24150
      WHEN 'BE' THEN 24150
      WHEN 'IE' THEN 23100
      WHEN 'IL' THEN 21000
      WHEN 'AE' THEN 19950
      WHEN 'KR' THEN 19950
      WHEN 'IT' THEN 18900
      WHEN 'ES' THEN 17850
      WHEN 'NZ' THEN 23100
      WHEN 'PT' THEN 14700
      WHEN 'GR' THEN 13650
      WHEN 'CZ' THEN 12600
      WHEN 'PL' THEN 11550
      WHEN 'HU' THEN 11550
      WHEN 'CL' THEN 11550
      WHEN 'CN' THEN 11550
      WHEN 'MY' THEN 10500
      WHEN 'MX' THEN 10500
      WHEN 'AR' THEN 9450
      WHEN 'BR' THEN 9450
      WHEN 'ZA' THEN 9450
      WHEN 'TH' THEN 9450
      WHEN 'TR' THEN 8400
      WHEN 'CO' THEN 8400
      WHEN 'PE' THEN 8400
      WHEN 'PH' THEN 8400
      WHEN 'MA' THEN 7350
      WHEN 'IN' THEN 6300
      WHEN 'ID' THEN 6300
      WHEN 'VN' THEN 6300
      WHEN 'EG' THEN 6300
      WHEN 'KE' THEN 6300
      WHEN 'NG' THEN 5250
      WHEN 'PK' THEN 5250
      WHEN 'BD' THEN 5250
      ELSE 10500
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 350000
      WHEN 'CH' THEN 490000
      WHEN 'NO' THEN 455000
      WHEN 'JP' THEN 455000
      WHEN 'SG' THEN 420000
      WHEN 'AU' THEN 437500
      WHEN 'GB' THEN 420000
      WHEN 'DE' THEN 402500
      WHEN 'FR' THEN 385000
      WHEN 'NL' THEN 402500
      WHEN 'SE' THEN 420000
      WHEN 'CA' THEN 367500
      WHEN 'AT' THEN 385000
      WHEN 'DK' THEN 420000
      WHEN 'FI' THEN 402500
      WHEN 'BE' THEN 402500
      WHEN 'IE' THEN 385000
      WHEN 'IL' THEN 350000
      WHEN 'AE' THEN 332500
      WHEN 'KR' THEN 332500
      WHEN 'IT' THEN 315000
      WHEN 'ES' THEN 297500
      WHEN 'NZ' THEN 385000
      WHEN 'PT' THEN 245000
      WHEN 'GR' THEN 227500
      WHEN 'CZ' THEN 210000
      WHEN 'PL' THEN 192500
      WHEN 'HU' THEN 192500
      WHEN 'CL' THEN 192500
      WHEN 'CN' THEN 192500
      WHEN 'MY' THEN 175000
      WHEN 'MX' THEN 175000
      WHEN 'AR' THEN 157500
      WHEN 'BR' THEN 157500
      WHEN 'ZA' THEN 157500
      WHEN 'TH' THEN 157500
      WHEN 'TR' THEN 140000
      WHEN 'CO' THEN 140000
      WHEN 'PE' THEN 140000
      WHEN 'PH' THEN 140000
      WHEN 'MA' THEN 122500
      WHEN 'IN' THEN 105000
      WHEN 'ID' THEN 105000
      WHEN 'VN' THEN 105000
      WHEN 'EG' THEN 105000
      WHEN 'KE' THEN 105000
      WHEN 'NG' THEN 87500
      WHEN 'PK' THEN 87500
      WHEN 'BD' THEN 87500
      ELSE 175000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('621111', '621112')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.07),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.4),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.07),
  'utilities',              ROUND(predicted_rev_per_firm * 0.02),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.02),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.07),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.04),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'MGMA Cost and Revenue Survey 2024 + AMA practice benchmarks. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'doctors_clinics'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
