-- ============================================================================
-- BULK IMPORT: hairdressers_beauty cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: Hair salon industry benchmarks 2024 (Homebase, FinancialModelsLab, BusinessDojo).
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.12),
  'payroll_total',          ROUND(rev_p50 * 0.45),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.12),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Hair salon industry benchmarks 2024 (Homebase, FinancialModelsLab, BusinessDojo). Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'hairdressers_beauty'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 2500
      WHEN 'CH' THEN 3500
      WHEN 'NO' THEN 3250
      WHEN 'JP' THEN 3250
      WHEN 'SG' THEN 3000
      WHEN 'AU' THEN 3125
      WHEN 'GB' THEN 3000
      WHEN 'DE' THEN 2875
      WHEN 'FR' THEN 2750
      WHEN 'NL' THEN 2875
      WHEN 'SE' THEN 3000
      WHEN 'CA' THEN 2625
      WHEN 'AT' THEN 2750
      WHEN 'DK' THEN 3000
      WHEN 'FI' THEN 2875
      WHEN 'BE' THEN 2875
      WHEN 'IE' THEN 2750
      WHEN 'IL' THEN 2500
      WHEN 'AE' THEN 2375
      WHEN 'KR' THEN 2375
      WHEN 'IT' THEN 2250
      WHEN 'ES' THEN 2125
      WHEN 'NZ' THEN 2750
      WHEN 'PT' THEN 1750
      WHEN 'GR' THEN 1625
      WHEN 'CZ' THEN 1500
      WHEN 'PL' THEN 1375
      WHEN 'HU' THEN 1375
      WHEN 'CL' THEN 1375
      WHEN 'CN' THEN 1375
      WHEN 'MY' THEN 1250
      WHEN 'MX' THEN 1250
      WHEN 'AR' THEN 1125
      WHEN 'BR' THEN 1125
      WHEN 'ZA' THEN 1125
      WHEN 'TH' THEN 1125
      WHEN 'TR' THEN 1000
      WHEN 'CO' THEN 1000
      WHEN 'PE' THEN 1000
      WHEN 'PH' THEN 1000
      WHEN 'MA' THEN 875
      WHEN 'IN' THEN 750
      WHEN 'ID' THEN 750
      WHEN 'VN' THEN 750
      WHEN 'EG' THEN 750
      WHEN 'KE' THEN 750
      WHEN 'NG' THEN 625
      WHEN 'PK' THEN 625
      WHEN 'BD' THEN 625
      ELSE 1250
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 60000
      WHEN 'CH' THEN 84000
      WHEN 'NO' THEN 78000
      WHEN 'JP' THEN 78000
      WHEN 'SG' THEN 72000
      WHEN 'AU' THEN 75000
      WHEN 'GB' THEN 72000
      WHEN 'DE' THEN 69000
      WHEN 'FR' THEN 66000
      WHEN 'NL' THEN 69000
      WHEN 'SE' THEN 72000
      WHEN 'CA' THEN 63000
      WHEN 'AT' THEN 66000
      WHEN 'DK' THEN 72000
      WHEN 'FI' THEN 69000
      WHEN 'BE' THEN 69000
      WHEN 'IE' THEN 66000
      WHEN 'IL' THEN 60000
      WHEN 'AE' THEN 57000
      WHEN 'KR' THEN 57000
      WHEN 'IT' THEN 54000
      WHEN 'ES' THEN 51000
      WHEN 'NZ' THEN 66000
      WHEN 'PT' THEN 42000
      WHEN 'GR' THEN 39000
      WHEN 'CZ' THEN 36000
      WHEN 'PL' THEN 33000
      WHEN 'HU' THEN 33000
      WHEN 'CL' THEN 33000
      WHEN 'CN' THEN 33000
      WHEN 'MY' THEN 30000
      WHEN 'MX' THEN 30000
      WHEN 'AR' THEN 27000
      WHEN 'BR' THEN 27000
      WHEN 'ZA' THEN 27000
      WHEN 'TH' THEN 27000
      WHEN 'TR' THEN 24000
      WHEN 'CO' THEN 24000
      WHEN 'PE' THEN 24000
      WHEN 'PH' THEN 24000
      WHEN 'MA' THEN 21000
      WHEN 'IN' THEN 18000
      WHEN 'ID' THEN 18000
      WHEN 'VN' THEN 18000
      WHEN 'EG' THEN 18000
      WHEN 'KE' THEN 18000
      WHEN 'NG' THEN 15000
      WHEN 'PK' THEN 15000
      WHEN 'BD' THEN 15000
      ELSE 30000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 25000
      WHEN 'CH' THEN 35000
      WHEN 'NO' THEN 32500
      WHEN 'JP' THEN 32500
      WHEN 'SG' THEN 30000
      WHEN 'AU' THEN 31250
      WHEN 'GB' THEN 30000
      WHEN 'DE' THEN 28750
      WHEN 'FR' THEN 27500
      WHEN 'NL' THEN 28750
      WHEN 'SE' THEN 30000
      WHEN 'CA' THEN 26250
      WHEN 'AT' THEN 27500
      WHEN 'DK' THEN 30000
      WHEN 'FI' THEN 28750
      WHEN 'BE' THEN 28750
      WHEN 'IE' THEN 27500
      WHEN 'IL' THEN 25000
      WHEN 'AE' THEN 23750
      WHEN 'KR' THEN 23750
      WHEN 'IT' THEN 22500
      WHEN 'ES' THEN 21250
      WHEN 'NZ' THEN 27500
      WHEN 'PT' THEN 17500
      WHEN 'GR' THEN 16250
      WHEN 'CZ' THEN 15000
      WHEN 'PL' THEN 13750
      WHEN 'HU' THEN 13750
      WHEN 'CL' THEN 13750
      WHEN 'CN' THEN 13750
      WHEN 'MY' THEN 12500
      WHEN 'MX' THEN 12500
      WHEN 'AR' THEN 11250
      WHEN 'BR' THEN 11250
      WHEN 'ZA' THEN 11250
      WHEN 'TH' THEN 11250
      WHEN 'TR' THEN 10000
      WHEN 'CO' THEN 10000
      WHEN 'PE' THEN 10000
      WHEN 'PH' THEN 10000
      WHEN 'MA' THEN 8750
      WHEN 'IN' THEN 7500
      WHEN 'ID' THEN 7500
      WHEN 'VN' THEN 7500
      WHEN 'EG' THEN 7500
      WHEN 'KE' THEN 7500
      WHEN 'NG' THEN 6250
      WHEN 'PK' THEN 6250
      WHEN 'BD' THEN 6250
      ELSE 12500
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 6000
      WHEN 'CH' THEN 8400
      WHEN 'NO' THEN 7800
      WHEN 'JP' THEN 7800
      WHEN 'SG' THEN 7200
      WHEN 'AU' THEN 7500
      WHEN 'GB' THEN 7200
      WHEN 'DE' THEN 6900
      WHEN 'FR' THEN 6600
      WHEN 'NL' THEN 6900
      WHEN 'SE' THEN 7200
      WHEN 'CA' THEN 6300
      WHEN 'AT' THEN 6600
      WHEN 'DK' THEN 7200
      WHEN 'FI' THEN 6900
      WHEN 'BE' THEN 6900
      WHEN 'IE' THEN 6600
      WHEN 'IL' THEN 6000
      WHEN 'AE' THEN 5700
      WHEN 'KR' THEN 5700
      WHEN 'IT' THEN 5400
      WHEN 'ES' THEN 5100
      WHEN 'NZ' THEN 6600
      WHEN 'PT' THEN 4200
      WHEN 'GR' THEN 3900
      WHEN 'CZ' THEN 3600
      WHEN 'PL' THEN 3300
      WHEN 'HU' THEN 3300
      WHEN 'CL' THEN 3300
      WHEN 'CN' THEN 3300
      WHEN 'MY' THEN 3000
      WHEN 'MX' THEN 3000
      WHEN 'AR' THEN 2700
      WHEN 'BR' THEN 2700
      WHEN 'ZA' THEN 2700
      WHEN 'TH' THEN 2700
      WHEN 'TR' THEN 2400
      WHEN 'CO' THEN 2400
      WHEN 'PE' THEN 2400
      WHEN 'PH' THEN 2400
      WHEN 'MA' THEN 2100
      WHEN 'IN' THEN 1800
      WHEN 'ID' THEN 1800
      WHEN 'VN' THEN 1800
      WHEN 'EG' THEN 1800
      WHEN 'KE' THEN 1800
      WHEN 'NG' THEN 1500
      WHEN 'PK' THEN 1500
      WHEN 'BD' THEN 1500
      ELSE 3000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 100000
      WHEN 'CH' THEN 140000
      WHEN 'NO' THEN 130000
      WHEN 'JP' THEN 130000
      WHEN 'SG' THEN 120000
      WHEN 'AU' THEN 125000
      WHEN 'GB' THEN 120000
      WHEN 'DE' THEN 115000
      WHEN 'FR' THEN 110000
      WHEN 'NL' THEN 115000
      WHEN 'SE' THEN 120000
      WHEN 'CA' THEN 105000
      WHEN 'AT' THEN 110000
      WHEN 'DK' THEN 120000
      WHEN 'FI' THEN 115000
      WHEN 'BE' THEN 115000
      WHEN 'IE' THEN 110000
      WHEN 'IL' THEN 100000
      WHEN 'AE' THEN 95000
      WHEN 'KR' THEN 95000
      WHEN 'IT' THEN 90000
      WHEN 'ES' THEN 85000
      WHEN 'NZ' THEN 110000
      WHEN 'PT' THEN 70000
      WHEN 'GR' THEN 65000
      WHEN 'CZ' THEN 60000
      WHEN 'PL' THEN 55000
      WHEN 'HU' THEN 55000
      WHEN 'CL' THEN 55000
      WHEN 'CN' THEN 55000
      WHEN 'MY' THEN 50000
      WHEN 'MX' THEN 50000
      WHEN 'AR' THEN 45000
      WHEN 'BR' THEN 45000
      WHEN 'ZA' THEN 45000
      WHEN 'TH' THEN 45000
      WHEN 'TR' THEN 40000
      WHEN 'CO' THEN 40000
      WHEN 'PE' THEN 40000
      WHEN 'PH' THEN 40000
      WHEN 'MA' THEN 35000
      WHEN 'IN' THEN 30000
      WHEN 'ID' THEN 30000
      WHEN 'VN' THEN 30000
      WHEN 'EG' THEN 30000
      WHEN 'KE' THEN 30000
      WHEN 'NG' THEN 25000
      WHEN 'PK' THEN 25000
      WHEN 'BD' THEN 25000
      ELSE 50000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'hairdressers_beauty'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 812112)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.12),
  'payroll_total',          ROUND(rev_p50 * 0.45),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.12),
  'utilities',              ROUND(rev_p50 * 0.03),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Hair salon industry benchmarks 2024 (Homebase, FinancialModelsLab, BusinessDojo). US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('812112')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 2500
      WHEN 'CH' THEN 3500
      WHEN 'NO' THEN 3250
      WHEN 'JP' THEN 3250
      WHEN 'SG' THEN 3000
      WHEN 'AU' THEN 3125
      WHEN 'GB' THEN 3000
      WHEN 'DE' THEN 2875
      WHEN 'FR' THEN 2750
      WHEN 'NL' THEN 2875
      WHEN 'SE' THEN 3000
      WHEN 'CA' THEN 2625
      WHEN 'AT' THEN 2750
      WHEN 'DK' THEN 3000
      WHEN 'FI' THEN 2875
      WHEN 'BE' THEN 2875
      WHEN 'IE' THEN 2750
      WHEN 'IL' THEN 2500
      WHEN 'AE' THEN 2375
      WHEN 'KR' THEN 2375
      WHEN 'IT' THEN 2250
      WHEN 'ES' THEN 2125
      WHEN 'NZ' THEN 2750
      WHEN 'PT' THEN 1750
      WHEN 'GR' THEN 1625
      WHEN 'CZ' THEN 1500
      WHEN 'PL' THEN 1375
      WHEN 'HU' THEN 1375
      WHEN 'CL' THEN 1375
      WHEN 'CN' THEN 1375
      WHEN 'MY' THEN 1250
      WHEN 'MX' THEN 1250
      WHEN 'AR' THEN 1125
      WHEN 'BR' THEN 1125
      WHEN 'ZA' THEN 1125
      WHEN 'TH' THEN 1125
      WHEN 'TR' THEN 1000
      WHEN 'CO' THEN 1000
      WHEN 'PE' THEN 1000
      WHEN 'PH' THEN 1000
      WHEN 'MA' THEN 875
      WHEN 'IN' THEN 750
      WHEN 'ID' THEN 750
      WHEN 'VN' THEN 750
      WHEN 'EG' THEN 750
      WHEN 'KE' THEN 750
      WHEN 'NG' THEN 625
      WHEN 'PK' THEN 625
      WHEN 'BD' THEN 625
      ELSE 1250
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 60000
      WHEN 'CH' THEN 84000
      WHEN 'NO' THEN 78000
      WHEN 'JP' THEN 78000
      WHEN 'SG' THEN 72000
      WHEN 'AU' THEN 75000
      WHEN 'GB' THEN 72000
      WHEN 'DE' THEN 69000
      WHEN 'FR' THEN 66000
      WHEN 'NL' THEN 69000
      WHEN 'SE' THEN 72000
      WHEN 'CA' THEN 63000
      WHEN 'AT' THEN 66000
      WHEN 'DK' THEN 72000
      WHEN 'FI' THEN 69000
      WHEN 'BE' THEN 69000
      WHEN 'IE' THEN 66000
      WHEN 'IL' THEN 60000
      WHEN 'AE' THEN 57000
      WHEN 'KR' THEN 57000
      WHEN 'IT' THEN 54000
      WHEN 'ES' THEN 51000
      WHEN 'NZ' THEN 66000
      WHEN 'PT' THEN 42000
      WHEN 'GR' THEN 39000
      WHEN 'CZ' THEN 36000
      WHEN 'PL' THEN 33000
      WHEN 'HU' THEN 33000
      WHEN 'CL' THEN 33000
      WHEN 'CN' THEN 33000
      WHEN 'MY' THEN 30000
      WHEN 'MX' THEN 30000
      WHEN 'AR' THEN 27000
      WHEN 'BR' THEN 27000
      WHEN 'ZA' THEN 27000
      WHEN 'TH' THEN 27000
      WHEN 'TR' THEN 24000
      WHEN 'CO' THEN 24000
      WHEN 'PE' THEN 24000
      WHEN 'PH' THEN 24000
      WHEN 'MA' THEN 21000
      WHEN 'IN' THEN 18000
      WHEN 'ID' THEN 18000
      WHEN 'VN' THEN 18000
      WHEN 'EG' THEN 18000
      WHEN 'KE' THEN 18000
      WHEN 'NG' THEN 15000
      WHEN 'PK' THEN 15000
      WHEN 'BD' THEN 15000
      ELSE 30000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 25000
      WHEN 'CH' THEN 35000
      WHEN 'NO' THEN 32500
      WHEN 'JP' THEN 32500
      WHEN 'SG' THEN 30000
      WHEN 'AU' THEN 31250
      WHEN 'GB' THEN 30000
      WHEN 'DE' THEN 28750
      WHEN 'FR' THEN 27500
      WHEN 'NL' THEN 28750
      WHEN 'SE' THEN 30000
      WHEN 'CA' THEN 26250
      WHEN 'AT' THEN 27500
      WHEN 'DK' THEN 30000
      WHEN 'FI' THEN 28750
      WHEN 'BE' THEN 28750
      WHEN 'IE' THEN 27500
      WHEN 'IL' THEN 25000
      WHEN 'AE' THEN 23750
      WHEN 'KR' THEN 23750
      WHEN 'IT' THEN 22500
      WHEN 'ES' THEN 21250
      WHEN 'NZ' THEN 27500
      WHEN 'PT' THEN 17500
      WHEN 'GR' THEN 16250
      WHEN 'CZ' THEN 15000
      WHEN 'PL' THEN 13750
      WHEN 'HU' THEN 13750
      WHEN 'CL' THEN 13750
      WHEN 'CN' THEN 13750
      WHEN 'MY' THEN 12500
      WHEN 'MX' THEN 12500
      WHEN 'AR' THEN 11250
      WHEN 'BR' THEN 11250
      WHEN 'ZA' THEN 11250
      WHEN 'TH' THEN 11250
      WHEN 'TR' THEN 10000
      WHEN 'CO' THEN 10000
      WHEN 'PE' THEN 10000
      WHEN 'PH' THEN 10000
      WHEN 'MA' THEN 8750
      WHEN 'IN' THEN 7500
      WHEN 'ID' THEN 7500
      WHEN 'VN' THEN 7500
      WHEN 'EG' THEN 7500
      WHEN 'KE' THEN 7500
      WHEN 'NG' THEN 6250
      WHEN 'PK' THEN 6250
      WHEN 'BD' THEN 6250
      ELSE 12500
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 6000
      WHEN 'CH' THEN 8400
      WHEN 'NO' THEN 7800
      WHEN 'JP' THEN 7800
      WHEN 'SG' THEN 7200
      WHEN 'AU' THEN 7500
      WHEN 'GB' THEN 7200
      WHEN 'DE' THEN 6900
      WHEN 'FR' THEN 6600
      WHEN 'NL' THEN 6900
      WHEN 'SE' THEN 7200
      WHEN 'CA' THEN 6300
      WHEN 'AT' THEN 6600
      WHEN 'DK' THEN 7200
      WHEN 'FI' THEN 6900
      WHEN 'BE' THEN 6900
      WHEN 'IE' THEN 6600
      WHEN 'IL' THEN 6000
      WHEN 'AE' THEN 5700
      WHEN 'KR' THEN 5700
      WHEN 'IT' THEN 5400
      WHEN 'ES' THEN 5100
      WHEN 'NZ' THEN 6600
      WHEN 'PT' THEN 4200
      WHEN 'GR' THEN 3900
      WHEN 'CZ' THEN 3600
      WHEN 'PL' THEN 3300
      WHEN 'HU' THEN 3300
      WHEN 'CL' THEN 3300
      WHEN 'CN' THEN 3300
      WHEN 'MY' THEN 3000
      WHEN 'MX' THEN 3000
      WHEN 'AR' THEN 2700
      WHEN 'BR' THEN 2700
      WHEN 'ZA' THEN 2700
      WHEN 'TH' THEN 2700
      WHEN 'TR' THEN 2400
      WHEN 'CO' THEN 2400
      WHEN 'PE' THEN 2400
      WHEN 'PH' THEN 2400
      WHEN 'MA' THEN 2100
      WHEN 'IN' THEN 1800
      WHEN 'ID' THEN 1800
      WHEN 'VN' THEN 1800
      WHEN 'EG' THEN 1800
      WHEN 'KE' THEN 1800
      WHEN 'NG' THEN 1500
      WHEN 'PK' THEN 1500
      WHEN 'BD' THEN 1500
      ELSE 3000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 100000
      WHEN 'CH' THEN 140000
      WHEN 'NO' THEN 130000
      WHEN 'JP' THEN 130000
      WHEN 'SG' THEN 120000
      WHEN 'AU' THEN 125000
      WHEN 'GB' THEN 120000
      WHEN 'DE' THEN 115000
      WHEN 'FR' THEN 110000
      WHEN 'NL' THEN 115000
      WHEN 'SE' THEN 120000
      WHEN 'CA' THEN 105000
      WHEN 'AT' THEN 110000
      WHEN 'DK' THEN 120000
      WHEN 'FI' THEN 115000
      WHEN 'BE' THEN 115000
      WHEN 'IE' THEN 110000
      WHEN 'IL' THEN 100000
      WHEN 'AE' THEN 95000
      WHEN 'KR' THEN 95000
      WHEN 'IT' THEN 90000
      WHEN 'ES' THEN 85000
      WHEN 'NZ' THEN 110000
      WHEN 'PT' THEN 70000
      WHEN 'GR' THEN 65000
      WHEN 'CZ' THEN 60000
      WHEN 'PL' THEN 55000
      WHEN 'HU' THEN 55000
      WHEN 'CL' THEN 55000
      WHEN 'CN' THEN 55000
      WHEN 'MY' THEN 50000
      WHEN 'MX' THEN 50000
      WHEN 'AR' THEN 45000
      WHEN 'BR' THEN 45000
      WHEN 'ZA' THEN 45000
      WHEN 'TH' THEN 45000
      WHEN 'TR' THEN 40000
      WHEN 'CO' THEN 40000
      WHEN 'PE' THEN 40000
      WHEN 'PH' THEN 40000
      WHEN 'MA' THEN 35000
      WHEN 'IN' THEN 30000
      WHEN 'ID' THEN 30000
      WHEN 'VN' THEN 30000
      WHEN 'EG' THEN 30000
      WHEN 'KE' THEN 30000
      WHEN 'NG' THEN 25000
      WHEN 'PK' THEN 25000
      WHEN 'BD' THEN 25000
      ELSE 50000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('812112')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.12),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.45),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.12),
  'utilities',              ROUND(predicted_rev_per_firm * 0.03),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.03),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.04),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.02),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'Hair salon industry benchmarks 2024 (Homebase, FinancialModelsLab, BusinessDojo). Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'hairdressers_beauty'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
