-- ============================================================================
-- BULK IMPORT: hotels_lodging cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: AHLA / STR 2024 industry benchmarks + hospitality cost studies (CBRE 2024).
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.32),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.12),
  'utilities',              ROUND(rev_p50 * 0.07),
  'marketing_acquisition',  ROUND(rev_p50 * 0.06),
  'insurance_professional', ROUND(rev_p50 * 0.05),
  'equipment_maintenance',  ROUND(rev_p50 * 0.06),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AHLA / STR 2024 industry benchmarks + hospitality cost studies (CBRE 2024). Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'hotels_lodging'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 10000
      WHEN 'CH' THEN 14000
      WHEN 'NO' THEN 13000
      WHEN 'JP' THEN 13000
      WHEN 'SG' THEN 12000
      WHEN 'AU' THEN 12500
      WHEN 'GB' THEN 12000
      WHEN 'DE' THEN 11500
      WHEN 'FR' THEN 11000
      WHEN 'NL' THEN 11500
      WHEN 'SE' THEN 12000
      WHEN 'CA' THEN 10500
      WHEN 'AT' THEN 11000
      WHEN 'DK' THEN 12000
      WHEN 'FI' THEN 11500
      WHEN 'BE' THEN 11500
      WHEN 'IE' THEN 11000
      WHEN 'IL' THEN 10000
      WHEN 'AE' THEN 9500
      WHEN 'KR' THEN 9500
      WHEN 'IT' THEN 9000
      WHEN 'ES' THEN 8500
      WHEN 'NZ' THEN 11000
      WHEN 'PT' THEN 7000
      WHEN 'GR' THEN 6500
      WHEN 'CZ' THEN 6000
      WHEN 'PL' THEN 5500
      WHEN 'HU' THEN 5500
      WHEN 'CL' THEN 5500
      WHEN 'CN' THEN 5500
      WHEN 'MY' THEN 5000
      WHEN 'MX' THEN 5000
      WHEN 'AR' THEN 4500
      WHEN 'BR' THEN 4500
      WHEN 'ZA' THEN 4500
      WHEN 'TH' THEN 4500
      WHEN 'TR' THEN 4000
      WHEN 'CO' THEN 4000
      WHEN 'PE' THEN 4000
      WHEN 'PH' THEN 4000
      WHEN 'MA' THEN 3500
      WHEN 'IN' THEN 3000
      WHEN 'ID' THEN 3000
      WHEN 'VN' THEN 3000
      WHEN 'EG' THEN 3000
      WHEN 'KE' THEN 3000
      WHEN 'NG' THEN 2500
      WHEN 'PK' THEN 2500
      WHEN 'BD' THEN 2500
      ELSE 5000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 3000000
      WHEN 'CH' THEN 4200000
      WHEN 'NO' THEN 3900000
      WHEN 'JP' THEN 3900000
      WHEN 'SG' THEN 3600000
      WHEN 'AU' THEN 3750000
      WHEN 'GB' THEN 3600000
      WHEN 'DE' THEN 3450000
      WHEN 'FR' THEN 3300000
      WHEN 'NL' THEN 3450000
      WHEN 'SE' THEN 3600000
      WHEN 'CA' THEN 3150000
      WHEN 'AT' THEN 3300000
      WHEN 'DK' THEN 3600000
      WHEN 'FI' THEN 3450000
      WHEN 'BE' THEN 3450000
      WHEN 'IE' THEN 3300000
      WHEN 'IL' THEN 3000000
      WHEN 'AE' THEN 2850000
      WHEN 'KR' THEN 2850000
      WHEN 'IT' THEN 2700000
      WHEN 'ES' THEN 2550000
      WHEN 'NZ' THEN 3300000
      WHEN 'PT' THEN 2100000
      WHEN 'GR' THEN 1950000
      WHEN 'CZ' THEN 1800000
      WHEN 'PL' THEN 1650000
      WHEN 'HU' THEN 1650000
      WHEN 'CL' THEN 1650000
      WHEN 'CN' THEN 1650000
      WHEN 'MY' THEN 1500000
      WHEN 'MX' THEN 1500000
      WHEN 'AR' THEN 1350000
      WHEN 'BR' THEN 1350000
      WHEN 'ZA' THEN 1350000
      WHEN 'TH' THEN 1350000
      WHEN 'TR' THEN 1200000
      WHEN 'CO' THEN 1200000
      WHEN 'PE' THEN 1200000
      WHEN 'PH' THEN 1200000
      WHEN 'MA' THEN 1050000
      WHEN 'IN' THEN 900000
      WHEN 'ID' THEN 900000
      WHEN 'VN' THEN 900000
      WHEN 'EG' THEN 900000
      WHEN 'KE' THEN 900000
      WHEN 'NG' THEN 750000
      WHEN 'PK' THEN 750000
      WHEN 'BD' THEN 750000
      ELSE 1500000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 1250000
      WHEN 'CH' THEN 1750000
      WHEN 'NO' THEN 1625000
      WHEN 'JP' THEN 1625000
      WHEN 'SG' THEN 1500000
      WHEN 'AU' THEN 1562500
      WHEN 'GB' THEN 1500000
      WHEN 'DE' THEN 1437500
      WHEN 'FR' THEN 1375000
      WHEN 'NL' THEN 1437500
      WHEN 'SE' THEN 1500000
      WHEN 'CA' THEN 1312500
      WHEN 'AT' THEN 1375000
      WHEN 'DK' THEN 1500000
      WHEN 'FI' THEN 1437500
      WHEN 'BE' THEN 1437500
      WHEN 'IE' THEN 1375000
      WHEN 'IL' THEN 1250000
      WHEN 'AE' THEN 1187500
      WHEN 'KR' THEN 1187500
      WHEN 'IT' THEN 1125000
      WHEN 'ES' THEN 1062500
      WHEN 'NZ' THEN 1375000
      WHEN 'PT' THEN 875000
      WHEN 'GR' THEN 812500
      WHEN 'CZ' THEN 750000
      WHEN 'PL' THEN 687500
      WHEN 'HU' THEN 687500
      WHEN 'CL' THEN 687500
      WHEN 'CN' THEN 687500
      WHEN 'MY' THEN 625000
      WHEN 'MX' THEN 625000
      WHEN 'AR' THEN 562500
      WHEN 'BR' THEN 562500
      WHEN 'ZA' THEN 562500
      WHEN 'TH' THEN 562500
      WHEN 'TR' THEN 500000
      WHEN 'CO' THEN 500000
      WHEN 'PE' THEN 500000
      WHEN 'PH' THEN 500000
      WHEN 'MA' THEN 437500
      WHEN 'IN' THEN 375000
      WHEN 'ID' THEN 375000
      WHEN 'VN' THEN 375000
      WHEN 'EG' THEN 375000
      WHEN 'KE' THEN 375000
      WHEN 'NG' THEN 312500
      WHEN 'PK' THEN 312500
      WHEN 'BD' THEN 312500
      ELSE 625000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 6,
    'lease_deposit', CASE country
      WHEN 'US' THEN 300000
      WHEN 'CH' THEN 420000
      WHEN 'NO' THEN 390000
      WHEN 'JP' THEN 390000
      WHEN 'SG' THEN 360000
      WHEN 'AU' THEN 375000
      WHEN 'GB' THEN 360000
      WHEN 'DE' THEN 345000
      WHEN 'FR' THEN 330000
      WHEN 'NL' THEN 345000
      WHEN 'SE' THEN 360000
      WHEN 'CA' THEN 315000
      WHEN 'AT' THEN 330000
      WHEN 'DK' THEN 360000
      WHEN 'FI' THEN 345000
      WHEN 'BE' THEN 345000
      WHEN 'IE' THEN 330000
      WHEN 'IL' THEN 300000
      WHEN 'AE' THEN 285000
      WHEN 'KR' THEN 285000
      WHEN 'IT' THEN 270000
      WHEN 'ES' THEN 255000
      WHEN 'NZ' THEN 330000
      WHEN 'PT' THEN 210000
      WHEN 'GR' THEN 195000
      WHEN 'CZ' THEN 180000
      WHEN 'PL' THEN 165000
      WHEN 'HU' THEN 165000
      WHEN 'CL' THEN 165000
      WHEN 'CN' THEN 165000
      WHEN 'MY' THEN 150000
      WHEN 'MX' THEN 150000
      WHEN 'AR' THEN 135000
      WHEN 'BR' THEN 135000
      WHEN 'ZA' THEN 135000
      WHEN 'TH' THEN 135000
      WHEN 'TR' THEN 120000
      WHEN 'CO' THEN 120000
      WHEN 'PE' THEN 120000
      WHEN 'PH' THEN 120000
      WHEN 'MA' THEN 105000
      WHEN 'IN' THEN 90000
      WHEN 'ID' THEN 90000
      WHEN 'VN' THEN 90000
      WHEN 'EG' THEN 90000
      WHEN 'KE' THEN 90000
      WHEN 'NG' THEN 75000
      WHEN 'PK' THEN 75000
      WHEN 'BD' THEN 75000
      ELSE 150000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000000
      WHEN 'CH' THEN 7000000
      WHEN 'NO' THEN 6500000
      WHEN 'JP' THEN 6500000
      WHEN 'SG' THEN 6000000
      WHEN 'AU' THEN 6250000
      WHEN 'GB' THEN 6000000
      WHEN 'DE' THEN 5750000
      WHEN 'FR' THEN 5500000
      WHEN 'NL' THEN 5750000
      WHEN 'SE' THEN 6000000
      WHEN 'CA' THEN 5250000
      WHEN 'AT' THEN 5500000
      WHEN 'DK' THEN 6000000
      WHEN 'FI' THEN 5750000
      WHEN 'BE' THEN 5750000
      WHEN 'IE' THEN 5500000
      WHEN 'IL' THEN 5000000
      WHEN 'AE' THEN 4750000
      WHEN 'KR' THEN 4750000
      WHEN 'IT' THEN 4500000
      WHEN 'ES' THEN 4250000
      WHEN 'NZ' THEN 5500000
      WHEN 'PT' THEN 3500000
      WHEN 'GR' THEN 3250000
      WHEN 'CZ' THEN 3000000
      WHEN 'PL' THEN 2750000
      WHEN 'HU' THEN 2750000
      WHEN 'CL' THEN 2750000
      WHEN 'CN' THEN 2750000
      WHEN 'MY' THEN 2500000
      WHEN 'MX' THEN 2500000
      WHEN 'AR' THEN 2250000
      WHEN 'BR' THEN 2250000
      WHEN 'ZA' THEN 2250000
      WHEN 'TH' THEN 2250000
      WHEN 'TR' THEN 2000000
      WHEN 'CO' THEN 2000000
      WHEN 'PE' THEN 2000000
      WHEN 'PH' THEN 2000000
      WHEN 'MA' THEN 1750000
      WHEN 'IN' THEN 1500000
      WHEN 'ID' THEN 1500000
      WHEN 'VN' THEN 1500000
      WHEN 'EG' THEN 1500000
      WHEN 'KE' THEN 1500000
      WHEN 'NG' THEN 1250000
      WHEN 'PK' THEN 1250000
      WHEN 'BD' THEN 1250000
      ELSE 2500000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'hotels_lodging'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 721110)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.32),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.12),
  'utilities',              ROUND(rev_p50 * 0.07),
  'marketing_acquisition',  ROUND(rev_p50 * 0.06),
  'insurance_professional', ROUND(rev_p50 * 0.05),
  'equipment_maintenance',  ROUND(rev_p50 * 0.06),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AHLA / STR 2024 industry benchmarks + hospitality cost studies (CBRE 2024). US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('721110')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 10000
      WHEN 'CH' THEN 14000
      WHEN 'NO' THEN 13000
      WHEN 'JP' THEN 13000
      WHEN 'SG' THEN 12000
      WHEN 'AU' THEN 12500
      WHEN 'GB' THEN 12000
      WHEN 'DE' THEN 11500
      WHEN 'FR' THEN 11000
      WHEN 'NL' THEN 11500
      WHEN 'SE' THEN 12000
      WHEN 'CA' THEN 10500
      WHEN 'AT' THEN 11000
      WHEN 'DK' THEN 12000
      WHEN 'FI' THEN 11500
      WHEN 'BE' THEN 11500
      WHEN 'IE' THEN 11000
      WHEN 'IL' THEN 10000
      WHEN 'AE' THEN 9500
      WHEN 'KR' THEN 9500
      WHEN 'IT' THEN 9000
      WHEN 'ES' THEN 8500
      WHEN 'NZ' THEN 11000
      WHEN 'PT' THEN 7000
      WHEN 'GR' THEN 6500
      WHEN 'CZ' THEN 6000
      WHEN 'PL' THEN 5500
      WHEN 'HU' THEN 5500
      WHEN 'CL' THEN 5500
      WHEN 'CN' THEN 5500
      WHEN 'MY' THEN 5000
      WHEN 'MX' THEN 5000
      WHEN 'AR' THEN 4500
      WHEN 'BR' THEN 4500
      WHEN 'ZA' THEN 4500
      WHEN 'TH' THEN 4500
      WHEN 'TR' THEN 4000
      WHEN 'CO' THEN 4000
      WHEN 'PE' THEN 4000
      WHEN 'PH' THEN 4000
      WHEN 'MA' THEN 3500
      WHEN 'IN' THEN 3000
      WHEN 'ID' THEN 3000
      WHEN 'VN' THEN 3000
      WHEN 'EG' THEN 3000
      WHEN 'KE' THEN 3000
      WHEN 'NG' THEN 2500
      WHEN 'PK' THEN 2500
      WHEN 'BD' THEN 2500
      ELSE 5000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 3000000
      WHEN 'CH' THEN 4200000
      WHEN 'NO' THEN 3900000
      WHEN 'JP' THEN 3900000
      WHEN 'SG' THEN 3600000
      WHEN 'AU' THEN 3750000
      WHEN 'GB' THEN 3600000
      WHEN 'DE' THEN 3450000
      WHEN 'FR' THEN 3300000
      WHEN 'NL' THEN 3450000
      WHEN 'SE' THEN 3600000
      WHEN 'CA' THEN 3150000
      WHEN 'AT' THEN 3300000
      WHEN 'DK' THEN 3600000
      WHEN 'FI' THEN 3450000
      WHEN 'BE' THEN 3450000
      WHEN 'IE' THEN 3300000
      WHEN 'IL' THEN 3000000
      WHEN 'AE' THEN 2850000
      WHEN 'KR' THEN 2850000
      WHEN 'IT' THEN 2700000
      WHEN 'ES' THEN 2550000
      WHEN 'NZ' THEN 3300000
      WHEN 'PT' THEN 2100000
      WHEN 'GR' THEN 1950000
      WHEN 'CZ' THEN 1800000
      WHEN 'PL' THEN 1650000
      WHEN 'HU' THEN 1650000
      WHEN 'CL' THEN 1650000
      WHEN 'CN' THEN 1650000
      WHEN 'MY' THEN 1500000
      WHEN 'MX' THEN 1500000
      WHEN 'AR' THEN 1350000
      WHEN 'BR' THEN 1350000
      WHEN 'ZA' THEN 1350000
      WHEN 'TH' THEN 1350000
      WHEN 'TR' THEN 1200000
      WHEN 'CO' THEN 1200000
      WHEN 'PE' THEN 1200000
      WHEN 'PH' THEN 1200000
      WHEN 'MA' THEN 1050000
      WHEN 'IN' THEN 900000
      WHEN 'ID' THEN 900000
      WHEN 'VN' THEN 900000
      WHEN 'EG' THEN 900000
      WHEN 'KE' THEN 900000
      WHEN 'NG' THEN 750000
      WHEN 'PK' THEN 750000
      WHEN 'BD' THEN 750000
      ELSE 1500000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 1250000
      WHEN 'CH' THEN 1750000
      WHEN 'NO' THEN 1625000
      WHEN 'JP' THEN 1625000
      WHEN 'SG' THEN 1500000
      WHEN 'AU' THEN 1562500
      WHEN 'GB' THEN 1500000
      WHEN 'DE' THEN 1437500
      WHEN 'FR' THEN 1375000
      WHEN 'NL' THEN 1437500
      WHEN 'SE' THEN 1500000
      WHEN 'CA' THEN 1312500
      WHEN 'AT' THEN 1375000
      WHEN 'DK' THEN 1500000
      WHEN 'FI' THEN 1437500
      WHEN 'BE' THEN 1437500
      WHEN 'IE' THEN 1375000
      WHEN 'IL' THEN 1250000
      WHEN 'AE' THEN 1187500
      WHEN 'KR' THEN 1187500
      WHEN 'IT' THEN 1125000
      WHEN 'ES' THEN 1062500
      WHEN 'NZ' THEN 1375000
      WHEN 'PT' THEN 875000
      WHEN 'GR' THEN 812500
      WHEN 'CZ' THEN 750000
      WHEN 'PL' THEN 687500
      WHEN 'HU' THEN 687500
      WHEN 'CL' THEN 687500
      WHEN 'CN' THEN 687500
      WHEN 'MY' THEN 625000
      WHEN 'MX' THEN 625000
      WHEN 'AR' THEN 562500
      WHEN 'BR' THEN 562500
      WHEN 'ZA' THEN 562500
      WHEN 'TH' THEN 562500
      WHEN 'TR' THEN 500000
      WHEN 'CO' THEN 500000
      WHEN 'PE' THEN 500000
      WHEN 'PH' THEN 500000
      WHEN 'MA' THEN 437500
      WHEN 'IN' THEN 375000
      WHEN 'ID' THEN 375000
      WHEN 'VN' THEN 375000
      WHEN 'EG' THEN 375000
      WHEN 'KE' THEN 375000
      WHEN 'NG' THEN 312500
      WHEN 'PK' THEN 312500
      WHEN 'BD' THEN 312500
      ELSE 625000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 6,
    'lease_deposit', CASE country
      WHEN 'US' THEN 300000
      WHEN 'CH' THEN 420000
      WHEN 'NO' THEN 390000
      WHEN 'JP' THEN 390000
      WHEN 'SG' THEN 360000
      WHEN 'AU' THEN 375000
      WHEN 'GB' THEN 360000
      WHEN 'DE' THEN 345000
      WHEN 'FR' THEN 330000
      WHEN 'NL' THEN 345000
      WHEN 'SE' THEN 360000
      WHEN 'CA' THEN 315000
      WHEN 'AT' THEN 330000
      WHEN 'DK' THEN 360000
      WHEN 'FI' THEN 345000
      WHEN 'BE' THEN 345000
      WHEN 'IE' THEN 330000
      WHEN 'IL' THEN 300000
      WHEN 'AE' THEN 285000
      WHEN 'KR' THEN 285000
      WHEN 'IT' THEN 270000
      WHEN 'ES' THEN 255000
      WHEN 'NZ' THEN 330000
      WHEN 'PT' THEN 210000
      WHEN 'GR' THEN 195000
      WHEN 'CZ' THEN 180000
      WHEN 'PL' THEN 165000
      WHEN 'HU' THEN 165000
      WHEN 'CL' THEN 165000
      WHEN 'CN' THEN 165000
      WHEN 'MY' THEN 150000
      WHEN 'MX' THEN 150000
      WHEN 'AR' THEN 135000
      WHEN 'BR' THEN 135000
      WHEN 'ZA' THEN 135000
      WHEN 'TH' THEN 135000
      WHEN 'TR' THEN 120000
      WHEN 'CO' THEN 120000
      WHEN 'PE' THEN 120000
      WHEN 'PH' THEN 120000
      WHEN 'MA' THEN 105000
      WHEN 'IN' THEN 90000
      WHEN 'ID' THEN 90000
      WHEN 'VN' THEN 90000
      WHEN 'EG' THEN 90000
      WHEN 'KE' THEN 90000
      WHEN 'NG' THEN 75000
      WHEN 'PK' THEN 75000
      WHEN 'BD' THEN 75000
      ELSE 150000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000000
      WHEN 'CH' THEN 7000000
      WHEN 'NO' THEN 6500000
      WHEN 'JP' THEN 6500000
      WHEN 'SG' THEN 6000000
      WHEN 'AU' THEN 6250000
      WHEN 'GB' THEN 6000000
      WHEN 'DE' THEN 5750000
      WHEN 'FR' THEN 5500000
      WHEN 'NL' THEN 5750000
      WHEN 'SE' THEN 6000000
      WHEN 'CA' THEN 5250000
      WHEN 'AT' THEN 5500000
      WHEN 'DK' THEN 6000000
      WHEN 'FI' THEN 5750000
      WHEN 'BE' THEN 5750000
      WHEN 'IE' THEN 5500000
      WHEN 'IL' THEN 5000000
      WHEN 'AE' THEN 4750000
      WHEN 'KR' THEN 4750000
      WHEN 'IT' THEN 4500000
      WHEN 'ES' THEN 4250000
      WHEN 'NZ' THEN 5500000
      WHEN 'PT' THEN 3500000
      WHEN 'GR' THEN 3250000
      WHEN 'CZ' THEN 3000000
      WHEN 'PL' THEN 2750000
      WHEN 'HU' THEN 2750000
      WHEN 'CL' THEN 2750000
      WHEN 'CN' THEN 2750000
      WHEN 'MY' THEN 2500000
      WHEN 'MX' THEN 2500000
      WHEN 'AR' THEN 2250000
      WHEN 'BR' THEN 2250000
      WHEN 'ZA' THEN 2250000
      WHEN 'TH' THEN 2250000
      WHEN 'TR' THEN 2000000
      WHEN 'CO' THEN 2000000
      WHEN 'PE' THEN 2000000
      WHEN 'PH' THEN 2000000
      WHEN 'MA' THEN 1750000
      WHEN 'IN' THEN 1500000
      WHEN 'ID' THEN 1500000
      WHEN 'VN' THEN 1500000
      WHEN 'EG' THEN 1500000
      WHEN 'KE' THEN 1500000
      WHEN 'NG' THEN 1250000
      WHEN 'PK' THEN 1250000
      WHEN 'BD' THEN 1250000
      ELSE 2500000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('721110')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.08),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.32),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.12),
  'utilities',              ROUND(predicted_rev_per_firm * 0.07),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.06),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.05),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.06),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AHLA / STR 2024 industry benchmarks + hospitality cost studies (CBRE 2024). Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'hotels_lodging'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
