-- ============================================================================
-- BULK IMPORT: legal_services cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: ABA Profile of the Legal Profession 2024 + Clio Legal Trends Report 2024.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.1),
  'payroll_total',          ROUND(rev_p50 * 0.45),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.01),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.05),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ABA Profile of the Legal Profession 2024 + Clio Legal Trends Report 2024. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'legal_services'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 4000
      WHEN 'CH' THEN 5600
      WHEN 'NO' THEN 5200
      WHEN 'JP' THEN 5200
      WHEN 'SG' THEN 4800
      WHEN 'AU' THEN 5000
      WHEN 'GB' THEN 4800
      WHEN 'DE' THEN 4600
      WHEN 'FR' THEN 4400
      WHEN 'NL' THEN 4600
      WHEN 'SE' THEN 4800
      WHEN 'CA' THEN 4200
      WHEN 'AT' THEN 4400
      WHEN 'DK' THEN 4800
      WHEN 'FI' THEN 4600
      WHEN 'BE' THEN 4600
      WHEN 'IE' THEN 4400
      WHEN 'IL' THEN 4000
      WHEN 'AE' THEN 3800
      WHEN 'KR' THEN 3800
      WHEN 'IT' THEN 3600
      WHEN 'ES' THEN 3400
      WHEN 'NZ' THEN 4400
      WHEN 'PT' THEN 2800
      WHEN 'GR' THEN 2600
      WHEN 'CZ' THEN 2400
      WHEN 'PL' THEN 2200
      WHEN 'HU' THEN 2200
      WHEN 'CL' THEN 2200
      WHEN 'CN' THEN 2200
      WHEN 'MY' THEN 2000
      WHEN 'MX' THEN 2000
      WHEN 'AR' THEN 1800
      WHEN 'BR' THEN 1800
      WHEN 'ZA' THEN 1800
      WHEN 'TH' THEN 1800
      WHEN 'TR' THEN 1600
      WHEN 'CO' THEN 1600
      WHEN 'PE' THEN 1600
      WHEN 'PH' THEN 1600
      WHEN 'MA' THEN 1400
      WHEN 'IN' THEN 1200
      WHEN 'ID' THEN 1200
      WHEN 'VN' THEN 1200
      WHEN 'EG' THEN 1200
      WHEN 'KE' THEN 1200
      WHEN 'NG' THEN 1000
      WHEN 'PK' THEN 1000
      WHEN 'BD' THEN 1000
      ELSE 2000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 48000
      WHEN 'CH' THEN 67200
      WHEN 'NO' THEN 62400
      WHEN 'JP' THEN 62400
      WHEN 'SG' THEN 57600
      WHEN 'AU' THEN 60000
      WHEN 'GB' THEN 57600
      WHEN 'DE' THEN 55200
      WHEN 'FR' THEN 52800
      WHEN 'NL' THEN 55200
      WHEN 'SE' THEN 57600
      WHEN 'CA' THEN 50400
      WHEN 'AT' THEN 52800
      WHEN 'DK' THEN 57600
      WHEN 'FI' THEN 55200
      WHEN 'BE' THEN 55200
      WHEN 'IE' THEN 52800
      WHEN 'IL' THEN 48000
      WHEN 'AE' THEN 45600
      WHEN 'KR' THEN 45600
      WHEN 'IT' THEN 43200
      WHEN 'ES' THEN 40800
      WHEN 'NZ' THEN 52800
      WHEN 'PT' THEN 33600
      WHEN 'GR' THEN 31200
      WHEN 'CZ' THEN 28800
      WHEN 'PL' THEN 26400
      WHEN 'HU' THEN 26400
      WHEN 'CL' THEN 26400
      WHEN 'CN' THEN 26400
      WHEN 'MY' THEN 24000
      WHEN 'MX' THEN 24000
      WHEN 'AR' THEN 21600
      WHEN 'BR' THEN 21600
      WHEN 'ZA' THEN 21600
      WHEN 'TH' THEN 21600
      WHEN 'TR' THEN 19200
      WHEN 'CO' THEN 19200
      WHEN 'PE' THEN 19200
      WHEN 'PH' THEN 19200
      WHEN 'MA' THEN 16800
      WHEN 'IN' THEN 14400
      WHEN 'ID' THEN 14400
      WHEN 'VN' THEN 14400
      WHEN 'EG' THEN 14400
      WHEN 'KE' THEN 14400
      WHEN 'NG' THEN 12000
      WHEN 'PK' THEN 12000
      WHEN 'BD' THEN 12000
      ELSE 24000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 20000
      WHEN 'CH' THEN 28000
      WHEN 'NO' THEN 26000
      WHEN 'JP' THEN 26000
      WHEN 'SG' THEN 24000
      WHEN 'AU' THEN 25000
      WHEN 'GB' THEN 24000
      WHEN 'DE' THEN 23000
      WHEN 'FR' THEN 22000
      WHEN 'NL' THEN 23000
      WHEN 'SE' THEN 24000
      WHEN 'CA' THEN 21000
      WHEN 'AT' THEN 22000
      WHEN 'DK' THEN 24000
      WHEN 'FI' THEN 23000
      WHEN 'BE' THEN 23000
      WHEN 'IE' THEN 22000
      WHEN 'IL' THEN 20000
      WHEN 'AE' THEN 19000
      WHEN 'KR' THEN 19000
      WHEN 'IT' THEN 18000
      WHEN 'ES' THEN 17000
      WHEN 'NZ' THEN 22000
      WHEN 'PT' THEN 14000
      WHEN 'GR' THEN 13000
      WHEN 'CZ' THEN 12000
      WHEN 'PL' THEN 11000
      WHEN 'HU' THEN 11000
      WHEN 'CL' THEN 11000
      WHEN 'CN' THEN 11000
      WHEN 'MY' THEN 10000
      WHEN 'MX' THEN 10000
      WHEN 'AR' THEN 9000
      WHEN 'BR' THEN 9000
      WHEN 'ZA' THEN 9000
      WHEN 'TH' THEN 9000
      WHEN 'TR' THEN 8000
      WHEN 'CO' THEN 8000
      WHEN 'PE' THEN 8000
      WHEN 'PH' THEN 8000
      WHEN 'MA' THEN 7000
      WHEN 'IN' THEN 6000
      WHEN 'ID' THEN 6000
      WHEN 'VN' THEN 6000
      WHEN 'EG' THEN 6000
      WHEN 'KE' THEN 6000
      WHEN 'NG' THEN 5000
      WHEN 'PK' THEN 5000
      WHEN 'BD' THEN 5000
      ELSE 10000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 4800
      WHEN 'CH' THEN 6720
      WHEN 'NO' THEN 6240
      WHEN 'JP' THEN 6240
      WHEN 'SG' THEN 5760
      WHEN 'AU' THEN 6000
      WHEN 'GB' THEN 5760
      WHEN 'DE' THEN 5520
      WHEN 'FR' THEN 5280
      WHEN 'NL' THEN 5520
      WHEN 'SE' THEN 5760
      WHEN 'CA' THEN 5040
      WHEN 'AT' THEN 5280
      WHEN 'DK' THEN 5760
      WHEN 'FI' THEN 5520
      WHEN 'BE' THEN 5520
      WHEN 'IE' THEN 5280
      WHEN 'IL' THEN 4800
      WHEN 'AE' THEN 4560
      WHEN 'KR' THEN 4560
      WHEN 'IT' THEN 4320
      WHEN 'ES' THEN 4080
      WHEN 'NZ' THEN 5280
      WHEN 'PT' THEN 3360
      WHEN 'GR' THEN 3120
      WHEN 'CZ' THEN 2880
      WHEN 'PL' THEN 2640
      WHEN 'HU' THEN 2640
      WHEN 'CL' THEN 2640
      WHEN 'CN' THEN 2640
      WHEN 'MY' THEN 2400
      WHEN 'MX' THEN 2400
      WHEN 'AR' THEN 2160
      WHEN 'BR' THEN 2160
      WHEN 'ZA' THEN 2160
      WHEN 'TH' THEN 2160
      WHEN 'TR' THEN 1920
      WHEN 'CO' THEN 1920
      WHEN 'PE' THEN 1920
      WHEN 'PH' THEN 1920
      WHEN 'MA' THEN 1680
      WHEN 'IN' THEN 1440
      WHEN 'ID' THEN 1440
      WHEN 'VN' THEN 1440
      WHEN 'EG' THEN 1440
      WHEN 'KE' THEN 1440
      WHEN 'NG' THEN 1200
      WHEN 'PK' THEN 1200
      WHEN 'BD' THEN 1200
      ELSE 2400
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 80000
      WHEN 'CH' THEN 112000
      WHEN 'NO' THEN 104000
      WHEN 'JP' THEN 104000
      WHEN 'SG' THEN 96000
      WHEN 'AU' THEN 100000
      WHEN 'GB' THEN 96000
      WHEN 'DE' THEN 92000
      WHEN 'FR' THEN 88000
      WHEN 'NL' THEN 92000
      WHEN 'SE' THEN 96000
      WHEN 'CA' THEN 84000
      WHEN 'AT' THEN 88000
      WHEN 'DK' THEN 96000
      WHEN 'FI' THEN 92000
      WHEN 'BE' THEN 92000
      WHEN 'IE' THEN 88000
      WHEN 'IL' THEN 80000
      WHEN 'AE' THEN 76000
      WHEN 'KR' THEN 76000
      WHEN 'IT' THEN 72000
      WHEN 'ES' THEN 68000
      WHEN 'NZ' THEN 88000
      WHEN 'PT' THEN 56000
      WHEN 'GR' THEN 52000
      WHEN 'CZ' THEN 48000
      WHEN 'PL' THEN 44000
      WHEN 'HU' THEN 44000
      WHEN 'CL' THEN 44000
      WHEN 'CN' THEN 44000
      WHEN 'MY' THEN 40000
      WHEN 'MX' THEN 40000
      WHEN 'AR' THEN 36000
      WHEN 'BR' THEN 36000
      WHEN 'ZA' THEN 36000
      WHEN 'TH' THEN 36000
      WHEN 'TR' THEN 32000
      WHEN 'CO' THEN 32000
      WHEN 'PE' THEN 32000
      WHEN 'PH' THEN 32000
      WHEN 'MA' THEN 28000
      WHEN 'IN' THEN 24000
      WHEN 'ID' THEN 24000
      WHEN 'VN' THEN 24000
      WHEN 'EG' THEN 24000
      WHEN 'KE' THEN 24000
      WHEN 'NG' THEN 20000
      WHEN 'PK' THEN 20000
      WHEN 'BD' THEN 20000
      ELSE 40000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'legal_services'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 541110)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.1),
  'payroll_total',          ROUND(rev_p50 * 0.45),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.01),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.04),
  'insurance_professional', ROUND(rev_p50 * 0.05),
  'equipment_maintenance',  ROUND(rev_p50 * 0.02),
  'regulatory_licensing',   ROUND(rev_p50 * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ABA Profile of the Legal Profession 2024 + Clio Legal Trends Report 2024. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('541110')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 4000
      WHEN 'CH' THEN 5600
      WHEN 'NO' THEN 5200
      WHEN 'JP' THEN 5200
      WHEN 'SG' THEN 4800
      WHEN 'AU' THEN 5000
      WHEN 'GB' THEN 4800
      WHEN 'DE' THEN 4600
      WHEN 'FR' THEN 4400
      WHEN 'NL' THEN 4600
      WHEN 'SE' THEN 4800
      WHEN 'CA' THEN 4200
      WHEN 'AT' THEN 4400
      WHEN 'DK' THEN 4800
      WHEN 'FI' THEN 4600
      WHEN 'BE' THEN 4600
      WHEN 'IE' THEN 4400
      WHEN 'IL' THEN 4000
      WHEN 'AE' THEN 3800
      WHEN 'KR' THEN 3800
      WHEN 'IT' THEN 3600
      WHEN 'ES' THEN 3400
      WHEN 'NZ' THEN 4400
      WHEN 'PT' THEN 2800
      WHEN 'GR' THEN 2600
      WHEN 'CZ' THEN 2400
      WHEN 'PL' THEN 2200
      WHEN 'HU' THEN 2200
      WHEN 'CL' THEN 2200
      WHEN 'CN' THEN 2200
      WHEN 'MY' THEN 2000
      WHEN 'MX' THEN 2000
      WHEN 'AR' THEN 1800
      WHEN 'BR' THEN 1800
      WHEN 'ZA' THEN 1800
      WHEN 'TH' THEN 1800
      WHEN 'TR' THEN 1600
      WHEN 'CO' THEN 1600
      WHEN 'PE' THEN 1600
      WHEN 'PH' THEN 1600
      WHEN 'MA' THEN 1400
      WHEN 'IN' THEN 1200
      WHEN 'ID' THEN 1200
      WHEN 'VN' THEN 1200
      WHEN 'EG' THEN 1200
      WHEN 'KE' THEN 1200
      WHEN 'NG' THEN 1000
      WHEN 'PK' THEN 1000
      WHEN 'BD' THEN 1000
      ELSE 2000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 48000
      WHEN 'CH' THEN 67200
      WHEN 'NO' THEN 62400
      WHEN 'JP' THEN 62400
      WHEN 'SG' THEN 57600
      WHEN 'AU' THEN 60000
      WHEN 'GB' THEN 57600
      WHEN 'DE' THEN 55200
      WHEN 'FR' THEN 52800
      WHEN 'NL' THEN 55200
      WHEN 'SE' THEN 57600
      WHEN 'CA' THEN 50400
      WHEN 'AT' THEN 52800
      WHEN 'DK' THEN 57600
      WHEN 'FI' THEN 55200
      WHEN 'BE' THEN 55200
      WHEN 'IE' THEN 52800
      WHEN 'IL' THEN 48000
      WHEN 'AE' THEN 45600
      WHEN 'KR' THEN 45600
      WHEN 'IT' THEN 43200
      WHEN 'ES' THEN 40800
      WHEN 'NZ' THEN 52800
      WHEN 'PT' THEN 33600
      WHEN 'GR' THEN 31200
      WHEN 'CZ' THEN 28800
      WHEN 'PL' THEN 26400
      WHEN 'HU' THEN 26400
      WHEN 'CL' THEN 26400
      WHEN 'CN' THEN 26400
      WHEN 'MY' THEN 24000
      WHEN 'MX' THEN 24000
      WHEN 'AR' THEN 21600
      WHEN 'BR' THEN 21600
      WHEN 'ZA' THEN 21600
      WHEN 'TH' THEN 21600
      WHEN 'TR' THEN 19200
      WHEN 'CO' THEN 19200
      WHEN 'PE' THEN 19200
      WHEN 'PH' THEN 19200
      WHEN 'MA' THEN 16800
      WHEN 'IN' THEN 14400
      WHEN 'ID' THEN 14400
      WHEN 'VN' THEN 14400
      WHEN 'EG' THEN 14400
      WHEN 'KE' THEN 14400
      WHEN 'NG' THEN 12000
      WHEN 'PK' THEN 12000
      WHEN 'BD' THEN 12000
      ELSE 24000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 20000
      WHEN 'CH' THEN 28000
      WHEN 'NO' THEN 26000
      WHEN 'JP' THEN 26000
      WHEN 'SG' THEN 24000
      WHEN 'AU' THEN 25000
      WHEN 'GB' THEN 24000
      WHEN 'DE' THEN 23000
      WHEN 'FR' THEN 22000
      WHEN 'NL' THEN 23000
      WHEN 'SE' THEN 24000
      WHEN 'CA' THEN 21000
      WHEN 'AT' THEN 22000
      WHEN 'DK' THEN 24000
      WHEN 'FI' THEN 23000
      WHEN 'BE' THEN 23000
      WHEN 'IE' THEN 22000
      WHEN 'IL' THEN 20000
      WHEN 'AE' THEN 19000
      WHEN 'KR' THEN 19000
      WHEN 'IT' THEN 18000
      WHEN 'ES' THEN 17000
      WHEN 'NZ' THEN 22000
      WHEN 'PT' THEN 14000
      WHEN 'GR' THEN 13000
      WHEN 'CZ' THEN 12000
      WHEN 'PL' THEN 11000
      WHEN 'HU' THEN 11000
      WHEN 'CL' THEN 11000
      WHEN 'CN' THEN 11000
      WHEN 'MY' THEN 10000
      WHEN 'MX' THEN 10000
      WHEN 'AR' THEN 9000
      WHEN 'BR' THEN 9000
      WHEN 'ZA' THEN 9000
      WHEN 'TH' THEN 9000
      WHEN 'TR' THEN 8000
      WHEN 'CO' THEN 8000
      WHEN 'PE' THEN 8000
      WHEN 'PH' THEN 8000
      WHEN 'MA' THEN 7000
      WHEN 'IN' THEN 6000
      WHEN 'ID' THEN 6000
      WHEN 'VN' THEN 6000
      WHEN 'EG' THEN 6000
      WHEN 'KE' THEN 6000
      WHEN 'NG' THEN 5000
      WHEN 'PK' THEN 5000
      WHEN 'BD' THEN 5000
      ELSE 10000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 4800
      WHEN 'CH' THEN 6720
      WHEN 'NO' THEN 6240
      WHEN 'JP' THEN 6240
      WHEN 'SG' THEN 5760
      WHEN 'AU' THEN 6000
      WHEN 'GB' THEN 5760
      WHEN 'DE' THEN 5520
      WHEN 'FR' THEN 5280
      WHEN 'NL' THEN 5520
      WHEN 'SE' THEN 5760
      WHEN 'CA' THEN 5040
      WHEN 'AT' THEN 5280
      WHEN 'DK' THEN 5760
      WHEN 'FI' THEN 5520
      WHEN 'BE' THEN 5520
      WHEN 'IE' THEN 5280
      WHEN 'IL' THEN 4800
      WHEN 'AE' THEN 4560
      WHEN 'KR' THEN 4560
      WHEN 'IT' THEN 4320
      WHEN 'ES' THEN 4080
      WHEN 'NZ' THEN 5280
      WHEN 'PT' THEN 3360
      WHEN 'GR' THEN 3120
      WHEN 'CZ' THEN 2880
      WHEN 'PL' THEN 2640
      WHEN 'HU' THEN 2640
      WHEN 'CL' THEN 2640
      WHEN 'CN' THEN 2640
      WHEN 'MY' THEN 2400
      WHEN 'MX' THEN 2400
      WHEN 'AR' THEN 2160
      WHEN 'BR' THEN 2160
      WHEN 'ZA' THEN 2160
      WHEN 'TH' THEN 2160
      WHEN 'TR' THEN 1920
      WHEN 'CO' THEN 1920
      WHEN 'PE' THEN 1920
      WHEN 'PH' THEN 1920
      WHEN 'MA' THEN 1680
      WHEN 'IN' THEN 1440
      WHEN 'ID' THEN 1440
      WHEN 'VN' THEN 1440
      WHEN 'EG' THEN 1440
      WHEN 'KE' THEN 1440
      WHEN 'NG' THEN 1200
      WHEN 'PK' THEN 1200
      WHEN 'BD' THEN 1200
      ELSE 2400
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 80000
      WHEN 'CH' THEN 112000
      WHEN 'NO' THEN 104000
      WHEN 'JP' THEN 104000
      WHEN 'SG' THEN 96000
      WHEN 'AU' THEN 100000
      WHEN 'GB' THEN 96000
      WHEN 'DE' THEN 92000
      WHEN 'FR' THEN 88000
      WHEN 'NL' THEN 92000
      WHEN 'SE' THEN 96000
      WHEN 'CA' THEN 84000
      WHEN 'AT' THEN 88000
      WHEN 'DK' THEN 96000
      WHEN 'FI' THEN 92000
      WHEN 'BE' THEN 92000
      WHEN 'IE' THEN 88000
      WHEN 'IL' THEN 80000
      WHEN 'AE' THEN 76000
      WHEN 'KR' THEN 76000
      WHEN 'IT' THEN 72000
      WHEN 'ES' THEN 68000
      WHEN 'NZ' THEN 88000
      WHEN 'PT' THEN 56000
      WHEN 'GR' THEN 52000
      WHEN 'CZ' THEN 48000
      WHEN 'PL' THEN 44000
      WHEN 'HU' THEN 44000
      WHEN 'CL' THEN 44000
      WHEN 'CN' THEN 44000
      WHEN 'MY' THEN 40000
      WHEN 'MX' THEN 40000
      WHEN 'AR' THEN 36000
      WHEN 'BR' THEN 36000
      WHEN 'ZA' THEN 36000
      WHEN 'TH' THEN 36000
      WHEN 'TR' THEN 32000
      WHEN 'CO' THEN 32000
      WHEN 'PE' THEN 32000
      WHEN 'PH' THEN 32000
      WHEN 'MA' THEN 28000
      WHEN 'IN' THEN 24000
      WHEN 'ID' THEN 24000
      WHEN 'VN' THEN 24000
      WHEN 'EG' THEN 24000
      WHEN 'KE' THEN 24000
      WHEN 'NG' THEN 20000
      WHEN 'PK' THEN 20000
      WHEN 'BD' THEN 20000
      ELSE 40000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('541110')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.1),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.45),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.01),
  'utilities',              ROUND(predicted_rev_per_firm * 0.02),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.04),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.05),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.02),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'ABA Profile of the Legal Profession 2024 + Clio Legal Trends Report 2024. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'legal_services'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
