-- ============================================================================
-- BULK IMPORT: residential_construction cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: NAHB Builder Cost survey 2024 + Construction Financial Management Association data.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.02),
  'payroll_total',          ROUND(rev_p50 * 0.25),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.5),
  'utilities',              ROUND(rev_p50 * 0.01),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.06),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NAHB Builder Cost survey 2024 + Construction Financial Management Association data. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'residential_construction'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 6000
      WHEN 'CH' THEN 8400
      WHEN 'NO' THEN 7800
      WHEN 'JP' THEN 7800
      WHEN 'SG' THEN 7200
      WHEN 'AU' THEN 7500
      WHEN 'GB' THEN 7200
      WHEN 'DE' THEN 6900
      WHEN 'FR' THEN 6600
      WHEN 'NL' THEN 6900
      WHEN 'SE' THEN 7200
      WHEN 'CA' THEN 6300
      WHEN 'AT' THEN 6600
      WHEN 'DK' THEN 7200
      WHEN 'FI' THEN 6900
      WHEN 'BE' THEN 6900
      WHEN 'IE' THEN 6600
      WHEN 'IL' THEN 6000
      WHEN 'AE' THEN 5700
      WHEN 'KR' THEN 5700
      WHEN 'IT' THEN 5400
      WHEN 'ES' THEN 5100
      WHEN 'NZ' THEN 6600
      WHEN 'PT' THEN 4200
      WHEN 'GR' THEN 3900
      WHEN 'CZ' THEN 3600
      WHEN 'PL' THEN 3300
      WHEN 'HU' THEN 3300
      WHEN 'CL' THEN 3300
      WHEN 'CN' THEN 3300
      WHEN 'MY' THEN 3000
      WHEN 'MX' THEN 3000
      WHEN 'AR' THEN 2700
      WHEN 'BR' THEN 2700
      WHEN 'ZA' THEN 2700
      WHEN 'TH' THEN 2700
      WHEN 'TR' THEN 2400
      WHEN 'CO' THEN 2400
      WHEN 'PE' THEN 2400
      WHEN 'PH' THEN 2400
      WHEN 'MA' THEN 2100
      WHEN 'IN' THEN 1800
      WHEN 'ID' THEN 1800
      WHEN 'VN' THEN 1800
      WHEN 'EG' THEN 1800
      WHEN 'KE' THEN 1800
      WHEN 'NG' THEN 1500
      WHEN 'PK' THEN 1500
      WHEN 'BD' THEN 1500
      ELSE 3000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 90000
      WHEN 'CH' THEN 126000
      WHEN 'NO' THEN 117000
      WHEN 'JP' THEN 117000
      WHEN 'SG' THEN 108000
      WHEN 'AU' THEN 112500
      WHEN 'GB' THEN 108000
      WHEN 'DE' THEN 103500
      WHEN 'FR' THEN 99000
      WHEN 'NL' THEN 103500
      WHEN 'SE' THEN 108000
      WHEN 'CA' THEN 94500
      WHEN 'AT' THEN 99000
      WHEN 'DK' THEN 108000
      WHEN 'FI' THEN 103500
      WHEN 'BE' THEN 103500
      WHEN 'IE' THEN 99000
      WHEN 'IL' THEN 90000
      WHEN 'AE' THEN 85500
      WHEN 'KR' THEN 85500
      WHEN 'IT' THEN 81000
      WHEN 'ES' THEN 76500
      WHEN 'NZ' THEN 99000
      WHEN 'PT' THEN 63000
      WHEN 'GR' THEN 58500
      WHEN 'CZ' THEN 54000
      WHEN 'PL' THEN 49500
      WHEN 'HU' THEN 49500
      WHEN 'CL' THEN 49500
      WHEN 'CN' THEN 49500
      WHEN 'MY' THEN 45000
      WHEN 'MX' THEN 45000
      WHEN 'AR' THEN 40500
      WHEN 'BR' THEN 40500
      WHEN 'ZA' THEN 40500
      WHEN 'TH' THEN 40500
      WHEN 'TR' THEN 36000
      WHEN 'CO' THEN 36000
      WHEN 'PE' THEN 36000
      WHEN 'PH' THEN 36000
      WHEN 'MA' THEN 31500
      WHEN 'IN' THEN 27000
      WHEN 'ID' THEN 27000
      WHEN 'VN' THEN 27000
      WHEN 'EG' THEN 27000
      WHEN 'KE' THEN 27000
      WHEN 'NG' THEN 22500
      WHEN 'PK' THEN 22500
      WHEN 'BD' THEN 22500
      ELSE 45000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 37500
      WHEN 'CH' THEN 52500
      WHEN 'NO' THEN 48750
      WHEN 'JP' THEN 48750
      WHEN 'SG' THEN 45000
      WHEN 'AU' THEN 46875
      WHEN 'GB' THEN 45000
      WHEN 'DE' THEN 43125
      WHEN 'FR' THEN 41250
      WHEN 'NL' THEN 43125
      WHEN 'SE' THEN 45000
      WHEN 'CA' THEN 39375
      WHEN 'AT' THEN 41250
      WHEN 'DK' THEN 45000
      WHEN 'FI' THEN 43125
      WHEN 'BE' THEN 43125
      WHEN 'IE' THEN 41250
      WHEN 'IL' THEN 37500
      WHEN 'AE' THEN 35625
      WHEN 'KR' THEN 35625
      WHEN 'IT' THEN 33750
      WHEN 'ES' THEN 31875
      WHEN 'NZ' THEN 41250
      WHEN 'PT' THEN 26250
      WHEN 'GR' THEN 24375
      WHEN 'CZ' THEN 22500
      WHEN 'PL' THEN 20625
      WHEN 'HU' THEN 20625
      WHEN 'CL' THEN 20625
      WHEN 'CN' THEN 20625
      WHEN 'MY' THEN 18750
      WHEN 'MX' THEN 18750
      WHEN 'AR' THEN 16875
      WHEN 'BR' THEN 16875
      WHEN 'ZA' THEN 16875
      WHEN 'TH' THEN 16875
      WHEN 'TR' THEN 15000
      WHEN 'CO' THEN 15000
      WHEN 'PE' THEN 15000
      WHEN 'PH' THEN 15000
      WHEN 'MA' THEN 13125
      WHEN 'IN' THEN 11250
      WHEN 'ID' THEN 11250
      WHEN 'VN' THEN 11250
      WHEN 'EG' THEN 11250
      WHEN 'KE' THEN 11250
      WHEN 'NG' THEN 9375
      WHEN 'PK' THEN 9375
      WHEN 'BD' THEN 9375
      ELSE 18750
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 9000
      WHEN 'CH' THEN 12600
      WHEN 'NO' THEN 11700
      WHEN 'JP' THEN 11700
      WHEN 'SG' THEN 10800
      WHEN 'AU' THEN 11250
      WHEN 'GB' THEN 10800
      WHEN 'DE' THEN 10350
      WHEN 'FR' THEN 9900
      WHEN 'NL' THEN 10350
      WHEN 'SE' THEN 10800
      WHEN 'CA' THEN 9450
      WHEN 'AT' THEN 9900
      WHEN 'DK' THEN 10800
      WHEN 'FI' THEN 10350
      WHEN 'BE' THEN 10350
      WHEN 'IE' THEN 9900
      WHEN 'IL' THEN 9000
      WHEN 'AE' THEN 8550
      WHEN 'KR' THEN 8550
      WHEN 'IT' THEN 8100
      WHEN 'ES' THEN 7650
      WHEN 'NZ' THEN 9900
      WHEN 'PT' THEN 6300
      WHEN 'GR' THEN 5850
      WHEN 'CZ' THEN 5400
      WHEN 'PL' THEN 4950
      WHEN 'HU' THEN 4950
      WHEN 'CL' THEN 4950
      WHEN 'CN' THEN 4950
      WHEN 'MY' THEN 4500
      WHEN 'MX' THEN 4500
      WHEN 'AR' THEN 4050
      WHEN 'BR' THEN 4050
      WHEN 'ZA' THEN 4050
      WHEN 'TH' THEN 4050
      WHEN 'TR' THEN 3600
      WHEN 'CO' THEN 3600
      WHEN 'PE' THEN 3600
      WHEN 'PH' THEN 3600
      WHEN 'MA' THEN 3150
      WHEN 'IN' THEN 2700
      WHEN 'ID' THEN 2700
      WHEN 'VN' THEN 2700
      WHEN 'EG' THEN 2700
      WHEN 'KE' THEN 2700
      WHEN 'NG' THEN 2250
      WHEN 'PK' THEN 2250
      WHEN 'BD' THEN 2250
      ELSE 4500
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 150000
      WHEN 'CH' THEN 210000
      WHEN 'NO' THEN 195000
      WHEN 'JP' THEN 195000
      WHEN 'SG' THEN 180000
      WHEN 'AU' THEN 187500
      WHEN 'GB' THEN 180000
      WHEN 'DE' THEN 172500
      WHEN 'FR' THEN 165000
      WHEN 'NL' THEN 172500
      WHEN 'SE' THEN 180000
      WHEN 'CA' THEN 157500
      WHEN 'AT' THEN 165000
      WHEN 'DK' THEN 180000
      WHEN 'FI' THEN 172500
      WHEN 'BE' THEN 172500
      WHEN 'IE' THEN 165000
      WHEN 'IL' THEN 150000
      WHEN 'AE' THEN 142500
      WHEN 'KR' THEN 142500
      WHEN 'IT' THEN 135000
      WHEN 'ES' THEN 127500
      WHEN 'NZ' THEN 165000
      WHEN 'PT' THEN 105000
      WHEN 'GR' THEN 97500
      WHEN 'CZ' THEN 90000
      WHEN 'PL' THEN 82500
      WHEN 'HU' THEN 82500
      WHEN 'CL' THEN 82500
      WHEN 'CN' THEN 82500
      WHEN 'MY' THEN 75000
      WHEN 'MX' THEN 75000
      WHEN 'AR' THEN 67500
      WHEN 'BR' THEN 67500
      WHEN 'ZA' THEN 67500
      WHEN 'TH' THEN 67500
      WHEN 'TR' THEN 60000
      WHEN 'CO' THEN 60000
      WHEN 'PE' THEN 60000
      WHEN 'PH' THEN 60000
      WHEN 'MA' THEN 52500
      WHEN 'IN' THEN 45000
      WHEN 'ID' THEN 45000
      WHEN 'VN' THEN 45000
      WHEN 'EG' THEN 45000
      WHEN 'KE' THEN 45000
      WHEN 'NG' THEN 37500
      WHEN 'PK' THEN 37500
      WHEN 'BD' THEN 37500
      ELSE 75000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'residential_construction'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 236115 + 236116 + 236117 + 236118)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.02),
  'payroll_total',          ROUND(rev_p50 * 0.25),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.5),
  'utilities',              ROUND(rev_p50 * 0.01),
  'marketing_acquisition',  ROUND(rev_p50 * 0.02),
  'insurance_professional', ROUND(rev_p50 * 0.06),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NAHB Builder Cost survey 2024 + Construction Financial Management Association data. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('236115', '236116', '236117', '236118')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 6000
      WHEN 'CH' THEN 8400
      WHEN 'NO' THEN 7800
      WHEN 'JP' THEN 7800
      WHEN 'SG' THEN 7200
      WHEN 'AU' THEN 7500
      WHEN 'GB' THEN 7200
      WHEN 'DE' THEN 6900
      WHEN 'FR' THEN 6600
      WHEN 'NL' THEN 6900
      WHEN 'SE' THEN 7200
      WHEN 'CA' THEN 6300
      WHEN 'AT' THEN 6600
      WHEN 'DK' THEN 7200
      WHEN 'FI' THEN 6900
      WHEN 'BE' THEN 6900
      WHEN 'IE' THEN 6600
      WHEN 'IL' THEN 6000
      WHEN 'AE' THEN 5700
      WHEN 'KR' THEN 5700
      WHEN 'IT' THEN 5400
      WHEN 'ES' THEN 5100
      WHEN 'NZ' THEN 6600
      WHEN 'PT' THEN 4200
      WHEN 'GR' THEN 3900
      WHEN 'CZ' THEN 3600
      WHEN 'PL' THEN 3300
      WHEN 'HU' THEN 3300
      WHEN 'CL' THEN 3300
      WHEN 'CN' THEN 3300
      WHEN 'MY' THEN 3000
      WHEN 'MX' THEN 3000
      WHEN 'AR' THEN 2700
      WHEN 'BR' THEN 2700
      WHEN 'ZA' THEN 2700
      WHEN 'TH' THEN 2700
      WHEN 'TR' THEN 2400
      WHEN 'CO' THEN 2400
      WHEN 'PE' THEN 2400
      WHEN 'PH' THEN 2400
      WHEN 'MA' THEN 2100
      WHEN 'IN' THEN 1800
      WHEN 'ID' THEN 1800
      WHEN 'VN' THEN 1800
      WHEN 'EG' THEN 1800
      WHEN 'KE' THEN 1800
      WHEN 'NG' THEN 1500
      WHEN 'PK' THEN 1500
      WHEN 'BD' THEN 1500
      ELSE 3000
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 90000
      WHEN 'CH' THEN 126000
      WHEN 'NO' THEN 117000
      WHEN 'JP' THEN 117000
      WHEN 'SG' THEN 108000
      WHEN 'AU' THEN 112500
      WHEN 'GB' THEN 108000
      WHEN 'DE' THEN 103500
      WHEN 'FR' THEN 99000
      WHEN 'NL' THEN 103500
      WHEN 'SE' THEN 108000
      WHEN 'CA' THEN 94500
      WHEN 'AT' THEN 99000
      WHEN 'DK' THEN 108000
      WHEN 'FI' THEN 103500
      WHEN 'BE' THEN 103500
      WHEN 'IE' THEN 99000
      WHEN 'IL' THEN 90000
      WHEN 'AE' THEN 85500
      WHEN 'KR' THEN 85500
      WHEN 'IT' THEN 81000
      WHEN 'ES' THEN 76500
      WHEN 'NZ' THEN 99000
      WHEN 'PT' THEN 63000
      WHEN 'GR' THEN 58500
      WHEN 'CZ' THEN 54000
      WHEN 'PL' THEN 49500
      WHEN 'HU' THEN 49500
      WHEN 'CL' THEN 49500
      WHEN 'CN' THEN 49500
      WHEN 'MY' THEN 45000
      WHEN 'MX' THEN 45000
      WHEN 'AR' THEN 40500
      WHEN 'BR' THEN 40500
      WHEN 'ZA' THEN 40500
      WHEN 'TH' THEN 40500
      WHEN 'TR' THEN 36000
      WHEN 'CO' THEN 36000
      WHEN 'PE' THEN 36000
      WHEN 'PH' THEN 36000
      WHEN 'MA' THEN 31500
      WHEN 'IN' THEN 27000
      WHEN 'ID' THEN 27000
      WHEN 'VN' THEN 27000
      WHEN 'EG' THEN 27000
      WHEN 'KE' THEN 27000
      WHEN 'NG' THEN 22500
      WHEN 'PK' THEN 22500
      WHEN 'BD' THEN 22500
      ELSE 45000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 37500
      WHEN 'CH' THEN 52500
      WHEN 'NO' THEN 48750
      WHEN 'JP' THEN 48750
      WHEN 'SG' THEN 45000
      WHEN 'AU' THEN 46875
      WHEN 'GB' THEN 45000
      WHEN 'DE' THEN 43125
      WHEN 'FR' THEN 41250
      WHEN 'NL' THEN 43125
      WHEN 'SE' THEN 45000
      WHEN 'CA' THEN 39375
      WHEN 'AT' THEN 41250
      WHEN 'DK' THEN 45000
      WHEN 'FI' THEN 43125
      WHEN 'BE' THEN 43125
      WHEN 'IE' THEN 41250
      WHEN 'IL' THEN 37500
      WHEN 'AE' THEN 35625
      WHEN 'KR' THEN 35625
      WHEN 'IT' THEN 33750
      WHEN 'ES' THEN 31875
      WHEN 'NZ' THEN 41250
      WHEN 'PT' THEN 26250
      WHEN 'GR' THEN 24375
      WHEN 'CZ' THEN 22500
      WHEN 'PL' THEN 20625
      WHEN 'HU' THEN 20625
      WHEN 'CL' THEN 20625
      WHEN 'CN' THEN 20625
      WHEN 'MY' THEN 18750
      WHEN 'MX' THEN 18750
      WHEN 'AR' THEN 16875
      WHEN 'BR' THEN 16875
      WHEN 'ZA' THEN 16875
      WHEN 'TH' THEN 16875
      WHEN 'TR' THEN 15000
      WHEN 'CO' THEN 15000
      WHEN 'PE' THEN 15000
      WHEN 'PH' THEN 15000
      WHEN 'MA' THEN 13125
      WHEN 'IN' THEN 11250
      WHEN 'ID' THEN 11250
      WHEN 'VN' THEN 11250
      WHEN 'EG' THEN 11250
      WHEN 'KE' THEN 11250
      WHEN 'NG' THEN 9375
      WHEN 'PK' THEN 9375
      WHEN 'BD' THEN 9375
      ELSE 18750
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 9000
      WHEN 'CH' THEN 12600
      WHEN 'NO' THEN 11700
      WHEN 'JP' THEN 11700
      WHEN 'SG' THEN 10800
      WHEN 'AU' THEN 11250
      WHEN 'GB' THEN 10800
      WHEN 'DE' THEN 10350
      WHEN 'FR' THEN 9900
      WHEN 'NL' THEN 10350
      WHEN 'SE' THEN 10800
      WHEN 'CA' THEN 9450
      WHEN 'AT' THEN 9900
      WHEN 'DK' THEN 10800
      WHEN 'FI' THEN 10350
      WHEN 'BE' THEN 10350
      WHEN 'IE' THEN 9900
      WHEN 'IL' THEN 9000
      WHEN 'AE' THEN 8550
      WHEN 'KR' THEN 8550
      WHEN 'IT' THEN 8100
      WHEN 'ES' THEN 7650
      WHEN 'NZ' THEN 9900
      WHEN 'PT' THEN 6300
      WHEN 'GR' THEN 5850
      WHEN 'CZ' THEN 5400
      WHEN 'PL' THEN 4950
      WHEN 'HU' THEN 4950
      WHEN 'CL' THEN 4950
      WHEN 'CN' THEN 4950
      WHEN 'MY' THEN 4500
      WHEN 'MX' THEN 4500
      WHEN 'AR' THEN 4050
      WHEN 'BR' THEN 4050
      WHEN 'ZA' THEN 4050
      WHEN 'TH' THEN 4050
      WHEN 'TR' THEN 3600
      WHEN 'CO' THEN 3600
      WHEN 'PE' THEN 3600
      WHEN 'PH' THEN 3600
      WHEN 'MA' THEN 3150
      WHEN 'IN' THEN 2700
      WHEN 'ID' THEN 2700
      WHEN 'VN' THEN 2700
      WHEN 'EG' THEN 2700
      WHEN 'KE' THEN 2700
      WHEN 'NG' THEN 2250
      WHEN 'PK' THEN 2250
      WHEN 'BD' THEN 2250
      ELSE 4500
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 150000
      WHEN 'CH' THEN 210000
      WHEN 'NO' THEN 195000
      WHEN 'JP' THEN 195000
      WHEN 'SG' THEN 180000
      WHEN 'AU' THEN 187500
      WHEN 'GB' THEN 180000
      WHEN 'DE' THEN 172500
      WHEN 'FR' THEN 165000
      WHEN 'NL' THEN 172500
      WHEN 'SE' THEN 180000
      WHEN 'CA' THEN 157500
      WHEN 'AT' THEN 165000
      WHEN 'DK' THEN 180000
      WHEN 'FI' THEN 172500
      WHEN 'BE' THEN 172500
      WHEN 'IE' THEN 165000
      WHEN 'IL' THEN 150000
      WHEN 'AE' THEN 142500
      WHEN 'KR' THEN 142500
      WHEN 'IT' THEN 135000
      WHEN 'ES' THEN 127500
      WHEN 'NZ' THEN 165000
      WHEN 'PT' THEN 105000
      WHEN 'GR' THEN 97500
      WHEN 'CZ' THEN 90000
      WHEN 'PL' THEN 82500
      WHEN 'HU' THEN 82500
      WHEN 'CL' THEN 82500
      WHEN 'CN' THEN 82500
      WHEN 'MY' THEN 75000
      WHEN 'MX' THEN 75000
      WHEN 'AR' THEN 67500
      WHEN 'BR' THEN 67500
      WHEN 'ZA' THEN 67500
      WHEN 'TH' THEN 67500
      WHEN 'TR' THEN 60000
      WHEN 'CO' THEN 60000
      WHEN 'PE' THEN 60000
      WHEN 'PH' THEN 60000
      WHEN 'MA' THEN 52500
      WHEN 'IN' THEN 45000
      WHEN 'ID' THEN 45000
      WHEN 'VN' THEN 45000
      WHEN 'EG' THEN 45000
      WHEN 'KE' THEN 45000
      WHEN 'NG' THEN 37500
      WHEN 'PK' THEN 37500
      WHEN 'BD' THEN 37500
      ELSE 75000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('236115', '236116', '236117', '236118')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.02),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.25),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.5),
  'utilities',              ROUND(predicted_rev_per_firm * 0.01),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.02),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.06),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.04),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.03),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NAHB Builder Cost survey 2024 + Construction Financial Management Association data. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'residential_construction'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
