-- ============================================================================
-- BULK IMPORT: restaurants cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: NRA 2024 Operations Survey ratios.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.06),
  'payroll_total',          ROUND(rev_p50 * 0.36),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.32),
  'utilities',              ROUND(rev_p50 * 0.04),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NRA 2024 Operations Survey ratios. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'restaurants'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 4500
      WHEN 'CH' THEN 6300
      WHEN 'NO' THEN 5850
      WHEN 'JP' THEN 5850
      WHEN 'SG' THEN 5400
      WHEN 'AU' THEN 5625
      WHEN 'GB' THEN 5400
      WHEN 'DE' THEN 5175
      WHEN 'FR' THEN 4950
      WHEN 'NL' THEN 5175
      WHEN 'SE' THEN 5400
      WHEN 'CA' THEN 4725
      WHEN 'AT' THEN 4950
      WHEN 'DK' THEN 5400
      WHEN 'FI' THEN 5175
      WHEN 'BE' THEN 5175
      WHEN 'IE' THEN 4950
      WHEN 'IL' THEN 4500
      WHEN 'AE' THEN 4275
      WHEN 'KR' THEN 4275
      WHEN 'IT' THEN 4050
      WHEN 'ES' THEN 3825
      WHEN 'NZ' THEN 4950
      WHEN 'PT' THEN 3150
      WHEN 'GR' THEN 2925
      WHEN 'CZ' THEN 2700
      WHEN 'PL' THEN 2475
      WHEN 'HU' THEN 2475
      WHEN 'CL' THEN 2475
      WHEN 'CN' THEN 2475
      WHEN 'MY' THEN 2250
      WHEN 'MX' THEN 2250
      WHEN 'AR' THEN 2025
      WHEN 'BR' THEN 2025
      WHEN 'ZA' THEN 2025
      WHEN 'TH' THEN 2025
      WHEN 'TR' THEN 1800
      WHEN 'CO' THEN 1800
      WHEN 'PE' THEN 1800
      WHEN 'PH' THEN 1800
      WHEN 'MA' THEN 1575
      WHEN 'IN' THEN 1350
      WHEN 'ID' THEN 1350
      WHEN 'VN' THEN 1350
      WHEN 'EG' THEN 1350
      WHEN 'KE' THEN 1350
      WHEN 'NG' THEN 1125
      WHEN 'PK' THEN 1125
      WHEN 'BD' THEN 1125
      ELSE 2250
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 195000
      WHEN 'CH' THEN 273000
      WHEN 'NO' THEN 253500
      WHEN 'JP' THEN 253500
      WHEN 'SG' THEN 234000
      WHEN 'AU' THEN 243750
      WHEN 'GB' THEN 234000
      WHEN 'DE' THEN 224250
      WHEN 'FR' THEN 214500
      WHEN 'NL' THEN 224250
      WHEN 'SE' THEN 234000
      WHEN 'CA' THEN 204750
      WHEN 'AT' THEN 214500
      WHEN 'DK' THEN 234000
      WHEN 'FI' THEN 224250
      WHEN 'BE' THEN 224250
      WHEN 'IE' THEN 214500
      WHEN 'IL' THEN 195000
      WHEN 'AE' THEN 185250
      WHEN 'KR' THEN 185250
      WHEN 'IT' THEN 175500
      WHEN 'ES' THEN 165750
      WHEN 'NZ' THEN 214500
      WHEN 'PT' THEN 136500
      WHEN 'GR' THEN 126750
      WHEN 'CZ' THEN 117000
      WHEN 'PL' THEN 107250
      WHEN 'HU' THEN 107250
      WHEN 'CL' THEN 107250
      WHEN 'CN' THEN 107250
      WHEN 'MY' THEN 97500
      WHEN 'MX' THEN 97500
      WHEN 'AR' THEN 87750
      WHEN 'BR' THEN 87750
      WHEN 'ZA' THEN 87750
      WHEN 'TH' THEN 87750
      WHEN 'TR' THEN 78000
      WHEN 'CO' THEN 78000
      WHEN 'PE' THEN 78000
      WHEN 'PH' THEN 78000
      WHEN 'MA' THEN 68250
      WHEN 'IN' THEN 58500
      WHEN 'ID' THEN 58500
      WHEN 'VN' THEN 58500
      WHEN 'EG' THEN 58500
      WHEN 'KE' THEN 58500
      WHEN 'NG' THEN 48750
      WHEN 'PK' THEN 48750
      WHEN 'BD' THEN 48750
      ELSE 97500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 81250
      WHEN 'CH' THEN 113750
      WHEN 'NO' THEN 105625
      WHEN 'JP' THEN 105625
      WHEN 'SG' THEN 97500
      WHEN 'AU' THEN 101563
      WHEN 'GB' THEN 97500
      WHEN 'DE' THEN 93438
      WHEN 'FR' THEN 89375
      WHEN 'NL' THEN 93438
      WHEN 'SE' THEN 97500
      WHEN 'CA' THEN 85313
      WHEN 'AT' THEN 89375
      WHEN 'DK' THEN 97500
      WHEN 'FI' THEN 93438
      WHEN 'BE' THEN 93438
      WHEN 'IE' THEN 89375
      WHEN 'IL' THEN 81250
      WHEN 'AE' THEN 77188
      WHEN 'KR' THEN 77188
      WHEN 'IT' THEN 73125
      WHEN 'ES' THEN 69063
      WHEN 'NZ' THEN 89375
      WHEN 'PT' THEN 56875
      WHEN 'GR' THEN 52813
      WHEN 'CZ' THEN 48750
      WHEN 'PL' THEN 44688
      WHEN 'HU' THEN 44688
      WHEN 'CL' THEN 44688
      WHEN 'CN' THEN 44688
      WHEN 'MY' THEN 40625
      WHEN 'MX' THEN 40625
      WHEN 'AR' THEN 36563
      WHEN 'BR' THEN 36563
      WHEN 'ZA' THEN 36563
      WHEN 'TH' THEN 36563
      WHEN 'TR' THEN 32500
      WHEN 'CO' THEN 32500
      WHEN 'PE' THEN 32500
      WHEN 'PH' THEN 32500
      WHEN 'MA' THEN 28438
      WHEN 'IN' THEN 24375
      WHEN 'ID' THEN 24375
      WHEN 'VN' THEN 24375
      WHEN 'EG' THEN 24375
      WHEN 'KE' THEN 24375
      WHEN 'NG' THEN 20313
      WHEN 'PK' THEN 20313
      WHEN 'BD' THEN 20313
      ELSE 40625
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 19500
      WHEN 'CH' THEN 27300
      WHEN 'NO' THEN 25350
      WHEN 'JP' THEN 25350
      WHEN 'SG' THEN 23400
      WHEN 'AU' THEN 24375
      WHEN 'GB' THEN 23400
      WHEN 'DE' THEN 22425
      WHEN 'FR' THEN 21450
      WHEN 'NL' THEN 22425
      WHEN 'SE' THEN 23400
      WHEN 'CA' THEN 20475
      WHEN 'AT' THEN 21450
      WHEN 'DK' THEN 23400
      WHEN 'FI' THEN 22425
      WHEN 'BE' THEN 22425
      WHEN 'IE' THEN 21450
      WHEN 'IL' THEN 19500
      WHEN 'AE' THEN 18525
      WHEN 'KR' THEN 18525
      WHEN 'IT' THEN 17550
      WHEN 'ES' THEN 16575
      WHEN 'NZ' THEN 21450
      WHEN 'PT' THEN 13650
      WHEN 'GR' THEN 12675
      WHEN 'CZ' THEN 11700
      WHEN 'PL' THEN 10725
      WHEN 'HU' THEN 10725
      WHEN 'CL' THEN 10725
      WHEN 'CN' THEN 10725
      WHEN 'MY' THEN 9750
      WHEN 'MX' THEN 9750
      WHEN 'AR' THEN 8775
      WHEN 'BR' THEN 8775
      WHEN 'ZA' THEN 8775
      WHEN 'TH' THEN 8775
      WHEN 'TR' THEN 7800
      WHEN 'CO' THEN 7800
      WHEN 'PE' THEN 7800
      WHEN 'PH' THEN 7800
      WHEN 'MA' THEN 6825
      WHEN 'IN' THEN 5850
      WHEN 'ID' THEN 5850
      WHEN 'VN' THEN 5850
      WHEN 'EG' THEN 5850
      WHEN 'KE' THEN 5850
      WHEN 'NG' THEN 4875
      WHEN 'PK' THEN 4875
      WHEN 'BD' THEN 4875
      ELSE 9750
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 325000
      WHEN 'CH' THEN 455000
      WHEN 'NO' THEN 422500
      WHEN 'JP' THEN 422500
      WHEN 'SG' THEN 390000
      WHEN 'AU' THEN 406250
      WHEN 'GB' THEN 390000
      WHEN 'DE' THEN 373750
      WHEN 'FR' THEN 357500
      WHEN 'NL' THEN 373750
      WHEN 'SE' THEN 390000
      WHEN 'CA' THEN 341250
      WHEN 'AT' THEN 357500
      WHEN 'DK' THEN 390000
      WHEN 'FI' THEN 373750
      WHEN 'BE' THEN 373750
      WHEN 'IE' THEN 357500
      WHEN 'IL' THEN 325000
      WHEN 'AE' THEN 308750
      WHEN 'KR' THEN 308750
      WHEN 'IT' THEN 292500
      WHEN 'ES' THEN 276250
      WHEN 'NZ' THEN 357500
      WHEN 'PT' THEN 227500
      WHEN 'GR' THEN 211250
      WHEN 'CZ' THEN 195000
      WHEN 'PL' THEN 178750
      WHEN 'HU' THEN 178750
      WHEN 'CL' THEN 178750
      WHEN 'CN' THEN 178750
      WHEN 'MY' THEN 162500
      WHEN 'MX' THEN 162500
      WHEN 'AR' THEN 146250
      WHEN 'BR' THEN 146250
      WHEN 'ZA' THEN 146250
      WHEN 'TH' THEN 146250
      WHEN 'TR' THEN 130000
      WHEN 'CO' THEN 130000
      WHEN 'PE' THEN 130000
      WHEN 'PH' THEN 130000
      WHEN 'MA' THEN 113750
      WHEN 'IN' THEN 97500
      WHEN 'ID' THEN 97500
      WHEN 'VN' THEN 97500
      WHEN 'EG' THEN 97500
      WHEN 'KE' THEN 97500
      WHEN 'NG' THEN 81250
      WHEN 'PK' THEN 81250
      WHEN 'BD' THEN 81250
      ELSE 162500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'restaurants'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 722511 + 722513)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.06),
  'payroll_total',          ROUND(rev_p50 * 0.36),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.32),
  'utilities',              ROUND(rev_p50 * 0.04),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NRA 2024 Operations Survey ratios. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('722511', '722513')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 4500
      WHEN 'CH' THEN 6300
      WHEN 'NO' THEN 5850
      WHEN 'JP' THEN 5850
      WHEN 'SG' THEN 5400
      WHEN 'AU' THEN 5625
      WHEN 'GB' THEN 5400
      WHEN 'DE' THEN 5175
      WHEN 'FR' THEN 4950
      WHEN 'NL' THEN 5175
      WHEN 'SE' THEN 5400
      WHEN 'CA' THEN 4725
      WHEN 'AT' THEN 4950
      WHEN 'DK' THEN 5400
      WHEN 'FI' THEN 5175
      WHEN 'BE' THEN 5175
      WHEN 'IE' THEN 4950
      WHEN 'IL' THEN 4500
      WHEN 'AE' THEN 4275
      WHEN 'KR' THEN 4275
      WHEN 'IT' THEN 4050
      WHEN 'ES' THEN 3825
      WHEN 'NZ' THEN 4950
      WHEN 'PT' THEN 3150
      WHEN 'GR' THEN 2925
      WHEN 'CZ' THEN 2700
      WHEN 'PL' THEN 2475
      WHEN 'HU' THEN 2475
      WHEN 'CL' THEN 2475
      WHEN 'CN' THEN 2475
      WHEN 'MY' THEN 2250
      WHEN 'MX' THEN 2250
      WHEN 'AR' THEN 2025
      WHEN 'BR' THEN 2025
      WHEN 'ZA' THEN 2025
      WHEN 'TH' THEN 2025
      WHEN 'TR' THEN 1800
      WHEN 'CO' THEN 1800
      WHEN 'PE' THEN 1800
      WHEN 'PH' THEN 1800
      WHEN 'MA' THEN 1575
      WHEN 'IN' THEN 1350
      WHEN 'ID' THEN 1350
      WHEN 'VN' THEN 1350
      WHEN 'EG' THEN 1350
      WHEN 'KE' THEN 1350
      WHEN 'NG' THEN 1125
      WHEN 'PK' THEN 1125
      WHEN 'BD' THEN 1125
      ELSE 2250
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 195000
      WHEN 'CH' THEN 273000
      WHEN 'NO' THEN 253500
      WHEN 'JP' THEN 253500
      WHEN 'SG' THEN 234000
      WHEN 'AU' THEN 243750
      WHEN 'GB' THEN 234000
      WHEN 'DE' THEN 224250
      WHEN 'FR' THEN 214500
      WHEN 'NL' THEN 224250
      WHEN 'SE' THEN 234000
      WHEN 'CA' THEN 204750
      WHEN 'AT' THEN 214500
      WHEN 'DK' THEN 234000
      WHEN 'FI' THEN 224250
      WHEN 'BE' THEN 224250
      WHEN 'IE' THEN 214500
      WHEN 'IL' THEN 195000
      WHEN 'AE' THEN 185250
      WHEN 'KR' THEN 185250
      WHEN 'IT' THEN 175500
      WHEN 'ES' THEN 165750
      WHEN 'NZ' THEN 214500
      WHEN 'PT' THEN 136500
      WHEN 'GR' THEN 126750
      WHEN 'CZ' THEN 117000
      WHEN 'PL' THEN 107250
      WHEN 'HU' THEN 107250
      WHEN 'CL' THEN 107250
      WHEN 'CN' THEN 107250
      WHEN 'MY' THEN 97500
      WHEN 'MX' THEN 97500
      WHEN 'AR' THEN 87750
      WHEN 'BR' THEN 87750
      WHEN 'ZA' THEN 87750
      WHEN 'TH' THEN 87750
      WHEN 'TR' THEN 78000
      WHEN 'CO' THEN 78000
      WHEN 'PE' THEN 78000
      WHEN 'PH' THEN 78000
      WHEN 'MA' THEN 68250
      WHEN 'IN' THEN 58500
      WHEN 'ID' THEN 58500
      WHEN 'VN' THEN 58500
      WHEN 'EG' THEN 58500
      WHEN 'KE' THEN 58500
      WHEN 'NG' THEN 48750
      WHEN 'PK' THEN 48750
      WHEN 'BD' THEN 48750
      ELSE 97500
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 81250
      WHEN 'CH' THEN 113750
      WHEN 'NO' THEN 105625
      WHEN 'JP' THEN 105625
      WHEN 'SG' THEN 97500
      WHEN 'AU' THEN 101563
      WHEN 'GB' THEN 97500
      WHEN 'DE' THEN 93438
      WHEN 'FR' THEN 89375
      WHEN 'NL' THEN 93438
      WHEN 'SE' THEN 97500
      WHEN 'CA' THEN 85313
      WHEN 'AT' THEN 89375
      WHEN 'DK' THEN 97500
      WHEN 'FI' THEN 93438
      WHEN 'BE' THEN 93438
      WHEN 'IE' THEN 89375
      WHEN 'IL' THEN 81250
      WHEN 'AE' THEN 77188
      WHEN 'KR' THEN 77188
      WHEN 'IT' THEN 73125
      WHEN 'ES' THEN 69063
      WHEN 'NZ' THEN 89375
      WHEN 'PT' THEN 56875
      WHEN 'GR' THEN 52813
      WHEN 'CZ' THEN 48750
      WHEN 'PL' THEN 44688
      WHEN 'HU' THEN 44688
      WHEN 'CL' THEN 44688
      WHEN 'CN' THEN 44688
      WHEN 'MY' THEN 40625
      WHEN 'MX' THEN 40625
      WHEN 'AR' THEN 36563
      WHEN 'BR' THEN 36563
      WHEN 'ZA' THEN 36563
      WHEN 'TH' THEN 36563
      WHEN 'TR' THEN 32500
      WHEN 'CO' THEN 32500
      WHEN 'PE' THEN 32500
      WHEN 'PH' THEN 32500
      WHEN 'MA' THEN 28438
      WHEN 'IN' THEN 24375
      WHEN 'ID' THEN 24375
      WHEN 'VN' THEN 24375
      WHEN 'EG' THEN 24375
      WHEN 'KE' THEN 24375
      WHEN 'NG' THEN 20313
      WHEN 'PK' THEN 20313
      WHEN 'BD' THEN 20313
      ELSE 40625
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 4,
    'lease_deposit', CASE country
      WHEN 'US' THEN 19500
      WHEN 'CH' THEN 27300
      WHEN 'NO' THEN 25350
      WHEN 'JP' THEN 25350
      WHEN 'SG' THEN 23400
      WHEN 'AU' THEN 24375
      WHEN 'GB' THEN 23400
      WHEN 'DE' THEN 22425
      WHEN 'FR' THEN 21450
      WHEN 'NL' THEN 22425
      WHEN 'SE' THEN 23400
      WHEN 'CA' THEN 20475
      WHEN 'AT' THEN 21450
      WHEN 'DK' THEN 23400
      WHEN 'FI' THEN 22425
      WHEN 'BE' THEN 22425
      WHEN 'IE' THEN 21450
      WHEN 'IL' THEN 19500
      WHEN 'AE' THEN 18525
      WHEN 'KR' THEN 18525
      WHEN 'IT' THEN 17550
      WHEN 'ES' THEN 16575
      WHEN 'NZ' THEN 21450
      WHEN 'PT' THEN 13650
      WHEN 'GR' THEN 12675
      WHEN 'CZ' THEN 11700
      WHEN 'PL' THEN 10725
      WHEN 'HU' THEN 10725
      WHEN 'CL' THEN 10725
      WHEN 'CN' THEN 10725
      WHEN 'MY' THEN 9750
      WHEN 'MX' THEN 9750
      WHEN 'AR' THEN 8775
      WHEN 'BR' THEN 8775
      WHEN 'ZA' THEN 8775
      WHEN 'TH' THEN 8775
      WHEN 'TR' THEN 7800
      WHEN 'CO' THEN 7800
      WHEN 'PE' THEN 7800
      WHEN 'PH' THEN 7800
      WHEN 'MA' THEN 6825
      WHEN 'IN' THEN 5850
      WHEN 'ID' THEN 5850
      WHEN 'VN' THEN 5850
      WHEN 'EG' THEN 5850
      WHEN 'KE' THEN 5850
      WHEN 'NG' THEN 4875
      WHEN 'PK' THEN 4875
      WHEN 'BD' THEN 4875
      ELSE 9750
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 325000
      WHEN 'CH' THEN 455000
      WHEN 'NO' THEN 422500
      WHEN 'JP' THEN 422500
      WHEN 'SG' THEN 390000
      WHEN 'AU' THEN 406250
      WHEN 'GB' THEN 390000
      WHEN 'DE' THEN 373750
      WHEN 'FR' THEN 357500
      WHEN 'NL' THEN 373750
      WHEN 'SE' THEN 390000
      WHEN 'CA' THEN 341250
      WHEN 'AT' THEN 357500
      WHEN 'DK' THEN 390000
      WHEN 'FI' THEN 373750
      WHEN 'BE' THEN 373750
      WHEN 'IE' THEN 357500
      WHEN 'IL' THEN 325000
      WHEN 'AE' THEN 308750
      WHEN 'KR' THEN 308750
      WHEN 'IT' THEN 292500
      WHEN 'ES' THEN 276250
      WHEN 'NZ' THEN 357500
      WHEN 'PT' THEN 227500
      WHEN 'GR' THEN 211250
      WHEN 'CZ' THEN 195000
      WHEN 'PL' THEN 178750
      WHEN 'HU' THEN 178750
      WHEN 'CL' THEN 178750
      WHEN 'CN' THEN 178750
      WHEN 'MY' THEN 162500
      WHEN 'MX' THEN 162500
      WHEN 'AR' THEN 146250
      WHEN 'BR' THEN 146250
      WHEN 'ZA' THEN 146250
      WHEN 'TH' THEN 146250
      WHEN 'TR' THEN 130000
      WHEN 'CO' THEN 130000
      WHEN 'PE' THEN 130000
      WHEN 'PH' THEN 130000
      WHEN 'MA' THEN 113750
      WHEN 'IN' THEN 97500
      WHEN 'ID' THEN 97500
      WHEN 'VN' THEN 97500
      WHEN 'EG' THEN 97500
      WHEN 'KE' THEN 97500
      WHEN 'NG' THEN 81250
      WHEN 'PK' THEN 81250
      WHEN 'BD' THEN 81250
      ELSE 162500
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('722511', '722513')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.06),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.36),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.32),
  'utilities',              ROUND(predicted_rev_per_firm * 0.04),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.03),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.04),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.04),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.01),
  'refreshed_at',           '2026-05-24',
  'source_note',            'NRA 2024 Operations Survey ratios. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'restaurants'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
