-- ============================================================================
-- BULK IMPORT: veterinary_pet_care cost-stack worldwide (Grade C extrapolation)
-- ============================================================================
-- Generated by scripts/generate/bulk_cost_stack_sql.ts
-- Industry baseline: src/lib/qa/industry_baselines.ts
-- Source: AVMA Economic State of the Veterinary Profession 2024 + VPI/Nationwide cost surveys.
-- Safe to re-run. Grade A/B cells are NOT overwritten.

-- 1. regional_cells (non-US sub-national rows)
UPDATE regional_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.4),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.18),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AVMA Economic State of the Veterinary Profession 2024 + VPI/Nationwide cost surveys. Country revenue captures local price level implicitly.',
  'grade',                  'C'
)
WHERE industry_id = 'veterinary_pet_care'
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE regional_cells
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 240000
      WHEN 'CH' THEN 336000
      WHEN 'NO' THEN 312000
      WHEN 'JP' THEN 312000
      WHEN 'SG' THEN 288000
      WHEN 'AU' THEN 300000
      WHEN 'GB' THEN 288000
      WHEN 'DE' THEN 276000
      WHEN 'FR' THEN 264000
      WHEN 'NL' THEN 276000
      WHEN 'SE' THEN 288000
      WHEN 'CA' THEN 252000
      WHEN 'AT' THEN 264000
      WHEN 'DK' THEN 288000
      WHEN 'FI' THEN 276000
      WHEN 'BE' THEN 276000
      WHEN 'IE' THEN 264000
      WHEN 'IL' THEN 240000
      WHEN 'AE' THEN 228000
      WHEN 'KR' THEN 228000
      WHEN 'IT' THEN 216000
      WHEN 'ES' THEN 204000
      WHEN 'NZ' THEN 264000
      WHEN 'PT' THEN 168000
      WHEN 'GR' THEN 156000
      WHEN 'CZ' THEN 144000
      WHEN 'PL' THEN 132000
      WHEN 'HU' THEN 132000
      WHEN 'CL' THEN 132000
      WHEN 'CN' THEN 132000
      WHEN 'MY' THEN 120000
      WHEN 'MX' THEN 120000
      WHEN 'AR' THEN 108000
      WHEN 'BR' THEN 108000
      WHEN 'ZA' THEN 108000
      WHEN 'TH' THEN 108000
      WHEN 'TR' THEN 96000
      WHEN 'CO' THEN 96000
      WHEN 'PE' THEN 96000
      WHEN 'PH' THEN 96000
      WHEN 'MA' THEN 84000
      WHEN 'IN' THEN 72000
      WHEN 'ID' THEN 72000
      WHEN 'VN' THEN 72000
      WHEN 'EG' THEN 72000
      WHEN 'KE' THEN 72000
      WHEN 'NG' THEN 60000
      WHEN 'PK' THEN 60000
      WHEN 'BD' THEN 60000
      ELSE 120000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 100000
      WHEN 'CH' THEN 140000
      WHEN 'NO' THEN 130000
      WHEN 'JP' THEN 130000
      WHEN 'SG' THEN 120000
      WHEN 'AU' THEN 125000
      WHEN 'GB' THEN 120000
      WHEN 'DE' THEN 115000
      WHEN 'FR' THEN 110000
      WHEN 'NL' THEN 115000
      WHEN 'SE' THEN 120000
      WHEN 'CA' THEN 105000
      WHEN 'AT' THEN 110000
      WHEN 'DK' THEN 120000
      WHEN 'FI' THEN 115000
      WHEN 'BE' THEN 115000
      WHEN 'IE' THEN 110000
      WHEN 'IL' THEN 100000
      WHEN 'AE' THEN 95000
      WHEN 'KR' THEN 95000
      WHEN 'IT' THEN 90000
      WHEN 'ES' THEN 85000
      WHEN 'NZ' THEN 110000
      WHEN 'PT' THEN 70000
      WHEN 'GR' THEN 65000
      WHEN 'CZ' THEN 60000
      WHEN 'PL' THEN 55000
      WHEN 'HU' THEN 55000
      WHEN 'CL' THEN 55000
      WHEN 'CN' THEN 55000
      WHEN 'MY' THEN 50000
      WHEN 'MX' THEN 50000
      WHEN 'AR' THEN 45000
      WHEN 'BR' THEN 45000
      WHEN 'ZA' THEN 45000
      WHEN 'TH' THEN 45000
      WHEN 'TR' THEN 40000
      WHEN 'CO' THEN 40000
      WHEN 'PE' THEN 40000
      WHEN 'PH' THEN 40000
      WHEN 'MA' THEN 35000
      WHEN 'IN' THEN 30000
      WHEN 'ID' THEN 30000
      WHEN 'VN' THEN 30000
      WHEN 'EG' THEN 30000
      WHEN 'KE' THEN 30000
      WHEN 'NG' THEN 25000
      WHEN 'PK' THEN 25000
      WHEN 'BD' THEN 25000
      ELSE 50000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 24000
      WHEN 'CH' THEN 33600
      WHEN 'NO' THEN 31200
      WHEN 'JP' THEN 31200
      WHEN 'SG' THEN 28800
      WHEN 'AU' THEN 30000
      WHEN 'GB' THEN 28800
      WHEN 'DE' THEN 27600
      WHEN 'FR' THEN 26400
      WHEN 'NL' THEN 27600
      WHEN 'SE' THEN 28800
      WHEN 'CA' THEN 25200
      WHEN 'AT' THEN 26400
      WHEN 'DK' THEN 28800
      WHEN 'FI' THEN 27600
      WHEN 'BE' THEN 27600
      WHEN 'IE' THEN 26400
      WHEN 'IL' THEN 24000
      WHEN 'AE' THEN 22800
      WHEN 'KR' THEN 22800
      WHEN 'IT' THEN 21600
      WHEN 'ES' THEN 20400
      WHEN 'NZ' THEN 26400
      WHEN 'PT' THEN 16800
      WHEN 'GR' THEN 15600
      WHEN 'CZ' THEN 14400
      WHEN 'PL' THEN 13200
      WHEN 'HU' THEN 13200
      WHEN 'CL' THEN 13200
      WHEN 'CN' THEN 13200
      WHEN 'MY' THEN 12000
      WHEN 'MX' THEN 12000
      WHEN 'AR' THEN 10800
      WHEN 'BR' THEN 10800
      WHEN 'ZA' THEN 10800
      WHEN 'TH' THEN 10800
      WHEN 'TR' THEN 9600
      WHEN 'CO' THEN 9600
      WHEN 'PE' THEN 9600
      WHEN 'PH' THEN 9600
      WHEN 'MA' THEN 8400
      WHEN 'IN' THEN 7200
      WHEN 'ID' THEN 7200
      WHEN 'VN' THEN 7200
      WHEN 'EG' THEN 7200
      WHEN 'KE' THEN 7200
      WHEN 'NG' THEN 6000
      WHEN 'PK' THEN 6000
      WHEN 'BD' THEN 6000
      ELSE 12000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 400000
      WHEN 'CH' THEN 560000
      WHEN 'NO' THEN 520000
      WHEN 'JP' THEN 520000
      WHEN 'SG' THEN 480000
      WHEN 'AU' THEN 500000
      WHEN 'GB' THEN 480000
      WHEN 'DE' THEN 460000
      WHEN 'FR' THEN 440000
      WHEN 'NL' THEN 460000
      WHEN 'SE' THEN 480000
      WHEN 'CA' THEN 420000
      WHEN 'AT' THEN 440000
      WHEN 'DK' THEN 480000
      WHEN 'FI' THEN 460000
      WHEN 'BE' THEN 460000
      WHEN 'IE' THEN 440000
      WHEN 'IL' THEN 400000
      WHEN 'AE' THEN 380000
      WHEN 'KR' THEN 380000
      WHEN 'IT' THEN 360000
      WHEN 'ES' THEN 340000
      WHEN 'NZ' THEN 440000
      WHEN 'PT' THEN 280000
      WHEN 'GR' THEN 260000
      WHEN 'CZ' THEN 240000
      WHEN 'PL' THEN 220000
      WHEN 'HU' THEN 220000
      WHEN 'CL' THEN 220000
      WHEN 'CN' THEN 220000
      WHEN 'MY' THEN 200000
      WHEN 'MX' THEN 200000
      WHEN 'AR' THEN 180000
      WHEN 'BR' THEN 180000
      WHEN 'ZA' THEN 180000
      WHEN 'TH' THEN 180000
      WHEN 'TR' THEN 160000
      WHEN 'CO' THEN 160000
      WHEN 'PE' THEN 160000
      WHEN 'PH' THEN 160000
      WHEN 'MA' THEN 140000
      WHEN 'IN' THEN 120000
      WHEN 'ID' THEN 120000
      WHEN 'VN' THEN 120000
      WHEN 'EG' THEN 120000
      WHEN 'KE' THEN 120000
      WHEN 'NG' THEN 100000
      WHEN 'PK' THEN 100000
      WHEN 'BD' THEN 100000
      ELSE 200000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE industry_id = 'veterinary_pet_care'
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 2. cells_master (US state/county rows, NAICS 541940)
UPDATE cells_master
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(rev_p50 * 0.08),
  'payroll_total',          ROUND(rev_p50 * 0.4),
  'cost_of_goods_sold',     ROUND(rev_p50 * 0.18),
  'utilities',              ROUND(rev_p50 * 0.02),
  'marketing_acquisition',  ROUND(rev_p50 * 0.03),
  'insurance_professional', ROUND(rev_p50 * 0.04),
  'equipment_maintenance',  ROUND(rev_p50 * 0.04),
  'regulatory_licensing',   ROUND(rev_p50 * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AVMA Economic State of the Veterinary Profession 2024 + VPI/Nationwide cost surveys. US state-level cell.',
  'grade',                  'C'
)
WHERE country = 'US'
  AND naics_6 IN ('541940')
  AND rev_p50 IS NOT NULL
  AND rev_p50 > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));

UPDATE cells_master
SET setup_costs = jsonb_build_object(
  'registration', jsonb_build_object(
    'business_registration_fee', 200,
    'industry_licenses_fee', 1500,
    'professional_license_fee', 0,
    'insurance_bond_initial', 1500,
    'certifications_initial', 300,
    'total_estimated', CASE country
      WHEN 'US' THEN 5000
      WHEN 'CH' THEN 7000
      WHEN 'NO' THEN 6500
      WHEN 'JP' THEN 6500
      WHEN 'SG' THEN 6000
      WHEN 'AU' THEN 6250
      WHEN 'GB' THEN 6000
      WHEN 'DE' THEN 5750
      WHEN 'FR' THEN 5500
      WHEN 'NL' THEN 5750
      WHEN 'SE' THEN 6000
      WHEN 'CA' THEN 5250
      WHEN 'AT' THEN 5500
      WHEN 'DK' THEN 6000
      WHEN 'FI' THEN 5750
      WHEN 'BE' THEN 5750
      WHEN 'IE' THEN 5500
      WHEN 'IL' THEN 5000
      WHEN 'AE' THEN 4750
      WHEN 'KR' THEN 4750
      WHEN 'IT' THEN 4500
      WHEN 'ES' THEN 4250
      WHEN 'NZ' THEN 5500
      WHEN 'PT' THEN 3500
      WHEN 'GR' THEN 3250
      WHEN 'CZ' THEN 3000
      WHEN 'PL' THEN 2750
      WHEN 'HU' THEN 2750
      WHEN 'CL' THEN 2750
      WHEN 'CN' THEN 2750
      WHEN 'MY' THEN 2500
      WHEN 'MX' THEN 2500
      WHEN 'AR' THEN 2250
      WHEN 'BR' THEN 2250
      WHEN 'ZA' THEN 2250
      WHEN 'TH' THEN 2250
      WHEN 'TR' THEN 2000
      WHEN 'CO' THEN 2000
      WHEN 'PE' THEN 2000
      WHEN 'PH' THEN 2000
      WHEN 'MA' THEN 1750
      WHEN 'IN' THEN 1500
      WHEN 'ID' THEN 1500
      WHEN 'VN' THEN 1500
      WHEN 'EG' THEN 1500
      WHEN 'KE' THEN 1500
      WHEN 'NG' THEN 1250
      WHEN 'PK' THEN 1250
      WHEN 'BD' THEN 1250
      ELSE 2500
    END,
    'source_note', 'Registration + licensing scaled from US baseline by country construction-cost index.'
  ),
  'capital', jsonb_build_object(
    'property_fitout', CASE country
      WHEN 'US' THEN 240000
      WHEN 'CH' THEN 336000
      WHEN 'NO' THEN 312000
      WHEN 'JP' THEN 312000
      WHEN 'SG' THEN 288000
      WHEN 'AU' THEN 300000
      WHEN 'GB' THEN 288000
      WHEN 'DE' THEN 276000
      WHEN 'FR' THEN 264000
      WHEN 'NL' THEN 276000
      WHEN 'SE' THEN 288000
      WHEN 'CA' THEN 252000
      WHEN 'AT' THEN 264000
      WHEN 'DK' THEN 288000
      WHEN 'FI' THEN 276000
      WHEN 'BE' THEN 276000
      WHEN 'IE' THEN 264000
      WHEN 'IL' THEN 240000
      WHEN 'AE' THEN 228000
      WHEN 'KR' THEN 228000
      WHEN 'IT' THEN 216000
      WHEN 'ES' THEN 204000
      WHEN 'NZ' THEN 264000
      WHEN 'PT' THEN 168000
      WHEN 'GR' THEN 156000
      WHEN 'CZ' THEN 144000
      WHEN 'PL' THEN 132000
      WHEN 'HU' THEN 132000
      WHEN 'CL' THEN 132000
      WHEN 'CN' THEN 132000
      WHEN 'MY' THEN 120000
      WHEN 'MX' THEN 120000
      WHEN 'AR' THEN 108000
      WHEN 'BR' THEN 108000
      WHEN 'ZA' THEN 108000
      WHEN 'TH' THEN 108000
      WHEN 'TR' THEN 96000
      WHEN 'CO' THEN 96000
      WHEN 'PE' THEN 96000
      WHEN 'PH' THEN 96000
      WHEN 'MA' THEN 84000
      WHEN 'IN' THEN 72000
      WHEN 'ID' THEN 72000
      WHEN 'VN' THEN 72000
      WHEN 'EG' THEN 72000
      WHEN 'KE' THEN 72000
      WHEN 'NG' THEN 60000
      WHEN 'PK' THEN 60000
      WHEN 'BD' THEN 60000
      ELSE 120000
    END,
    'equipment_initial', CASE country
      WHEN 'US' THEN 100000
      WHEN 'CH' THEN 140000
      WHEN 'NO' THEN 130000
      WHEN 'JP' THEN 130000
      WHEN 'SG' THEN 120000
      WHEN 'AU' THEN 125000
      WHEN 'GB' THEN 120000
      WHEN 'DE' THEN 115000
      WHEN 'FR' THEN 110000
      WHEN 'NL' THEN 115000
      WHEN 'SE' THEN 120000
      WHEN 'CA' THEN 105000
      WHEN 'AT' THEN 110000
      WHEN 'DK' THEN 120000
      WHEN 'FI' THEN 115000
      WHEN 'BE' THEN 115000
      WHEN 'IE' THEN 110000
      WHEN 'IL' THEN 100000
      WHEN 'AE' THEN 95000
      WHEN 'KR' THEN 95000
      WHEN 'IT' THEN 90000
      WHEN 'ES' THEN 85000
      WHEN 'NZ' THEN 110000
      WHEN 'PT' THEN 70000
      WHEN 'GR' THEN 65000
      WHEN 'CZ' THEN 60000
      WHEN 'PL' THEN 55000
      WHEN 'HU' THEN 55000
      WHEN 'CL' THEN 55000
      WHEN 'CN' THEN 55000
      WHEN 'MY' THEN 50000
      WHEN 'MX' THEN 50000
      WHEN 'AR' THEN 45000
      WHEN 'BR' THEN 45000
      WHEN 'ZA' THEN 45000
      WHEN 'TH' THEN 45000
      WHEN 'TR' THEN 40000
      WHEN 'CO' THEN 40000
      WHEN 'PE' THEN 40000
      WHEN 'PH' THEN 40000
      WHEN 'MA' THEN 35000
      WHEN 'IN' THEN 30000
      WHEN 'ID' THEN 30000
      WHEN 'VN' THEN 30000
      WHEN 'EG' THEN 30000
      WHEN 'KE' THEN 30000
      WHEN 'NG' THEN 25000
      WHEN 'PK' THEN 25000
      WHEN 'BD' THEN 25000
      ELSE 50000
    END,
    'initial_inventory', 10000,
    'working_capital_reserve_months', 3,
    'lease_deposit', CASE country
      WHEN 'US' THEN 24000
      WHEN 'CH' THEN 33600
      WHEN 'NO' THEN 31200
      WHEN 'JP' THEN 31200
      WHEN 'SG' THEN 28800
      WHEN 'AU' THEN 30000
      WHEN 'GB' THEN 28800
      WHEN 'DE' THEN 27600
      WHEN 'FR' THEN 26400
      WHEN 'NL' THEN 27600
      WHEN 'SE' THEN 28800
      WHEN 'CA' THEN 25200
      WHEN 'AT' THEN 26400
      WHEN 'DK' THEN 28800
      WHEN 'FI' THEN 27600
      WHEN 'BE' THEN 27600
      WHEN 'IE' THEN 26400
      WHEN 'IL' THEN 24000
      WHEN 'AE' THEN 22800
      WHEN 'KR' THEN 22800
      WHEN 'IT' THEN 21600
      WHEN 'ES' THEN 20400
      WHEN 'NZ' THEN 26400
      WHEN 'PT' THEN 16800
      WHEN 'GR' THEN 15600
      WHEN 'CZ' THEN 14400
      WHEN 'PL' THEN 13200
      WHEN 'HU' THEN 13200
      WHEN 'CL' THEN 13200
      WHEN 'CN' THEN 13200
      WHEN 'MY' THEN 12000
      WHEN 'MX' THEN 12000
      WHEN 'AR' THEN 10800
      WHEN 'BR' THEN 10800
      WHEN 'ZA' THEN 10800
      WHEN 'TH' THEN 10800
      WHEN 'TR' THEN 9600
      WHEN 'CO' THEN 9600
      WHEN 'PE' THEN 9600
      WHEN 'PH' THEN 9600
      WHEN 'MA' THEN 8400
      WHEN 'IN' THEN 7200
      WHEN 'ID' THEN 7200
      WHEN 'VN' THEN 7200
      WHEN 'EG' THEN 7200
      WHEN 'KE' THEN 7200
      WHEN 'NG' THEN 6000
      WHEN 'PK' THEN 6000
      WHEN 'BD' THEN 6000
      ELSE 12000
    END,
    'pre_opening_marketing', 8000,
    'total_estimated', CASE country
      WHEN 'US' THEN 400000
      WHEN 'CH' THEN 560000
      WHEN 'NO' THEN 520000
      WHEN 'JP' THEN 520000
      WHEN 'SG' THEN 480000
      WHEN 'AU' THEN 500000
      WHEN 'GB' THEN 480000
      WHEN 'DE' THEN 460000
      WHEN 'FR' THEN 440000
      WHEN 'NL' THEN 460000
      WHEN 'SE' THEN 480000
      WHEN 'CA' THEN 420000
      WHEN 'AT' THEN 440000
      WHEN 'DK' THEN 480000
      WHEN 'FI' THEN 460000
      WHEN 'BE' THEN 460000
      WHEN 'IE' THEN 440000
      WHEN 'IL' THEN 400000
      WHEN 'AE' THEN 380000
      WHEN 'KR' THEN 380000
      WHEN 'IT' THEN 360000
      WHEN 'ES' THEN 340000
      WHEN 'NZ' THEN 440000
      WHEN 'PT' THEN 280000
      WHEN 'GR' THEN 260000
      WHEN 'CZ' THEN 240000
      WHEN 'PL' THEN 220000
      WHEN 'HU' THEN 220000
      WHEN 'CL' THEN 220000
      WHEN 'CN' THEN 220000
      WHEN 'MY' THEN 200000
      WHEN 'MX' THEN 200000
      WHEN 'AR' THEN 180000
      WHEN 'BR' THEN 180000
      WHEN 'ZA' THEN 180000
      WHEN 'TH' THEN 180000
      WHEN 'TR' THEN 160000
      WHEN 'CO' THEN 160000
      WHEN 'PE' THEN 160000
      WHEN 'PH' THEN 160000
      WHEN 'MA' THEN 140000
      WHEN 'IN' THEN 120000
      WHEN 'ID' THEN 120000
      WHEN 'VN' THEN 120000
      WHEN 'EG' THEN 120000
      WHEN 'KE' THEN 120000
      WHEN 'NG' THEN 100000
      WHEN 'PK' THEN 100000
      WHEN 'BD' THEN 100000
      ELSE 200000
    END,
    'source_note', 'Capital fit-out scaled from US baseline by country construction-cost index.'
  ),
  'payback_months_estimate', NULL,
  'refreshed_at', '2026-05-24',
  'grade', 'C'
)
WHERE country = 'US'
  AND naics_6 IN ('541940')
  AND rev_p50 IS NOT NULL
  AND (setup_costs IS NULL OR setup_costs->>'grade' IN ('C', 'D'));

-- 3. extrapolated_cells (country-level fallback)
UPDATE extrapolated_cells
SET cost_stack = jsonb_build_object(
  'rent_occupancy',         ROUND(predicted_rev_per_firm * 0.08),
  'payroll_total',          ROUND(predicted_rev_per_firm * 0.4),
  'cost_of_goods_sold',     ROUND(predicted_rev_per_firm * 0.18),
  'utilities',              ROUND(predicted_rev_per_firm * 0.02),
  'marketing_acquisition',  ROUND(predicted_rev_per_firm * 0.03),
  'insurance_professional', ROUND(predicted_rev_per_firm * 0.04),
  'equipment_maintenance',  ROUND(predicted_rev_per_firm * 0.04),
  'regulatory_licensing',   ROUND(predicted_rev_per_firm * 0.02),
  'refreshed_at',           '2026-05-24',
  'source_note',            'AVMA Economic State of the Veterinary Profession 2024 + VPI/Nationwide cost surveys. Country-level extrapolation; coarser than regional_cells.',
  'grade',                  'D'
)
WHERE industry_id = 'veterinary_pet_care'
  AND predicted_rev_per_firm IS NOT NULL
  AND predicted_rev_per_firm > 0
  AND (cost_stack IS NULL OR cost_stack->>'grade' IN ('C', 'D'));
