/**
 * GENERATED by scripts/gen_served_files.ts from public/ and the routes of src/app; do not edit by hand. The edge middleware
 * reads it (src/lib/routing/edge_not_found.ts) to tell a file this site serves from an address that only looks like one;
 * tests/routing/edge_not_found.test.ts reds when this file and a fresh generation differ.
 */

/** Every address with a dot in its last part that this site serves: each file under public/, then each file a route of src/app
 *  writes there. Exact, as the middleware sees a path after its lowercase redirect: a capital in a file's name is an address
 *  no request reaches. */
export const SERVED_FILES: ReadonlySet<string> = new Set([
  /* public/ */
  "/atlas-accent.svg",
  "/atlas-columns.svg",
  "/atlas-crosshatch.svg",
  "/atlas-grid.svg",
  "/atlas-pattern-dark.svg",
  "/atlas-pattern.svg",
  "/atlas-pinstripe.svg",
  "/atlas-rosette.svg",
  "/cities/README.txt",
  "/cities/birmingham.jpeg",
  "/cities/bristol.jpeg",
  "/cities/edinburgh.jpeg",
  "/cities/glasgow.jpeg",
  "/cities/leeds.jpeg",
  "/cities/london.jpeg",
  "/cities/manchester.jpeg",
  "/countries/gb.jpeg",
  "/data/uk/2026.10/citation.cff",
  "/data/uk/2026.10/failures_by_trade.csv",
  "/data/uk/2026.10/food_by_borough.csv",
  "/data/uk/2026.10/ledger.json",
  "/data/uk/2026.10/rateable_value_by_borough.csv",
  "/data/uk/2026.10/readme.md",
  "/data/uk/2026.10/station_footfall.csv",
  "/data/uk/2026.10/survival_by_borough.csv",
  "/data/uk/2026.10/survival_by_trade_group.csv",
  "/data/uk/2026.10/trades_by_borough.csv",
  "/data/uk/2026.10/trades_sic.json",
  "/geo/countries-110m.json",
  "/london-cities.png",
  "/spine/_skyline.jpeg",
  "/spine/london.jpeg",
  /* src/app/robots.ts */
  "/robots.txt",
  /* src/app/sitemap.ts */
  "/sitemap/0.xml",
  "/sitemap/1.xml",
  "/sitemap/2.xml",
  "/sitemap/3.xml",
  "/sitemap/4.xml",
  "/sitemap/5.xml",
  "/sitemap/6.xml",
  "/sitemap/7.xml",
  "/sitemap/8.xml",
]);
