/**
 * build_city_images_manifest , writes data/cities/images_manifest.json from the
 * files that EXIST in public/cities/, one per city slug (<slug>.jpeg). The
 * manifest is what the pager card and the city hero read (founder ruling 2 of
 * 2026-09-04: the card's image is the city hero's image), so a card can never
 * point at a photo that is not there. Run after adding photos:
 *   npx tsx scripts/build_city_images_manifest.ts
 * The asset contract: JPEG, 4:3, at least 640x480, under 160KB, a real
 * photograph the atlas has the right to show; the credit belongs in
 * data/cities/images_credits.json beside it (kept by hand).
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
const dir = "public/cities";
const out: Record<string, { file: string; bytes: number }> = {};
for (const f of readdirSync(dir)) {
  const m = /^([a-z0-9-]+)\.(jpe?g)$/i.exec(f);
  if (!m) continue;
  out[m[1]] = { file: `/cities/${f}`, bytes: statSync(path.join(dir, f)).size };
}
writeFileSync("data/cities/images_manifest.json", JSON.stringify({ anchor: "Generated by scripts/build_city_images_manifest.ts from public/cities. Do not edit by hand.", cities: out }, null, 2) + "\n");
console.log("city images:", Object.keys(out).length, Object.keys(out).join(" "));
