/**
 * build_city_images_manifest , writes data/cities/images_manifest.json from the
 * files that EXIST in public/cities/, one per city slug (<slug>.jpeg). The
 * manifest is what the pager card and the city hero read (founder ruling 2 of
 * 2026-09-04: the card's image is the city hero's image), so a card can never
 * point at a photo that is not there. Run after adding photos:
 *   npx tsx scripts/build_city_images_manifest.ts
 * The asset contract: JPEG, 4:3, at least 640x480, under 160KB, a real
 * photograph the atlas has the right to show; the credit belongs in
 * data/cities/images_credits.json beside it (kept by hand).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
const dir = "public/cities";
const out: Record<string, { file: string; bytes: number }> = {};
/* A folder with no photograph in it is an empty manifest, not a crash: since
   2026-09-11 no covered city holds one (the London file was the street map he
   ruled out by name, and it left this folder), and a fresh clone may not carry
   the folder at all. */
for (const f of existsSync(dir) ? readdirSync(dir) : []) {
  const m = /^([a-z0-9-]+)\.(jpe?g)$/i.exec(f);
  if (!m) continue;
  out[m[1]] = { file: `/cities/${f}`, bytes: statSync(path.join(dir, f)).size };
}
writeFileSync("data/cities/images_manifest.json", JSON.stringify({ anchor: "Generated by scripts/build_city_images_manifest.ts from public/cities. Do not edit by hand.", cities: out }, null, 2) + "\n");
console.log("city images:", Object.keys(out).length, Object.keys(out).join(" "));

/* THE COUNTRY PHOTOGRAPHS (2026-09-25), the same contract one level up: public/countries/<iso2>.jpeg, read into
   data/countries/images_manifest.json, which the country hero reads (hero_board.ts heroImageFor). The alt text comes from the
   hand-kept record of where each photograph came from (data/cities/images_credits.json), so a photograph with no record draws
   with an empty alt rather than a guessed one. */
const credits = existsSync("data/cities/images_credits.json")
  ? (JSON.parse(readFileSync("data/cities/images_credits.json", "utf8")) as { photos?: Record<string, { alt?: string }> }).photos ?? {}
  : {};
const cdir = "public/countries";
const countries: Record<string, { file: string; bytes: number; alt: string }> = {};
for (const f of existsSync(cdir) ? readdirSync(cdir) : []) {
  const m = /^([a-z]{2})\.(jpe?g)$/i.exec(f);
  if (!m) continue;
  countries[m[1].toLowerCase()] = { file: `/countries/${f}`, bytes: statSync(path.join(cdir, f)).size, alt: credits[m[1].toLowerCase()]?.alt ?? "" };
}
mkdirSync("data/countries", { recursive: true });
writeFileSync("data/countries/images_manifest.json", JSON.stringify({ anchor: "Generated by scripts/build_city_images_manifest.ts from public/countries. Do not edit by hand.", countries }, null, 2) + "\n");
console.log("country images:", Object.keys(countries).length, Object.keys(countries).join(" "));
