/**
 * scripts/counts.ts , the one place a count about this repo is produced.
 *
 * WHY IT EXISTS. The gate count alone was stated at roughly 78 line locations
 * across 32 files, at TEN different values (25, 26, 31, 53, 58, 95, 98, 99, 101,
 * 102). Every one of those was typed by somebody who had just measured it, and
 * every one was true for a while. That is the whole defect: a number is wrong the
 * moment it is typed, because typing it is the act that decouples it from its
 * source. `docs/loop/artifacts/failure-log.md` records it as the class behind
 * every tick of this loop so far.
 *
 * So documents stop STATING counts and start CARRYING them. Each carrier holds a
 * marked block this script writes, and `--check` fails the chain when a block no
 * longer matches what the repo actually contains.
 *
 * MODES
 *   (no args)  print the counts, touch nothing
 *   --write    rewrite every marked block in the carriers
 *   --check    exit 1 if any block is stale, naming the command that fixes it
 *
 * THE GATE COUNT IS PARSED WITH `strip_comments`, NOT GREPPED, and the
 * difference is not academic. The GATES array in `prebuild_all.ts` contains 35
 * comment blocks, several of which quote gate registrations verbatim while
 * explaining them. A naive `grep -c '{ name: "'` returns the right answer today
 * BY LUCK, and would drift the first time somebody writes an example in a
 * comment. The repo has a tested stripper for exactly this and it is used here.
 *
 * WHAT IT CANNOT DO, stated: it counts what the repo contains, never whether a
 * count is the RIGHT thing for a document to say. A carrier can hold a perfectly
 * fresh number in a sentence that is nonsense. And `tracked files` comes from
 * `git ls-files`, so it is a claim about the index rather than about the working
 * tree: a file that exists and is untracked is invisible here, deliberately,
 * because untracked files are not part of the repo.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

import { newCommentState, stripComments } from "./lib/strip_comments";

const BEGIN = "<!-- counts:begin (generated by scripts/counts.ts, do not edit by hand) -->";
const END = "<!-- counts:end -->";

/** Every document that carries a generated block. Add a file here, not a number. */
const CARRIERS = [
  "CLAUDE.md",
  "docs/verification-protocol.md",
  "docs/loop/02-ORGANISATION-RESEARCH.md",
];

type Counts = {
  gates: number;
  trackedFiles: number;
  routes: number;
  docs: number;
  scripts: number;
};

function gitLines(args: string[]): string[] {
  const out = execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  return out.split("\n").filter(Boolean);
}

/** GATES entries in prebuild_all.ts, comments stripped so a quoted example cannot count. */
function countGates(): number {
  const src = fs.readFileSync(path.join("scripts", "prebuild_all.ts"), "utf8").split("\n");
  const state = newCommentState();
  let n = 0;
  for (const line of src) {
    const code = stripComments(line, state);
    if (/^\s*\{\s*name:\s*"/.test(code)) n++;
  }
  return n;
}

function measure(): Counts {
  const tracked = gitLines(["ls-files"]);
  return {
    gates: countGates(),
    trackedFiles: tracked.length,
    routes: tracked.filter((f) => /^src\/app\/.*\/page\.tsx$/.test(f) || f === "src/app/page.tsx")
      .length,
    docs: tracked.filter((f) => f.startsWith("docs/")).length,
    scripts: tracked.filter((f) => f.startsWith("scripts/")).length,
  };
}

/** The block body. One fact per line, each naming how it was counted. */
function render(c: Counts): string {
  return [
    BEGIN,
    `- **${c.gates}** gates in the prebuild chain (\`GATES\` in \`scripts/prebuild_all.ts\`, comments stripped)`,
    `- **${c.trackedFiles}** tracked files, **${c.docs}** under \`docs/\`, **${c.scripts}** under \`scripts/\``,
    `- **${c.routes}** App Router page routes`,
    "",
    `Generated by \`npx tsx scripts/counts.ts --write\`. Do not type these numbers anywhere; carry this block instead.`,
    END,
  ].join("\n");
}

function replaceBlock(text: string, block: string): string | null {
  const i = text.indexOf(BEGIN);
  const j = text.indexOf(END);
  if (i === -1 || j === -1 || j < i) return null;
  return text.slice(0, i) + block + text.slice(j + END.length);
}

function main() {
  const args = process.argv.slice(2);
  const write = args.includes("--write");
  const check = args.includes("--check");
  const counts = measure();
  const block = render(counts);

  if (!write && !check) {
    console.log(block);
    return;
  }

  const stale: string[] = [];
  const missing: string[] = [];

  for (const file of CARRIERS) {
    if (!fs.existsSync(file)) {
      missing.push(file);
      continue;
    }
    const text = fs.readFileSync(file, "utf8");
    const next = replaceBlock(text, block);
    if (next === null) {
      missing.push(file);
      continue;
    }
    if (next !== text) {
      if (write) fs.writeFileSync(file, next);
      else stale.push(file);
    }
  }

  if (missing.length > 0) {
    console.error(
      `[counts] FAIL: ${missing.length} carrier(s) have no counts block: ${missing.join(", ")}`,
    );
    console.error(`Add the markers, then run: npx tsx scripts/counts.ts --write`);
    process.exit(1);
  }

  if (check && stale.length > 0) {
    console.error(`[counts] FAIL: ${stale.length} carrier(s) hold a stale counts block:`);
    for (const f of stale) console.error(`  ${f}`);
    /* cog's --check-fail-msg, copied on purpose: a failure that does not name the
       command that fixes it costs the reader a search every single time. */
    console.error(`\nFix with: npx tsx scripts/counts.ts --write`);
    process.exit(1);
  }

  console.log(
    write
      ? `[counts] wrote ${CARRIERS.length} carrier(s): ${counts.gates} gates, ${counts.trackedFiles} tracked files, ${counts.routes} routes`
      : `[counts] PASS: ${CARRIERS.length} carrier(s) current (${counts.gates} gates, ${counts.trackedFiles} tracked files, ${counts.docs} docs, ${counts.scripts} scripts, ${counts.routes} routes)`,
  );
}

main();
