/**
 * scripts/gen_hood_slugs.ts
 *
 * Writes src/lib/routing/hood_slugs.ts: the neighbourhood slugs the edge middleware needs to tell an address that names a
 * page from one that names nothing (masterplan step 01, 2026-10-05). The middleware runs on every request at the edge and
 * must never import src/lib/spine/hood_scheme.ts, which pulls the neighbourhood data in; this table is the few kilobytes of
 * slugs it reads instead. tests/routing/edge_not_found.test.ts reds when the committed file and a fresh generation differ.
 *
 *   npx tsx scripts/gen_hood_slugs.ts
 */
import { writeFileSync } from "node:fs";
import neighborhoodsJson from "../data/cities/neighborhoods_v1.json";
import { hasHoodScheme, spineHoodCities, spineHoodDistricts } from "../src/lib/spine/hood_scheme";

export const HOOD_SLUGS_FILE = "src/lib/routing/hood_slugs.ts";

type Scheme = { neighborhoods?: Array<{ slug?: string }> };

/** The file's whole text, from the hub's own admission functions and the neighbourhoods file. */
export function renderHoodSlugs(): string {
  const schemes = (neighborhoodsJson as { cities: Record<string, Scheme> }).cities;
  const hubs = Object.keys(schemes).filter((slug) => hasHoodScheme(slug)).sort();
  const row = (slug: string, slugs: string[]) => `  ${JSON.stringify(slug)}: [${slugs.map((s) => JSON.stringify(s)).join(", ")}],`;
  const neighborhoods = hubs.map((slug) => row(slug, (schemes[slug].neighborhoods ?? []).map((n) => String(n.slug ?? "").toLowerCase()).filter(Boolean)));
  const districts = spineHoodCities().sort().map((slug) => row(slug, (spineHoodDistricts(slug) ?? []).map((d) => d.slug)));
  return [
    "/**",
    " * GENERATED by scripts/gen_hood_slugs.ts from data/cities/neighborhoods_v1.json and the hub's admission gate",
    " * (src/lib/spine/hood_scheme.ts); do not edit by hand. The edge middleware reads it (src/lib/routing/edge_not_found.ts),",
    " * never the neighbourhood data itself; tests/routing/edge_not_found.test.ts reds when this file and a fresh generation differ.",
    " */",
    "",
    "/** Each city with a neighbourhood hub (`hasHoodScheme`), and every neighbourhood its scheme names. A key here is a city",
    " *  whose `/cities/<slug>/neighborhoods` renders; the slugs are the districts the three-part addresses of before 2026-08-16",
    " *  named (`/gb/london/west-end`). */",
    "export const NEIGHBORHOOD_SLUGS: Readonly<Record<string, readonly string[]>> = {",
    ...neighborhoods,
    "};",
    "",
    "/** The admitted districts of each city (`spineHoodDistricts`): `/cities/<slug>/neighborhoods/<district>` renders for these only. */",
    "export const HOOD_DISTRICT_SLUGS: Readonly<Record<string, readonly string[]>> = {",
    ...districts,
    "};",
    "",
  ].join("\n");
}

if (require.main === module) {
  const text = renderHoodSlugs();
  writeFileSync(HOOD_SLUGS_FILE, text);
  console.log(`gen_hood_slugs: ${text.split("\n").length} lines written to ${HOOD_SLUGS_FILE}`);
}
