/**
 * scripts/gen_retired.ts , generates src/lib/taxonomy/retired.ts.
 *
 * WHY GENERATED RATHER THAN HAND-WRITTEN. A hand-written list of sixty slugs
 * drifts from the rules that produced it within one edit, and then nobody can
 * say which is authoritative. The rules live in scope_rules.ts; this projects
 * them into a lookup the middleware can use at request time without importing
 * the whole taxonomy.
 *
 * KEYED BY SLUG, NOT BY ID, and that distinction is load-bearing. A URL carries
 * the slug, and `industryToSlug` derives it from the activity's NAME, not its
 * id: "Aerospace & other transport mfg" has the id `other_transport_mfg` and the
 * slug `aerospace-other-transport-mfg`. Keying this file by id would produce a
 * map the middleware could never match, and it would fail silently, as a 404
 * rather than an error.
 *
 * Re-run after any change to scope_rules.ts or to the taxonomy:
 *   npx tsx scripts/gen_retired.ts
 */
import { writeFileSync } from "node:fs";
import { isInScope } from "../src/lib/taxonomy/scope_rules";
import { industryToSlug } from "../src/lib/taxonomy";
import { TAXONOMY_REDIRECTS } from "../src/lib/taxonomy/legacy_redirects";
import { MERGES } from "../src/lib/taxonomy/merges";
import industriesJson from "../src/lib/taxonomy/industries.json";

interface Industry {
  id: string;
  name: string;
  sector_id: string;
}
const INDUSTRIES = (industriesJson as unknown as { industries: Industry[] }).industries;

const rows: string[] = [];
const retiredSlugs = new Set<string>();
let n = 0;
let collapsed = 0;

for (const ind of INDUSTRIES) {
  const verdict = isInScope(ind);
  if (verdict.inScope) continue;
  n++;
  retiredSlugs.add(industryToSlug(ind.id));

  /* A SCOPE-RETIRED ACTIVITY HAS NO SURVIVOR, by definition: it is not a
     duplicate of something, it simply does not belong here. So it goes to the
     activity directory, matching the precedent already in the middleware for
     retired sector pages. Do not invent a nearer destination: sending a reader
     to a sector page that no longer lists the thing they asked for is worse
     than sending them somewhere that plainly shows what the atlas does hold.

     Phase 2 adds MERGED activities to this same map, and those DO have a
     survivor, so they get `/industries/<survivor>` instead. */
  rows.push(
    `  ${JSON.stringify(industryToSlug(ind.id))}: {\n` +
      `    reason: ${JSON.stringify("out of scope: fails " + verdict.failed.join(", "))},\n` +
      `    redirectTo: "/industries",\n` +
      `  },`,
  );
}

/* MERGED ACTIVITIES. Unlike a scope retirement, a merge HAS a survivor, and
   the survivor's page is a genuinely better destination than the directory: the
   reader asked about lingerie and the clothing page answers them.

   Runs after the scope loop so a merged id that is ALSO out of scope keeps its
   scope reason, which is the more informative of the two. */
let merged = 0;
for (const [fromId, toId] of Object.entries(MERGES)) {
  const fromSlug = industryToSlug(fromId);
  if (retiredSlugs.has(fromSlug)) continue; // already retired for scope
  merged++;
  retiredSlugs.add(fromSlug);
  rows.push(
    `  ${JSON.stringify(fromSlug)}: {\n` +
      `    reason: ${JSON.stringify(`merged into ${toId}: the same business under another name`)},\n` +
      `    redirectTo: ${JSON.stringify("/industries/" + industryToSlug(toId))},\n` +
      `  },`,
  );
}

/* CHAIN COLLAPSE. Legacy slugs point at activities that are now retired or
   merged, so `/industries/crop-farming` would answer 308 to
   `/industries/grain-farming`, which answers 308 again: two hops. Search
   engines follow a chain but dilute equity across it and read longer ones as
   soft 404s, and the founder named search as his fear about this change. Emit a
   DIRECT entry for each so every old URL resolves in one hop.

   Order matters: this runs after BOTH loops above, so `retiredSlugs` holds
   every scope retirement and every merge before it is consulted. */
for (const [legacySlug, target] of Object.entries(TAXONOMY_REDIRECTS)) {
  if (!retiredSlugs.has(target)) continue;
  if (retiredSlugs.has(legacySlug)) continue; // already emitted above
  collapsed++;
  /* Inherit the target's own destination rather than defaulting to the
     directory: if the target was MERGED, the legacy slug should land on the
     survivor's page too, not be dumped at the index. */
  const targetRow = rows.find((r) => r.startsWith(`  ${JSON.stringify(target)}:`));
  const dest = targetRow?.match(/redirectTo: "([^"]+)"/)?.[1] ?? "/industries";
  rows.push(
    `  ${JSON.stringify(legacySlug)}: {\n` +
      `    reason: ${JSON.stringify(
        `legacy slug for ${target}, which is no longer published. Direct, to avoid a two-hop chain`,
      )},\n` +
      `    redirectTo: ${JSON.stringify(dest)},\n` +
      `  },`,
  );
}

const body = `/**
 * src/lib/taxonomy/retired.ts
 *
 * GENERATED by scripts/gen_retired.ts. DO NOT HAND-EDIT: change
 * src/lib/taxonomy/scope_rules.ts and re-run the generator, or this list and
 * the rules that made it drift apart and neither one is authoritative.
 *
 * Every activity retired from the atlas, why, and where its URL now sends a
 * reader.
 *
 * NOTHING IS DELETED. A retired slug keeps existing and answers a permanent
 * redirect, because a 404 throws away whatever search authority the page had
 * and adds a crawl error on top of losing it. The founder named SEO as his
 * specific fear about this change and it is a real one. Slug renames are banned
 * outright; this is the sanctioned way to remove an activity from the atlas.
 *
 * KEYED BY SLUG, not by id. A URL carries the slug, and the slug is derived
 * from the activity NAME: "Aerospace & other transport mfg" has the id
 * \`other_transport_mfg\` and the slug \`aerospace-other-transport-mfg\`.
 *
 * 308 rather than 301, matching the retired-sector precedent already in
 * src/middleware.ts. Both are permanent and both pass equity.
 */

export interface RetiredEntry {
  /** Why it went, in words a human can audit. */
  reason: string;
  /** Where its URL sends a reader now. Never itself, never a 404. */
  redirectTo: string;
}

export const RETIRED: Record<string, RetiredEntry> = {
${rows.join("\n")}
};

/** The redirect target for a retired slug, or null if the slug is still live. */
export function redirectFor(slug: string): string | null {
  return RETIRED[slug]?.redirectTo ?? null;
}
`;

writeFileSync("src/lib/taxonomy/retired.ts", body);
console.log(
  `wrote src/lib/taxonomy/retired.ts with ${n + merged + collapsed} entries ` +
    `(${n} out of scope, ${merged} merged, ${collapsed} legacy slugs collapsed to one hop)`,
);
