/**
 * scripts/gen_presence_manifest.ts , builds src/lib/taxonomy/presence_manifest.json.
 *
 * WHAT IT ANSWERS. For every country the atlas claims, crossed with every
 * published activity: does a real database row exist, and is it a trusted local
 * measurement or something weaker. That answer decides whether the pair gets a
 * page at all (src/lib/taxonomy/presence.ts).
 *
 * WHY IT IS A SEPARATE SCRIPT RATHER THAN A LIVE LOOKUP. Two reasons, and the
 * second is the one that matters.
 *
 *   1. Volume. Roughly 190 countries crossed with roughly 138 activities is
 *      over 26,000 pairs. That is a build-time job, not a per-request one.
 *
 *   2. **A LIVE LOOKUP WOULD MAKE A SLOW DATABASE UNPUBLISH THE SITE.** Cell
 *      lookups exceed their 4s budget from a developer machine to the database
 *      region, and `getCellBySlug` cannot distinguish a timeout from an empty
 *      result: both end in the synthesize branch. If presence were decided live,
 *      one slow afternoon would take real pages off the site, silently, page by
 *      page, with every gate still green.
 *
 * THIS CANNOT RUN FROM A MACHINE WHOSE QUERIES TIME OUT. It will produce a
 * manifest saying the atlas holds nothing anywhere, which is the most dangerous
 * possible output: it looks generated and it would hide everything. The guard
 * below refuses to write that.
 *
 * Run where the database is genuinely reachable:
 *   npx tsx --env-file=.env.local scripts/gen_presence_manifest.ts
 */
import { writeFileSync } from "node:fs";
import { INDUSTRIES, COUNTRIES } from "../src/lib/taxonomy";
import { getCellBySlug } from "../src/lib/cells";
import { isTrustedLocalCell } from "../src/lib/cells/trust";
import type { Presence } from "../src/lib/taxonomy/presence";

const OUT = "src/lib/taxonomy/presence_manifest.json";

/**
 * Refuse to write a manifest claiming the atlas holds almost nothing. A run
 * against an unreachable database produces exactly that, and shipping it would
 * unpublish the site. Tuned low on purpose: this is a catastrophe guard, not a
 * quality bar.
 */
const MIN_MEASURED_PAIRS = 200;

async function main() {
  const countries: Record<string, Record<string, Presence>> = {};
  let measured = 0;
  let modelled = 0;
  let none = 0;

  for (const country of COUNTRIES) {
    const iso = country.code.toLowerCase();
    const row: Record<string, Presence> = {};

    for (const ind of INDUSTRIES) {
      /* The country's own slug is used as the geography, which asks the
         question at the altitude presence is decided at: does this country hold
         this trade anywhere. A per-city manifest would be 25,000 times larger
         and answers a question nothing asks. */
      const cell = await getCellBySlug(iso, iso, ind.id);

      let verdict: Presence;
      if (cell?.is_synthetic) {
        /* Synthesized whole. Either the database holds nothing, or the query
           timed out. THIS SCRIPT CANNOT TELL THOSE APART, which is why the
           guard below exists rather than a per-pair retry. */
        verdict = "none";
        none++;
      } else if (isTrustedLocalCell(cell, ind.id)) {
        verdict = "measured";
        measured++;
      } else {
        verdict = "modelled";
        modelled++;
      }

      /* `none` is the default in presence.ts for a known country, so writing it
         is redundant and would roughly triple the file. Omit it. */
      if (verdict !== "none") row[ind.id] = verdict;
    }

    countries[iso] = row;
    process.stdout.write(
      `  ${iso}  measured ${Object.values(row).filter((v) => v === "measured").length}` +
        `  modelled ${Object.values(row).filter((v) => v === "modelled").length}\n`,
    );
  }

  console.log(`\n  totals: ${measured} measured, ${modelled} modelled, ${none} none`);

  if (measured < MIN_MEASURED_PAIRS) {
    console.error(
      `\n  REFUSING TO WRITE. Only ${measured} measured pairs, below the ${MIN_MEASURED_PAIRS} floor.\n` +
        `  That is what an unreachable database looks like, and shipping it would\n` +
        `  hide almost every page on the site. Nothing was written.\n`,
    );
    process.exit(1);
  }

  writeFileSync(
    OUT,
    JSON.stringify(
      {
        generated_at: new Date().toISOString(),
        note:
          "GENERATED by scripts/gen_presence_manifest.ts. A pair omitted from a " +
          "country listed here means the query ran and found nothing. A country " +
          "absent from this file is unknown, not empty, and publishes. See " +
          "src/lib/taxonomy/presence.ts.",
        countries,
      },
      null,
      2,
    ) + "\n",
  );
  console.log(`  wrote ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
