/**
 * gen_city_paths: write src/lib/routing/city_paths_generated.ts, the city
 * slugs each country holds, from data/cities/city_list_v1.json.
 *
 * WHY A GENERATED TABLE (the goal's D4, 2026-09-24): the edge middleware sends
 * `/gb/london` to `/cities/london` before its "place we do not hold" rewrite,
 * and the city list is 216 KB of fields the middleware never reads (population,
 * wages, sources); bundling it at the edge to ask one question would carry all
 * of it on every request. The table holds the slugs alone, a few kilobytes, the
 * way src/lib/taxonomy/retired.ts carries the retired trades' redirects. The
 * gate verify_city_path_redirect.ts reds when the table and the list disagree,
 * with this command as the remedy.
 *
 * usage: npx tsx scripts/gen_city_paths.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

type ListedCity = { slug: string; iso2: string };
const cities = (JSON.parse(readFileSync("data/cities/city_list_v1.json", "utf8")) as { cities: ListedCity[] }).cities;
const byCountry = new Map<string, string[]>();
for (const c of cities) {
  const cc = String(c.iso2).toLowerCase();
  if (!byCountry.has(cc)) byCountry.set(cc, []);
  byCountry.get(cc)!.push(String(c.slug).toLowerCase());
}
const lines = [...byCountry.keys()].sort().map((cc) => `  ${JSON.stringify(cc)}: [${byCountry.get(cc)!.sort().map((s) => JSON.stringify(s)).join(", ")}],`);
const out = [
  "/**",
  " * GENERATED by scripts/gen_city_paths.ts from data/cities/city_list_v1.json; do",
  " * not edit by hand. The city slugs each country holds, for the edge middleware and",
  " * the region route (src/lib/cities/city_path.ts); verify_city_path_redirect.ts reds",
  " * when this table and the list disagree.",
  " */",
  "export const CITY_SLUGS_BY_COUNTRY: Readonly<Record<string, readonly string[]>> = {",
  ...lines,
  "};",
  "",
].join("\n");
writeFileSync("src/lib/routing/city_paths_generated.ts", out);
console.log(`gen_city_paths: ${cities.length} cities under ${byCountry.size} countries written to src/lib/routing/city_paths_generated.ts`);
