/**
 * AUTO-GENERATED by scripts/cities/build_uk_cities.ts from data/cities/city_list_v1.json: the UK's cities with a page of their
 * own, by name. Do not edit; run the script. tests/home/destination.test.ts holds this file to the list.
 */
export const UK_CITY_PAGES: ReadonlyArray<{ slug: string; label: string }> = [
  {
    slug: "birmingham",
    label: "Birmingham"
  },
  {
    slug: "bristol",
    label: "Bristol"
  },
  {
    slug: "edinburgh",
    label: "Edinburgh"
  },
  {
    slug: "glasgow",
    label: "Glasgow"
  },
  {
    slug: "leeds",
    label: "Leeds"
  },
  {
    slug: "london",
    label: "London"
  },
  {
    slug: "manchester",
    label: "Manchester"
  }
];
