/**
 * atlas-pictograms-data.ts - the 64-mark trade/venue pictogram manifest,
 * ported from the design export (atlas-pictograms.js) per
 * docs/brand/visual-assets.md 2.4. GENERATED by a one-shot converter;
 * edit glyphs here directly from now on (the export is reference only).
 * Same grid/stroke family as the ma- icons, one accent max.
 */

export type AtlasPictogramId =
  | "restaurant"
  | "pizzeria"
  | "kebab"
  | "sushi"
  | "burger"
  | "cafe"
  | "bakery"
  | "patisserie"
  | "juice"
  | "bar"
  | "seafood"
  | "icecream"
  | "foodtruck"
  | "barber"
  | "salon"
  | "nails"
  | "spa"
  | "pharmacy"
  | "dentist"
  | "clinic"
  | "optician"
  | "vet"
  | "gym"
  | "yoga"
  | "grocery"
  | "convenience"
  | "greengrocer"
  | "florist"
  | "bookshop"
  | "clothing"
  | "shoes"
  | "jewellery"
  | "electronics"
  | "mobile"
  | "hardware"
  | "gift"
  | "auto"
  | "carwash"
  | "plumber"
  | "electrician"
  | "carpenter"
  | "painter"
  | "locksmith"
  | "laundry"
  | "tailor"
  | "cleaning"
  | "movers"
  | "print"
  | "law"
  | "accountant"
  | "software"
  | "design"
  | "architecture"
  | "estate"
  | "photography"
  | "marketing"
  | "hotel"
  | "guesthouse"
  | "travel"
  | "coworking"
  | "v-high-street"
  | "v-mall"
  | "v-airport"
  | "v-station";

export type AtlasPictogramGroup =
  | "food-drink"
  | "health-personal-care"
  | "retail-shops"
  | "trades-home-services"
  | "professional-creative"
  | "hospitality-leisure"
  | "venues";

export interface AtlasPictogramDef {
  id: AtlasPictogramId;
  group: AtlasPictogramGroup;
  label: string;
  /** Raw SVG inner markup (viewBox 0 0 32 32, stroke-based). The
   *  accent classes "a" (stroke) / "af" (fill) bind to the vermillion
   *  token through the component layer, never a hardcoded hex. */
  body: string;
}

export const ATLAS_PICTOGRAMS: AtlasPictogramDef[] = [
  {
    id: "restaurant",
    group: "food-drink",
    label: "Restaurant",
    body: "<path d=\"M10.5 4v4.6M13 4v4.6M15.5 4v4.6\"/><path d=\"M10.5 8.6h5v.6a2.5 2.5 0 0 1-5 0Z\"/><path d=\"M13 11.7V28\"/><path d=\"M21.5 4c-1.8 1.3-2.8 4-2.8 7.7V15h2.8\"/><path d=\"M21.5 4V28\"/>",
  },
  {
    id: "pizzeria",
    group: "food-drink",
    label: "Pizzeria",
    body: "<path d=\"M16 4 5 24h22Z\"/><path d=\"M7 22.5h18\"/><circle class=\"af\" cx=\"13\" cy=\"17.5\" r=\"1.4\"/><circle class=\"af\" cx=\"18.5\" cy=\"19.5\" r=\"1.4\"/><circle class=\"af\" cx=\"15.5\" cy=\"12.5\" r=\"1.2\"/>",
  },
  {
    id: "kebab",
    group: "food-drink",
    label: "Kebab / shawarma",
    body: "<path d=\"M16 3v5M16 22v7\"/><ellipse cx=\"16\" cy=\"15\" rx=\"5.5\" ry=\"7.5\"/><path d=\"M10.8 12h10.4M10.5 15h11M10.8 18h10.4\" opacity=\".55\"/>",
  },
  {
    id: "sushi",
    group: "food-drink",
    label: "Sushi",
    body: "<circle cx=\"16\" cy=\"16\" r=\"8.5\"/><circle cx=\"16\" cy=\"16\" r=\"6\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"2.4\"/><path d=\"M16 7.5v3M16 21.5v3M7.5 16h3M21.5 16h3\" opacity=\".5\"/>",
  },
  {
    id: "burger",
    group: "food-drink",
    label: "Burger joint",
    body: "<path d=\"M6 12.5c0-4.2 4.5-7 10-7s10 2.8 10 7Z\"/><path d=\"M6 16.5h20\"/><path d=\"M6 19.5c0 2.6 2 4.2 4.2 4.2h11.6c2.2 0 4.2-1.6 4.2-4.2Z\"/><circle class=\"af\" cx=\"11\" cy=\"9.5\" r=\".7\"/><circle class=\"af\" cx=\"16\" cy=\"8.4\" r=\".7\"/><circle class=\"af\" cx=\"21\" cy=\"9.5\" r=\".7\"/>",
  },
  {
    id: "cafe",
    group: "food-drink",
    label: "Café / coffee",
    body: "<path d=\"M7 11h15v6a6 6 0 0 1-6 6h-3a6 6 0 0 1-6-6Z\"/><path d=\"M22 12.5h2.5a3 3 0 0 1 0 6H22\"/><path d=\"M6 27h18\"/><path class=\"a\" d=\"M11 4c-1 1.5-1 3 0 4.5M16 4c-1 1.5-1 3 0 4.5\"/>",
  },
  {
    id: "bakery",
    group: "food-drink",
    label: "Bakery",
    body: "<path d=\"M5 18c0-5 4-8 11-8s11 3 11 8a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2Z\"/><path d=\"M11 11l-1.5 8M16 10v9M21 11l1.5 8\" opacity=\".55\"/>",
  },
  {
    id: "patisserie",
    group: "food-drink",
    label: "Patisserie / desserts",
    body: "<path d=\"M8 13h16l-2 11a1.8 1.8 0 0 1-1.8 1.5H11.8A1.8 1.8 0 0 1 10 24Z\"/><path d=\"M8 13a8 5 0 0 1 16 0\"/><path d=\"M13 15 12 24M16 15v9M19 15 20 24\" opacity=\".4\"/><path class=\"af\" d=\"M16 4c0 1.5-1.5 2-1.5 3.5a1.5 1.5 0 0 0 3 0C17.5 6 16 5.5 16 4Z\"/>",
  },
  {
    id: "juice",
    group: "food-drink",
    label: "Juice & smoothie bar",
    body: "<path d=\"M9 9h14l-1.5 16a2 2 0 0 1-2 1.8h-7a2 2 0 0 1-2-1.8Z\"/><path d=\"M9 13.5h14\" opacity=\".5\"/><path class=\"a\" d=\"M20 5 16.5 13\"/>",
  },
  {
    id: "bar",
    group: "food-drink",
    label: "Bar / pub",
    body: "<path d=\"M6 7h20L16 18Z\"/><path d=\"M16 18v8\"/><path d=\"M11 26h10\"/><circle class=\"af\" cx=\"19\" cy=\"10\" r=\"1.3\"/>",
  },
  {
    id: "seafood",
    group: "food-drink",
    label: "Seafood",
    body: "<path d=\"M22 16c-3.5 4.5-9 4.5-13 2-2-1-3.5-1.5-5-2 1.5-.5 3-1 5-2 4-2.5 9.5-2.5 13 2Z\"/><path d=\"M22 16 27 12v8Z\"/><path d=\"M14 11.5c1 2 1 7 0 9\" opacity=\".5\"/><circle class=\"af\" cx=\"9.5\" cy=\"14.5\" r=\".9\"/>",
  },
  {
    id: "icecream",
    group: "food-drink",
    label: "Ice cream / gelato",
    body: "<path d=\"M11 14h10l-5 13Z\"/><circle cx=\"13\" cy=\"11\" r=\"4\"/><circle cx=\"19\" cy=\"11\" r=\"4\"/><path d=\"M12.5 17l1.5 4M19.5 17 18 21\" opacity=\".5\"/><circle class=\"af\" cx=\"16\" cy=\"6\" r=\"1.4\"/>",
  },
  {
    id: "foodtruck",
    group: "food-drink",
    label: "Food truck",
    body: "<path d=\"M3 12h14v9H3Z\"/><path d=\"M17 14h4l3 3v4h-7Z\"/><circle cx=\"8\" cy=\"21.5\" r=\"2.2\"/><circle cx=\"20\" cy=\"21.5\" r=\"2.2\"/><path d=\"M3 21h2.5M10.5 21h7M22.5 21H24\"/><path class=\"a\" d=\"M4 12V8.5h12V12\"/><path d=\"M6 14.5h7v3H6Z\" opacity=\".5\"/>",
  },
  {
    id: "barber",
    group: "health-personal-care",
    label: "Barber",
    body: "<rect x=\"11\" y=\"5\" width=\"10\" height=\"22\" rx=\"5\"/><path class=\"a\" d=\"M11.3 9.5 20.7 6.5M11 14 21 11M11 18.5 20.7 15.5M11.3 23 21 20\"/>",
  },
  {
    id: "salon",
    group: "health-personal-care",
    label: "Hair & beauty salon",
    body: "<circle cx=\"8\" cy=\"11\" r=\"2.8\"/><circle cx=\"8\" cy=\"21\" r=\"2.8\"/><path d=\"M10.4 12.6 24 25\"/><path d=\"M10.4 19.4 24 7\"/><circle cx=\"16\" cy=\"16\" r=\"1\"/>",
  },
  {
    id: "nails",
    group: "health-personal-care",
    label: "Nail salon",
    body: "<path d=\"M11 11h10v13a2 2 0 0 1-2 2h-6a2 2 0 0 1-2-2Z\"/><path d=\"M13.5 11V8h5v3\"/><path d=\"M11 16h10\" opacity=\".5\"/><rect class=\"a\" x=\"14\" y=\"3.5\" width=\"4\" height=\"4.5\" rx=\"1\"/>",
  },
  {
    id: "spa",
    group: "health-personal-care",
    label: "Spa / massage",
    body: "<ellipse cx=\"16\" cy=\"23\" rx=\"8\" ry=\"2.6\"/><ellipse cx=\"16\" cy=\"17.5\" rx=\"6\" ry=\"2.3\"/><ellipse cx=\"16\" cy=\"12.5\" rx=\"4.5\" ry=\"2\"/><ellipse class=\"af\" cx=\"16\" cy=\"8.2\" rx=\"3\" ry=\"1.6\"/>",
  },
  {
    id: "pharmacy",
    group: "health-personal-care",
    label: "Pharmacy",
    body: "<rect x=\"9\" y=\"10\" width=\"14\" height=\"15\" rx=\"2.5\"/><path d=\"M11 10V7a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v3\"/><path class=\"a\" d=\"M16 14v7M12.5 17.5h7\"/>",
  },
  {
    id: "dentist",
    group: "health-personal-care",
    label: "Dentist",
    body: "<path d=\"M9 5c-2.2 0-3.6 2-3.6 5 0 4 1 6 1.9 10 .4 2 .8 4 2.1 4 1.4 0 1.5-3 2-5s.8-3 1.6-3 1.1 1 1.6 3 .6 5 2 5c1.3 0 1.7-2 2.1-4 .9-4 1.9-6 1.9-10 0-3-1.4-5-3.6-5-1.6 0-2.6 1-4 1s-2.4-1-4-1Z\"/><path class=\"a\" d=\"M20 8.5c.9.6 1.2 1.7 1.1 2.9\"/>",
  },
  {
    id: "clinic",
    group: "health-personal-care",
    label: "Doctor / clinic",
    body: "<rect x=\"5\" y=\"7\" width=\"22\" height=\"20\" rx=\"2.5\"/><path d=\"M5 12h22\"/><path d=\"M11 7V4h10v3\" opacity=\".6\"/><path class=\"a\" d=\"M16 16v7M12.5 19.5h7\"/>",
  },
  {
    id: "optician",
    group: "health-personal-care",
    label: "Optician",
    body: "<circle cx=\"9\" cy=\"17\" r=\"4.5\"/><circle cx=\"23\" cy=\"17\" r=\"4.5\"/><path d=\"M13.5 16.5c1.5-1.6 3.5-1.6 5 0\"/><path d=\"M4.5 16 6 11.5M27.5 16 26 11.5\"/>",
  },
  {
    id: "vet",
    group: "health-personal-care",
    label: "Veterinary",
    body: "<circle cx=\"16\" cy=\"19.5\" r=\"4.5\"/><circle cx=\"9.5\" cy=\"13.5\" r=\"2.2\"/><circle class=\"af\" cx=\"14\" cy=\"10\" r=\"2.2\"/><circle cx=\"18.5\" cy=\"10\" r=\"2.2\"/><circle cx=\"22.5\" cy=\"13.5\" r=\"2.2\"/>",
  },
  {
    id: "gym",
    group: "health-personal-care",
    label: "Gym / fitness",
    body: "<path d=\"M4 16h24\"/><rect x=\"3\" y=\"11\" width=\"4\" height=\"10\" rx=\"1.3\"/><rect x=\"25\" y=\"11\" width=\"4\" height=\"10\" rx=\"1.3\"/><rect x=\"8\" y=\"13\" width=\"3\" height=\"6\" rx=\"1\"/><rect x=\"21\" y=\"13\" width=\"3\" height=\"6\" rx=\"1\"/>",
  },
  {
    id: "yoga",
    group: "health-personal-care",
    label: "Yoga / pilates",
    body: "<circle cx=\"16\" cy=\"8\" r=\"2.6\"/><path d=\"M16 11v4.5\"/><path d=\"M8 24c0-4 3.6-7 8-7s8 3 8 7Z\"/><path d=\"M10.5 19.5 16 22.5l5.5-3\" opacity=\".5\"/>",
  },
  {
    id: "grocery",
    group: "retail-shops",
    label: "Grocery / supermarket",
    body: "<path d=\"M4 5h3l2.6 13a2 2 0 0 0 2 1.6h9.6a2 2 0 0 0 2-1.5L26 9H8\"/><circle cx=\"12.5\" cy=\"24\" r=\"2\"/><circle cx=\"22\" cy=\"24\" r=\"2\"/>",
  },
  {
    id: "convenience",
    group: "retail-shops",
    label: "Convenience shop",
    body: "<path d=\"M5 12 7 7h18l2 5\"/><path d=\"M5 12h22\"/><path d=\"M7 12v15h18V12\"/><path d=\"M13 27v-8h6v8\"/><path class=\"a\" d=\"M5 12v3M9 12v3M13 12v3M17 12v3M21 12v3M25 12v3\"/>",
  },
  {
    id: "greengrocer",
    group: "retail-shops",
    label: "Greengrocer / produce",
    body: "<path d=\"M16 9c-1.6-2.2-5.2-2.6-7.2 0-2.3 2.9-1.6 8.3 1 11.4 1.6 1.9 2.6 2.1 3.6 2.1s2-.2 3.6-2.1c2.6-3.1 3.3-8.5 1-11.4-2-2.6-5.6-2.2-7.2 0Z\"/><path d=\"M16 9V6\" opacity=\".6\"/><path class=\"a\" d=\"M16 8c0-2.2 1.1-3.8 3.3-4.3\"/>",
  },
  {
    id: "florist",
    group: "retail-shops",
    label: "Florist",
    body: "<circle cx=\"16\" cy=\"8.5\" r=\"3\"/><circle cx=\"21.5\" cy=\"11.5\" r=\"3\"/><circle cx=\"21.5\" cy=\"17.5\" r=\"3\"/><circle cx=\"10.5\" cy=\"17.5\" r=\"3\"/><circle cx=\"10.5\" cy=\"11.5\" r=\"3\"/><circle class=\"af\" cx=\"16\" cy=\"14\" r=\"2\"/><path d=\"M16 17v9M16 22c2 0 3.5-1.3 4-3\" opacity=\".7\"/>",
  },
  {
    id: "bookshop",
    group: "retail-shops",
    label: "Bookshop",
    body: "<path d=\"M16 9C13 7 8 7 5 8v15c3-1 8-1 11 1 3-2 8-2 11-1V8c-3-1-8-1-11 1Z\"/><path d=\"M16 9v16\"/>",
  },
  {
    id: "clothing",
    group: "retail-shops",
    label: "Clothing boutique",
    body: "<path d=\"M11 5 7 8l-3 3 3 3 2-1.5V26h14V12.5l2 1.5 3-3-3-3-4-3-2 2.2a3 3 0 0 1-6 0Z\"/>",
  },
  {
    id: "shoes",
    group: "retail-shops",
    label: "Shoe shop",
    body: "<path d=\"M4 19h2.5l3-5 3 2 3-2 3.5 1c4 1 6.5 2 6.5 4v1a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1Z\"/><path d=\"M9.5 14l1 4M15.5 14l1 4\" opacity=\".5\"/><path class=\"a\" d=\"M21 17l3.5.7\"/>",
  },
  {
    id: "jewellery",
    group: "retail-shops",
    label: "Jewellery",
    body: "<path d=\"M9 6h14l4 6-11 14L5 12Z\"/><path d=\"M5 12h22\"/><path d=\"M9 6l3 6 4-6M23 6l-3 6-4-6M12 12l4 14 4-14\" opacity=\".55\"/>",
  },
  {
    id: "electronics",
    group: "retail-shops",
    label: "Electronics",
    body: "<rect x=\"4\" y=\"6\" width=\"24\" height=\"15\" rx=\"2\"/><path d=\"M11 25h10M16 21v4\"/><circle class=\"a\" cx=\"16\" cy=\"13\" r=\"3.2\"/><path class=\"a\" d=\"M16 9.6V13\"/>",
  },
  {
    id: "mobile",
    group: "retail-shops",
    label: "Mobile / phone shop",
    body: "<rect x=\"9\" y=\"4\" width=\"14\" height=\"24\" rx=\"3\"/><path d=\"M14 25h4\"/><path class=\"a\" d=\"M13.5 14.5v2.5M16 12.5v4.5M18.5 10.5v6.5\"/>",
  },
  {
    id: "hardware",
    group: "retail-shops",
    label: "Hardware / DIY",
    body: "<path d=\"M21 7a4.5 4.5 0 0 1-5.6 5.6L7 21l4 4 8.4-8.4A4.5 4.5 0 0 1 25 11l-3.3 3.3-2.8-.7-.7-2.8Z\"/>",
  },
  {
    id: "gift",
    group: "retail-shops",
    label: "Gift shop",
    body: "<rect x=\"5\" y=\"12\" width=\"22\" height=\"14\" rx=\"1.5\"/><path d=\"M5 16h22\"/><path class=\"a\" d=\"M16 12v14\"/><path class=\"a\" d=\"M16 12c-1.8-3.6-6.5-3.6-6.5-1 0 2.4 4 1 6.5 1 2.5 0 6.5 1.4 6.5-1 0-2.6-4.7-2.6-6.5 1Z\"/>",
  },
  {
    id: "auto",
    group: "trades-home-services",
    label: "Auto repair / garage",
    body: "<path d=\"M5 19l2.2-6.5A2.5 2.5 0 0 1 9.6 11h12.8a2.5 2.5 0 0 1 2.4 1.5L27 19\"/><path d=\"M4 19h24v3.5a1 1 0 0 1-1 1h-3v-1.5H8v1.5H5a1 1 0 0 1-1-1Z\"/><circle cx=\"9.5\" cy=\"22\" r=\"2.4\"/><circle cx=\"22.5\" cy=\"22\" r=\"2.4\"/><path d=\"M9 18.5 10.5 13M23 18.5 21.5 13\" opacity=\".5\"/>",
  },
  {
    id: "carwash",
    group: "trades-home-services",
    label: "Car wash",
    body: "<path d=\"M6 22l1.6-5A2.2 2.2 0 0 1 9.7 15.5h12.6a2.2 2.2 0 0 1 2.1 1.5L26 22\"/><path d=\"M5 22h22v2.5a1 1 0 0 1-1 1h-2v-1.5H9v1.5H6a1 1 0 0 1-1-1Z\"/><circle cx=\"10\" cy=\"24\" r=\"2\"/><circle cx=\"22\" cy=\"24\" r=\"2\"/><path class=\"a\" d=\"M9 9c0 1.3-1 1.7-1 3a1 1 0 0 0 2 0c0-1.3-1-1.7-1-3ZM16 7c0 1.4-1.1 1.9-1.1 3.2a1.1 1.1 0 0 0 2.2 0c0-1.3-1.1-1.8-1.1-3.2ZM23 9c0 1.3-1 1.7-1 3a1 1 0 0 0 2 0c0-1.3-1-1.7-1-3Z\"/>",
  },
  {
    id: "plumber",
    group: "trades-home-services",
    label: "Plumber",
    body: "<path d=\"M6 9h5v5H6Z\"/><path d=\"M8.5 9V6h3.5\"/><path d=\"M11 11h8a4 4 0 0 1 4 4\"/><path class=\"a\" d=\"M23 16c0 1.6-1.3 2.2-1.3 3.7a1.3 1.3 0 0 0 2.6 0c0-1.5-1.3-2.1-1.3-3.7Z\"/>",
  },
  {
    id: "electrician",
    group: "trades-home-services",
    label: "Electrician",
    body: "<path d=\"M17 3 7 17h6l-2 12 11-14h-6Z\"/>",
  },
  {
    id: "carpenter",
    group: "trades-home-services",
    label: "Carpenter / joiner",
    body: "<path d=\"M6 6h5v17h17v5H6Z\"/><path d=\"M6 11h5M6 16h5M11 23v5M16 23v5\" opacity=\".55\"/>",
  },
  {
    id: "painter",
    group: "trades-home-services",
    label: "Painter / decorator",
    body: "<rect x=\"5\" y=\"6\" width=\"16\" height=\"6\" rx=\"2\"/><path d=\"M21 9h3v4h-6\"/><path d=\"M18 13v2a2 2 0 0 1-2 2h-2v5\"/><path class=\"a\" d=\"M5 14.5h16\"/>",
  },
  {
    id: "locksmith",
    group: "trades-home-services",
    label: "Locksmith",
    body: "<rect x=\"7\" y=\"14\" width=\"18\" height=\"13\" rx=\"2.5\"/><path d=\"M11 14v-3a5 5 0 0 1 10 0v3\"/><circle class=\"af\" cx=\"16\" cy=\"20\" r=\"1.8\"/><path class=\"a\" d=\"M16 21.8V24\"/>",
  },
  {
    id: "laundry",
    group: "trades-home-services",
    label: "Dry cleaner / laundry",
    body: "<path d=\"M16 6a2.5 2.5 0 0 1 2.6 2.5c0 1.4-1.1 2.1-2.6 2.6\"/><path d=\"M16 11 5 21a1.2 1.2 0 0 0 .7 2.1h20.6A1.2 1.2 0 0 0 27 21Z\"/>",
  },
  {
    id: "tailor",
    group: "trades-home-services",
    label: "Tailor",
    body: "<path d=\"M9 6h14M9 26h14\"/><path d=\"M11 6v20M21 6v20\"/><path class=\"a\" d=\"M11 11h10M11 16h10M11 21h10\"/>",
  },
  {
    id: "cleaning",
    group: "trades-home-services",
    label: "Cleaning service",
    body: "<path d=\"M11 12h7v13a2 2 0 0 1-2 2h-3a2 2 0 0 1-2-2Z\"/><path d=\"M11 12V9h3\"/><path d=\"M14 9V6h3l3-2\"/><path class=\"a\" d=\"M22 5.5h3M23 3.5l2-1M23 7.5l2 1\"/>",
  },
  {
    id: "movers",
    group: "trades-home-services",
    label: "Movers / removals",
    body: "<path d=\"M5 11 16 6l11 5-11 5Z\"/><path d=\"M5 11v11l11 5V16\"/><path d=\"M27 11v11l-11 5\"/><path class=\"a\" d=\"M11 8.5 22 13.5\"/>",
  },
  {
    id: "print",
    group: "trades-home-services",
    label: "Print shop",
    body: "<rect x=\"6\" y=\"12\" width=\"20\" height=\"9\" rx=\"1.5\"/><path d=\"M9 12V6h14v6\"/><path d=\"M9 21h14v5H9Z\"/><circle cx=\"22.5\" cy=\"16.5\" r=\"1\"/><path class=\"a\" d=\"M11.5 24h6\"/>",
  },
  {
    id: "law",
    group: "professional-creative",
    label: "Law firm",
    body: "<path d=\"M16 5v20\"/><path d=\"M9 25h14\"/><path d=\"M7 9h18\"/><circle cx=\"16\" cy=\"8\" r=\"1.4\"/><path class=\"a\" d=\"M7 9 4 15a3.5 3.5 0 0 0 6 0Z\"/><path class=\"a\" d=\"M25 9 22 15a3.5 3.5 0 0 0 6 0Z\"/>",
  },
  {
    id: "accountant",
    group: "professional-creative",
    label: "Accountant",
    body: "<rect x=\"5\" y=\"6\" width=\"22\" height=\"20\" rx=\"2\"/><path d=\"M5 13h22M5 19.5h22\"/><circle class=\"af\" cx=\"11\" cy=\"9.5\" r=\"1.5\"/><circle cx=\"17\" cy=\"9.5\" r=\"1.5\"/><circle cx=\"22\" cy=\"9.5\" r=\"1.5\"/><circle cx=\"9\" cy=\"16.2\" r=\"1.5\"/><circle class=\"af\" cx=\"15\" cy=\"16.2\" r=\"1.5\"/><circle cx=\"21\" cy=\"16.2\" r=\"1.5\"/><circle cx=\"12\" cy=\"22.8\" r=\"1.5\"/><circle cx=\"18\" cy=\"22.8\" r=\"1.5\"/><circle class=\"af\" cx=\"23\" cy=\"22.8\" r=\"1.5\"/>",
  },
  {
    id: "software",
    group: "professional-creative",
    label: "Software studio",
    body: "<path d=\"M11 10 4 16l7 6\"/><path d=\"M21 10l7 6-7 6\"/><path class=\"a\" d=\"M18 7 14 25\"/>",
  },
  {
    id: "design",
    group: "professional-creative",
    label: "Design / creative agency",
    body: "<path d=\"M16 4 9 18l7 4 7-4Z\"/><path d=\"M16 22v6\"/><path d=\"M16 4v18\" opacity=\".5\"/><circle class=\"af\" cx=\"16\" cy=\"14\" r=\"1.6\"/>",
  },
  {
    id: "architecture",
    group: "professional-creative",
    label: "Architecture studio",
    body: "<path d=\"M16 5a2 2 0 0 1 1 3.7L21 24M16 5a2 2 0 0 0-1 3.7L11 24\"/><circle cx=\"16\" cy=\"6.8\" r=\".9\"/><path class=\"a\" d=\"M9 26l2.2-2.2M23 26l-2.2-2.2\"/>",
  },
  {
    id: "estate",
    group: "professional-creative",
    label: "Estate agent",
    body: "<path d=\"M5 15 16 6l11 9\"/><path d=\"M8 13v13h16V13\"/><path d=\"M13 26v-7h6v7\"/><path class=\"a\" d=\"M19.5 16.5v-2h2\"/>",
  },
  {
    id: "photography",
    group: "professional-creative",
    label: "Photography studio",
    body: "<circle cx=\"16\" cy=\"16\" r=\"10\"/><path d=\"M16 6.2 21 15M25 11.5 16.5 17M24.5 21.5 14.6 18M16 25.8 11 17M7 20.5 15.4 15M7.5 10.5 17.4 14\" opacity=\".7\"/><circle class=\"af\" cx=\"16\" cy=\"16\" r=\"1.8\"/>",
  },
  {
    id: "marketing",
    group: "professional-creative",
    label: "Marketing agency",
    body: "<path d=\"M6 13v6h3l9 5V8l-9 5Z\"/><path d=\"M6 13H5a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h1\"/><path d=\"M11 19.5v3.5a2 2 0 0 0 4 0v-1.7\" opacity=\".6\"/><path class=\"a\" d=\"M22 10c2.2 1.8 2.2 10.2 0 12\"/>",
  },
  {
    id: "hotel",
    group: "hospitality-leisure",
    label: "Hotel",
    body: "<path d=\"M3 14v10\"/><path d=\"M29 19v5\"/><path d=\"M3 24h26\"/><path d=\"M3 19h26\"/><path d=\"M6 19v-3a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v3\"/><path class=\"a\" d=\"M7 17.3h6\"/>",
  },
  {
    id: "guesthouse",
    group: "hospitality-leisure",
    label: "Guesthouse / B&B",
    body: "<path d=\"M5 14 16 6l11 8\"/><path d=\"M8 13v13h16V13\"/><path class=\"af\" d=\"M16 17.5c-1.2-1.6-3.8-1-3.8 1 0 1.7 2 3.1 3.8 4.4 1.8-1.3 3.8-2.7 3.8-4.4 0-2-2.6-2.6-3.8-1Z\"/>",
  },
  {
    id: "travel",
    group: "hospitality-leisure",
    label: "Travel agency",
    body: "<rect x=\"5\" y=\"11\" width=\"22\" height=\"14\" rx=\"2.5\"/><path d=\"M11 11V8a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v3\"/><path d=\"M16 11v14\" opacity=\".5\"/><rect class=\"a\" x=\"9\" y=\"16\" width=\"4\" height=\"3\" rx=\".6\"/>",
  },
  {
    id: "coworking",
    group: "hospitality-leisure",
    label: "Co-working space",
    body: "<path d=\"M8 9h16v11H8Z\"/><path d=\"M5 20h22l-2 3a2 2 0 0 1-1.6.8H8.6A2 2 0 0 1 7 23Z\"/><path class=\"a\" d=\"M12 14h8M12 17h5\" opacity=\".9\"/>",
  },
  {
    id: "v-high-street",
    group: "venues",
    label: "High street",
    body: "<path d=\"M4 26h24\"/><path d=\"M5 26V14l2-4h6l1 4v12\"/><path d=\"M14 26V13l2-4h6l1 4v13\"/><path d=\"M23 26V14l2-3h2v15\"/><path class=\"a\" d=\"M5 14h9M14 13h9\"/><path d=\"M8 26v-5h3v5\" opacity=\".6\"/>",
  },
  {
    id: "v-mall",
    group: "venues",
    label: "Shopping mall",
    body: "<path d=\"M4 27V12h24v15\"/><path d=\"M4 12 16 6l12 6\"/><path d=\"M11 27v-9a5 5 0 0 1 10 0v9\"/><path class=\"a\" d=\"M16 27V18\"/><path d=\"M7 16h3M22 16h3\" opacity=\".5\"/>",
  },
  {
    id: "v-airport",
    group: "venues",
    label: "Airport",
    body: "<path d=\"M4 27h24\"/><path d=\"M6 27V16h12v11\"/><path d=\"M6 16l6-3 6 3\"/><path d=\"M20 27V8h3v19\"/><path class=\"a\" d=\"M19.5 8h4l-1.5 3.2h-1Z\"/><path d=\"M9 22h3M9 18.5h3\" opacity=\".5\"/>",
  },
  {
    id: "v-station",
    group: "venues",
    label: "Station",
    body: "<path d=\"M8 6h16a3 3 0 0 1 3 3v11a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3V9a3 3 0 0 1 3-3Z\"/><path d=\"M5 14h22\"/><path d=\"M9 9h14v4H9Z\" opacity=\".5\"/><circle class=\"af\" cx=\"11\" cy=\"18.5\" r=\"1.4\"/><circle class=\"af\" cx=\"21\" cy=\"18.5\" r=\"1.4\"/><path d=\"M9 26l3-3M23 26l-3-3\"/>",
  },
];

export const ATLAS_PICTOGRAMS_BY_ID: Record<AtlasPictogramId, AtlasPictogramDef> = Object.fromEntries(
  ATLAS_PICTOGRAMS.map((d) => [d.id, d]),
) as Record<AtlasPictogramId, AtlasPictogramDef>;
