/**
 * Plan v27 Lane D - knowledge base article registry.
 *
 * 60 evergreen pages in three families:
 *   Family A: "How much does X make?" (20)
 *   Family B: "What is a healthy margin for X?" (20)
 *   Family C: "How to read benchmarks" (15) + reserved (5)
 *
 * Each article carries:
 *   - slug              URL slug
 *   - family            A | B | C
 *   - title             human-readable headline
 *   - question          search-intent phrasing
 *   - oneLineAnswer     bolded single-sentence answer
 *   - body              array of paragraphs (3-5 sentences each)
 *   - relatedIndustryIds for deep-link block to Atlas benchmarks
 *   - relatedSlugs      cross-links to other learn pages
 *
 * Bodies are deterministic editorial - no LLM at render time. No
 * citations in body (R-002).
 */

export type LearnArticle = {
  slug: string;
  family: "A" | "B" | "C";
  title: string;
  question: string;
  oneLineAnswer: string;
  body: string[];
  relatedIndustryIds: string[];
  relatedSlugs: string[];
  headlineNumber?: { value: string; label: string };
};

export const LEARN_ARTICLES: LearnArticle[] = [
  // ============ FAMILY A: How much does X make ============
  {
    slug: "how-much-does-a-restaurant-make",
    family: "A",
    title: "How much does a restaurant make?",
    question: "How much does an independent restaurant make per year?",
    oneLineAnswer: "An independent full-service restaurant typically takes in $850K-$1.4M in annual revenue, with the median sitting near $1.1M in a mid-tier US city.",
    headlineNumber: { value: "$1.1M", label: "Median annual revenue, US mid-tier city" },
    body: [
      "A typical independent restaurant runs a small team and a tight margin. Most of the money flows through food costs (28-34% of revenue), labor (28-36%), rent and utilities (8-12%), and the rest covers everything from insurance to point-of-sale fees. The middle 50% of restaurants land between $700K and $1.6M in annual revenue.",
      "Location is the single biggest swing factor. A restaurant on a high-traffic street in a tier-1 city can clear $2-3M and still feel cramped on margin; the same concept in a tier-3 city or suburb often runs $500-800K. Cuisine also matters: fast-casual concepts typically post higher revenue per square foot than full-service.",
      "What this means for an operator: a healthy independent restaurant needs to clear roughly $700K to be self-sustaining once an owner draws a working wage. Below that line, owners often work for less than their staff's hourly rate.",
    ],
    relatedIndustryIds: ["restaurants"],
    relatedSlugs: ["restaurant-profit-margin", "how-much-does-a-coffee-shop-make", "how-to-read-revenue-benchmarks"],
  },
  {
    slug: "how-much-does-a-coffee-shop-make",
    family: "A",
    title: "How much does a coffee shop make?",
    question: "How much does an independent coffee shop make per year?",
    oneLineAnswer: "An independent coffee shop typically takes in $400K-$900K in annual revenue, with the median around $600K.",
    headlineNumber: { value: "$600K", label: "Median annual revenue" },
    body: [
      "Coffee shops sit lower on the revenue scale than restaurants because the average ticket is smaller. The math is volume-driven: a busy independent shop sells 250-450 drinks a day at $4-7 each, plus a tail of pastries and retail beans. Annual revenue lands between $400K and $900K for most independents.",
      "Cost of goods runs lighter than restaurants (typically 18-25%) but labor is heavier - a coffee shop is a service business that lives or dies on barista quality. Rent matters more than for almost any other small business because foot traffic is everything.",
      "A coffee shop crosses into healthy territory above roughly $550K. Below that, owners are usually subsidizing the business with their own time.",
    ],
    relatedIndustryIds: ["coffee_shops"],
    relatedSlugs: ["how-much-does-a-restaurant-make", "how-much-does-a-bakery-make", "coffee-shop-profit-margin"],
  },
  {
    slug: "how-much-does-a-bakery-make",
    family: "A",
    title: "How much does a bakery make?",
    question: "How much does an independent bakery make per year?",
    oneLineAnswer: "An independent retail bakery typically takes in $450K-$950K in annual revenue.",
    headlineNumber: { value: "$650K", label: "Median annual revenue" },
    body: [
      "A retail bakery is a hybrid: it's a kitchen running at restaurant cost-of-goods discipline, paired with a storefront running at coffee-shop traffic patterns. The median lands near $650K, but the spread is wide - wholesale-heavy bakeries that supply restaurants can clear $1-2M, while pure-storefront neighborhood bakeries often run $350-500K.",
      "Margins are tightest at the small end because flour, butter, and dairy are commodities. Specialty bakeries (sourdough, gluten-free, ethnic specialties) tend to command higher per-unit prices and run healthier.",
      "The healthiest bakeries pair retail with one of three additions: catering, wholesale to local cafés, or a coffee program. Pure retail-only bakeries are the toughest model.",
    ],
    relatedIndustryIds: ["artisan_bakery_wholesale", "specialty_food_production"],
    relatedSlugs: ["how-much-does-a-restaurant-make", "how-much-does-a-coffee-shop-make"],
  },
  {
    slug: "how-much-does-a-food-truck-make",
    family: "A",
    title: "How much does a food truck make?",
    question: "How much does a food truck make per year?",
    oneLineAnswer: "An owner-operated food truck typically takes in $250K-$500K in annual revenue.",
    headlineNumber: { value: "$340K", label: "Median annual revenue" },
    body: [
      "Food trucks are the smallest format in food service: lower revenue, but also lower fixed cost. A solo or two-person food truck typically posts $250-500K in annual revenue, with the median near $340K. The cost base is small - fuel, commissary fees, food cost, and one or two labor lines.",
      "Weather and seasonality drive the variance more than for any restaurant. In cities with a long winter, food trucks lose three to four months of meaningful revenue. In year-round-warm climates, they post 30-50% more.",
      "The math works at half the revenue of a restaurant because the fixed cost is a fraction. A food truck clearing $300K can pay its owner-operator a working wage; a restaurant at the same revenue cannot.",
    ],
    relatedIndustryIds: ["restaurants"],
    relatedSlugs: ["how-much-does-a-restaurant-make", "restaurant-profit-margin"],
  },
  {
    slug: "how-much-does-a-barbershop-make",
    family: "A",
    title: "How much does a barbershop make?",
    question: "How much does an independent barbershop make per year?",
    oneLineAnswer: "An independent barbershop typically takes in $180K-$420K per year.",
    headlineNumber: { value: "$260K", label: "Median annual revenue" },
    body: [
      "A barbershop's revenue scales almost linearly with chair count. A solo-operator shop runs $80-150K. A 3-chair shop with two contractors typically posts $200-350K. A larger 5-7 chair operation in a dense urban area can clear $500-700K.",
      "Cost of goods is negligible (under 5%). Labor is the line that matters - most barbershops run on a booth-rental model where stylists are independent contractors paying $200-400/week for a chair. That keeps the owner's revenue lean but the model stable.",
      "Barbershops are one of the highest-margin small businesses by category, with a clean owner take-home percentage when the chair-rental model is used.",
    ],
    relatedIndustryIds: ["hair_salons"],
    relatedSlugs: ["how-much-does-a-hair-salon-make", "how-much-does-a-nail-salon-make"],
  },
  {
    slug: "how-much-does-a-hair-salon-make",
    family: "A",
    title: "How much does a hair salon make?",
    question: "How much does an independent hair salon make per year?",
    oneLineAnswer: "An independent hair salon typically takes in $250K-$600K per year.",
    headlineNumber: { value: "$380K", label: "Median annual revenue" },
    body: [
      "Hair salons run on similar economics to barbershops but with a higher per-ticket average (color services, extensions, retail product sales). The middle of the market lands at $250-600K with median around $380K.",
      "Retail product sales matter more here than in any other personal-services category. A salon that runs a tight retail program (15-25% of revenue from shampoo, conditioner, and tools) is meaningfully healthier than one that doesn't.",
      "Tier-1 cities run materially higher because color services charge a city-level premium that the underlying cost base doesn't fully absorb.",
    ],
    relatedIndustryIds: ["hair_salons"],
    relatedSlugs: ["how-much-does-a-barbershop-make", "how-much-does-a-nail-salon-make", "how-much-does-a-spa-make"],
  },
  {
    slug: "how-much-does-a-nail-salon-make",
    family: "A",
    title: "How much does a nail salon make?",
    question: "How much does a nail salon make per year?",
    oneLineAnswer: "An independent nail salon typically takes in $200K-$450K per year.",
    headlineNumber: { value: "$290K", label: "Median annual revenue" },
    body: [
      "Nail salons run on tighter per-service revenue than hair salons but at higher throughput. A typical shop runs 8-12 stations and processes 30-50 clients a day. Revenue lands between $200-450K for most.",
      "The category is competitive - densely-packed in urban areas, with prices held down by tight margins. Salons that succeed usually differentiate on either a premium experience (luxury upgrades, dedicated rooms) or speed (express manicure formats).",
      "Owner take-home tends to be lower than barbershops because labor is the full-time payroll model, not chair rental.",
    ],
    relatedIndustryIds: ["hair_salons"],
    relatedSlugs: ["how-much-does-a-hair-salon-make", "how-much-does-a-spa-make"],
  },
  {
    slug: "how-much-does-a-spa-make",
    family: "A",
    title: "How much does a spa make?",
    question: "How much does an independent day spa make per year?",
    oneLineAnswer: "An independent day spa typically takes in $400K-$900K per year.",
    headlineNumber: { value: "$580K", label: "Median annual revenue" },
    body: [
      "A day spa runs at a higher revenue tier than salons because the per-service ticket is larger (facials, massage, body treatments) and add-on retail is substantial. Most independents land in the $400-900K range.",
      "Labor is the dominant cost - typically 38-48% of revenue - because spa services don't scale: one therapist serves one client at a time. Real estate matters less than for cafés because clients book ahead.",
      "Spas paired with a medical aesthetics arm (injectables, laser) can run materially higher revenue, but those are a different category with different licensing requirements.",
    ],
    relatedIndustryIds: ["hair_salons"],
    relatedSlugs: ["how-much-does-a-hair-salon-make", "how-much-does-a-nail-salon-make"],
  },
  {
    slug: "how-much-does-a-law-firm-make",
    family: "A",
    title: "How much does a small law firm make?",
    question: "How much does a small law firm make per year?",
    oneLineAnswer: "A small law firm (1-5 lawyers) typically generates $400K-$2M in annual revenue.",
    headlineNumber: { value: "$850K", label: "Median annual revenue, small firms" },
    body: [
      "Small law firms run a wide revenue band because everything scales with the lawyers' billable rate and practice mix. A solo practitioner in transactional or estate work typically clears $300-500K. A 3-5 lawyer firm in litigation or corporate runs $1-2M. Boutique IP or M&A shops can clear well above that.",
      "Cost of goods is essentially zero - legal services don't have a material input cost. The cost structure is people: lawyers, paralegals, and support staff, typically 55-65% of revenue.",
      "Owner partners take home a much larger share of revenue than in most service businesses because the leverage on knowledge-work output is high.",
    ],
    relatedIndustryIds: ["law_offices"],
    relatedSlugs: ["how-much-does-an-accounting-firm-make", "professional-services-margin"],
  },
  {
    slug: "how-much-does-an-accounting-firm-make",
    family: "A",
    title: "How much does an accounting firm make?",
    question: "How much does a small accounting firm make per year?",
    oneLineAnswer: "A small accounting firm (1-5 CPAs) typically takes in $350K-$1.5M in annual revenue.",
    headlineNumber: { value: "$700K", label: "Median annual revenue, small firms" },
    body: [
      "Accounting firms run a similar revenue profile to law firms but with a different seasonality and a lower per-hour rate. A solo CPA typically clears $250-400K. A 3-5 person firm with a stable client book can run $800K-1.5M.",
      "The economics improve substantially when a firm has a recurring monthly book - bookkeeping, fractional CFO work, or multi-year tax engagements. Project-only firms run on tax-season peaks and quieter middle months.",
      "Most small firms are owner-operated; the partner draw is roughly 35-50% of revenue.",
    ],
    relatedIndustryIds: ["accounting_services"],
    relatedSlugs: ["how-much-does-a-law-firm-make", "professional-services-margin"],
  },
  {
    slug: "how-much-does-a-dental-practice-make",
    family: "A",
    title: "How much does a dental practice make?",
    question: "How much does a small dental practice make per year?",
    oneLineAnswer: "A single-doctor dental practice typically generates $800K-$1.6M in annual revenue.",
    headlineNumber: { value: "$1.1M", label: "Median annual revenue, single-doctor" },
    body: [
      "A single-doctor dental practice runs a heavy fixed-cost base: equipment, sterilization, and lease typically eat 30-40% of revenue before labor. Revenue lands in the $800K-1.6M range for most.",
      "Add a hygienist and a second operatory and revenue scales materially without doubling cost. Multi-doctor practices often clear $2-4M.",
      "Owner take-home varies more than in other professional services because insurance reimbursement rates compress what a practice can charge. Specialties (orthodontics, oral surgery) clear higher than general dentistry.",
    ],
    relatedIndustryIds: ["dental_offices"],
    relatedSlugs: ["how-much-does-a-medical-practice-make"],
  },
  {
    slug: "how-much-does-a-medical-practice-make",
    family: "A",
    title: "How much does a small medical practice make?",
    question: "How much does a small medical practice make per year?",
    oneLineAnswer: "A small primary-care practice typically takes in $700K-$1.5M in annual revenue.",
    headlineNumber: { value: "$1.0M", label: "Median annual revenue, primary care" },
    body: [
      "A single-doctor primary-care practice typically posts $700K-1.5M in annual revenue. Specialties run materially higher: a dermatology or orthopedics practice can clear $2-5M per doctor.",
      "The cost structure is dominated by staff (medical assistants, billers, front desk) and electronic-health-record systems. Insurance reimbursement is the binding constraint on revenue - the practice can't simply raise prices.",
      "Owner take-home depends heavily on payer mix. Practices weighted toward Medicare and Medicaid earn less per visit than those with strong commercial insurance.",
    ],
    relatedIndustryIds: ["medical_offices"],
    relatedSlugs: ["how-much-does-a-dental-practice-make"],
  },
  {
    slug: "how-much-does-a-gym-make",
    family: "A",
    title: "How much does a gym make?",
    question: "How much does an independent gym make per year?",
    oneLineAnswer: "An independent gym typically takes in $250K-$1.2M in annual revenue.",
    headlineNumber: { value: "$520K", label: "Median annual revenue" },
    body: [
      "An independent gym's revenue is almost entirely membership-driven, with some retail and personal-training mixed in. A typical 2,000-3,500 sq ft boutique gym runs 200-600 members at $80-180/month, putting most in the $250K-$1.2M range.",
      "Real estate is the largest fixed cost (often 15-25% of revenue) and is the line that kills underperforming gyms. The healthiest model is a higher-priced boutique format (CrossFit, Pilates, yoga) where the per-member revenue is double a traditional gym and the space requirement is smaller.",
      "Personal training and retail are usually material profit centers even when they're a small share of revenue, because they carry much higher margins than the membership base.",
    ],
    relatedIndustryIds: ["fitness_centers"],
    relatedSlugs: ["how-much-does-a-yoga-studio-make"],
  },
  {
    slug: "how-much-does-a-yoga-studio-make",
    family: "A",
    title: "How much does a yoga studio make?",
    question: "How much does a yoga studio make per year?",
    oneLineAnswer: "An independent yoga studio typically takes in $180K-$500K in annual revenue.",
    headlineNumber: { value: "$310K", label: "Median annual revenue" },
    body: [
      "Yoga studios run a tighter revenue band than gyms because the format is class-based, not member-based. A typical studio runs 20-40 classes a week at 8-20 students per class. Revenue lands in the $180-500K range.",
      "Teacher pay is the dominant cost. Most studios pay teachers per-class plus per-head, which keeps the cost variable but limits the upside on a packed class.",
      "Workshops, teacher training, and retail are the lines that turn a marginally profitable studio into a healthy one. Pure class-only studios have a tough math.",
    ],
    relatedIndustryIds: ["fitness_centers"],
    relatedSlugs: ["how-much-does-a-gym-make"],
  },
  {
    slug: "how-much-does-a-bookstore-make",
    family: "A",
    title: "How much does an independent bookstore make?",
    question: "How much does an independent bookstore make per year?",
    oneLineAnswer: "An independent bookstore typically takes in $400K-$1.1M in annual revenue.",
    headlineNumber: { value: "$580K", label: "Median annual revenue" },
    body: [
      "An independent bookstore runs on thin margins - books carry standard 40-45% gross margin, but rent and staff eat most of that. A typical neighborhood bookstore lands at $400-700K. Larger flagship stores with strong event programming clear $1M+.",
      "Sideline products (cards, journals, gifts, café) often run double the margin of books and are what makes the difference between a bookstore that pays the rent and one that doesn't.",
      "The healthiest independent bookstores combine three things: a strong curation reputation, a regular event program that builds community, and a meaningful non-book retail line.",
    ],
    relatedIndustryIds: ["specialty_retail"],
    relatedSlugs: ["how-much-does-a-vintage-clothing-store-make", "retail-margin"],
  },
  {
    slug: "how-much-does-a-vintage-clothing-store-make",
    family: "A",
    title: "How much does a vintage clothing store make?",
    question: "How much does a vintage or thrift clothing store make per year?",
    oneLineAnswer: "An independent vintage clothing store typically takes in $200K-$650K in annual revenue.",
    headlineNumber: { value: "$340K", label: "Median annual revenue" },
    body: [
      "Vintage and curated thrift stores run a tight category because the cost of goods is genuinely variable - owners sourcing inventory at estate sales, flea markets, or wholesalers. Revenue lands in the $200-650K range.",
      "Margins are healthier than mainstream apparel retail because the cost of goods is often below 20%. The constraint is sourcing time, not margin.",
      "Online sales (Etsy, Depop, Instagram) are now a meaningful share of revenue for most stores - typically 20-40% of total - and have a different cost structure than the storefront.",
    ],
    relatedIndustryIds: ["specialty_retail"],
    relatedSlugs: ["how-much-does-a-bookstore-make", "retail-margin"],
  },
  {
    slug: "how-much-does-a-record-store-make",
    family: "A",
    title: "How much does a record store make?",
    question: "How much does an independent record store make per year?",
    oneLineAnswer: "An independent record store typically takes in $180K-$550K in annual revenue.",
    headlineNumber: { value: "$290K", label: "Median annual revenue" },
    body: [
      "Independent record stores have benefited from a decade-long vinyl resurgence. A typical neighborhood shop now clears $180-550K, with the strongest stores in tier-1 cities running well above that.",
      "New vinyl is a low-margin business (38-44% gross). Used vinyl, where the store sources at $1-5 and sells at $8-30, is the profit engine. The healthiest stores run a 50/50 new-to-used mix.",
      "Events, in-store performances, and a curated turntable accessory selection are how a record store moves from a hobby business to one that pays an owner a working wage.",
    ],
    relatedIndustryIds: ["specialty_retail"],
    relatedSlugs: ["how-much-does-a-bookstore-make", "retail-margin"],
  },
  {
    slug: "how-much-does-a-plumber-make",
    family: "A",
    title: "How much does a plumbing business make?",
    question: "How much does a small plumbing business make per year?",
    oneLineAnswer: "A small plumbing business (1-3 trucks) typically takes in $400K-$1.5M in annual revenue.",
    headlineNumber: { value: "$720K", label: "Median annual revenue" },
    body: [
      "A solo plumber with a single truck typically clears $200-400K. A 2-3 truck operation with one or two journeymen runs $700K-1.5M. Larger plumbing companies with a service-and-installation split can clear several million.",
      "Service work (calls, repairs) carries higher margins than new-construction installation. The healthiest plumbing businesses are heavy on service and use installation as a secondary revenue line.",
      "Owner take-home in trades is among the strongest of any SMB category - well-run plumbing businesses often clear 25-35% net margin.",
    ],
    relatedIndustryIds: ["plumbing_hvac"],
    relatedSlugs: ["how-much-does-an-electrician-make", "how-much-does-an-hvac-business-make"],
  },
  {
    slug: "how-much-does-an-electrician-make",
    family: "A",
    title: "How much does an electrician make?",
    question: "How much does a small electrical contracting business make?",
    oneLineAnswer: "A small electrical contractor (1-3 trucks) typically takes in $450K-$1.6M in annual revenue.",
    headlineNumber: { value: "$780K", label: "Median annual revenue" },
    body: [
      "Solo electricians clear $200-400K. Small electrical contractors with a handful of journeymen run $750K-1.6M. Commercial electricians clear more per project but have longer payment cycles than residential.",
      "Solar, EV-charger installation, and smart-home work have all opened higher-margin specialties in the past five years. Electricians with these specialties run materially higher revenue per truck than purely traditional shops.",
      "The category is supply-constrained - fewer licensed electricians are coming up than retiring. Pricing power has shifted toward existing operators.",
    ],
    relatedIndustryIds: ["plumbing_hvac"],
    relatedSlugs: ["how-much-does-a-plumber-make", "how-much-does-an-hvac-business-make"],
  },
  {
    slug: "how-much-does-an-hvac-business-make",
    family: "A",
    title: "How much does an HVAC business make?",
    question: "How much does a small HVAC business make per year?",
    oneLineAnswer: "A small HVAC business (1-3 trucks) typically takes in $500K-$1.8M in annual revenue.",
    headlineNumber: { value: "$900K", label: "Median annual revenue" },
    body: [
      "HVAC runs at the higher end of the trades because the unit ticket is large - installations are $5-15K, and maintenance contracts add steady recurring revenue. Solo operators clear $250-450K; 3-truck shops run $1-1.8M.",
      "Maintenance contracts (typically $200-500/year per home) are the strategic asset. They smooth seasonal cash flow and generate the service calls that lead to higher-ticket installation work.",
      "The seasonality is more extreme than plumbing or electrical: summer cooling and winter heating spikes, with the shoulder seasons being lean. Healthy HVAC businesses use the shoulders for maintenance contract work.",
    ],
    relatedIndustryIds: ["plumbing_hvac"],
    relatedSlugs: ["how-much-does-a-plumber-make", "how-much-does-an-electrician-make"],
  },

  // ============ FAMILY B: Healthy margins ============
  {
    slug: "restaurant-profit-margin",
    family: "B",
    title: "Restaurant profit margin: what's healthy?",
    question: "What is a healthy profit margin for a restaurant?",
    oneLineAnswer: "A healthy independent restaurant runs a 4-8% net profit margin. Above 10% is exceptional; below 3% is unsustainable.",
    headlineNumber: { value: "4-8%", label: "Healthy net profit margin" },
    body: [
      "Restaurant profit margins are notoriously tight. The math: food costs eat 28-34% of revenue, labor 28-36%, occupancy 8-12%, and everything else (utilities, insurance, POS, marketing, supplies) another 15-20%. What's left at the bottom is the net margin.",
      "A 4-8% net profit margin is the healthy band. A restaurant clearing 4% on $1M of revenue earns the owner $40K - which only works if the owner draws a separate working wage. Above 8% is exceptional and usually requires either a strong bar program, a tight cost discipline, or above-average pricing power.",
      "Below 3% is unsustainable because the variance in any given month exceeds the margin. A bad month wipes out a good month. Restaurants in that band typically don't survive a downturn.",
    ],
    relatedIndustryIds: ["restaurants"],
    relatedSlugs: ["how-much-does-a-restaurant-make", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "coffee-shop-profit-margin",
    family: "B",
    title: "Coffee shop profit margin: what's healthy?",
    question: "What is a healthy profit margin for a coffee shop?",
    oneLineAnswer: "A healthy independent coffee shop runs a 5-12% net profit margin.",
    headlineNumber: { value: "5-12%", label: "Healthy net profit margin" },
    body: [
      "Coffee shops can run materially better margins than restaurants because cost of goods is lighter (18-25% vs 30%+). The trade-off: smaller absolute revenue, so a healthy margin produces a smaller dollar number.",
      "A coffee shop clearing 8% on $600K of revenue earns the owner $48K. A coffee shop clearing 12% on the same revenue earns $72K - the difference is usually in retail attachment (beans, gear, baked goods) and pricing discipline.",
      "Multi-location coffee operators run leaner per-shop margins (typically 5-8%) because they carry overhead the single-shop doesn't, but they make it up on volume.",
    ],
    relatedIndustryIds: ["coffee_shops"],
    relatedSlugs: ["how-much-does-a-coffee-shop-make", "restaurant-profit-margin"],
  },
  {
    slug: "ecommerce-profit-margin",
    family: "B",
    title: "E-commerce profit margin: what's healthy?",
    question: "What is a healthy profit margin for an e-commerce business?",
    oneLineAnswer: "A healthy e-commerce business runs a 8-20% net profit margin, depending on product category and customer-acquisition costs.",
    headlineNumber: { value: "8-20%", label: "Healthy net profit margin" },
    body: [
      "E-commerce margins span a wide band because the categories are so different. Apparel runs 8-15% net. Beauty and personal care runs 15-25%. Heavy commodity goods (pet food, consumables) run 4-10%. The variance is mostly explained by customer-acquisition cost relative to repeat-purchase rate.",
      "The hidden killer is paid traffic. A business that pays $40 to acquire a customer who buys $80 worth of goods is gross-margin-positive but probably net-negative once shipping, returns, and fixed costs land.",
      "The healthiest e-commerce businesses have a meaningful percentage of repeat purchase or subscription revenue, which collapses customer-acquisition cost over the customer's lifetime.",
    ],
    relatedIndustryIds: ["ecommerce_retail", "specialty_retail"],
    relatedSlugs: ["retail-margin", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "saas-gross-margin",
    family: "B",
    title: "SaaS gross margin: what's healthy?",
    question: "What is a healthy gross margin for a SaaS business?",
    oneLineAnswer: "A healthy SaaS business runs a 70-85% gross margin.",
    headlineNumber: { value: "70-85%", label: "Healthy gross margin" },
    body: [
      "SaaS gross margins are the highest of any standard business category because the marginal cost of one more user is essentially zero. The cost of goods is hosting, support, and payment processing - typically 15-30% of revenue.",
      "Below 70% gross margin, a SaaS business has a structural problem: either too much manual service per customer (so it's actually a services business pretending to be software) or hosting costs eating too much (typically a sign the unit economics need rework).",
      "Above 85% is exceptional and usually only sustained by businesses that have negligible support costs because the product is self-serve.",
    ],
    relatedIndustryIds: ["software_dev_services"],
    relatedSlugs: ["professional-services-margin", "how-saas-revenue-scales"],
  },
  {
    slug: "agency-profit-margin",
    family: "B",
    title: "Agency profit margin: what's healthy?",
    question: "What is a healthy profit margin for a marketing or design agency?",
    oneLineAnswer: "A healthy small agency runs a 15-25% net profit margin.",
    headlineNumber: { value: "15-25%", label: "Healthy net profit margin" },
    body: [
      "Agency economics are dominated by people cost. Labor (salaries, benefits, contractor pay) typically eats 55-65% of revenue. Rent, software, and overhead take another 8-15%. What's left is the agency's net margin.",
      "Above 25% is rare and usually means an agency has a high billable-utilization rate (over 75%) or a project-pricing model that captures value rather than billing hours.",
      "Below 15% is usually a sign of underpricing or low utilization. The fix is almost always raising rates rather than cutting costs - agencies that try to grow into profitability rarely make it.",
    ],
    relatedIndustryIds: ["marketing_agencies", "creative_design"],
    relatedSlugs: ["professional-services-margin", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "construction-margin",
    family: "B",
    title: "Construction margin: what's healthy?",
    question: "What is a healthy margin for a residential construction business?",
    oneLineAnswer: "A healthy residential construction business runs an 8-15% net profit margin on project revenue.",
    headlineNumber: { value: "8-15%", label: "Healthy net profit margin" },
    body: [
      "Construction margins are project-by-project and depend heavily on whether the business carries materials cost or passes it through. Cost-plus contracts protect margin; fixed-price contracts can compress or expand it based on execution.",
      "An 8-15% net margin on full project revenue (including pass-through materials) is healthy. Some businesses run the math on labor margin instead - that band is typically 25-40%, which is what most operators benchmark against internally.",
      "The killer in construction is bid pricing under uncertainty. Healthy businesses build in a 5-10% contingency on materials and timeline and refuse to bid below that band.",
    ],
    relatedIndustryIds: ["construction_residential"],
    relatedSlugs: ["how-much-does-a-plumber-make", "trade-business-margins"],
  },
  {
    slug: "retail-margin",
    family: "B",
    title: "Retail margin: what's healthy?",
    question: "What is a healthy margin for a small retail store?",
    oneLineAnswer: "A healthy small retail store runs a 5-12% net profit margin.",
    headlineNumber: { value: "5-12%", label: "Healthy net profit margin" },
    body: [
      "Retail gross margins (the spread between wholesale cost and retail price) typically run 40-55% for apparel and gifts, 30-40% for books and groceries, and 50-65% for cosmetics and beauty. Net margin after rent, staff, and operations lands at 5-12% for the healthiest stores.",
      "Inventory management is the single biggest lever. A store that turns inventory four times a year is roughly twice as efficient as one that turns it twice a year, even at the same gross margin.",
      "The strongest small retail stores combine a tight curated selection with a meaningful online channel - typically 20-40% of total revenue - which makes the storefront an experience rather than the only sales surface.",
    ],
    relatedIndustryIds: ["specialty_retail"],
    relatedSlugs: ["how-much-does-a-bookstore-make", "ecommerce-profit-margin"],
  },
  {
    slug: "professional-services-margin",
    family: "B",
    title: "Professional services margin: what's healthy?",
    question: "What is a healthy margin for a professional services firm?",
    oneLineAnswer: "A healthy small professional services firm runs a 15-30% net profit margin, with owner draws on top.",
    headlineNumber: { value: "15-30%", label: "Healthy net profit margin" },
    body: [
      "Professional services - law, accounting, consulting, design - run on people cost. Labor typically eats 50-65% of revenue. Real estate is 5-10%. Software, insurance, and overhead another 5-10%. What's left is net margin plus owner draw.",
      "The cleaner way to read these businesses is on owner-comp-plus-net-margin combined. A well-run small firm where the partner draws a market salary AND retains 15-20% as net margin is doing very well.",
      "Underperforming firms usually have a labor utilization problem: too many people for the billable hours, or the wrong mix of senior-to-junior staff.",
    ],
    relatedIndustryIds: ["law_offices", "accounting_services"],
    relatedSlugs: ["agency-profit-margin", "saas-gross-margin"],
  },
  {
    slug: "trade-business-margins",
    family: "B",
    title: "Trade business margins: what's healthy?",
    question: "What is a healthy margin for a small trade business (plumbing, electrical, HVAC)?",
    oneLineAnswer: "A healthy small trade business runs a 15-25% net profit margin.",
    headlineNumber: { value: "15-25%", label: "Healthy net profit margin" },
    body: [
      "Trade businesses run higher net margins than most service businesses because the demand is non-discretionary and pricing power has tilted toward existing operators in the past decade.",
      "The math: labor is the dominant cost (typically 35-45% of revenue), then materials (15-25%), then trucks, insurance, and overhead. Net margin in the 15-25% band is achievable for well-run shops.",
      "The drivers of high-margin trade businesses are: a meaningful percentage of service work (vs new-construction installation), recurring maintenance contracts, and tight scheduling discipline that keeps trucks utilized.",
    ],
    relatedIndustryIds: ["plumbing_hvac"],
    relatedSlugs: ["how-much-does-a-plumber-make", "construction-margin"],
  },
  {
    slug: "gym-profit-margin",
    family: "B",
    title: "Gym profit margin: what's healthy?",
    question: "What is a healthy profit margin for an independent gym?",
    oneLineAnswer: "A healthy independent gym runs a 10-20% net profit margin.",
    headlineNumber: { value: "10-20%", label: "Healthy net profit margin" },
    body: [
      "Gym economics are dominated by rent and labor. A typical boutique gym runs 18-25% on real estate, 30-40% on labor (including teachers and front desk), and 5-10% on equipment lease and maintenance.",
      "The 10-20% net margin band is achievable when membership pricing reflects the local market and the gym runs a meaningful personal-training program (which carries materially higher margins than the base membership).",
      "Below 10% usually means underpricing - gym owners often anchor on the big-box gym chain price ($20-30/month) when the boutique format supports $80-180/month.",
    ],
    relatedIndustryIds: ["fitness_centers"],
    relatedSlugs: ["how-much-does-a-gym-make", "how-much-does-a-yoga-studio-make"],
  },
  {
    slug: "real-estate-brokerage-margin",
    family: "B",
    title: "Real estate brokerage margin: what's healthy?",
    question: "What is a healthy margin for a small real estate brokerage?",
    oneLineAnswer: "A healthy small real estate brokerage runs a 12-22% net profit margin on the brokerage's share of commission.",
    headlineNumber: { value: "12-22%", label: "Healthy net profit margin" },
    body: [
      "Real estate brokerage economics are unusual: the agents are independent contractors, so the brokerage's revenue is the company-side share of commission (typically 20-40% of gross commission), not the gross transaction value.",
      "On that brokerage-share basis, healthy operations run 12-22% net margin. The cost lines are office space, broker-of-record liability, MLS and tech fees, and marketing.",
      "Brokerages with a productive agent base (high deals-per-agent) clear well above this band. Brokerages with a passive roster of agents who don't transact much struggle.",
    ],
    relatedIndustryIds: ["real_estate_brokerage"],
    relatedSlugs: ["agency-profit-margin", "professional-services-margin"],
  },
  {
    slug: "auto-repair-margin",
    family: "B",
    title: "Auto repair shop margin: what's healthy?",
    question: "What is a healthy margin for an auto repair shop?",
    oneLineAnswer: "A healthy independent auto repair shop runs a 12-22% net profit margin.",
    headlineNumber: { value: "12-22%", label: "Healthy net profit margin" },
    body: [
      "Auto repair shops run on a labor-and-parts model. Labor typically marks up at 100-200% on technician cost; parts mark up at 25-50% over wholesale. A typical 2-3 bay shop clears $400-900K in revenue.",
      "Net margins in the 12-22% band are healthy for an owner-operated shop. The biggest variance is whether the shop has a specialty (European cars, diesel, hybrids) that supports higher labor rates.",
      "Shops that build a meaningful repeat-customer base usually run materially higher margins because they don't pay for new-customer acquisition every month.",
    ],
    relatedIndustryIds: ["auto_repair"],
    relatedSlugs: ["how-much-does-a-plumber-make", "trade-business-margins"],
  },
  {
    slug: "specialty-food-margin",
    family: "B",
    title: "Specialty food production margin: what's healthy?",
    question: "What is a healthy margin for a specialty food production business?",
    oneLineAnswer: "A healthy specialty food production business runs a 10-20% net profit margin.",
    headlineNumber: { value: "10-20%", label: "Healthy net profit margin" },
    body: [
      "Specialty food production - sauces, jams, chocolate, baked goods sold wholesale or DTC - runs higher margins than restaurants because the volume is industrial and the cost structure is fixed.",
      "Direct-to-consumer brands run higher margins (15-25%) but pay heavily for customer acquisition. Wholesale brands run lower margins (8-15%) but have stable repeat orders from distributors.",
      "The healthiest specialty food businesses operate both channels: DTC for brand-building and margin, wholesale for stable volume.",
    ],
    relatedIndustryIds: ["specialty_food_production", "artisan_bakery_wholesale"],
    relatedSlugs: ["ecommerce-profit-margin", "how-much-does-a-bakery-make"],
  },
  {
    slug: "veterinary-practice-margin",
    family: "B",
    title: "Veterinary practice margin: what's healthy?",
    question: "What is a healthy margin for a small veterinary practice?",
    oneLineAnswer: "A healthy small veterinary practice runs a 12-20% net profit margin.",
    headlineNumber: { value: "12-20%", label: "Healthy net profit margin" },
    body: [
      "Veterinary practices run economics similar to small medical practices but with no insurance reimbursement layer compressing prices. That makes for healthier and more stable margins.",
      "A single-doctor practice typically clears $700K-1.2M in revenue with a 12-20% net margin. Multi-doctor practices and those with surgical specialties run higher revenue per doctor.",
      "Inventory (food, medications, retail) is a meaningful profit center for healthy practices - typically 15-25% of revenue, with retail margins much better than at a human pharmacy.",
    ],
    relatedIndustryIds: ["veterinary_clinics"],
    relatedSlugs: ["how-much-does-a-medical-practice-make", "professional-services-margin"],
  },
  {
    slug: "dog-grooming-margin",
    family: "B",
    title: "Dog grooming margin: what's healthy?",
    question: "What is a healthy margin for a dog grooming business?",
    oneLineAnswer: "A healthy dog grooming business runs a 18-30% net profit margin.",
    headlineNumber: { value: "18-30%", label: "Healthy net profit margin" },
    body: [
      "Dog grooming is one of the higher-margin small businesses by category. Cost of goods is minimal (shampoo, towels, equipment depreciation), labor is the main expense, and the per-service ticket has steadily increased over the past decade.",
      "A single-groomer salon clears $80-150K. A 2-3 groomer shop runs $250-450K. Net margins in the 18-30% band are achievable because the owner is usually one of the groomers.",
      "Mobile grooming is a smaller-revenue but higher-margin variant - no real estate, premium pricing, and a tight clientele.",
    ],
    relatedIndustryIds: ["pet_grooming"],
    relatedSlugs: ["how-much-does-a-barbershop-make", "veterinary-practice-margin"],
  },
  {
    slug: "tutoring-business-margin",
    family: "B",
    title: "Tutoring business margin: what's healthy?",
    question: "What is a healthy margin for a small tutoring business?",
    oneLineAnswer: "A healthy small tutoring business runs a 25-45% net profit margin.",
    headlineNumber: { value: "25-45%", label: "Healthy net profit margin" },
    body: [
      "Tutoring businesses run high margins because the cost structure is light. A solo tutor working from home or a small office clears 60-80% net on their direct work. A tutoring business with multiple tutors typically pays them 40-60% of their session revenue, leaving 25-45% net.",
      "The healthiest tutoring businesses are specialty-focused (SAT/ACT, MCAT, AP exams) where pricing power is highest. General academic tutoring runs lower margins because parents anchor on a lower per-hour expectation.",
      "Group classes (small-group SAT prep, math enrichment) materially expand margin per tutor-hour and are how tutoring businesses scale beyond the founder's calendar.",
    ],
    relatedIndustryIds: ["tutoring_services"],
    relatedSlugs: ["agency-profit-margin", "professional-services-margin"],
  },
  {
    slug: "photography-business-margin",
    family: "B",
    title: "Photography business margin: what's healthy?",
    question: "What is a healthy margin for a small photography business?",
    oneLineAnswer: "A healthy small photography business runs a 20-35% net profit margin.",
    headlineNumber: { value: "20-35%", label: "Healthy net profit margin" },
    body: [
      "Photography businesses run on a project-pricing model with low fixed cost. The main expenses are equipment depreciation, software (editing tools, cloud storage), occasional second-shooter fees, and marketing.",
      "Wedding photography runs higher per-project revenue ($3-8K typically) but is highly seasonal. Commercial photography (product, real estate, editorial) runs more steady throughout the year at lower per-project rates.",
      "The healthiest photography businesses have either a tight specialty (specific style or category) that commands premium pricing or a high-volume model (real estate photography with 5-10 shoots per day).",
    ],
    relatedIndustryIds: ["photography_services"],
    relatedSlugs: ["agency-profit-margin", "videography-margin"],
  },
  {
    slug: "videography-margin",
    family: "B",
    title: "Videography margin: what's healthy?",
    question: "What is a healthy margin for a small videography business?",
    oneLineAnswer: "A healthy small videography business runs a 15-30% net profit margin.",
    headlineNumber: { value: "15-30%", label: "Healthy net profit margin" },
    body: [
      "Videography runs lower margins than photography because the post-production time per project is much longer. A wedding video that costs $4K to deliver typically requires 40-60 hours of edit time, which compresses the per-hour margin.",
      "Commercial videography (corporate, real estate, social-media content) runs better margins than wedding because the deliverables are tighter and the client relationships are more repeatable.",
      "The healthiest videography businesses build a productized service (e.g., real estate listing videos, weekly content packages) that lets them template the post-production workflow.",
    ],
    relatedIndustryIds: ["videography_services"],
    relatedSlugs: ["photography-business-margin", "agency-profit-margin"],
  },
  {
    slug: "freelance-developer-margin",
    family: "B",
    title: "Freelance developer margin: what's healthy?",
    question: "What is a healthy effective margin for a freelance software developer?",
    oneLineAnswer: "A healthy freelance developer's effective margin is 60-80% of billed revenue, with utilization being the main constraint.",
    headlineNumber: { value: "60-80%", label: "Effective margin" },
    body: [
      "A solo freelance developer runs on a near-zero cost base (laptop, software, internet, occasional contractor fees), so the headline gross margin is enormous. The real constraint is utilization: how many of the year's working hours are billable.",
      "A freelancer billing 25 hours a week year-round at $100/hour clears around $130K. Billing 35 hours/week clears $180K. The difference is not pricing - it's sales pipeline and discipline.",
      "The healthiest freelance developer businesses transition from time-and-materials billing to fixed-bid or retainer engagements as they get senior, which decouples revenue from hours.",
    ],
    relatedIndustryIds: ["software_dev_services"],
    relatedSlugs: ["saas-gross-margin", "professional-services-margin"],
  },

  // ============ FAMILY C: How to read benchmarks ============
  {
    slug: "what-is-a-revenue-benchmark",
    family: "C",
    title: "What is a revenue benchmark?",
    question: "What is a revenue benchmark and how do I use one?",
    oneLineAnswer: "A revenue benchmark is the typical annual revenue for businesses of a given size in a given industry and geography - useful as a sanity check, not as a target.",
    body: [
      "A revenue benchmark answers a specific question: 'what does the middle firm in this category actually take in?' It's not the average and it's not the best-in-class - it's the middle. Half of firms are below it, half are above.",
      "Benchmarks are most useful as a sanity check. If you're running a coffee shop and your annual revenue is $250K when the median for your city is $600K, something is structurally off - pricing, traffic, or category mix. If you're at $1.4M when the median is $600K, you're outperforming on something worth understanding.",
      "Benchmarks are least useful as targets. The middle is descriptive, not prescriptive. The best operators in any category are several multiples above the median, and they usually got there by doing something the median doesn't.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["how-smb-revenue-is-measured", "why-benchmarks-vary-by-city", "what-coverage-tier-means"],
  },
  {
    slug: "how-smb-revenue-is-measured",
    question: "How is small-business revenue measured?",
    family: "C",
    title: "How is small-business revenue measured?",
    oneLineAnswer: "Small-business revenue is measured several ways - gross sales, tax-filed receipts, or industry-survey estimates - and each method produces a slightly different number.",
    body: [
      "There are three main ways SMB revenue gets measured. First, gross sales reported on tax filings - the most authoritative source, but available with a 1-2 year lag and rolled up to coarse industry codes. Second, industry surveys and trade-association reports - more current, but typically reflect the firms willing to share data, which skews to mid-size and above. Third, derived estimates from establishment counts, employee counts, and industry-average per-employee revenue.",
      "Atlas combines all three. Where official filings are available, those anchor the numbers. Where they're not, survey data and derived estimates fill in. Every page shows a coverage tier that tells you which kind of source is anchoring the figure.",
      "The variance between methods is usually 10-25%. For a coffee shop, the question 'how much revenue' has a range, not a point. That's why benchmarks should be read as a band, not as a single figure.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-a-revenue-benchmark", "what-coverage-tier-means", "how-to-read-percentile-bands"],
  },
  {
    slug: "why-benchmarks-vary-by-city",
    family: "C",
    title: "Why benchmarks vary by city",
    question: "Why do business benchmarks vary so much from city to city?",
    oneLineAnswer: "City-level benchmarks vary because four things change across geographies: wage levels, real estate cost, density of competition, and how much locals can spend.",
    body: [
      "The same restaurant concept in San Francisco and in Cleveland will post very different revenue numbers, and the difference is almost entirely structural. San Francisco wages are roughly 2x Cleveland's, rents are 3-4x, but the customer base can also spend more per visit. These compound.",
      "Atlas adjusts for this with country-level cost-of-living multipliers and city-level wealth z-scores. The headline figure on every page reflects the local economy, not a national average.",
      "Two practical implications: first, never compare your business to a national benchmark without adjusting for your city. Second, when expanding to a new market, look at the local benchmark for your category, not your home market's number.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-a-revenue-benchmark", "how-to-read-revenue-benchmarks"],
  },
  {
    slug: "what-coverage-tier-means",
    family: "C",
    title: "What coverage tier means",
    question: "What does the coverage tier on each page mean?",
    oneLineAnswer: "Coverage tier tells you what kind of source is behind the number: measured, regional, estimated, or modeled.",
    body: [
      "Every page in Atlas displays a coverage chip near the headline number. The four tiers, in order of confidence: Measured (green) means the figures come from direct measurement of firms in that geography and industry. Regional (blue) means a broader benchmark from a higher level (state, country) is applied to this specific cell. Estimated (amber) means the figure is computed from country-level economic indicators (GDP per capita, governance, urbanization) combined with global industry averages. Modeled (gray) means there's no underlying observation; the number is a transparent model output.",
      "What you should do with each tier: Measured numbers can be cited and compared directly. Regional numbers are strong directional signals - fine for general planning, not for precise modeling. Estimated and Modeled numbers are orientation, useful to set a range, not a single point.",
      "Atlas covers the global SMB universe, so most pages outside the largest economies sit at Estimated or Modeled. The transparency about which tier you're reading is the point - the number is honest about what it can claim.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["how-smb-revenue-is-measured", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "how-to-read-percentile-bands",
    family: "C",
    title: "How to read percentile bands",
    question: "How do I read the p10, p25, p75, p90 percentile bands?",
    oneLineAnswer: "Percentile bands show the spread of firms within a category - the p25 to p75 range covers the middle 50% of businesses.",
    body: [
      "The median tells you where the middle firm sits. The percentile bands - p10, p25, p75, p90 - tell you how wide the spread is.",
      "P25 to p75 is the interquartile range: the middle 50% of firms. If a restaurant category has p25 = $700K and p75 = $1.4M, half of all restaurants in that category land in that band. P10 and p90 mark the outer edges - what the smallest and largest firms look like, ignoring the very extreme outliers.",
      "Useful rule of thumb: if you're benchmarking your own business, find the percentile you fall into. Above p75 you're outperforming the category. Below p25 you have a structural issue worth investigating.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-a-revenue-benchmark", "how-smb-revenue-is-measured"],
  },
  {
    slug: "how-to-read-revenue-benchmarks",
    family: "C",
    title: "How to read revenue benchmarks",
    question: "How do I read revenue benchmarks correctly?",
    oneLineAnswer: "Read the median as a sanity check, the percentile bands as the realistic spread, and the coverage tier as the confidence level - together they tell you what the number means.",
    body: [
      "A revenue benchmark page has three layers worth understanding. The headline number is the median - the middle firm. Around it are the percentile bands showing the spread (typically p25 to p75 covers half of firms). Above that is the coverage chip showing how the number was produced.",
      "How to use these together: if you're checking whether your business is healthy, look at the percentile you fall into. If you're sizing an opportunity, use the median × number of firms to estimate the market. If you're comparing across cities or countries, check that both benchmarks are at the same coverage tier - comparing a Measured number to a Modeled one is misleading.",
      "The thing most people miss: benchmarks describe a steady-state market. A new business in year one will usually run materially below the median. A mature business in year five should be at or above it.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-a-revenue-benchmark", "how-to-read-percentile-bands", "what-coverage-tier-means"],
  },
  {
    slug: "smb-vs-large-business-benchmarks",
    family: "C",
    title: "SMB vs large-business benchmarks",
    question: "Why are SMB benchmarks different from large-business benchmarks?",
    oneLineAnswer: "Small-business and large-business economics are structurally different - averaging across both produces numbers that describe neither.",
    body: [
      "An industry's revenue distribution is bimodal: a long tail of small businesses (often under $5M revenue) and a much shorter head of large corporations (often above $50M). The two groups have different cost structures, different pricing power, and different growth trajectories.",
      "If you average across the whole industry, you get a number that's pulled up by the large corporations and is misleading for a small business. Atlas benchmarks SMBs specifically - typically firms with under 100 employees and under $50M in revenue - so the figures are comparable to what a small operator actually sees.",
      "The exception: a few categories (manufacturing, biotech, telecom) are dominated by large corporations and don't have a meaningful SMB segment. Atlas flags those categories with a 'mixed' or 'corp-only' tag so you know what you're reading.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-a-revenue-benchmark", "how-smb-revenue-is-measured"],
  },
  {
    slug: "what-is-a-size-band",
    family: "C",
    title: "What is a size band?",
    question: "What does 'small', 'medium', 'large' mean in benchmarks?",
    oneLineAnswer: "Size bands group businesses by employee count or revenue scale - typically small (1-20 employees), medium (20-100), and large (100+).",
    body: [
      "Size bands matter because revenue scales with firm size. A 'small' restaurant might post $400-800K; a 'medium' restaurant with multiple locations might post $2-5M. Without size bands, the median is misleading.",
      "Atlas typically uses three bands: small (the owner-operator and immediate-team format), medium (the expanded multi-location or multi-team format), and large (the corporate-scale format). Each band shows its own median and percentile spread.",
      "What this means in practice: if you're a solo founder or a 5-person team, the 'small' band is your peer group. The 'medium' band describes where you might land after several years of growth. The 'large' band is a different category of business with different economics - useful for context, but not for direct comparison.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["how-to-read-percentile-bands", "smb-vs-large-business-benchmarks"],
  },
  {
    slug: "currency-and-benchmarks",
    family: "C",
    title: "Currency and benchmarks",
    question: "Why are non-US benchmarks shown in dollars?",
    oneLineAnswer: "Atlas shows all benchmarks in USD for comparability across countries - every country page lists the local currency separately so conversion is one click away.",
    body: [
      "A restaurant in Tokyo that posts ¥120M and a restaurant in New York that posts $1.1M are roughly the same size, but presenting one in yen and the other in dollars makes the comparison hard. Atlas converts everything to USD using a representative annual exchange rate.",
      "Every country page shows the local currency code at the top of the page. For more precise comparison, divide the USD figure by the country's purchasing power parity (PPP) adjustment factor - a dollar buys more in Bangladesh than in Switzerland, and benchmarks should be read with that in mind.",
      "Practical takeaway: use the USD figure for cross-country comparison; use the local currency mental model for local planning.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["why-benchmarks-vary-by-city", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "how-saas-revenue-scales",
    family: "C",
    title: "How SaaS revenue scales differently",
    question: "Why does SaaS revenue follow different rules than traditional small business revenue?",
    oneLineAnswer: "SaaS revenue scales on subscribers × ARPU, not on hours worked or units sold, so the benchmarks look very different from traditional service or retail businesses.",
    body: [
      "A traditional small business is constrained by physical capacity (chairs, tables, trucks, hours). A SaaS business is constrained by acquisition cost and churn. That makes the revenue benchmark a different animal: SaaS at $1M ARR is a 5-person team; SaaS at $10M ARR might still be a 20-person team.",
      "Atlas separates SaaS from traditional software services for this reason. A SaaS benchmark page will show ARR (annual recurring revenue) instead of project revenue, and the percentile spread is much wider than for service businesses.",
      "If you're benchmarking a SaaS business, look at the ARR figure plus the implied gross margin (typically 70-85% - see the SaaS gross margin page). If you're benchmarking a services business that calls itself SaaS, look at the service business benchmark instead.",
    ],
    relatedIndustryIds: ["software_dev_services"],
    relatedSlugs: ["saas-gross-margin", "freelance-developer-margin"],
  },
  {
    slug: "how-margin-differs-from-revenue",
    family: "C",
    title: "How margin differs from revenue",
    question: "What is the difference between revenue and margin?",
    oneLineAnswer: "Revenue is the money flowing in; margin is the percentage of that money the business keeps after costs. A high-revenue business with a thin margin can be less profitable than a low-revenue business with a fat margin.",
    body: [
      "Revenue gets all the attention; margin is what actually feeds the owner. A restaurant clearing $2M in revenue at 5% net margin generates $100K of profit. A barbershop clearing $300K at 25% margin generates $75K. The barbershop owner with less revenue might be more financially healthy.",
      "Atlas tracks both. The benchmark pages start with revenue (the headline number, easy to compare), but the deeper pages and the related knowledge-base entries cover typical margin ranges for each category.",
      "When making decisions about which business to start, compare margin × revenue together. A high-margin small business is often the better path to owner take-home than a low-margin larger one.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["restaurant-profit-margin", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "what-is-establishment-count",
    family: "C",
    title: "What is establishment count?",
    question: "What does the establishment count on a benchmark page mean?",
    oneLineAnswer: "Establishment count is the number of distinct business locations operating in a geography and industry - useful for sizing the local market and competition.",
    body: [
      "Establishment count answers: how many of these are there? If a city has 1,200 coffee shops, the per-resident density tells you whether you're entering a saturated market or an underserved one.",
      "Atlas displays establishment counts where available. Combined with the median revenue, you can estimate the total market size: 1,200 coffee shops × $600K median = roughly $720M in city-wide coffee revenue.",
      "Use this for two things: sizing a market opportunity, and gauging competition density. A neighborhood with 8 coffee shops within a quarter mile is a different proposition from one with 2.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["why-benchmarks-vary-by-city", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "how-employment-numbers-work",
    family: "C",
    title: "How employment numbers work",
    question: "How are employment numbers calculated on benchmark pages?",
    oneLineAnswer: "Employment numbers reflect typical full-time-equivalent employees per firm - including the owner-operator where they work in the business.",
    body: [
      "When a benchmark page shows '6.2 employees per firm,' that means the typical firm in this category has between five and seven people on payroll, counted as full-time equivalents. A business with three full-time and four half-time employees would count as five FTE.",
      "The owner-operator is usually counted in this number for small businesses, which is why even one-person businesses don't typically show '0' employees. The category 'self-employed, no employees' is a separate filing distinction.",
      "Combined with median revenue, this gives you revenue per employee - a useful productivity benchmark across cities and across firm sizes within the same category.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-is-establishment-count", "smb-vs-large-business-benchmarks"],
  },
  {
    slug: "how-wage-data-relates-to-revenue",
    family: "C",
    title: "How wage data relates to revenue",
    question: "How does the median wage on a benchmark page relate to revenue?",
    oneLineAnswer: "Median wage shows what the typical employee in this category earns - useful for estimating labor cost as a percentage of revenue.",
    body: [
      "A restaurant benchmark page that shows $1.1M median revenue and 12 median FTE at a $34K median wage tells you the labor line is roughly $408K, or 37% of revenue. That matches the industry-typical 28-36% range for restaurants and confirms the benchmark is internally consistent.",
      "Use this calculation to sanity-check any benchmark. If revenue ÷ (employees × wage) lands outside the normal labor-cost range for the category, one of the three numbers is probably off.",
      "Wage numbers are typically gross - before payroll taxes and benefits. The fully-loaded cost to the employer is usually 18-30% higher than the gross wage.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["how-employment-numbers-work", "what-is-a-revenue-benchmark"],
  },
  {
    slug: "why-extrapolated-data-still-matters",
    family: "C",
    title: "Why extrapolated data still matters",
    question: "Why does Atlas show extrapolated data instead of leaving cells blank?",
    oneLineAnswer: "A defensible estimate is more useful than a blank page - but only when you can see clearly what's measured and what's estimated.",
    body: [
      "If Atlas only showed cells where direct measurements exist, most of the world map would be blank. The largest economies have full coverage, but small countries and niche industries don't. A blank page tells the user nothing.",
      "Instead, Atlas estimates the missing cells from country-level economic indicators (GDP per capita, governance, urbanization) combined with global industry averages. The result is a number - bounded, sanity-checked, and clearly labeled as estimated.",
      "The coverage chip on every page is the contract: it tells you whether the number was measured or estimated, so you can decide how much weight to give it. An estimated number is a useful starting point; treating it as a precise measurement would be a mistake.",
    ],
    relatedIndustryIds: [],
    relatedSlugs: ["what-coverage-tier-means", "how-smb-revenue-is-measured"],
  },
];

export const LEARN_BY_SLUG = new Map(LEARN_ARTICLES.map((a) => [a.slug, a]));
export const LEARN_BY_FAMILY = (family: "A" | "B" | "C") =>
  LEARN_ARTICLES.filter((a) => a.family === family);
